//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

//
PRINT Running NET-UMTS-UmtsGprsSCPR
PRINT OPening RConnection using qos default from policy file
//
LOAD_SUITE te_esockteststepsSuite -SharedData
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script



RUN_TEST_STEP 100 te_esockteststepsSuite startsimtsyStep z:\testdata\configs\UmtsGprsSCPR\Config1Case9.ini StartSimTSY
RUN_TEST_STEP 100 te_esockteststepsSuite creatersocketservStep z:\testdata\configs\UmtsGprsSCPR\Config1Case9.ini CreateSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite createrconnectionStep z:\testdata\configs\UmtsGprsSCPR\Config1Case9.ini CreateConn1

RUN_TEST_STEP 100 te_esockteststepsSuite connectrsocketservStep z:\testdata\configs\UmtsGprsSCPR\Config1Case9.ini ConnectSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite openrconnectionStep z:\testdata\configs\UmtsGprsSCPR\Config1Case9.ini OpenConn1
RUN_TEST_STEP 100 te_esockteststepsSuite startrconnectionStep z:\testdata\configs\UmtsGprsSCPR\Config1Case9.ini StartConn1

RUN_TEST_STEP 100 te_esockteststepsSuite closerconnectionStep z:\testdata\configs\UmtsGprsSCPR\Config1Case9.ini CloseConn1
RUN_TEST_STEP 100 te_esockteststepsSuite closersocketservStep z:\testdata\configs\UmtsGprsSCPR\Config1Case9.ini CloseSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite stopsimtsyStep z:\testdata\configs\UmtsGprsSCPR\Config1Case9.ini StopSimTSY
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep



RUN_SCRIPT z:\TestData\scripts\te_esock_test_unloadesockForced.script

PRINT Completed NET-UMTS-UmtsGprsSCPR


