// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run SsmSupLoaderStep tests

LOAD_SUITE tsus_ssmutilsrv

START_TESTCASE 			DEVSRVS-SSMA-SUS-0004
//! @SYMTestCaseID 		DEVSRVS-SSMA-SUS-0004
//! @SYMPREQ 			PREQ1871
//! @SYMREQ			REQ9159
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Unit-test for XSusPluginLoader, testing all public methods
//! @SYMTestActions		The test performs basic operations on a XSusPluginLoader object namely calling the following methods:
//!					1.Call LoadDllFileLC() with missing file
//!					2.Call LoadDllFileLC() with wrong DLL type
//!					3.Call LoadDllFileLC() with wrong identity
//!					4.Call LoadDllFileLC() on a valid SUP
//!					5.Call CreatePluginLC() on a valid SUP
//!					6.Call CreatePluginLC() with the wrong ordinal number.
//! @SYMTestExpectedResults  	1.KErrNotFound
//!				  2.KErrNotSupported
//!				  3.KErrBadName
//!				  4.KErrNone and RLibrary Handle() != KNullHandle
//!				  5.KErrNone and CSusPluginFrame != NULL
//!				  6.KErrNoMemory.
RUN_TEST_STEP 100 tsus_ssmutilsrv SsmSupLoaderStep
END_TESTCASE 			DEVSRVS-SSMA-SUS-0004