// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run SsmSupInfoStep tests

LOAD_SUITE tsus_ssmutilsrv

START_TESTCASE 			DEVSRVS-SSMA-SUS-0001
//! @SYMTestCaseID 		DEVSRVS-SSMA-SUS-0001
//! @SYMPREQ 			PREQ1871
//! @SYMREQ			REQ9159
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Unit-test for TSsmSupInfo, testing all public methods
//! @SYMTestActions		The test performs basic operations on a TSsmSupInfo object namely calling the following methods:
//! 					1.Constructors and copy constructor.
//! 					2.Set()Identity()FileName()NewLOrdinal().
//! 					3.Check InternalizeL() and ExternalizeL().
//! @SYMTestExpectedResults All methods handle the object data appropriately with no errors reported.
RUN_TEST_STEP 100 tsus_ssmutilsrv SsmSupInfoStep
END_TESTCASE 			DEVSRVS-SSMA-SUS-0001