// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run SusUtilServerStep tests

LOAD_SUITE tsus_ssmutilsrv

START_TESTCASE 			DEVSRVS-SSMA-SUS-0010
//! @SYMTestCaseID 		DEVSRVS-SSMA-SUS-0010
//! @SYMPREQ 			PREQ1871
//! @SYMTestType		IT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Check that a loaded SUP can request a swp change
//! @SYMTestActions		The test assumes that a valid SUP is loaded correctly and available to use. 
//! 				The test will check that upon request of the SUP to change a System-Wide Property value the value of this swp is correctly updated according to the value specified by the SUP.
//! 				The test also checks that multiple SUPs can be loaded from the same file
//! @SYMTestExpectedResults 	The swp value is correctly updated.
RUN_TEST_STEP 100 tsus_ssmutilsrv SusLoadPluginStep
END_TESTCASE 			DEVSRVS-SSMA-SUS-0010