// Copyright (c) 2004-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_SCRIPT z:\TestData\Scripts\TE_smsprt_setup.script

LOAD_SUITE TE_smsprt -SharedData

//!@file

START_TESTCASE SMS-SMSStack-NA-3001
//!@SYMTestCaseID SMS-SMSStack-NA-3001
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Simple Tx And Rx
//!@SYMTestPriority critical
//!@SYMTestActions Test simple transmit and receive
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSimpleTxAndRx z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber0
END_TESTCASE SMS-SMSStack-NA-3001

START_TESTCASE SMS-SMSStack-NA-3002
//!@SYMTestCaseID SMS-SMSStack-NA-3002
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Status Report
//!@SYMTestPriority critical
//!@SYMTestActions  Test status report
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestStatusReport z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber1
END_TESTCASE SMS-SMSStack-NA-3002


START_TESTCASE SMS-SMSStack-NA-3003
//!@SYMTestCaseID SMS-SMSStack-NA-3003
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Tx With Error
//!@SYMTestPriority critical
//!@SYMTestActions Test Transmit with Error
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestTxWithError z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber2
END_TESTCASE SMS-SMSStack-NA-3003


START_TESTCASE SMS-SMSStack-NA-3004
//!@SYMTestCaseID SMS-SMSStack-NA-3004
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Tx Failed
//!@SYMTestPriority critical
//!@SYMTestActions  Test Transmit with failure
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestTxFailed z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber3
END_TESTCASE SMS-SMSStack-NA-3004


START_TESTCASE SMS-SMSStack-NA-3005
//!@SYMTestCaseID SMS-SMSStack-NA-3005
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Matching To Observer
//!@SYMTestPriority critical
//!@SYMTestActions  Test Matching To Observer
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestMatchingToObserver z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber4
END_TESTCASE SMS-SMSStack-NA-3005


START_TESTCASE SMS-SMSStack-NA-3006
//!@SYMTestCaseID SMS-SMSStack-NA-3006
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Command Messages
//!@SYMTestPriority critical
//!@SYMTestActions Test Command Messages
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestCommandMessages z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber5
END_TESTCASE SMS-SMSStack-NA-3006


START_TESTCASE SMS-SMSStack-NA-3007
//!@SYMTestCaseID SMS-SMSStack-NA-3007
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Simple Rx
//!@SYMTestPriority critical
//!@SYMTestActions Test Simple Receive
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSimpleRx z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber6
END_TESTCASE SMS-SMSStack-NA-3007


START_TESTCASE SMS-SMSStack-NA-3008
//!@SYMTestCaseID SMS-SMSStack-NA-3008
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test 7bit Mess Test
//!@SYMTestPriority critical
//!@SYMTestActions  Test 7bit Mess Test
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt Test7bitMessTest z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber7
END_TESTCASE SMS-SMSStack-NA-3008


START_TESTCASE SMS-SMSStack-NA-3009
//!@SYMTestCaseID SMS-SMSStack-NA-3009
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Class Messages
//!@SYMTestPriority critical
//!@SYMTestActions Test Class Messages
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestClassMessages z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber8
END_TESTCASE SMS-SMSStack-NA-3009


START_TESTCASE SMS-SMSStack-NA-3010
//!@SYMTestCaseID SMS-SMSStack-NA-3010
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Rx Concatenated
//!@SYMTestPriority critical
//!@SYMTestActions  Test receive concatenated
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestRxConcatenated z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber9
END_TESTCASE SMS-SMSStack-NA-3010


START_TESTCASE SMS-SMSStack-NA-3011
//!@SYMTestCaseID SMS-SMSStack-NA-3011
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Rx Duplicate
//!@SYMTestPriority critical
//!@SYMTestActions  Test receive duplicate
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestRxDuplicate z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber10
END_TESTCASE SMS-SMSStack-NA-3011


START_TESTCASE SMS-SMSStack-NA-3012
//!@SYMTestCaseID SMS-SMSStack-NA-3012
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Rx Ring Tone A
//!@SYMTestPriority critical
//!@SYMTestActions  Test receive ring tone A
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestRxRingToneA z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber11
END_TESTCASE SMS-SMSStack-NA-3012


START_TESTCASE SMS-SMSStack-NA-3013
//!@SYMTestCaseID SMS-SMSStack-NA-3013
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Tx Rx Concatenated
//!@SYMTestPriority critical
//!@SYMTestActions  Test Transmit/receive concatenated messages
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestTxRxConcatenated z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber12
END_TESTCASE SMS-SMSStack-NA-3013


START_TESTCASE SMS-SMSStack-NA-3014
//!@SYMTestCaseID SMS-SMSStack-NA-3014
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Param Storage
//!@SYMTestPriority critical
//!@SYMTestActions  Test storage of parameters
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestParamStorage z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber13
END_TESTCASE SMS-SMSStack-NA-3014


START_TESTCASE SMS-SMSStack-NA-3015
//!@SYMTestCaseID SMS-SMSStack-NA-3015
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Sms Store
//!@SYMTestPriority critical
//!@SYMTestActions  Test Sms Store
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSmsStore z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber14
END_TESTCASE SMS-SMSStack-NA-3015


START_TESTCASE SMS-SMSStack-NA-3016
//!@SYMTestCaseID SMS-SMSStack-NA-3016
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Sms Store List
//!@SYMTestPriority critical
//!@SYMTestActions  Test Sms Store List
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSmsStoreList z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber15
END_TESTCASE SMS-SMSStack-NA-3016


START_TESTCASE SMS-SMSStack-NA-3017
//!@SYMTestCaseID SMS-SMSStack-NA-3017
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Delete Sms
//!@SYMTestPriority critical
//!@SYMTestActions Test Delete Sms
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestDeleteSms z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber15
END_TESTCASE SMS-SMSStack-NA-3017


START_TESTCASE SMS-SMSStack-NA-3018
//!@SYMTestCaseID SMS-SMSStack-NA-3018
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Socket Binding
//!@SYMTestPriority critical
//!@SYMTestActions  Test Socket Binding
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSocketBinding z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber16
END_TESTCASE SMS-SMSStack-NA-3018

START_TESTCASE SMS-SMSStack-NA-3098
//!@SYMTestCaseID SMS-SMSStack-NA-3098
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test SMS address class
//!@SYMTestPriority High
//!@SYMTestActions  Test SMS address class
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSmsAddr
END_TESTCASE SMS-SMSStack-NA-3098

START_TESTCASE SMS-SMSStack-NA-3019
//!@SYMTestCaseID SMS-SMSStack-NA-3019
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Sms Event Logger
//!@SYMTestPriority critical
//!@SYMTestActions  Test Sms Event Logger
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSmsEventLogger z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber17
END_TESTCASE SMS-SMSStack-NA-3019


START_TESTCASE SMS-SMSStack-NA-3020
//!@SYMTestCaseID SMS-SMSStack-NA-3020
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Bearer Change
//!@SYMTestPriority critical
//!@SYMTestActions  Test Bearer Change
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestBearerChange z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber18
END_TESTCASE SMS-SMSStack-NA-3020


START_TESTCASE SMS-SMSStack-NA-3094
//!@SYMTestCaseID SMS-SMSStack-NA-3094
//!@SYMREQ DEF080837
//!@SYMTestCaseDesc Test Restore Bearer
//!@SYMTestPriority critical
//!@SYMTestActions  Test Restore Bearer
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestRestoreBearer 
END_TESTCASE SMS-SMSStack-NA-3094


START_TESTCASE SMS-SMSStack-NA-3021
//!@SYMTestCaseID SMS-SMSStack-NA-3021
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Recv Mode Change
//!@SYMTestPriority critical
//!@SYMTestActions  Test Recieve Mode Change
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestRecvModeChange z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber19
END_TESTCASE SMS-SMSStack-NA-3021


START_TESTCASE SMS-SMSStack-NA-3022
//!@SYMTestCaseID SMS-SMSStack-NA-3022
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Tsy Caps
//!@SYMTestPriority critical
//!@SYMTestActions  Test Tsy Capabilities
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestTsyCaps z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber20
END_TESTCASE SMS-SMSStack-NA-3022


START_TESTCASE SMS-SMSStack-NA-3023
//!@SYMTestCaseID SMS-SMSStack-NA-3023
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test OOM Send Sms
//!@SYMTestPriority critical
//!@SYMTestActions  Test send sms with out of memory conditions
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 1000 TE_smsprt TestOOMSendSms z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber21
END_TESTCASE SMS-SMSStack-NA-3023


START_TESTCASE SMS-SMSStack-NA-3024
//!@SYMTestCaseID SMS-SMSStack-NA-3024
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test OOM Write Sms
//!@SYMTestPriority critical
//!@SYMTestActions  Test write sms with out of memory conditions
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 1000 TE_smsprt TestOOMWriteSms z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber22
END_TESTCASE SMS-SMSStack-NA-3024


START_TESTCASE SMS-SMSStack-NA-3025
//!@SYMTestCaseID SMS-SMSStack-NA-3025
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test OOM Read Sms
//!@SYMTestPriority critical
//!@SYMTestActions  Test Read Sms with out of memory conditions
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 1000 TE_smsprt TestOOMReadSms z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber23
END_TESTCASE SMS-SMSStack-NA-3025


START_TESTCASE SMS-SMSStack-NA-3026
//!@SYMTestCaseID SMS-SMSStack-NA-3026
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test OOM Read Sms List
//!@SYMTestPriority critical
//!@SYMTestActions  Test read sms list with out of memory conditions
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 1000 TE_smsprt TestOOMReadSmsList z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber24
END_TESTCASE SMS-SMSStack-NA-3026


START_TESTCASE SMS-SMSStack-NA-3027
//!@SYMTestCaseID SMS-SMSStack-NA-3027
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test OOM Delete Sms
//!@SYMTestPriority critical
//!@SYMTestActions  Test delete sms with out of memory conditions
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 1000 TE_smsprt TestOOMDeleteSms z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber25
END_TESTCASE SMS-SMSStack-NA-3027


START_TESTCASE SMS-SMSStack-NA-3028
//!@SYMTestCaseID SMS-SMSStack-NA-3028
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc TestOOMSmsParams
//!@SYMTestPriority critical
//!@SYMTestActions  Test sms params with out of memory conditions
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 1000 TE_smsprt TestOOMSmsParams z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber26
END_TESTCASE SMS-SMSStack-NA-3028


START_TESTCASE SMS-SMSStack-NA-3029
//!@SYMTestCaseID SMS-SMSStack-NA-3029
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc TestMeStoreDupAndMiss
//!@SYMTestPriority critical
//!@SYMTestActions  Test Me store with duplicate and missing pdus'
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestMeStoreDupAndMiss z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber27
END_TESTCASE SMS-SMSStack-NA-3029


START_TESTCASE SMS-SMSStack-NA-3030
//!@SYMTestCaseID SMS-SMSStack-NA-3030
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Sim Store Dup And Miss
//!@SYMTestPriority critical
//!@SYMTestActions  Test Sim Store with duplicate and Missing pdus'
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSimStoreDupAndMiss z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber28
END_TESTCASE SMS-SMSStack-NA-3030


START_TESTCASE SMS-SMSStack-NA-3031
//!@SYMTestCaseID SMS-SMSStack-NA-3031
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc TestRxCphs
//!@SYMTestPriority critical
//!@SYMTestActions   Test the reception of a CPHS Message Waiting Indication
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestRxCphs z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber30
END_TESTCASE SMS-SMSStack-NA-3031


START_TESTCASE SMS-SMSStack-NA-3032
//!@SYMTestCaseID SMS-SMSStack-NA-3032
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Invalid PDUs
//!@SYMTestPriority critical
//!@SYMTestActions  Test receiving invalid pdus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestInvalidPDUs z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber31
END_TESTCASE SMS-SMSStack-NA-3032


START_TESTCASE SMS-SMSStack-NA-3033
//!@SYMTestCaseID SMS-SMSStack-NA-3033
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Stress
//!@SYMTestPriority critical
//!@SYMTestActions  Test Transmit and Receive large number of different messages
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 700 TE_smsprt TestStress z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber32

END_TESTCASE SMS-SMSStack-NA-3033

START_TESTCASE SMS-SMSStack-NA-3034
//!@SYMTestCaseID SMS-SMSStack-NA-3034
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Combined Store
//!@SYMTestPriority critical
//!@SYMTestActions  Test Combined Store
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestCombinedStore z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber33
END_TESTCASE SMS-SMSStack-NA-3034


START_TESTCASE SMS-SMSStack-NA-3035
//!@SYMTestCaseID SMS-SMSStack-NA-3035
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Params Inter
//!@SYMTestPriority critical
//!@SYMTestActions  Test retrieving and storing the sms parameters
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestParamsInter z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber34
END_TESTCASE SMS-SMSStack-NA-3035


START_TESTCASE SMS-SMSStack-NA-3036
//!@SYMTestCaseID SMS-SMSStack-NA-3036
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc TestTxRxAlphanumeric
//!@SYMTestPriority critical
//!@SYMTestActions  est a Transmit And receive of messages with alphanumeric dest/orig addresses
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestTxRxAlphanumeric z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber35
END_TESTCASE SMS-SMSStack-NA-3036


START_TESTCASE SMS-SMSStack-NA-3037
//!@SYMTestCaseID SMS-SMSStack-NA-3037
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Rx Suspend
//!@SYMTestPriority critical
//!@SYMTestActions  Test Receive Suspension
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestRxSuspend 
END_TESTCASE SMS-SMSStack-NA-3037


START_TESTCASE SMS-SMSStack-NA-3038
//!@SYMTestCaseID SMS-SMSStack-NA-3038
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Enumerate Corrupted
//!@SYMTestPriority critical
//!@SYMTestActions Test Enumeration of Corrupted messages
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestEnumerateCorrupted z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber37
END_TESTCASE SMS-SMSStack-NA-3038


START_TESTCASE SMS-SMSStack-NA-3039
//!@SYMTestCaseID SMS-SMSStack-NA-3039
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc TestCancelling
//!@SYMTestPriority critical
//!@SYMTestActions  Test Cancellacion of an sms operation
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestCancelling z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber38
END_TESTCASE SMS-SMSStack-NA-3039


START_TESTCASE SMS-SMSStack-NA-3040
//!@SYMTestCaseID SMS-SMSStack-NA-3040
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Send And Recv Msgs With Different TON
//!@SYMTestPriority critical
//!@SYMTestActions  Test send And recieve messages with different TON
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSendAndRecvMsgsWithDifferentTON 
END_TESTCASE SMS-SMSStack-NA-3040


START_TESTCASE SMS-SMSStack-NA-3041
//!@SYMTestCaseID SMS-SMSStack-NA-3041
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Send And Receive Indicator Msgs
//!@SYMTestPriority critical
//!@SYMTestActions  Test send and receive indicator messages
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSendAndReceiveIndicatorMsgs
END_TESTCASE SMS-SMSStack-NA-3041


START_TESTCASE SMS-SMSStack-NA-3042
//!@SYMTestCaseID SMS-SMSStack-NA-3042
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Send and Receive Max Length Msg
//!@SYMTestPriority critical
//!@SYMTestActions  Test Send Recv Maximum Length Message (255 Pdus)
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 5000 TE_smsprt TestSendRecvMaxLengthMsg
END_TESTCASE SMS-SMSStack-NA-3042


START_TESTCASE SMS-SMSStack-NA-3043
//!@SYMTestCaseID SMS-SMSStack-NA-3043
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Send And Recv Msgs With Different PID
//!@SYMTestPriority critical
//!@SYMTestActions  Test Send And Receive Msgs With Different PID
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSendAndRecvMsgsWithDifferentPID
END_TESTCASE SMS-SMSStack-NA-3043


START_TESTCASE SMS-SMSStack-NA-3044
//!@SYMTestCaseID SMS-SMSStack-NA-3044
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc  Sms Params Error Cases
//!@SYMTestPriority critical
//!@SYMTestActions Test Sms Parameters Error Cases
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt SmsParamsErrorCases
END_TESTCASE SMS-SMSStack-NA-3044


START_TESTCASE SMS-SMSStack-NA-3097
//!@SYMTestCaseID SMS-SMSStack-NA-3097
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Resend Failed Concatinated Message
//!@SYMTestPriority critical
//!@SYMTestActions Test Resend Failed Concatinated Message
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestResendFailedConcatinatedMessage z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber44
END_TESTCASE SMS-SMSStack-NA-3097


START_TESTCASE SMS-SMSStack-NA-3045
//!@SYMTestCaseID SMS-SMSStack-NA-3045
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Multipart Wap Message
//!@SYMTestPriority critical
//!@SYMTestActions Test Multipart Wap Message
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestMultipartWapMessage z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber45
END_TESTCASE SMS-SMSStack-NA-3045


START_TESTCASE SMS-SMSStack-NA-3046
//!@SYMTestCaseID SMS-SMSStack-NA-3046
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test MOSES Message
//!@SYMTestPriority critical
//!@SYMTestActions  Test MOSES Message
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestMOSESMessage z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber46
END_TESTCASE SMS-SMSStack-NA-3046


START_TESTCASE SMS-SMSStack-NA-3047
//!@SYMTestCaseID SMS-SMSStack-NA-3047
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Clock Back
//!@SYMTestPriority critical
//!@SYMTestActions  Test Clock Back
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestClockBack z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber47
END_TESTCASE SMS-SMSStack-NA-3047


START_TESTCASE SMS-SMSStack-NA-3048
//!@SYMTestCaseID SMS-SMSStack-NA-3048
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Enumerate NoMessages
//!@SYMTestPriority critical
//!@SYMTestActions  Test enumeration of no messages
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestEnumerateNoMessages z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber48
END_TESTCASE SMS-SMSStack-NA-3048


START_TESTCASE SMS-SMSStack-NA-3049
//!@SYMTestCaseID SMS-SMSStack-NA-3049
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Concatenated Message Logging
//!@SYMTestPriority critical
//!@SYMTestActions  Test Concatenated Message Logging
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestConcatenatedMessageLogging z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber50
END_TESTCASE SMS-SMSStack-NA-3049


START_TESTCASE SMS-SMSStack-NA-3050
//!@SYMTestCaseID SMS-SMSStack-NA-3050
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Enumeration Of Status Report
//!@SYMTestPriority critical
//!@SYMTestActions  Test Enumeration Of Status Report
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestEnumerationOfStatusReport z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber51
END_TESTCASE SMS-SMSStack-NA-3050


START_TESTCASE SMS-SMSStack-NA-3051
//!@SYMTestCaseID SMS-SMSStack-NA-3051
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test IE
//!@SYMTestPriority critical
//!@SYMTestActions  Test IE
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestIE z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber52
END_TESTCASE SMS-SMSStack-NA-3051


START_TESTCASE SMS-SMSStack-NA-3052
//!@SYMTestCaseID SMS-SMSStack-NA-3052
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Email IE
//!@SYMTestPriority critical
//!@SYMTestActions Test Email IE
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestEmailIE z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber53
END_TESTCASE SMS-SMSStack-NA-3052


START_TESTCASE SMS-SMSStack-NA-3053
//!@SYMTestCaseID SMS-SMSStack-NA-3053
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Max Read Time For Sms Store List
//!@SYMTestPriority critical
//!@SYMTestActions Test Maximim Read Time For Sms Store List
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestMaxReadTimeForSmsStoreList z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber54
END_TESTCASE SMS-SMSStack-NA-3053


START_TESTCASE SMS-SMSStack-NA-3054
//!@SYMTestCaseID SMS-SMSStack-NA-3054
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc  Test Same Log Id Multiple PDU
//!@SYMTestPriority critical
//!@SYMTestActions  Test same log id multiple pdu
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSameLogIdMultiplePDU z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber57
END_TESTCASE SMS-SMSStack-NA-3054


START_TESTCASE SMS-SMSStack-NA-3055
//!@SYMTestCaseID SMS-SMSStack-NA-3055
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Same Log Id Single PDU
//!@SYMTestPriority critical
//!@SYMTestActions  Test Same Log Id Single PDU
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSameLogIdSinglePDU z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber58
END_TESTCASE SMS-SMSStack-NA-3055


START_TESTCASE SMS-SMSStack-NA-3056
//!@SYMTestCaseID SMS-SMSStack-NA-3056
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Write Status Report To SIM
//!@SYMTestPriority critical
//!@SYMTestActions Test Writing of a status report to the sim
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestWriteStatusReportToSIM z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber49
END_TESTCASE SMS-SMSStack-NA-3056


START_TESTCASE SMS-SMSStack-NA-3057
//!@SYMTestCaseID SMS-SMSStack-NA-3057
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc  Test Tx Sms With Delayed Completion
//!@SYMTestPriority critical
//!@SYMTestActions   Test transmit of a sms with delayed completion
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_UTILS MakeReadWrite c:\private\101F7989\esock\smswap.sms.bak
RUN_UTILS copyfile c:\private\101F7989\esock\smswap.sms.esk c:\private\101F7989\esock\smswap.sms.bak
RUN_UTILS MakeReadWrite c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS copyfile z:\sms\smswap.sms-sendTryTimeout.esk c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS MakeReadWrite c:\private\101F7989\esock\smswap.sms.esk

RUN_TEST_STEP 500 TE_smsprt TestTxSmsWithDelayedCompletion z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber60

RUN_UTILS DeleteFile c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS copyfile c:\private\101F7989\esock\smswap.sms.bak c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS DeleteFile c:\private\101F7989\esock\smswap.sms.bak
END_TESTCASE SMS-SMSStack-NA-3057


START_TESTCASE SMS-SMSStack-NA-3058
//!@SYMTestCaseID SMS-SMSStack-NA-3058
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Sms Store Read Cancel
//!@SYMTestPriority critical
//!@SYMTestActions Test sms store read with cancel
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSmsStoreReadCancel
END_TESTCASE SMS-SMSStack-NA-3058


START_TESTCASE SMS-SMSStack-NA-3059
//!@SYMTestCaseID SMS-SMSStack-NA-3059
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Bind When Powered Down With Publish Subscribe
//!@SYMTestPriority critical
//!@SYMTestActions  Test bind when powered down with publish and subscribe
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestBindWhenPoweredDownWithPublishSubscribe
END_TESTCASE SMS-SMSStack-NA-3059


START_TESTCASE SMS-SMSStack-NA-3060
//!@SYMTestCaseID SMS-SMSStack-NA-3060
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc TestObserverNotifiedWhenPoweredDownWithPublishSubscribe
//!@SYMTestPriority critical
//!@SYMTestActions  Test observer notified when powered down with publish and subscribe
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestObserverNotifiedWhenPoweredDownWithPublishSubscribe z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber59

END_TESTCASE SMS-SMSStack-NA-3060

START_TESTCASE SMS-SMSStack-NA-3061
//!@SYMTestCaseID SMS-SMSStack-NA-3061
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Sms CNumber Change WithPublish Subscribe
//!@SYMTestPriority critical
//!@SYMTestActions  Test sms CNumber change with publish and subscribe
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSmsCNumberChangeWithPublishSubscribe z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber55
END_TESTCASE SMS-SMSStack-NA-3061


START_TESTCASE SMS-SMSStack-NA-3062
//!@SYMTestCaseID SMS-SMSStack-NA-3062
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Status Report Time
//!@SYMTestPriority critical
//!@SYMTestActions  Test Status Report Time
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestStatusReportTime z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber62
END_TESTCASE SMS-SMSStack-NA-3062


START_TESTCASE SMS-SMSStack-NA-3063
//!@SYMTestCaseID SMS-SMSStack-NA-3063
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Tx 8Bit Wap With Status
//!@SYMTestPriority critical
//!@SYMTestActions  Test Transmit 8Bit wap message with status
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestTx8BitWapWithStatus z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber63
END_TESTCASE SMS-SMSStack-NA-3063


START_TESTCASE SMS-SMSStack-NA-3064
//!@SYMTestCaseID SMS-SMSStack-NA-3064
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Sim Store Corrupt Message
//!@SYMTestPriority critical
//!@SYMTestActions  Test sim store with corrupt message
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestSimStoreCorruptMessage z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber64
END_TESTCASE SMS-SMSStack-NA-3064



START_TESTCASE SMS-SMSStack-NA-3065
//!@SYMTestCaseID SMS-SMSStack-NA-3065
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Corrupt Pdu With Negative Response
//!@SYMTestPriority critical
//!@SYMTestActions  Test a corrupt pdu with anegative response
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_UTILS MakeReadWrite c:\private\101F7989\esock\smswap.sms.bak
RUN_UTILS copyfile c:\private\101F7989\esock\smswap.sms.esk c:\private\101F7989\esock\smswap.sms.bak
RUN_UTILS MakeReadWrite c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS copyfile z:\sms\testsmswap.sms.esk c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS MakeReadWrite c:\private\101F7989\esock\smswap.sms.esk
RUN_TEST_STEP 500 TE_smsprt TestCorruptPduWithNegativeResponse z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber65
RUN_UTILS DeleteFile c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS copyfile c:\private\101F7989\esock\smswap.sms.bak c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS DeleteFile c:\private\101F7989\esock\smswap.sms.bak
END_TESTCASE SMS-SMSStack-NA-3065


START_TESTCASE SMS-SMSStack-NA-3066
//!@SYMTestCaseID SMS-SMSStack-NA-3066
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Boot Timer can be configured to a non default value
//!@SYMTestPriority critical
//!@SYMTestActions  Check that boot timer can be configured from smswap.sms.esk file.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_UTILS MakeReadWrite c:\private\101F7989\esock\smswap.sms.bak
RUN_UTILS copyfile c:\private\101F7989\esock\smswap.sms.esk c:\private\101F7989\esock\smswap.sms.bak
RUN_UTILS MakeReadWrite c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS copyfile z:\sms\smswap.sms-bootTimerTimeout.esk c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS MakeReadWrite c:\private\101F7989\esock\smswap.sms.esk
RUN_TEST_STEP 500 TE_smsprt TestBootTimer z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber45
RUN_UTILS DeleteFile c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS copyfile c:\private\101F7989\esock\smswap.sms.bak c:\private\101F7989\esock\smswap.sms.esk
RUN_UTILS DeleteFile c:\private\101F7989\esock\smswap.sms.bak
END_TESTCASE SMS-SMSStack-NA-3066


START_TESTCASE SMS-SMSStack-NA-3067
//!@SYMTestCaseID SMS-SMSStack-NA-3067
//!@SYMREQ REQ4612
//!@SYMTestCaseDesc Test CSmsMessageTimeStamp
//!@SYMTestPriority critical
//!@SYMTestActions Create message with know system utc time.  Set and get also checked
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestCSmsMessageTimeStamp
END_TESTCASE SMS-SMSStack-NA-3067

START_TESTCASE SMS-SMSStack-NA-3068
//!@SYMTestCaseID SMS-SMSStack-NA-3068
//!@SYMREQ REQ4612
//!@SYMTestCaseDesc Test service center time stamp in PDU with CSmsMessage interface.
//!@SYMTestPriority critical
//!@SYMTestActions Simulate receiving deliver PDU's.  Create message and interogate PDU and check time stamp and validity period.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestCSmsMessageWithDeliverPDU z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber66
END_TESTCASE SMS-SMSStack-NA-3068

START_TESTCASE SMS-SMSStack-NA-3069
//!@SYMTestCaseID SMS-SMSStack-NA-3069
//!@SYMREQ REQ4612
//!@SYMTestCaseDesc Test Status Report
//!@SYMTestPriority critical
//!@SYMTestActions  Test status report
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestCSmsMessageWithStatusReportPDU z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber67
END_TESTCASE SMS-SMSStack-NA-3069

START_TESTCASE SMS-SMSStack-NA-3070
//!@SYMTestCaseID SMS-SMSStack-NA-3070
//!@SYMREQ REQ4612
//!@SYMTestCaseDesc Test Submit PDU
//!@SYMTestPriority critical
//!@SYMTestActions  Create a submit message.  Send it using SimTSY.  SimTSY will validate the PDU to what is expected.  Status=0
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestCSmsMessageWithSubmitPDU z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber68
END_TESTCASE SMS-SMSStack-NA-3070

START_TESTCASE SMS-SMSStack-NA-3071
//!@SYMTestCaseID SMS-SMSStack-NA-3071
//!@SYMREQ DEF055800
//!@SYMTestCaseDesc Test Handling of PDUs with PID 0x40
//!@SYMTestPriority critical
//!@SYMTestActions  Check that PDUs with PID 0x40 are acknowledged but not forwarded to the client
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_smsprt TestHandlePID40h z:\testdata\configs\smsstacksimtsytestnumbers.ini TestNumber69
END_TESTCASE SMS-SMSStack-NA-3071

RUN_SCRIPT  z:\testdata\scripts\smsstackcleanprivatedata.script
