// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors: 
//
// Description: Unit test case to test functionalities of CCmdCheckUserDrive,CCustomCmdClearStartupReason,CCustomCmdDeleteTempFiles,
//							CCmdInitRamDrive and CCustomCmdValidateRTC custom commands.
//

PRINT Run CCmdCheckUserDrive,CCustomCmdClearStartupReason,CCustomCmdDeleteTempFiles,CCmdInitRamDrive and CCustomCmdValidateRTC tests

LOAD_SUITE tunitcustcmd_server

START_TESTCASE 			DEVSRVS-SSREFPLUGINS-CUSTCMD-0028
//! @SYMTestCaseID 		DEVSRVS-SSREFPLUGINS-CUSTCMD-0028
//! @SYMDEF            		DEF139173
//! @SYMTestType		UT
//! @SYMTestPriority		High
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Tests the behaviour of CCustomCmdValidateRTC.
//! @SYMTestActions			The test performs operations on a CmdCheckUserDrive,CCustomCmdClearStartupReason,CCustomCmdDeleteTempFiles,CCmdInitRamDrive and CCustomCmdValidateRTC classess, namely calling the following methods:
//! 					1.	NewL - Creating the object
//! 					2.	Initialize - Initialising the custom cmd
//! 					3.	Execute - Executing the custom cmd
//!					4.	Close
//!					5.	Release
//! @SYMTestExpectedResults 	CmdCheckUserDrive,CCustomCmdClearStartupReason,CCustomCmdDeleteTempFiles and CCmdInitRamDrive  
//!														commands should execute normally and should complete with KErrNone. CCustomCmdValidateRTC command will complete with KErrNotSupported.
//!											
RUN_TEST_STEP 100 tunitcustcmd_server CTestCustomCmdExecute
END_TESTCASE 			DEVSRVS-SSREFPLUGINS-CUSTCMD-0028
