// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run CCustomCmdTestSecurityCheck tests

LOAD_SUITE tunitcustcmd_server

START_TESTCASE 			DEVSRVS-SSREFPLUGINS-CUSTCMD-0006
//! @SYMTestCaseID 		DEVSRVS-SSREFPLUGINS-CUSTCMD-0006
//! @SYMPREQ 			PREQ1871
//! @SYMREQ 			REQ9143, REQ9144 and REQ9138
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Tests behaviour of CSsmUiSpecific.
//! 				Tests Sim present behaviour of CCustomCmdCheck.
//! 				Tests Sim rejected behaviour of CCustomCmdCheck.
//! 				Tests Sim blocked behaviour of CCustomCmdCheck.
//! 				Tests Pin required behaviour of CCustomCmdCheck.
//! 				Tests Sim less offline support behaviour of CCustomCmdCheck.
//! 				Tests Sim lock behaviour of CCustomCmdCheck.
//! 				Tests Pin asked behaviour of CCustomCmdCheck.
//! 				Tests PUK asked behaviour of CCustomCmdCheck.
//! 				Tests Sim related functions of CCustomCmdCheck.
//! 				Tests security observer behaviour of CCustomCmdCheck.
//! @SYMTestActions			TestGeneralL() Test different functions on CSsmUiSpecific object. Followings functions are tested:
//! 					1. CSsmUiSpecific::StartupPSUid()
//! 					2. CSsmUiSpecific::SecurityPinNotifierUid()
//!					3. CSsmUiSpecific::IsSimlessOfflineSupported()
//! 					4. CSsmUiSpecific::InstanceL()
//! 					5. SetSecurityStatus()
//! 					6. SecurityStatus()
//! 					7. CSsmUiSpecific::Release()
//! 				Test HandleSIMPresent() on CCustomCmdCheck object with different security states
//! 				Test HandleSIMRejected() on CCustomCmdCheck object with different security states
//! 				Test HandleSIMBlocked() on CCustomCmdCheck object with different security states
//! 				Test HandlePINRequired() on CCustomCmdCheck object with different security states
//! 				Test HandleSIMLessOfflineSupported() on CCustomCmdCheck object with different security states
//! 				Test HandleSIMLock() on CCustomCmdCheck object with different security states
//! 				Test HandlePINAsked() on iCustomCmdCheck object with different security states
//! 				Test HandlePUKAsked() on CCustomCmdCheck object with different security states
//! 				Test TestSimFunctionsL() following functions on CCustomCmdCheck TestSimNotSupported
//! 				Test TestSecurityNoteObserverL() creation, destruction and observing functions of CSecurityNoteObserver class					
//! @SYMTestExpectedResults 	Command should execute normally and should complete with expected return code.
//! 				Command should execute normally and should complete with expected return code.
//! 				Command should execute normally and should complete with expected return code.
//! 				Command should execute normally and should complete with expected return code.
//! 				Command should execute normally and should complete with expected return code.
//! 				Command should execute normally and should complete with expected return code.
//! 				Command should execute normally and should complete with expected return code.
//! 				Command should execute normally and should complete with expected return code.
//! 				Command should execute normally and should complete with expected return code.
//! 				Command should execute normally and should complete with expected return code.
//! 				1. All the operations execute normally.
//! 				2. Should change the PS value inside the security note observer.
RUN_TEST_STEP 100 tunitcustcmd_server CCustomCmdTestSimSecurityCheck
END_TESTCASE 			DEVSRVS-SSREFPLUGINS-CUSTCMD-0006

