//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @File
//! @SYMTestSuiteName LBS-POSITIONING-STATUS
//! @SYMScriptTestEnvironment TEF

PRINT Run all te_lbspositioningstatusserver Suite Tests
LOAD_SUITE te_lbspositioningstatusserver


START_TESTCASE                LBS-POSITIONING-STATUS-1001
//! @SYMTestCaseID              LBS-POSITIONING-STATUS-1001
//! @SYMTestCaseDesc            Checking that the positioining status component works correctly
//! @SYMTestPriority            Low
//! @SYMTestActions             1. Change the MO-LR flag to be 1
//!                             2. Change the NI flag to be 1
//!                             2. Change the MO-LR and NI flags to be 0
//!                             2. Change the NI flag to be 1
//!                             2. Change the NI flag to be 2
//!                             2. Change the NI flag to be 0
//! @SYMTestExpectedResults     The client of the API gets notified correctly when there is a change in the positioning status
//! @SYMTestType                UT
//! @SYMCreationDate            24/3/2010
//! @SYMAuthor                  SorinBasca
//! @SYMTestStatus              3. Released
RUN_TEST_STEP 30 te_lbspositioningstatusserver StatusStep
END_TESTCASE                  LBS-POSITIONING-STATUS-1001

