//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script

PRINT TE_SocketServer: Component Tests
PRINT ------------------------------
PRINT

LOAD_SUITE TE_SocketServer
PRINT ------------------------------
PRINT


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0101
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0101

// run test 1
PRINT Test 1
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test1
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0101


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0102
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0102

// run test 2
PRINT Test 2
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test2
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0102


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0103
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0103

// run test 3
PRINT Test 3
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test3
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0103


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0104
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0104

// run test 4
PRINT Test 4
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_3.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test3
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0104


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0105
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0105

// run test 5
PRINT Test 5
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_4.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test5
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0105


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0106
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0106

// run test 6
PRINT Test 6
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_5.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test5
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0106


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0107
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0107

// run test 7
PRINT Test 7
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_4.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test7
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0107


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0108
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0108

// run test 8
PRINT Test 8
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_5.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test7
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0108


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0109
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0109

// run test 9
PRINT Test 9
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test9
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0109


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0110
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0110

// run test 10
PRINT Test 10
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_3.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test9
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0110


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0111
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0111

// run test 16
PRINT Test 16
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test16
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0111


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0112
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0112

// run test 17
//Taken out because base does not support this behavior and looks upon the
//Problem as a client error
//PRINT Test 17
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
//RUN_TEST_STEP !OOM 100 TE_SocketServer Test17
//TEST_COMPLETE
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0112


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0113
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0113

// run test 18
PRINT Test 18
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test18
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0113


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0114
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0114

// run test 20
PRINT Test 20
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test20
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0114


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0115
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0115

// run test 21
PRINT Test 21
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test21
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0115


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0116
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0116


// run test 22
PRINT Test 22
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test22
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0116


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0117
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0117

// run test 23
PRINT Test 23
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test23
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0117


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0118
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0118

// run test 24
PRINT Test 24
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test24
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0118


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0119
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0119

// run test 25
PRINT Test 25
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test25
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0119


START_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0120
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-OOM-0120

// run test 29
PRINT Test 29
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP !OOM 100 TE_SocketServer Test29
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-OOM-0120


RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_1.script

