//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script

PRINT TE_SocketServer: Component Tests
PRINT ------------------------------
PRINT

LOAD_SUITE TE_SocketServer
PRINT ------------------------------
PRINT


START_TESTCASE			COMINF-ESOCK-SocketServer-0101
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0101

// run test 1
PRINT Test 1
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test1
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0101


START_TESTCASE			COMINF-ESOCK-SocketServer-0102
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0102

// run test 2
PRINT Test 2
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test2
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0102


START_TESTCASE			COMINF-ESOCK-SocketServer-0103
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0103

// run test 3
PRINT Test 3
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test3
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0103


START_TESTCASE			COMINF-ESOCK-SocketServer-0104
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0104

// run test 4
PRINT Test 4
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_3.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test3
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0104


START_TESTCASE			COMINF-ESOCK-SocketServer-0105
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0105

// run test 5
PRINT Test 5
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_4.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test5
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0105


START_TESTCASE			COMINF-ESOCK-SocketServer-0106
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0106

// run test 6
PRINT Test 6
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_5.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test5
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0106


START_TESTCASE			COMINF-ESOCK-SocketServer-0107
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0107

// run test 7
PRINT Test 7
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_4.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test7
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0107


START_TESTCASE			COMINF-ESOCK-SocketServer-0108
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0108

// run test 8
PRINT Test 8
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_5.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test7
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0108


START_TESTCASE			COMINF-ESOCK-SocketServer-0109
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0109

// run test 9
PRINT Test 9
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test9
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0109


START_TESTCASE			COMINF-ESOCK-SocketServer-0110
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0110

// run test 10
PRINT Test 10
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_3.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test9
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0110


START_TESTCASE			COMINF-ESOCK-SocketServer-0111
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0111

// run test 16
PRINT Test 16
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test16
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0111


START_TESTCASE			COMINF-ESOCK-SocketServer-0112
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0112

// run test 17
//Taken out because base does not support this behavior and looks upon the
//Problem as a client error
//PRINT Test 17
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
//RUN_TEST_STEP 100 TE_SocketServer Test17
//TEST_COMPLETE
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0112


START_TESTCASE			COMINF-ESOCK-SocketServer-0113
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0113

// run test 18
PRINT Test 18
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test18
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0113


START_TESTCASE			COMINF-ESOCK-SocketServer-0114
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0114

// run test 20
PRINT Test 20
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test20
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0114


START_TESTCASE			COMINF-ESOCK-SocketServer-0115
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0115

// run test 21
PRINT Test 21
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test21
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0115


START_TESTCASE			COMINF-ESOCK-SocketServer-0116
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0116

// run test 22
PRINT Test 22
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test22
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0116


START_TESTCASE			COMINF-ESOCK-SocketServer-0117
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0117

// run test 23
PRINT Test 23
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test23
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0117


START_TESTCASE			COMINF-ESOCK-SocketServer-0118
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0118

// run test 24
PRINT Test 24
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test24
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0118


START_TESTCASE			COMINF-ESOCK-SocketServer-0119
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0119

// run test 25
PRINT Test 25
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test25
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0119


START_TESTCASE			COMINF-ESOCK-SocketServer-0120
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0120

// run test 29
PRINT Test 29
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
RUN_TEST_STEP 100 TE_SocketServer Test29
TEST_COMPLETE
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
END_TESTCASE			COMINF-ESOCK-SocketServer-0120



START_TESTCASE			COMINF-ESOCK-SocketServer-0121
//!@SYMTestCaseID		COMINF-ESOCK-SocketServer-0121
//!@SYMTestCaseDesc           	Confirm protocol manager support for 3PC based flows.
//!	Includes protocol reference ownership and protocol description support.
//!@SYMPREQ                   	DEF111327
//!@SYMTestPriority           	Critical
//!@SYMTestType               	CIT
//!@SYMTestExpectedResults
//! Expect protocol count to follow the configuration or otherwise of the extra 3PC based dummy protocol.
//! Expect protocol description available for 3PC based dummy protocol when configured.

LOAD_SUITE te_esockteststepsSuite -SharedData

// Unload esock to make config changes
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script

// Load esk files appropriate to dummy protocol, archiving the existing esk for reinstatement later
RUN_UTILS CopyFile c:\private\101f7989\ESock\ip.tcpip.esk c:\private\101f7989\ESock\ip.tcpip.esk.COMINF-ESOCK-SocketServer-0121.archive
RUN_UTILS DeleteFile c:\private\101f7989\ESock\ip.tcpip.esk
RUN_UTILS CopyFile z:\testdata\configs\ip.tcpip.esk.cominf-esock-socketserver_with_3pc_dummy_flow c:\private\101f7989\ESock\ip.tcpip.esk

// Load esock
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

// Create resources we need
RUN_TEST_STEP 100 te_esockteststepsSuite creatersocketservStep z:\testdata\configs\cominf-esock-socketserver-0121.ini CreateSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite connectrsocketservStep z:\testdata\configs\cominf-esock-socketserver-0121.ini ConnectSockSvr1

// Query the number of protocols
RUN_TEST_STEP 100 te_esockteststepsSuite SocketServerNumProtocolsStep z:\testdata\configs\cominf-esock-socketserver-0121.ini QueryNumProtocols

// Query the protocol info for the dummy protocol and then for the udp protocol
RUN_TEST_STEP 100 te_esockteststepsSuite SocketServerFindProtocolStep z:\testdata\configs\cominf-esock-socketserver-0121.ini QueryDummyProtocolDesc
RUN_TEST_STEP 100 te_esockteststepsSuite SocketServerFindProtocolStep z:\testdata\configs\cominf-esock-socketserver-0121.ini QueryUdpProtocolDesc

// Close the resources that we used
RUN_TEST_STEP 100 te_esockteststepsSuite closersocketservStep z:\testdata\configs\cominf-esock-socketserver-0121.ini CloseSockSvr1

// Unload esock in order to reinstate esock configuration
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script

// Reinstate archived esk file and ced so that esock is no longer aware of dummy protocol
RUN_UTILS MakeReadWrite c:\private\101f7989\ESock\ip.tcpip.esk
RUN_UTILS DeleteFile c:\private\101f7989\ESock\ip.tcpip.esk
RUN_UTILS CopyFile c:\private\101f7989\ESock\ip.tcpip.esk.cominf-esock-socketserver-0121.archive c:\private\101f7989\ESock\ip.tcpip.esk
RUN_UTILS DeleteFile c:\private\101f7989\ESock\ip.tcpip.esk.cominf-esock-socketserver-0121.archive

// Now going to confirm the values without the dummy flow in place
// Load esock again
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

RUN_TEST_STEP 100 te_esockteststepsSuite connectrsocketservStep z:\testdata\configs\cominf-esock-socketserver-0121.ini ConnectSockSvr1

// Confirm that we have one fewer protocols having removed the 3PC dummy protocol
RUN_TEST_STEP 100 te_esockteststepsSuite SocketServerNumProtocolsStep z:\testdata\configs\cominf-esock-socketserver-0121.ini QueryNumProtocols_2
RUN_TEST_STEP 100 te_esockteststepsSuite CompareIntegerValuesStep z:\testdata\configs\cominf-esock-socketserver-0121.ini ConfirmNumProtocolsDifference

RUN_TEST_STEP 100 te_esockteststepsSuite closersocketservStep z:\testdata\configs\cominf-esock-socketserver-0121.ini CloseSockSvr1

// Clean up
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep

RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesock_mayleak.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script

END_TESTCASE			COMINF-ESOCK-SocketServer-0121





START_TESTCASE			COMINF-ESOCK-SocketServer-0122
//! @SYMTestCaseID		COMINF-ESOCK-SocketServer-0122
//!@SYMTestCaseDesc
//! Confirm that starting and stopping a configured 3PC protocol from RSocketServ::Start() & RSocketServ::Stop()
//! returns silently without error.
//!@SYMPREQ                   	DEF111327
//!@SYMTestPriority           	Critical
//!@SYMTestType               	CIT
//!@SYMTestExpectedResults
//! Expect no error when starting or stopping a configured 3PC based protocol.
//! This behaviour is a backward compatibility measure as 3PC based flows are ECOM based and their loading is not managed by the protocol manager.

LOAD_SUITE te_esockteststepsSuite -SharedData

// Unload esock to make config changes
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_2.script

// Load esk files appropriate to dummy protocol, archiving the existing esk for reinstatement later
RUN_UTILS CopyFile c:\private\101f7989\ESock\ip.tcpip.esk c:\private\101f7989\ESock\ip.tcpip.esk.COMINF-ESOCK-SocketServer-0122.archive
RUN_UTILS DeleteFile c:\private\101f7989\ESock\ip.tcpip.esk
RUN_UTILS CopyFile z:\testdata\configs\ip.tcpip.esk.cominf-esock-socketserver_with_3pc_dummy_flow c:\private\101f7989\ESock\ip.tcpip.esk

// Load esock
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

// Create resources we need
RUN_TEST_STEP 100 te_esockteststepsSuite creatersocketservStep z:\testdata\configs\cominf-esock-socketserver-0122.ini CreateSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite connectrsocketservStep z:\testdata\configs\cominf-esock-socketserver-0122.ini ConnectSockSvr1

// Start the dummy protocol. This ought to return silently without doing anything as dummy is a 3PC type flow
RUN_TEST_STEP 100 te_esockteststepsSuite SocketServerStartProtocolStep z:\testdata\configs\cominf-esock-socketserver-0122.ini StartDummyProtocol

// Try a legacy protocol too
RUN_TEST_STEP 100 te_esockteststepsSuite SocketServerStartProtocolStep z:\testdata\configs\cominf-esock-socketserver-0122.ini StartTcpProtocol

// Try stopping the dummy protocol
RUN_TEST_STEP 100 te_esockteststepsSuite SocketServerStopProtocolStep z:\testdata\configs\cominf-esock-socketserver-0122.ini StopDummyProtocol

// Stop the legacy one too
RUN_TEST_STEP 100 te_esockteststepsSuite SocketServerStopProtocolStep z:\testdata\configs\cominf-esock-socketserver-0122.ini StopTcpProtocol

// Close the resources that we used
RUN_TEST_STEP 100 te_esockteststepsSuite closersocketservStep z:\testdata\configs\cominf-esock-socketserver-0122.ini CloseSockSvr1

// Clean up
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep

RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script

// Reinstate archived esk file and ced so that esock is no longer aware of dummy protocol
RUN_UTILS MakeReadWrite c:\private\101f7989\ESock\ip.tcpip.esk
RUN_UTILS DeleteFile c:\private\101f7989\ESock\ip.tcpip.esk
RUN_UTILS CopyFile c:\private\101f7989\ESock\ip.tcpip.esk.cominf-esock-socketserver-0122.archive c:\private\101f7989\ESock\ip.tcpip.esk
RUN_UTILS DeleteFile c:\private\101f7989\ESock\ip.tcpip.esk.cominf-esock-socketserver-0122.archive

RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script

END_TESTCASE			COMINF-ESOCK-SocketServer-0122



RUN_SCRIPT z:\testdata\scripts\te_esock_test_copy_config_1.script


