//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
//
PRINT example CommDb Protect test
PRINT 
//
run_script z:\TestData\scripts\esock_test_unloadesock.script
CED c:\test\CommDb\ts_commdb\C\Protect.xml -f
run_script z:\TestData\scripts\esock_test_loadesock.script

LOAD_SUITE TS_CommDb.dll

//Protecting Normal table
RUN_TEST_STEP -1, TS_CommDb,step_051_01
TEST_COMPLETE
//Protecting Connection Pref Table
RUN_TEST_STEP -1, TS_CommDb,step_053_01
TEST_COMPLETE

//UProtecting Normal table
RUN_TEST_STEP -1, TS_CommDb,step_051_02
TEST_COMPLETE
//UProtecting Connection Pref Table
RUN_TEST_STEP -1, TS_CommDb,step_053_02
TEST_COMPLETE

//Protecting Normal Record
RUN_TEST_STEP -1, TS_CommDb,step_052_01
TEST_COMPLETE
//Protecting Connection Pref Record
RUN_TEST_STEP -1, TS_CommDb,step_054_01
TEST_COMPLETE

//UProtecting Normal Record
RUN_TEST_STEP -1, TS_CommDb,step_052_02
TEST_COMPLETE
//UProtecting Connection Pref Record
RUN_TEST_STEP -1, TS_CommDb,step_054_02
TEST_COMPLETE


//Test Protecting Normal table
RUN_TEST_STEP -1, TS_CommDb,step_055_01
TEST_COMPLETE
//Protecting Connection Pref Table
RUN_TEST_STEP -1, TS_CommDb,step_057_01
TEST_COMPLETE

//Test UProtecting Normal table
RUN_TEST_STEP -1, TS_CommDb,step_055_02
TEST_COMPLETE
//UProtecting Connection Pref Table
RUN_TEST_STEP -1, TS_CommDb,step_057_02
TEST_COMPLETE

//Test Protecting Normal Record
RUN_TEST_STEP -1, TS_CommDb,step_056_01
TEST_COMPLETE
//TEst Protecting Connection Pref Record
RUN_TEST_STEP -1, TS_CommDb,step_058_01
TEST_COMPLETE

//Test UProtecting Normal Record
RUN_TEST_STEP -1, TS_CommDb,step_056_02
TEST_COMPLETE
//Test UProtecting Connection Pref Record
RUN_TEST_STEP -1, TS_CommDb,step_058_02
TEST_COMPLETE
