//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Running CASE19
PRINT Associate two sockets with one existing subconnection
RUN_UTILS DeleteFile c:\rconnectiontest.ini
RUN_UTILS CopyFile z:\testdata\configs\te_RSubConnectionCase19.ini c:\rconnectiontest.ini
RUN_UTILS MakeReadWrite c:\rconnectiontest.ini

//
LOAD_SUITE te_esockteststepsSuite -SharedData
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script
LOAD_SUITE te_echo

START_TESTCASE			COMINF-ESOCK-RSubconnection-0801
//! @SYMTestCaseID		COMINF-ESOCK-RSubconnection-0801
// start simtsy
RUN_TEST_STEP 100 te_esockteststepsSuite StartSimTSYStep z:\testdata\configs\te_RSubConnectionCase19.ini SimTsy

// start Echo Daemon
RUN_TEST_STEP 100 te_echo StartEchoDaemon c:\rconnectiontest.ini EchoDaemon1
RUN_TEST_STEP 100 te_echo StartEchoDaemon c:\rconnectiontest.ini EchoDaemon2

RUN_TEST_STEP 100 te_esockteststepsSuite creatersocketservStep z:\testdata\configs\te_RSubConnectionCase19.ini CreateSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite creatersocketStep z:\testdata\configs\te_RSubConnectionCase19.ini CreateTcpSock1
RUN_TEST_STEP 100 te_esockteststepsSuite creatersocketStep z:\testdata\configs\te_RSubConnectionCase19.ini CreateUdpSock2
RUN_TEST_STEP 100 te_esockteststepsSuite createrconnectionStep z:\testdata\configs\te_RSubConnectionCase19.ini CreateConn1
RUN_TEST_STEP 100 te_esockteststepsSuite creatersubconnectionStep z:\testdata\configs\te_RSubConnectionCase19.ini CreateSubConn1
RUN_TEST_STEP 100 te_esockteststepsSuite connectrsocketservStep z:\testdata\configs\te_RSubConnectionCase19.ini ConnectSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite openrconnectionStep z:\testdata\configs\te_RSubConnectionCase19.ini OpenConn1
RUN_TEST_STEP 100 te_esockteststepsSuite startrconnectionStep z:\testdata\configs\te_RSubConnectionCase19.ini StartConn1
RUN_TEST_STEP 100 te_esockteststepsSuite openrsubconnectionStep z:\testdata\configs\te_RSubConnectionCase19.ini OpenSubConn1
RUN_TEST_STEP 100 te_esockteststepsSuite openrsocketStep z:\testdata\configs\te_RSubConnectionCase19.ini OpenTcpSock1
RUN_TEST_STEP 100 te_esockteststepsSuite openrsocketStep z:\testdata\configs\te_RSubConnectionCase19.ini OpenTcpSock2

//uncomment below when RSubConnection::Open() supports EAttachToDefault
//RUN_TEST_STEP 100 te_esockteststepsSuite addrsockettorsubconnectionStep z:\testdata\configs\te_RSubConnectionCase19.ini AddTcpSock1ToSubConn1
RUN_TEST_STEP 100 te_esockteststepsSuite connectrsocketStep z:\testdata\configs\te_RSubConnectionCase19.ini ConnectTcpSock1
RUN_TEST_STEP 100 te_esockteststepsSuite sendreceiversocketStep z:\testdata\configs\te_RSubConnectionCase19.ini SendReceiveTcpSock1

//uncomment below when RSubConnection::Open() supports EAttachToDefault
//RUN_TEST_STEP 100 te_esockteststepsSuite addrsockettorsubconnectionStep z:\testdata\configs\te_RSubConnectionCase19.ini AddUdpSock2ToSubConn1
RUN_TEST_STEP 100 te_esockteststepsSuite connectrsocketStep z:\testdata\configs\te_RSubConnectionCase19.ini ConnectUdpSock2
RUN_TEST_STEP 100 te_esockteststepsSuite sendreceiversocketStep z:\testdata\configs\te_RSubConnectionCase19.ini SendReceiveUdpSock2
RUN_TEST_STEP 100 te_esockteststepsSuite closersocketStep z:\testdata\configs\te_RSubConnectionCase19.ini CloseTcpSock1
RUN_TEST_STEP 100 te_esockteststepsSuite closersocketStep z:\testdata\configs\te_RSubConnectionCase19.ini CloseUdpSock2
RUN_TEST_STEP 100 te_esockteststepsSuite closersubconnectionStep z:\testdata\configs\te_RSubConnectionCase19.ini CloseSubConn1
RUN_TEST_STEP 100 te_esockteststepsSuite closerconnectionStep z:\testdata\configs\te_RSubConnectionCase19.ini CloseConn1
RUN_TEST_STEP 100 te_esockteststepsSuite closersocketservStep z:\testdata\configs\te_RSubConnectionCase19.ini CloseSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep
END_TESTCASE			COMINF-ESOCK-RSubconnection-0801

// stop Echo Deamon
run_test_step 100, te_echo StopEchoDaemon c:\rconnectiontest.ini EchoDaemon1
run_test_step 100, te_echo StopEchoDaemon c:\rconnectiontest.ini EchoDaemon2

// stop simtsy
RUN_TEST_STEP 100 te_esockteststepsSuite StopSimTSYStep z:\testdata\configs\te_RSubConnectionCase19.ini SimTsy
RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script

PRINT Completed CASE19




