//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Running CASE41
PRINT Check Reject incoming connection

//
LOAD_SUITE te_esockteststepsSuite -SharedData
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE			COMINF-ESOCK-RSubconnection-3001
//! @SYMTestCaseID		COMINF-ESOCK-RSubconnection-3001

RUN_TEST_STEP 100 te_esockteststepsSuite creatersocketservStep z:\testdata\configs\te_RSubConnectionCase41.ini CreateSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite createrconnectionStep z:\testdata\configs\te_RSubConnectionCase41.ini CreateConn1
RUN_TEST_STEP 100 te_esockteststepsSuite creatersubconnectionStep z:\testdata\configs\te_RSubConnectionCase41.ini CreateSubConn1
RUN_TEST_STEP 100 te_esockteststepsSuite creatersubconparameterbundleStep z:\testdata\configs\te_RSubConnectionCase41.ini CreateSubConn1Params
RUN_TEST_STEP 100 te_esockteststepsSuite creatersubconparameterfamilyStep z:\testdata\configs\te_RSubConnectionCase41.ini CreateSubConn1ParamsFamily
RUN_TEST_STEP 100 te_esockteststepsSuite connectrsocketservStep z:\testdata\configs\te_RSubConnectionCase41.ini ConnectSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite openrconnectionStep z:\testdata\configs\te_RSubConnectionCase41.ini OpenConn1
RUN_TEST_STEP 100 te_esockteststepsSuite startrconnectionStep z:\testdata\configs\te_RSubConnectionCase41.ini StartConn1
RUN_TEST_STEP 100 te_esockteststepsSuite waitforincomingconnectionStep z:\testdata\configs\te_RSubConnectionCase41.ini WaitForIncomingOnConn1
RUN_TEST_STEP 100 te_esockteststepsSuite initialiseGenQosParameterSetStep z:\testdata\configs\te_RSubConnectionCase41.ini InitGenQosParams
RUN_TEST_STEP 100 te_esockteststepsSuite getrsubconparametersStep z:\testdata\configs\te_RSubConnectionCase41.ini GetParamsOnSubConn1
RUN_TEST_STEP 100 te_esockteststepsSuite comparegenqosparametersetStep z:\testdata\configs\te_RSubConnectionCase41.ini CompareSubConnParams
RUN_TEST_STEP 100 te_esockteststepsSuite rejectincomingconnectionStep z:\testdata\configs\te_RSubConnectionCase41.ini RejectIncomingConnection
RUN_TEST_STEP 100 te_esockteststepsSuite closerconnectionStep z:\testdata\configs\te_RSubConnectionCase41.ini CloseConn1
RUN_TEST_STEP 100 te_esockteststepsSuite closersocketservStep z:\testdata\configs\te_RSubConnectionCase41.ini CloseSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep
END_TESTCASE			COMINF-ESOCK-RSubconnection-3001

RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script

PRINT Completed CASE41


