// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Copies RWindow files from rom (or simulated rom in case of emulator) to c to make
// it easier to manually run tests from c
// 
//

RUN_UTILS MkDir c:\graphics\

// copy script files
RUN_UTILS CopyFile	z:\graphics\graphics-wserv-integ-dsa.script	c:\graphics\graphics-wserv-integ-dsa.script
RUN_UTILS MakeReadWrite	c:\graphics\graphics-wserv-integ-dsa.script

// copy ini data file
RUN_UTILS CopyFile	z:\graphics\graphics-wserv-integ-dsa.ini	c:\graphics\graphics-wserv-integ-dsa.ini
RUN_UTILS MakeReadWrite	c:\graphics\graphics-wserv-integ-dsa.ini

