//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
// Shutdown esock in order to modify the comms database, update the database and restart esock
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
ced z:\testdata\configs\te_zerocopy_loopback_link_enabled.cfg
run_script z:\testdata\scripts\te_esock_test_loadesock.script


// Load and run our tcp loopback test case
load_suite te_loopback

start_testcase TcpLoop

run_test_step 1000 te_loopback tcploop z:\TestData\configs\te_zerocopy_loopback.ini

end_testcase			TcpLoop


// Unload
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script


