//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all te_C32PerformanceUSBTests Tests
LOAD_SUITE te_C32PerformanceSuite

//! @SYMTestCaseID NET-C32-I-0064-HP
//! @SYMTestCaseDesc Load ECACM in Dealer thread
//! @SYMPREQ Preq890
//! @SYMTestActions Send 1 MB of data through ECACM loaded in Dealer thread
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0064-HP
PRINT Test scenario :- Load ECACM in Dealer thread
PRINT Copying CMI files

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig14\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig14\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig14\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig14\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig14\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite12.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script


/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestCaseID NET-C32-I-0065-HP
//! @SYMTestCaseDesc Load ECACM in a Player thread
//! @SYMPREQ Preq890
//! @SYMTestActions Send 1 MB of data through ECACM loaded in a Player thread
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0065-HP
PRINT Test scenario :- Load ECACM in a Player thread

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig15\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig15\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig15\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig15\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig15\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite13.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script


/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestCaseID NET-C32-I-0066-HP
//! @SYMTestCaseDesc Load ECACM and ECUART in dealer thread.
//! @SYMPREQ Preq890
//! @SYMTestActions Sending 1MB of data through ECACM and ECUART which are loaded in dealer thread.
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0066-HP
PRINT Test scenario :- Load ECACM and ECUART in in dealer thread.
PRINT Copying CMI files

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig16\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig16\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig16\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig16\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig16\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite14.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestCaseID NET-C32-I-0067-HP
//! @SYMTestCaseDesc Load ECACM in Dealer thread and ECUART in a Player thread
//! @SYMPREQ Preq890
//! @SYMTestActions Sending 1MB of data through ECACM which is loaded in dealer thread and ECUART in player  thread
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0067-HP
PRINT Test scenario :- Load ECACM in Dealer thread and ECUART in a Player thread
PRINT Copying CMI files

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig17\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig17\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig17\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig17\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig17\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite15.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestCaseID NET-C32-I-0068-HP
//! @SYMTestCaseDesc Load EACM and ECUART in separate player threads
//! @SYMPREQ Preq890
//! @SYMTestActions Send 1MB of data through EACM and ECUART which are loaded in two separate player threads
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0068-HP
PRINT Test scenario :- Load EACM and ECUART in separate player threads
PRINT Copying CMI files

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig18\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig18\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig18\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig18\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig18\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite16.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script


/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestCaseID NET-C32-I-0069-HP
//! @SYMTestCaseDesc Load EACM and ECUART in same player thread
//! @SYMPREQ Preq890
//! @SYMTestActions Sending 1MB of data through EACM  and ECUART which are loaded in same  player threads
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0069-HP
PRINT Test scenario :- Load EACM and ECUART in same player thread
PRINT Copying CMI files

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig19\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig19\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig19\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig19\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig19\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite17.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestCaseID NET-C32-I-0070-HP
//! @SYMTestCaseDesc Load EACM in Dealer thread and ECUART, Loopback, DummyCsy,DummyCsy1, DummyCsy2 in separate Player threads
//! @SYMPREQ Preq890
//! @SYMTestActions Send 1 MB of data through EACM which is loaded in dealer thread and ECUART, Loopback, DummyCsy,DummyCsy1, DummyCsy2  loaded in separate player threads. 
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0070-HP
PRINT Test scenario :- Send 1 MB of data through EACM which is loaded in dealer thread and ECUART, Loopback, DummyCsy,DummyCsy1, DummyCsy2  loaded in separate player threads. 
PRINT Copying CMI files

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig20\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig20\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig20\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig20\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig20\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig20\c32_fifth.cmi c:\private\101F7988\c32_fifth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fifth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite18.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestCaseID NET-C32-I-0071-HP
//! @SYMTestCaseDesc Load Loopback in Dealer thread, Dummy and DummyCsy1 in same Player Thread,DummyCsy2 in another Player Thread, DummyCsy3 in another Player thread
//! @SYMPREQ Preq890
//! @SYMTestActions Sending data through Loopback loaded in Dealer thread, Dummy and DummyCsy1 in same Player Thread,DummyCsy2 in another Player Thread, DummyCsy3 in another Player thread
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0071-HP
PRINT Test scenario :- Load Loopback in Dealer thread, Dummy and DummyCsy1 in same Player Thread,DummyCsy2 in another Player Thread, DummyCsy3 in another Player thread
PRINT Copying CMI files

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig21\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig21\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig21\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig21\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig21\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig21\c32_fifth.cmi c:\private\101F7988\c32_fifth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fifth.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig21\c32_sixth.cmi c:\private\101F7988\c32_sixth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_sixth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite19.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script


/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestCaseID NET-C32-I-0072-HP
//! @SYMTestCaseDesc Load EACM ,ECUART, Loopback, DummyCsy,DummyCsy1, DummyCsy2 in same Player thread
//! @SYMPREQ Preq890
//! @SYMTestActions Send 1mb of data through EACM,ECUART ,Loopback, DummyCsy, DummyCsy1, DummyCsy2 loaded in same  player thread
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0072-HP
PRINT Test scenario :- Send 1mb of data through EACM,ECUART ,Loopback, DummyCsy, DummyCsy1, DummyCsy2 loaded in same  player thread
PRINT Copying CMI files

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig22\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig22\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig22\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig22\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig22\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite20.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestCaseID NET-C32-I-0073-HP
//! @SYMTestCaseDesc Send 1 MB of data through EACM,ECUART loaded  in same Player thread, Loopback and DummyCsy in another player thread,DummyCsy1 and DummyCsy2 in another player thread
//! @SYMPREQ Preq890
//! @SYMTestActions Send 1 MB of data through EACM,ECUART loaded  in same Player thread, Loopback and DummyCsy in another player thread,DummyCsy1 and DummyCsy2 in another player thread
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0073-HP
PRINT Test scenario :- Send 1 MB of data through EACM,ECUART loaded  in same Player thread, Loopback and DummyCsy in another player thread,DummyCsy1 and DummyCsy2 in another player thread
PRINT Copying CMI files

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig23\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig23\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig23\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig23\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig23\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite21.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestCaseID NET-C32-I-0074-HP
//! @SYMTestCaseDesc Send data through ACM CSY (1 MB Data ) loaded in one  Player thread, ECUART loaded in another player thread,Loopback and DummyCsy in another player thread,DummyCsy1 and DummyCsy2 in another player thread
//! @SYMPREQ Preq890
//! @SYMTestActions Send data through ACM CSY (1 MB Data ) loaded in one  Player thread, ECUART loaded in another player thread,Loopback and DummyCsy in another player thread,DummyCsy1 and DummyCsy2 in another player thread
//! @SYMTestExpectedResults Compare the execution time with old C32 code
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType ST

PRINT Test case ID  :- NET-C32-I-0074-HP
PRINT Test scenario :- Send data through ACM CSY (1 MB Data ) loaded in one  Player thread, ECUART loaded in another player thread,Loopback and DummyCsy in another player thread,DummyCsy1 and DummyCsy2 in another player thread
PRINT Copying CMI files

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig24\c32.cmi c:\private\101F7988\c32.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig24\c32_first.cmi c:\private\101F7988\c32_first.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_first.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig24\c32_second.cmi c:\private\101F7988\c32_second.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_second.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig24\c32_third.cmi c:\private\101F7988\c32_third.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_third.cmi

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32PerformanceConfig24\c32_fourth.cmi c:\private\101F7988\c32_fourth.cmi
RUN_UTILS MakeReadWrite c:\private\101F7988\c32_fourth.cmi

RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script

RUN_TEST_STEP 10000 te_C32PerformanceSuite CC32RunThreadStep z:\testdata\configs\te_C32PerformanceSuite22.ini 

RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

PRINT Complete te_C32PerformanceUSBTests
