// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Tests in this script run in "Network Lifetime" mode and do not require a network connection.
// TE_RConnectionSuite UPS Tests
// 
//

//! @file te_rconnectionupstests_netlifetime_NonConnected.script
//! @SYMTestSuiteName COMINF-ESOCK-RConnectionSuite-UPS
//! @SYMScriptTestEnvironment networking

// Shutdown ESock, load the appropriate CommDB
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
ced z:\TestData\configs\rconnectionudp.xml

// Copy across the necessary config file
run_utils MakeReadWrite c:\rconnectiontest.ini
run_utils DeleteFile c:\rconnectiontest.ini
run_utils CopyFile z:\TestData\configs\rconnectiontest_vlan7.ini c:\rconnectiontest.ini
RUN_UTILS MakeReadWrite c:\rconnectiontest.ini

// Copy across the Reference policy file under test
run_utils mkdir c:\private\10283558\
run_utils mkdir c:\private\10283558\policies\
run_utils CopyFile z:\System\data\ups_101F7989_10281DD8.rsc c:\private\10283558\policies\ups_101F7989_10281DD8.rsc
run_utils MakeReadWrite c:\private\10283558\policies\ups_101F7989_10281DD8.rsc

// Copy across the "Network Lifetime" NetUPS component coniguration file
run_utils MakeReadWrite c:\private\101f7989\esock\netups.ini
run_utils DeleteFile c:\private\101f7989\esock\netups.ini
run_utils mkdir c:\private\101f7989\
run_utils mkdir c:\private\101f7989\esock\
run_utils CopyFile z:\TestData\configs\netups_NetLifetime.ini c:\private\101f7989\esock\netups.ini
run_utils MakeReadWrite c:\private\101f7989\esock\netups.ini

// Copy across the config file specific to the UPS tests
run_utils MakeReadWrite c:\ipupstest.ini
run_utils CopyFile z:\TestData\configs\ipupstest.ini c:\ipupstest.ini

//Restart ESock
run_script z:\TestData\scripts\te_esock_test_loadesock.script


// Load the necessary test servers
LOAD_SUITE TE_RConnectionUpsSuite

//Set overriding of test notifier config file
RUN_TEST_STEP 100, TE_RConnectionUpsSuite SetNotifFileOverride


PRINT
PRINT  ---- Implicit, Always, Network Lifetime ----
PRINT

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0284
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0284
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted when response is Always. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo on a UDP socket.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest1b c:\rconnectiontest.ini TestConfig1
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0284

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0285
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0285
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted only once for both Always response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo followed by another Implicit RSocket::SendTo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest2b c:\rconnectiontest.ini TestConfig2
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0285

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0286
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0286
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted only once for both Always response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, followed by Implicit RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest3b c:\rconnectiontest.ini TestConfig2
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0286

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0287
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0287
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted only once for both Always response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, followed by RConnection::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest6b c:\rconnectiontest.ini TestConfig2
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0287

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0288
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0288
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted after every Always response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, Delete UPS decision Database, followed by RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest7b c:\rconnectiontest.ini TestConfig47
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0288

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0289
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0289
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted only once for Always and SessionNo response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit Implicit RSocket::SendTo, close RSocket, Delete UPS decision Database, followed by RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

//Copy of Standard Test 7 but second button press is SessionNo so second API call should fail
heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest7b c:\rconnectiontest.ini TestConfig48
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0289

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script



PRINT
PRINT  ---- Implicit, SessionYes, Network Lifetime ----
PRINT

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0290
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0290
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted when response is SessionYes. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo() on a UDP socket.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest1b c:\rconnectiontest.ini TestConfig3
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0290

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0291
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0291
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted only once for both SessionYes response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo followed by another Implicit RSocket::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest2b c:\rconnectiontest.ini TestConfig4
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0291

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0292
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0292
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted for both SessionYes response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, followed by Implicit RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest3b c:\rconnectiontest.ini TestConfig51
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0292

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0293
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0293
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted for both SessionYes and Never response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, followed by Implicit RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

//Copy of Standard Test 3 but second button press is never so second API call should fail
heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest3b c:\rconnectiontest.ini TestConfig52
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0293

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0294
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0294
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted only once for both SessionYes response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, followed by RConnection::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest6b c:\rconnectiontest.ini TestConfig4
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0294

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0295
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0295
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted for both SessionYes response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, Delete UPS decision Database, followed by RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest7b c:\rconnectiontest.ini TestConfig51
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0295

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0296
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0296
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted for both SessionYes and Never response. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, Delete UPS decision Database, followed by RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

//Copy of Standard Test 7 but second button press is Never so second API call should fail
heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest7b c:\rconnectiontest.ini TestConfig52
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0296

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


PRINT
PRINT  ---- Implicit, Never, Network Lifetime ----
PRINT

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0297
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0297
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted when response is Never, appropriate error code is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::Connect() on a TCP socket
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest1b c:\rconnectiontest.ini TestConfig5
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0297

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0298
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0298
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Appropriate error code is returned when user respond first with Never, then with Always(Prompted only once). Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo followed by another Implicit RSocket::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest2b c:\rconnectiontest.ini TestConfig8
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0298

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0299
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0299
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Appropriate error code is returned when user respond first with Never, then with Always(Prompted only once). Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, followed by Implicit RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest3b c:\rconnectiontest.ini TestConfig8
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0299

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0300
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0300
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Appropriate error code is returned when user respond first with Never, then with Always(Prompted only once). Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, followed by RConnection::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest6b c:\rconnectiontest.ini TestConfig8
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0300

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0301
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0301
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Appropriate error code is returned when user respond with Never twice(Prompted only once). Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, Delete UPS decision Database, followed by RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest7b c:\rconnectiontest.ini TestConfig55
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0301

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0302
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0302
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Appropriate error code is returned when user respond with Never and SessionYes(Prompted only once). Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, Delete UPS decision Database, followed by RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

//Copy of Standard Test 7 but second button press is SessionYes so second API call should pass
heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest7b c:\rconnectiontest.ini TestConfig58
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0302

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script



PRINT
PRINT  ---- Implicit, SessionNo, Network Lifetime ----
PRINT

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0303
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0303
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted and response is SessionNo. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo on a UDP socket
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest1b c:\rconnectiontest.ini TestConfig16
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0303

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0304
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0304
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when both the responses are SessionNo. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo followed by another Implicit RSocket::SendTo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest2b c:\rconnectiontest.ini TestConfig19
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0304

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0305
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0305
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when both the responses are SessionNo. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, followed by Implicit RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest3b c:\rconnectiontest.ini TestConfig61
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0305

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0306
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0306
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when responses are SessionNo and Always. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, followed by Implicit RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

//Copy of Standard Test 3 but second button press is Always so second API call should pass
heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest3b c:\rconnectiontest.ini TestConfig64
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0306

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0307
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0307
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when both the responses are SessionNo. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, followed by RConnection::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest6b c:\rconnectiontest.ini TestConfig19
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0307

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0308
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0308
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when both the responses are SessionNo. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, Delete UPS decision Database, followed by RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest7b c:\rconnectiontest.ini TestConfig61
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0308

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0309
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0309
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when responses are SessionNo and Always. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo, close RSocket, Delete UPS decision Database, followed by RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

//Copy of Standard Test 7 but second button press is Always so second API call should pass
heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest7b c:\rconnectiontest.ini TestConfig64
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0309

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script



PRINT
PRINT  ---- Explicit, Always, Network Lifetime ----
PRINT

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0310
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0310
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when both the responses are Always. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an explicit RSocket::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest11 c:\rconnectiontest.ini TestConfig28
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0310

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0311
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0311
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when all three responses are Always. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an explicit RSocket::SendTo followed by an explicit RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest15 c:\rconnectiontest.ini TestConfig29
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0311

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0312
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0312
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when all three responses are Always. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by RConnection2::Start followed by an explicit RSocket::SendTo using RConnection2.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest16 c:\rconnectiontest.ini TestConfig29
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0312

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0313
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0313
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when all three responses are Always. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start, close RConnection, RConnection2::Start, followed by an explicit RSocket::SendTo on RConnection2.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest17 c:\rconnectiontest.ini TestConfig29
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0313

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0314
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0314
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted twice when all three responses are Always. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start, close RConnection, Delete UPS Decision DB Followed by an RConnection2::Start, followed by an explicit.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest18 c:\rconnectiontest.ini TestConfig67
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0314

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0315
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0315
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when both the responses are Always. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest19 c:\rconnectiontest.ini TestConfig28
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0315

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0316
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0316
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when all three responses are Always. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo followed by RConnection2::Start, followed by RConnection3::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest23 c:\rconnectiontest.ini TestConfig30
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0316

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0317
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0317
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when all three responses are Always. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo, followed by RConnection2::Start. Close all RSockets and RConnections, followed by RConnection3::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest24 c:\rconnectiontest.ini TestConfig30
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0317

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script



PRINT
PRINT  ---- Explicit, SessionYes, Network Lifetime ----
PRINT


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0318
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0318
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when both the responses are SessionYes. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an explicit RSocket::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest11 c:\rconnectiontest.ini TestConfig32
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0318

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0319
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0319
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when all the three responses are SessionYes. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an explicit RSocket::SendTo, followed by an explicit RSocket2::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest15 c:\rconnectiontest.ini TestConfig33
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0319

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0320
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0320
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when all the three responses are SessionYes. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by RConnection2::Start, followed by an explicit RSocket::SendTo using RConnection2.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest16 c:\rconnectiontest.ini TestConfig33
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0320

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0321
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0321
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when all the three responses are SessionYes. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start, close RConnection, RConnection2::Start, followed by an explicit RSocket::SendTo on RConnection2.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest17 c:\rconnectiontest.ini TestConfig68
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0321

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0322
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0322
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted twice when all the three responses are SessionYes. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start, close RConnection, Delete UPS Decision DB, Followed by an RConnection2::Start, followed by an explicit.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest18 c:\rconnectiontest.ini TestConfig85
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0322

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0323
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0323
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when both the responses are SessionYes. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest19 c:\rconnectiontest.ini TestConfig32
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0323

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0324
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0324
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when all three responses are SessionYes. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo,followed by RConnection2::Start,followed by RConnection3::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest23 c:\rconnectiontest.ini TestConfig34
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0324

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0325
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0325
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted twice when all four responses are SessionYes. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo,followed by RConnection2::Start. Close all RSockets and RConnections, followed by RConnection3::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest24 c:\rconnectiontest.ini TestConfig86
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0325

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script



PRINT
PRINT  ---- Explicit, Never, Network Lifetime ----
PRINT

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0326
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0326
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc ----Invalid test!
//!@SYMTestPriority Critical
//!@SYMTestActions ----Invalid test!
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

// Never followed by SessionYes - Invalid test!
//heap_mark
//run_test_step 100, TE_RConnectionUpsSuite UPSTest18 c:\rconnectiontest.ini TestConfig71
//heap_markend
//test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0326

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0327
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0327
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when the responses are Never and then Always. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest19 c:\rconnectiontest.ini TestConfig36
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0327

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0328
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0328
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when the responses are Never and then Always. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo,followed by RConnection2::Start,followed by RConnection3::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest23 c:\rconnectiontest.ini TestConfig40
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0328

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0329
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0329
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when the responses are Never and then Always. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo,followed by RConnection2::Start. Close all RSockets and RConnections,followed by RConnection3::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest24 c:\rconnectiontest.ini TestConfig40
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0329

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script



PRINT
PRINT  ---- Explicit, SessionNo, Network Lifetime ----
PRINT

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0330
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0330
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when the responses are SessionNo and Always. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest19 c:\rconnectiontest.ini TestConfig42
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0330

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0331
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0331
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when the responses are SessionNo and Always. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo,followed by RConnection2::Start, followed by RConnection3::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest23 c:\rconnectiontest.ini TestConfig46
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0331

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0332
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0332
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted once when the responses are SessionNo and Always. Appropriate error is returned. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions RConnection::Start followed by an implicit RSocket::SendTo,followed by RConnection2::Start. Close all RSockets and RConnections,followed by RConnection3::Start.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest24 c:\rconnectiontest.ini TestConfig46
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0332

run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script


PRINT
PRINT ---- Advanced Tests ----
PRINT

START_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0333
//! @SYMTestCaseID COMINF-ESOCK-RConnectionSuite-UPS-0333
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User prompted twice when both the responses are SessionYes. Test run in "Network Lifetime" mode.
//!@SYMTestPriority Critical
//!@SYMTestActions Implicit RSocket::SendTo specifying a local address of interface SendTo to a local address should never result in prompting.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT
//! @SYMCreationDate        15-04-2008
//!@SYMTestStatus 3. Released

heap_mark
run_test_step 100, TE_RConnectionUpsSuite UPSTest31 c:\rconnectiontest.ini TestConfig81
heap_markend
test_complete
END_TESTCASE COMINF-ESOCK-RConnectionSuite-UPS-0333


run_test_step 100, TE_RConnectionUpsSuite CloseInterfaces
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_script z:\TestData\scripts\te_esock_test_loadesock.script



## close down
run_utils DeleteFile c:\rconnectiontest.ini

//Unset overriding of test notifier config file
RUN_TEST_STEP 100, TE_RConnectionUpsSuite UnsetNotifFileOverride
