//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

#
# do udp testing with the dummy nif and null agt
#
 run_script z:\TestData\scripts\te_rconnectionudptests_Connection.script

#
# now do tests with tcp sockets (with nt ras)
#

run_script z:\TestData\scripts\te_rconnectiontcptests_Connection.script

#
# now do host resolver tests (with nt ras)
#

run_script z:\TestData\scripts\te_rconnectionhostresolvertests_Connection.script

#
# now do all interface notification tests
#

run_script z:\TestData\scripts\te_rconnectionallinterfacenotificationtests_Connection.script

#
# do connection managment tests
#

run_script z:\TestData\scripts\te_RConnectioncmmtests_Connection.script

#
# do host resolver tests with bad NT RAS username/password
#

run_script z:\TestData\scripts\te_RConnectionNTRAS_BadTests_Connection.script

#
# do ethernet config daemon tests using DHCP
#

run_script z:\testdata\scripts\te_RConnectionConfigDaemonTests_Connection.script

#
# force CCover to write back any changes to its data file before shutting down. In non-CCover
# builds this will do nothing.


test_complete
