//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
ced z:\TestData\configs\ainethernet.xml
run_script z:\TestData\scripts\te_esock_test_loadesock.script

run_utils DeleteFile c:\rconnectiontest.ini
run_utils CopyFile z:\TestData\configs\rconnectiontest_vlan2.ini c:\rconnectiontest.ini
RUN_UTILS MakeReadWrite c:\rconnectiontest.ini

run_script z:\TestData\scripts\te_rconnectionallinterfacenot_Connection_Tests.script

run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
run_utils DeleteFile c:\rconnectiontest.ini