//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
//! @file
//! @SYMTestSuiteName APPFWK-SYSMON
// 

//
LOAD_SERVER tsysmon_server
//

//! @SYMTestCaseID 		DEVSRVS-SYSSTART-SYSMON-0031
//! @SYMPREQ 			PREQ1089
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies
//! @SYMTestCaseDesc	Attempt to register a System Critical process
//! @SYMTestActions		The process to be registered must be running and be set as System Critical.
//! Open a connection to the SysMon process. (This will return 'KErrNone'.)
//! Attempt to register the process.
//! @SYMTestExpectedResults 	The attempt to register the process returns 'KErrNotSupported'
//
START_TESTCASE DEVSRVS-SYSSTART-SYSMON-0031
RUN_TEST_STEP 100 tsysmon_server Register z:\sysstarttest\configs\tsysmon.ini APPFWK-SYSMON-0031
END_TESTCASE DEVSRVS-SYSSTART-SYSMON-0031
