// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run RestartThrottle test 

LOAD_SUITE tsysmon_server
START_TESTCASE 			DEVSRVS-SYSSTART-SYSMON-0004
//! @SYMTestCaseID 		DEVSRVS-SYSSTART-SYSMON-0004
//! @SYMPREQ 			PREQ1089
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		A process can be restarted on failure only after throttle time.
//! @SYMTestActions		1. Start a process 
//! 				2. Call RSysMonSession::Monitor() for this process with EWaitForStart, retry count = 1, 
//! 				   and EIgnoreProcessFailure.
//! 				3. Kill the process
//! 				5. Then the test should try connect to the TestApp. The connection should fail - this 
//! 				   is the actual test
//! 				6. The test execute test should wait the throttle time (may be 15 sec). 
//! 				7. Then try to connect to the server and poke the server. This is because System Monitor 
//! 				   will wait throttle time to restart the process. 	   
//! @SYMTestExpectedResults 	pass
RUN_TEST_STEP 100 tsysmon_server RestartThrottle
END_TESTCASE 			DEVSRVS-SYSSTART-SYSMON-0004
