// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run SelfMonIgnore test 

LOAD_SUITE tsysmon_server

START_TESTCASE 			DEVSRVS-SYSSTART-SYSMON-0006
//! @SYMTestCaseID 		DEVSRVS-SYSSTART-SYSMON-0006
//! @SYMPREQ 			PREQ1089
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Self monitoring with ignore failure should not need any plat sec capability.
//! @SYMTestActions		1. Start a process from test-execute test. 
//! 				2. Make sure the process has NO caps
//! 				3. Assert that Sysmon refuse recoverymethod ERestartOS for MonitorSelf
//! 				4. Assert that Sysmon accept recoverymethod EIgnoreOnFailure for MonitorSelf
//! 				5. Kill the process and let it restart.
//! 				6. Bonusstep, assert that commandline arguments is preserved when restarting process
//! 				7. Cleanup and shutdown
//! @SYMTestExpectedResults 	Pass
RUN_TEST_STEP 100 tsysmon_server SelfMonIgnore
END_TESTCASE 			DEVSRVS-SYSSTART-SYSMON-0006

