# commonengine level configuration makefile

#Define this platform as default if nothing is defined

MAKEFILE = $(EPOCROOT)/sf/os/devicesrv/commonservices/commonengine/makefile

commonengine_all    :: commonengine_config

include include_template.mk