// Copyright (c) 2003-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_SCRIPT z:\TestData\Scripts\TE_etelisv_setup.script

RUN_PROGRAM -1 setcap TE_EtelIsv.exe FFFFE c:\sys\bin\TE_EtelIsv1.exe  

PRINT Start TE_etelisv Test Suite

LOAD_SUITE TE_EtelIsv1

PRINT  Start TE_etelisv1 Test Suite

START_TESTCASE TEL-EtelIsv-GT0166-1000
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1000
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Get Phone Id
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the Phone Id using etelisv 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetPhoneId z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetPhoneId z:\testdata\configs\te_etelisv.ini BufferModeDisabled
   
END_TESTCASE TEL-EtelIsv-GT0166-1000

START_TESTCASE TEL-EtelIsv-GT0166-1001
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1001
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Get Phone Id Error Scenario
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the Phone Id Error scenario using etelisv
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetPhoneIdError z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetPhoneIdError z:\testdata\configs\te_etelisv.ini BufferModeDisabled
 
END_TESTCASE TEL-EtelIsv-GT0166-1001

START_TESTCASE TEL-EtelIsv-GT0166-1002
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1002
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Get Subscriber Id
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the Subscriber ID using etelisv
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT 
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetSubscriberId z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetSubscriberId z:\testdata\configs\te_etelisv.ini BufferModeDisabled
 
END_TESTCASE TEL-EtelIsv-GT0166-1002

START_TESTCASE TEL-EtelIsv-GT0166-1003
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1003
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Get SubscriberId with Error
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the subscriber Id error scenario
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT 
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetSubscriberIdError z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetSubscriberIdError z:\testdata\configs\te_etelisv.ini BufferModeDisabled
  
 
END_TESTCASE TEL-EtelIsv-GT0166-1003

START_TESTCASE TEL-EtelIsv-GT0166-1004
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1004
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Get Indicator
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the idicators
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetIndicator z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetIndicator z:\testdata\configs\te_etelisv.ini BufferModeDisabled
 
 
END_TESTCASE TEL-EtelIsv-GT0166-1004

START_TESTCASE TEL-EtelIsv-GT0166-1005
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1005
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Get Battery Info
//!@SYMTestPriority critical
//!@SYMTestActions Tests the  retreival if the battery information
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetBatteryInfo z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetBatteryInfo z:\testdata\configs\te_etelisv.ini BufferModeDisabled
 
 
END_TESTCASE TEL-EtelIsv-GT0166-1005

START_TESTCASE TEL-EtelIsv-GT0166-1006
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1006
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Get Signal Strength
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the signal strength
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetSignalStrength z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetSignalStrength z:\testdata\configs\te_etelisv.ini BufferModeDisabled
 
 
END_TESTCASE TEL-EtelIsv-GT0166-1006

START_TESTCASE TEL-EtelIsv-GT0166-1007
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1007
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Get Lock Info
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the lock information 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetLockInfo z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetLockInfo z:\testdata\configs\te_etelisv.ini BufferModeDisabled
 
 
END_TESTCASE TEL-EtelIsv-GT0166-1007

START_TESTCASE TEL-EtelIsv-GT0166-1008
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1008
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Send DTMF Tones
//!@SYMTestPriority critical
//!@SYMTestActions Tests the sending of DTMF Tones
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestSendDTMFTones

 
END_TESTCASE TEL-EtelIsv-GT0166-1008

START_TESTCASE TEL-EtelIsv-GT0166-1009
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1009
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Get Network Registration Status
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the Network Registration Status
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetNetworkRegistrationStatus z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetNetworkRegistrationStatus z:\testdata\configs\te_etelisv.ini BufferModeDisabled
 
END_TESTCASE TEL-EtelIsv-GT0166-1009

START_TESTCASE TEL-EtelIsv-GT0166-1010
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1010
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Get Current NetworkName
//!@SYMTestPriority critical
//!@SYMTestActions Testd the retreival of the current network name
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT 
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCurrentNetworkName z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCurrentNetworkName z:\testdata\configs\te_etelisv.ini BufferModeDisabled

END_TESTCASE TEL-EtelIsv-GT0166-1010

START_TESTCASE TEL-EtelIsv-GT0166-1011
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1011
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Get Current Network Info
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the current network information
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCurrentNetworkInfo z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCurrentNetworkInfo z:\testdata\configs\te_etelisv.ini BufferModeDisabled

END_TESTCASE TEL-EtelIsv-GT0166-1011

START_TESTCASE TEL-EtelIsv-GT0166-1036
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1036
//!@SYMREQ INC072906
//!@SYMTestCaseDesc Test Get Current Network Info Eighteen Characters
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the current network information when long network names are passed
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCurrentNetworkInfoEighteenChars

END_TESTCASE TEL-EtelIsv-GT0166-1036

START_TESTCASE TEL-EtelIsv-GT0166-1037
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1037
//!@SYMREQ INC072906
//!@SYMTestCaseDesc Test Get Current Network Info Eighteen Characters using TNetworkInfoV2 and TNetworkNameV2
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the current network information when long network names are passed
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCurrentNetworkInfoEighteenCharsV2

END_TESTCASE TEL-EtelIsv-GT0166-1037

START_TESTCASE TEL-EtelIsv-GT0166-1038
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1038
//!@SYMREQ INC072906 
//!@SYMTestCaseDesc Test Get Current Network Info Twenty Three Chars
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the current network information when long network names are passed
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCurrentNetworkInfoTwentyThreeChars

END_TESTCASE TEL-EtelIsv-GT0166-1038

START_TESTCASE TEL-EtelIsv-GT0166-1039
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1039
//!@SYMREQ INC072906 
//!@SYMTestCaseDesc Test Get Current Network Info Twenty Three Characters using TNetworkInfoV2 and TNetworkNameV2
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the current network information when long network names are passed
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCurrentNetworkInfoTwentyThreeCharsV2

END_TESTCASE TEL-EtelIsv-GT0166-1039

START_TESTCASE TEL-EtelIsv-GT0166-1012
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1012
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc
//!@SYMTestPriority critical
//!@SYMTestActions
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetOperatorName z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetOperatorName z:\testdata\configs\te_etelisv.ini BufferModeDisabled

 
END_TESTCASE TEL-EtelIsv-GT0166-1012

START_TESTCASE TEL-EtelIsv-GT0166-1013
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1013
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Get Identity Service
//!@SYMTestPriority critical
//!@SYMTestActions Test the retreival of the identity service
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1  TestGetIdentityService z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1  TestGetIdentityService z:\testdata\configs\te_etelisv.ini BufferModeDisabled
 
 
END_TESTCASE TEL-EtelIsv-GT0166-1013

START_TESTCASE TEL-EtelIsv-GT0166-1014
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1014
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Get Supplementary Service Status
//!@SYMTestPriority critical
//!@SYMTestActions Tests the retreival of the Supplementary Service Status
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1  TestGetSupplementaryServiceStatus z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1  TestGetSupplementaryServiceStatus z:\testdata\configs\te_etelisv.ini BufferModeDisabled

 
 
END_TESTCASE TEL-EtelIsv-GT0166-1014

START_TESTCASE TEL-EtelIsv-GT0166-1015
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1015
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Register For Notification
//!@SYMTestPriority critical
//!@SYMTestActions Tests Register notifications
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestRegisterForNotification z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestRegisterForNotification z:\testdata\configs\te_etelisv.ini BufferModeDisabled

 
END_TESTCASE TEL-EtelIsv-GT0166-1015

START_TESTCASE TEL-EtelIsv-GT0166-1016
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1016
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Register For Notification Cancel
//!@SYMTestPriority critical
//!@SYMTestActions Tests Register For Notification Cancel
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestRegisterForNotificationCancel

 
END_TESTCASE TEL-EtelIsv-GT0166-1016

START_TESTCASE TEL-EtelIsv-GT0166-1017
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1017
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Dial New Call
//!@SYMTestPriority critical
//!@SYMTestActions Tests the dialing of a new call 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestDialNewCall z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestDialNewCall z:\testdata\configs\te_etelisv.ini BufferModeDisabled

 
END_TESTCASE TEL-EtelIsv-GT0166-1017

START_TESTCASE TEL-EtelIsv-GT0166-1018
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1018
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc TestHangup
//!@SYMTestPriority critical
//!@SYMTestActions Test Hanging up a call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestHangup

 
END_TESTCASE TEL-EtelIsv-GT0166-1018

START_TESTCASE TEL-EtelIsv-GT0166-1019
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1019
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Get Call Info
//!@SYMTestPriority critical
//!@SYMTestActions Test retreival of call information
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCallInfo z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCallInfo z:\testdata\configs\te_etelisv.ini BufferModeDisabled

 
END_TESTCASE TEL-EtelIsv-GT0166-1019

START_TESTCASE TEL-EtelIsv-GT0166-1020
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1020
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Hold
//!@SYMTestPriority critical
//!@SYMTestActions Test Holding a call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestHold

 
END_TESTCASE TEL-EtelIsv-GT0166-1020

START_TESTCASE TEL-EtelIsv-GT0166-1021
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1021
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test REsume
//!@SYMTestPriority critical
//!@SYMTestActions Test resuming a call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestResume

 
END_TESTCASE TEL-EtelIsv-GT0166-1021

START_TESTCASE TEL-EtelIsv-GT0166-1022
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1022
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test swap
//!@SYMTestPriority critical
//!@SYMTestActions Test swapping a call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestSwap
 
END_TESTCASE TEL-EtelIsv-GT0166-1022

START_TESTCASE TEL-EtelIsv-GT0166-1023
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1023
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Hold Resume 2 Calls
//!@SYMTestPriority critical
//!@SYMTestActions Test the holding and resuming of two calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestHoldResume2Calls


END_TESTCASE TEL-EtelIsv-GT0166-1023

START_TESTCASE TEL-EtelIsv-GT0166-1024
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1024
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Line Status
//!@SYMTestPriority critical
//!@SYMTestActions Test Retreival of line status
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetLineStatus z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetLineStatus z:\testdata\configs\te_etelisv.ini BufferModeDisabled

 
END_TESTCASE TEL-EtelIsv-GT0166-1024

START_TESTCASE TEL-EtelIsv-GT0166-1025
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1025
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Get Call Dynamic Caps
//!@SYMTestPriority critical
//!@SYMTestActions Test Call Dynamic Capabillities
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCallDynamicCaps z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestGetCallDynamicCaps z:\testdata\configs\te_etelisv.ini BufferModeDisabled


 
END_TESTCASE TEL-EtelIsv-GT0166-1025

START_TESTCASE TEL-EtelIsv-GT0166-1026
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1026
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc TestAnswerIncomingCall
//!@SYMTestPriority critical
//!@SYMTestActions Test answering of an incoming call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestAnswerIncomingCall

 
END_TESTCASE TEL-EtelIsv-GT0166-1026

START_TESTCASE TEL-EtelIsv-GT0166-1027
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1027
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Call and Noitify
//!@SYMTestPriority critical
//!@SYMTestActions Test call with notification
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestCallAndNotify

END_TESTCASE TEL-EtelIsv-GT0166-1027

START_TESTCASE TEL-EtelIsv-GT0166-1028
//!@SYMTestCaseID TEL-EtelIsv-GT0166-1028
//!@SYMREQ REQ2116
//!@SYMTestCaseDesc Test Stress
//!@SYMTestPriority critical
//!@SYMTestActions Test etelisv under stress
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestStress

END_TESTCASE TEL-EtelIsv-GT0166-1028

START_TESTCASE TEL-EtelIsv-GT0212-1029
//!@SYMTestCaseID TEL-EtelIsv-GT0212-1029
//!@SYMREQ REQ3593
//!@SYMTestCaseDesc Test Flight Mode With Publish and Subscribe
//!@SYMTestPriority critical
//!@SYMTestActions Test Flight Mode With Publish and Subscribe
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestFlightModeWithPublishSubscribe z:\testdata\configs\te_etelisv.ini BufferModeEnabled
RUN_TEST_STEP 500 TE_EtelIsv1 TestFlightModeWithPublishSubscribe z:\testdata\configs\te_etelisv.ini BufferModeDisabled

END_TESTCASE TEL-EtelIsv-GT0212-1029

START_TESTCASE TEL-EtelIsv-GT0212-1030
//!@SYMTestCaseID TEL-EtelIsv-GT0212-1030
//!@SYMREQ REQ3593
//!@SYMTestCaseDesc Test Phone Function Flight Mode On With Publish Subscribe
//!@SYMTestPriority critical
//!@SYMTestActions Test Phone Function Flight Mode On With Publish Subscribe
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestPhoneFuncFlightModeOnWithPublishSubscribe 

END_TESTCASE TEL-EtelIsv-GT0212-1030

START_TESTCASE TEL-EtelIsv-GT0212-1031
//!@SYMTestCaseID TEL-EtelIsv-GT0212-1031
//!@SYMREQ REQ3593
//!@SYMTestCaseDesc Test Call Function Flight Mode On With Publish and Subscribe
//!@SYMTestPriority critical
//!@SYMTestActions

//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestCallFuncFlightModeOnWithPublishSubscribe

END_TESTCASE TEL-EtelIsv-GT0212-1031

START_TESTCASE TEL-EtelIsv-GT0212-1032
//!@SYMTestCaseID TEL-EtelIsv-GT0212-1032
//!@SYMREQ REQ3593
//!@SYMTestCaseDesc TestLineFuncFlightModeOnWithPublishSubscribe
//!@SYMTestPriority critical
//!@SYMTestActions Test Line Function Flight Mode On With Publish and Subscribe
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestLineFuncFlightModeOnWithPublishSubscribe

END_TESTCASE TEL-EtelIsv-GT0212-1032

START_TESTCASE TEL-EtelIsv-GT0212-1033
//!@SYMTestCaseID TEL-EtelIsv-GT0212-1033
//!@SYMREQ REQ3593
//!@SYMTestCaseDesc Test Network Function with Flight Mode On With Publish and Subscribe
//!@SYMTestPriority critical
//!@SYMTestActions  Test Network Function with Flight Mode On With Publish and Subscribe
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestNetworkFuncFlightModeOnWithPublishSubscribe

END_TESTCASE TEL-EtelIsv-GT0212-1033

START_TESTCASE TEL-EtelIsv-GT0212-1034
//!@SYMTestCaseID TEL-EtelIsv-GT0212-1034
//!@SYMREQ REQ3593
//!@SYMTestCaseDesc Test Supp Serv Func Flight Mode On With Publish and Subscribe
//!@SYMTestPriority critical
//!@SYMTestActions Test Supplementary Service Function with flight mode on with publish and subscribe
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestSuppServFuncFlightModeOnWithPublishSubscribe

END_TESTCASE TEL-EtelIsv-GT0212-1034

START_TESTCASE TEL-EtelIsv-GT0246-1035
//!@SYMTestCaseID           TEL-EtelIsv-GT0246-1035
//!@SYMREQ                  CNON-67WJ2G
//!@SYMTestCaseDesc         Test deprecated data call APIs
//!@SYMTestPriority         Critical
//!@SYMTestActions          Calls each deprecated API and ensures it returns KErrNotSupported
//!@SYMTestExpectedResults  Pass
//!@SYMTestType             CT
RUN_TEST_STEP 100 TE_EtelIsv1 TestDeprecatedDataCallAPIs

END_TESTCASE TEL-EtelIsv-GT0246-1035


START_TESTCASE TEL-EtelIsv-NA-1037
//!@SYMTestCaseID TEL-EtelIsv-NA-1037
//!@SYMDEF INC093297 
//!@SYMTestCaseDesc Test opening the CTelephony class when no valid phone is available.
//!@SYMTestPriority Critical
//!@SYMTestActions Opens CTelephony when SIMTSY cannot be opened.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 500 TE_EtelIsv1 TestFailedOpen
END_TESTCASE TEL-EtelIsv-NA-1037

 
// Run test cases with no capabilities
RUN_SCRIPT z:\TestData\Scripts\te_etelisvnocaps.script  
 

