// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE  te_etelisvcaps1

START_TESTCASE TEL-EtelIsv-GT0246-1037
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1037
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on FlightMode notification request.   
//!@SYMTestActions
//1. Request FligtMode change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyFlightModeChange z:\testdata\configs\te_etelisvcaps.ini NotifyFlightModeChange
END_TESTCASE TEL-EtelIsv-GT0246-1037

START_TESTCASE TEL-EtelIsv-GT0246-1038
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1038
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on Indicator notification request.   
//!@SYMTestActions
//1. Request Indicator change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capabilities of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyIndicatorChange z:\testdata\configs\te_etelisvcaps.ini NotifyIndicatorChange
END_TESTCASE TEL-EtelIsv-GT0246-1038

START_TESTCASE TEL-EtelIsv-GT0246-1039
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1039
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on BatteryInfo notification request.   
//!@SYMTestActions
//1. Request BatteryInfo change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyBatteryInfoChange z:\testdata\configs\te_etelisvcaps.ini NotifyBatteryInfoChange
END_TESTCASE TEL-EtelIsv-GT0246-1039

START_TESTCASE TEL-EtelIsv-GT0246-1040
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1040
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on SignalStrength notification request.   
//!@SYMTestActions
//1. Request SignalStrength change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifySignalStrengthChange z:\testdata\configs\te_etelisvcaps.ini NotifySignalStrengthChange
END_TESTCASE TEL-EtelIsv-GT0246-1040

START_TESTCASE TEL-EtelIsv-GT0246-1041
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1041
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on Pin1LockInfo notification request.   
//!@SYMTestActions
//1. Request Pin1LockInfo change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyPin1LockInfoChange z:\testdata\configs\te_etelisvcaps.ini NotifyPin1LockInfoChange
END_TESTCASE TEL-EtelIsv-GT0246-1041

START_TESTCASE TEL-EtelIsv-GT0246-1042
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1042
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on Pin2LockInfo notification request.   
//!@SYMTestActions
//1. Request Pin2LockInfo change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyPin2LockInfoChange z:\testdata\configs\te_etelisvcaps.ini NotifyPin2LockInfoChange
END_TESTCASE TEL-EtelIsv-GT0246-1042

START_TESTCASE TEL-EtelIsv-GT0246-1043
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1043
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on VoiceLineStatus notification request.   
//!@SYMTestActions
//1. Request VoiceLineStatus change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyVoiceLineStatusChange z:\testdata\configs\te_etelisvcaps.ini NotifyVoiceLineStatusChange
END_TESTCASE TEL-EtelIsv-GT0246-1043

START_TESTCASE TEL-EtelIsv-GT0246-1044
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1044
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on OwnedCall1Status notification request.   
//!@SYMTestActions
//1. Request OwnedCall1Status change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyOwnedCall1StatusChange z:\testdata\configs\te_etelisvcaps.ini NotifyOwnedCall1StatusChange
END_TESTCASE TEL-EtelIsv-GT0246-1044

START_TESTCASE TEL-EtelIsv-GT0246-1045
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1045
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on OwnedCall2Status notification request.   
//!@SYMTestActions
//1. Request OwnedCall2Status change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyOwnedCall2StatusChange z:\testdata\configs\te_etelisvcaps.ini NotifyOwnedCall2StatusChange
END_TESTCASE TEL-EtelIsv-GT0246-1045

START_TESTCASE TEL-EtelIsv-GT0246-1046
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1046
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on OwnedCall1RemotePartyInfo notification request.   
//!@SYMTestActions
//1. Request OwnedCall1RemotePartyInfo change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyOwnedCall1RemotePartyInfoChange z:\testdata\configs\te_etelisvcaps.ini NotifyOwnedCall1RemotePartyInfoChange
END_TESTCASE TEL-EtelIsv-GT0246-1046

START_TESTCASE TEL-EtelIsv-GT0246-1047
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1047
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on OwnedCall2RemotePartyInfo notification request.   
//!@SYMTestActions
//1. Request OwnedCall2RemotePartyInfo change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyOwnedCall2RemotePartyInfoChange z:\testdata\configs\te_etelisvcaps.ini NotifyOwnedCall2RemotePartyInfoChange
END_TESTCASE TEL-EtelIsv-GT0246-1047

START_TESTCASE TEL-EtelIsv-GT0246-1048
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1048
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on NetworkRegistrationStatus notification request.   
//!@SYMTestActions
//1. Request NetworkRegistrationStatus change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyNetworkRegistrationStatusChange z:\testdata\configs\te_etelisvcaps.ini NotifyNetworkRegistrationStatusChange
END_TESTCASE TEL-EtelIsv-GT0246-1048

START_TESTCASE TEL-EtelIsv-GT0246-1049
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1049
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on CurrentNetworkInfo notification request.   
//!@SYMTestActions
//1. Request CurrentNetworkInfo change notification on ETel3rdParty API (NotifyChange)
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 NotifyCurrentNetworkInfoChange z:\testdata\configs\te_etelisvcaps.ini NotifyCurrentNetworkInfoChange
END_TESTCASE TEL-EtelIsv-GT0246-1049

START_TESTCASE TEL-EtelIsv-GT0246-1050
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1050
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetPhoneId API method.   
//!@SYMTestActions
//1. Call GetPhoneId on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetPhoneIdTestStep z:\testdata\configs\te_etelisvcaps.ini GetPhoneIdTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1050

START_TESTCASE TEL-EtelIsv-GT0246-1051
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1051
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetSubscriberId API method.   
//!@SYMTestActions
//1. Call GetSubscriberId on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetSubscriberIdTestStep z:\testdata\configs\te_etelisvcaps.ini GetSubscriberIdTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1051

START_TESTCASE TEL-EtelIsv-GT0246-1052
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1052
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetIndicator API method.   
//!@SYMTestActions
//1. Call GetIndicator on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetIndicatorTestStep z:\testdata\configs\te_etelisvcaps.ini GetIndicatorTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1052

START_TESTCASE TEL-EtelIsv-GT0246-1053
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1053
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetBatteryInfo API method.   
//!@SYMTestActions
//1. Call GetBatteryInfo on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetBatteryInfoTestStep z:\testdata\configs\te_etelisvcaps.ini GetBatteryInfoTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1053

START_TESTCASE TEL-EtelIsv-GT0246-1054
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1054
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetSignalStrength API method.   
//!@SYMTestActions
//1. Call GetSignalStrength on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetSignalStrengthTestStep z:\testdata\configs\te_etelisvcaps.ini GetSignalStrengthTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1054

START_TESTCASE TEL-EtelIsv-GT0246-1055
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1055
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetLockInfo API method.   
//!@SYMTestActions
//1. Call GetLockInfo on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetLockInfoTestStep z:\testdata\configs\te_etelisvcaps.ini GetLockInfoTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1055

START_TESTCASE TEL-EtelIsv-GT0246-1056
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1056
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on SendDTMFTones API method.   
//!@SYMTestActions
//1. Create one call in external process
//2. Call SendDTMFTones on ETel3rdParty API.
//3. Check for the result of the request status and verify it against capability of the executable
//
//4. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 SendDTMFTonesTestStep z:\testdata\configs\te_etelisvcaps.ini SendDTMFTonesTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1056

START_TESTCASE TEL-EtelIsv-GT0246-1057
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1057
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetFlightMode API method.   
//!@SYMTestActions
//1. Call GetFlightMode on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetFlightModeTestStep z:\testdata\configs\te_etelisvcaps.ini GetFlightModeTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1057

START_TESTCASE TEL-EtelIsv-GT0246-1058
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1058
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetLineStatus API method.   
//!@SYMTestActions
//1. Call GetLineStatus on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetLineStatusTestStep z:\testdata\configs\te_etelisvcaps.ini GetLineStatusTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1058

START_TESTCASE TEL-EtelIsv-GT0246-1059
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1059
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetCallInfo API method.   
//!@SYMTestActions
//1. Create two calls in external process
//2. Call GetCallInfo on ETel3rdParty API.
//3. Check for the result of the request status and verify it against capability of the executable
//
//4. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetCallInfoTestStep z:\testdata\configs\te_etelisvcaps.ini GetCallInfoTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1059

START_TESTCASE TEL-EtelIsv-GT0246-1060
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1060
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on DialNewCall API method.   
//!@SYMTestActions
//1. Call DialNewCall on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 DialNewCallTestStep z:\testdata\configs\te_etelisvcaps.ini DialNewCallTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1060

START_TESTCASE TEL-EtelIsv-GT0246-1061
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1061
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetCallDynamicCaps API method.   
//!@SYMTestActions
//1. Create a call
//2. Call GetCallDynamicCaps on ETel3rdParty API.
//3. Check for the result of the request status and verify it against capability of the executable
//
//4. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetCallDynamicCapsTestStep z:\testdata\configs\te_etelisvcaps.ini GetCallDynamicCapsTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1061

START_TESTCASE TEL-EtelIsv-GT0246-1062
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1062
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetCallStatus API method.   
//!@SYMTestActions
//1. Create a call
//2. Call GetCallStatus on ETel3rdParty API.
//3. Check for the result of the request status and verify it against capability of the executable
//
//4. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetCallStatusTestStep z:\testdata\configs\te_etelisvcaps.ini GetCallStatusTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1062

START_TESTCASE TEL-EtelIsv-GT0246-1063
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1063
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on Resume API method.   
//!@SYMTestActions
//1. Create a call and put in on hold
//2. Call Resume on ETel3rdParty API.
//3. Check for the result of the request status and verify it against capability of the executable
//
//4. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 ResumeTestStep z:\testdata\configs\te_etelisvcaps.ini ResumeTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1063

START_TESTCASE TEL-EtelIsv-GT0246-1064
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1064
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on Hold API method.   
//!@SYMTestActions
//1. Create a call
//2. Call Hold on ETel3rdParty API.
//3. Check for the result of the request status and verify it against capability of the executable
//
//4. Re-run this test step with different set of capabilities. Done in subsequent script files.   
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 HoldTestStep z:\testdata\configs\te_etelisvcaps.ini HoldTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1064

START_TESTCASE TEL-EtelIsv-GT0246-1065
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1065
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on Swap API method.   
//!@SYMTestActions
//1. Create two calls. One active and one on hold. 
//2. Call Swap on ETel3rdParty API.
//3. Check for the result of the request status and verify it against capability of the executable
//
//4. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 SwapTestStep z:\testdata\configs\te_etelisvcaps.ini SwapTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1065

START_TESTCASE TEL-EtelIsv-GT0246-1066
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1066
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on HangUp API method.   
//!@SYMTestActions
//1. Create a call
//2. Call HangUp on ETel3rdParty API.
//3. Check for the result of the request status and verify it against capability of the executable
//
//4. Re-run this test step with different set of capabilities. Done in subsequent script files.    
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 HangUpTestStep z:\testdata\configs\te_etelisvcaps.ini HangUpTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1066

START_TESTCASE TEL-EtelIsv-GT0246-1067
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1067
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on AnswerIncomingCall API method.   
//!@SYMTestActions
//1. Trigger SimTsy to initialize the call
//1. Call AnswerIncomingCall on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 AnswerIncomingCallTestStep z:\testdata\configs\te_etelisvcaps.ini AnswerIncomingCallTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1067

START_TESTCASE TEL-EtelIsv-GT0246-1068
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1068
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetNetworkRegistration API method.   
//!@SYMTestActions
//1. Call GetNetworkRegistration on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetNetworkRegistrationTestStep z:\testdata\configs\te_etelisvcaps.ini GetNetworkRegistrationTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1068

START_TESTCASE TEL-EtelIsv-GT0246-1069
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1069
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetNetworkInfo API method.   
//!@SYMTestActions
//1. Call GetNetworkInfo on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetNetworkInfoTestStep z:\testdata\configs\te_etelisvcaps.ini GetNetworkInfoTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1069

START_TESTCASE TEL-EtelIsv-GT0246-1070
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1070
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetNetworkName API method.   
//!@SYMTestActions
//1. Call GetNetworkName on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetNetworkNameTestStep z:\testdata\configs\te_etelisvcaps.ini GetNetworkNameTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1070

START_TESTCASE TEL-EtelIsv-GT0246-1071
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1071
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetOperatorName API method.   
//!@SYMTestActions
//1. Call GetOperatorName on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetOperatorNameTestStep z:\testdata\configs\te_etelisvcaps.ini GetOperatorNameTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1071

START_TESTCASE TEL-EtelIsv-GT0246-1072
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1072
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetCallForwarding API method.   
//!@SYMTestActions
//1. Call GetCallForwarding on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetCallForwardingTestStep z:\testdata\configs\te_etelisvcaps.ini GetCallForwardingTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1072

START_TESTCASE TEL-EtelIsv-GT0246-1073
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1073
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetCallBarring API method.   
//!@SYMTestActions
//1. Call GetCallBarring on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetCallBarringTestStep z:\testdata\configs\te_etelisvcaps.ini GetCallBarringTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1073

START_TESTCASE TEL-EtelIsv-GT0246-1074
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1074
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetCallWaiting API method.   
//!@SYMTestActions
//1. Call GetCallWaiting on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetCallWaitingTestStep z:\testdata\configs\te_etelisvcaps.ini GetCallWaitingTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1074

START_TESTCASE TEL-EtelIsv-GT0246-1075
//!@SYMTestCaseID TEL-EtelIsv-GT0246-1075
//!@SYMDEF DEF090803
//!@SYMTestPriority Critical
//!@SYMTestCaseDesc Verify the capability check on GetIdentityService API method.   
//!@SYMTestActions
//1. Call GetIdentityService on ETel3rdParty API.
//2. Check for the result of the request status and verify it against capability of the executable
//
//3. Re-run this test step with different set of capabilities. Done in subsequent script files.  
//!@SYMTestExpectedResults The status of the request should be adequate. If there are not enough capabilities, KErrPermissionDenied should be returned.

RUN_TEST_STEP 100 te_etelisvcaps1 GetIdentityServiceTestStep z:\testdata\configs\te_etelisvcaps.ini GetIdentityServiceTestStep
END_TESTCASE TEL-EtelIsv-GT0246-1075


