//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_csat_component

START_TESTCASE BA-CSAT-SSMS-SNSSMPC-0001
//!@SYMTestCaseID BA-CSAT-SSMS-SNSSMPC-0001
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Test support in CSAT for RSat::NotifySendSmPCmd
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendSmPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendSMSFU.TestNotifySendSmPCmd0001L
END_TESTCASE BA-CSAT-SSMS-SNSSMPC-0001

START_TESTCASE BA-CSAT-SSMS-SNSSMPC-0002
//!@SYMTestCaseID BA-CSAT-SSMS-SNSSMPC-0002
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Test support in CSAT for cancelling of RSat::NotifySendSmPCmd
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RSat::NotifySendSmPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendSMSFU.TestNotifySendSmPCmd0002L
END_TESTCASE BA-CSAT-SSMS-SNSSMPC-0002

START_TESTCASE BA-CSAT-SSMS-SNSSMPC-0004
//!@SYMTestCaseID BA-CSAT-SSMS-SNSSMPC-0004
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Test support in CSAT for multiple client requests to RSat::NotifySendSmPCmd
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RSat::NotifySendSmPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendSMSFU.TestNotifySendSmPCmd0004L
END_TESTCASE BA-CSAT-SSMS-SNSSMPC-0004

