//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_csat_component

START_TESTCASE BA-CSAT-FRMS-SFRMPC-0001
//!@SYMTestCaseID BA-CSAT-FRMS-SFRMPC-0001
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Test support in CSAT for RSat::NotifySetFramesPCmd
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySetFramesPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatFramesFU.TestNotifySetFramesPCmd0001L
END_TESTCASE BA-CSAT-FRMS-SFRMPC-0001

START_TESTCASE BA-CSAT-FRMS-GFRMSPC-0001
//!@SYMTestCaseID BA-CSAT-FRMS-GFRMSPC-0001
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Test support in CSAT for RSat::NotifyGetFramesStatusPCmd
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifyGetFramesStatusPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatFramesFU.TestNotifyGetFramesStatusPCmd0001L
END_TESTCASE BA-CSAT-FRMS-GFRMSPC-0001

