//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_csat_component

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Test support in CSAT for RSat::NotifySendUssdPCmd
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001L
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0002
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0002
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Test support in CSAT for cancelling of RSat::NotifySendUssdPCmd
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0002L
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0002

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0004
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0004
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Test support in CSAT for multiple client requests to RSat::NotifySendUssdPCmd
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0004L
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0004

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001b
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001b
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Expected Sequence 1.1 (SEND USSD, 7-bit data, successful)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001bL
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001b

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001c
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001c
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Expected Sequence 1.2 (SEND USSD, 8-bit data, successful)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001cL
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001c

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001d
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001d
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Expected Sequence 1.3 (SEND USSD, UCS2 data, successful)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001dL
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001d

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001e
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001e
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Expected Sequence 1.4 ( SEND USSD, 7-bit data, unsuccessful (Return Error) )
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001eL
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001e

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001f
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001f
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Expected Sequence 1.5 ( SEND USSD, 7-bit data, unsuccessful (Reject))
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001fL
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001f

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001g
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001g
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Expected Sequence 1.7 (SEND USSD, 7-bit data, successful, no alpha identifier)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001gL
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001g

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001h
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001h
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Expected Sequence 1.8 (SEND USSD, 7-bit data, successful, null length alpha identifier)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001hL
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001h

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001i
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001i
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Expected Sequence 2.1A (SEND USSD, 7-bit data, successful, basic icon self explanatory, successful)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001iL
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001i

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001j
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001j
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Test for coverage. 
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001jL
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001j

START_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001k
//!@SYMTestCaseID BA-CSAT-SUSSD-SNSUPC-0001k
//!@SYMPREQ 1780
//!@SYMComponent telephony_csat
//!@SYMTestCaseDesc Test CSatNotifySendUssd::CreateTerminalRespL()
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySendUssdPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_csat_component TEFUnit.CCSatSendUSSDFU.TestNotifySendUssdPCmd0001kL
END_TESTCASE BA-CSAT-SUSSD-SNSUPC-0001k



