//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_csat_component

RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_setupcall_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_displaytext_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_getinkey_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_getinput_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_playtone_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_refresh_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_setupmenu_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_selectitem_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_sendsms_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_sendss_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_sendussd_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_providelocalinfo_individual.script
//RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_setupeventlist_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_setupidlemodetext_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_senddtmf_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_languagenotification_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_launchbrowser_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_openchannel_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_closechannel_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_getchannelstatus_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_frames_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_multimediamsg_individual.script
RUN_SCRIPT z:\testdata\scripts\te_csatcomponent_sendreceivedata_individual.script
