//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run StfpCsToCdRetry1Panic SysStart test 
//
LOAD_SUITE appfwk_sysstart_test_server

START_TESTCASE 			DEVSRVS-SYSSTART-STARTUP-0005
//!   @SYMTestCaseID 		DEVSRVS-SYSSTART-STARTUP-0005
//!   @SYMPREQ			PREQ967   
//!   @SYMREQ                  	REQ4660  
//!   @SYMTestCaseDesc 	    	Tests behaviour of SysStart when State Transition 
//!                            	Failure Policy set to 1 retry and panic on failure for
//!                            		transition from Critical Static to Critical Dynamic.                     
//!                            	Stage Under Test: Critical Static to Critical Dynamic.
//!                            		no_of_retries_on_failure = ERetry1.
//!                            		action_on_failure = EPanicOnFailure.  
//!   @SYMTestPriority   	Low   
//!   @SYMTestType		Component Integration Test 
//!   @SYMTestStatus 	  	Implemented     
//!   @SYMTestActions  	    	The test determines that SysStart behaved consistent with the
//!                            	State Transition Failure Policy set to 1 retry and panic on failure
//!                            		when the Critical Static to Critical Dynamic transition is failed.
//!                            		i.e. the same as the default.
//!                            	It achieves this by checking the results contained in a file created 
//!                            		by the SysStart SSA test component (t_stfp.exe).
//!                            	Namely:
//!                            	T_STFP_ResultFile.txt - contents of which includes the number of times 
//!                            		each transition was requested, and how many were failed.   
//!   @SYMTestExpectedResults  	The expected values match the results contained within the result files.  
//!   @SYMTestCaseDependencies 	appfwk_sysstart_test_stfp_emulator3.rss appfwk_sysstart_test_stfp_hardware3.rss
RUN_TEST_STEP 100 appfwk_sysstart_test_server StfpCsToCdRetry1Panic
END_TESTCASE 			DEVSRVS-SYSSTART-STARTUP-0005