//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run ProcStartFailPanic SysStart test 
//
LOAD_SUITE appfwk_sysstart_test_server

START_TESTCASE 			DEVSRVS-SYSSTART-STARTUP-0069
//!   @SYMTestCaseID 		DEVSRVS-SYSSTART-STARTUP-0069
//!   @SYMPREQ			PREQ1192   
//!   @SYMREQ                   REQ5246
//!   @SYMTestCaseDesc 	   	Startup resource file contains a list of non-existent apps to launch.  
//!   @SYMTestPriority   	High  
//!   @SYMTestType		Component Integration Test 
//!   @SYMTestStatus 	  	Implemented   
//!   @SYMTestActions  	    	SysStart attempts to launch non-existent exe's
//!   				SysStart panics when attempting to launch a non-existent process with fire and forget
//!   					as startup command  
//!   @SYMTestExpectedResults   SysStart records the failed attempts to start the non-existent apps
//!   					t_app5 result file does not exist   
//!   @SYMTestCaseDependencies 	appfwk_sysstart_test_proc_emulator9.rss appfwk_sysstart_test_proc_hardware9.rss
RUN_TEST_STEP 100 appfwk_sysstart_test_server ProcStartFailPanic
END_TESTCASE 			DEVSRVS-SYSSTART-STARTUP-0069