//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run DefRendFailAppPanic SysStart test 
//
LOAD_SUITE appfwk_sysstart_test_server

START_TESTCASE 			DEVSRVS-SYSSTART-STARTUP-0074
//! @SYMTestCaseID 		DEVSRVS-SYSSTART-STARTUP-0074
//! @SYMPREQ			PREQ1192
//! @SYMREQ                  	REQ5246
//! @SYMTestCaseDesc 	    	SysStart panics if app fails the rendezvous with EPanicOnCommandFailure set in
//!  					startup resource file
//! @SYMTestPriority   	    	High
//! @SYMTestType		Component Integration Test
//! @SYMTestStatus 	  	Implemented
//! @SYMTestActions  	    	SysStart launches app22 (START_APP_INFO)
//!    					app22 increments start count
//!    					app22 pauses for 5s
//!    					SysStart launches app23 (START_PROC_INFO)
//!    					app23 increments start count
//!    					app23 increments rend count
//!    					app23 rendezvous's
//!    					SysStart waits
//!    					app22 returns from pause, increments rend fail count
//!    					app22 fails rendezvous (KErrGeneral)
//!    					SysStart panics
//! @SYMTestExpectedResults  	t_app22 start count = 1
//!    					t_app22 rendezvous count = 0
//!    					t_app22 rendezvous fail count = 1
//!    					t_app23 start count = 1
//!    					t_app22 rendezvous count = 1
//!    					t_app22 rendezvous fail count = 0
//!    					t_app5 result file does not exist
//! @SYMTestCaseDependencies 	appfwk_sysstart_test_def_emulator21.rss appfwk_sysstart_test_def_hardware21.rss
RUN_TEST_STEP 100 appfwk_sysstart_test_server DefRendFailAppPanic
END_TESTCASE 			DEVSRVS-SYSSTART-STARTUP-0074