//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run DefInvalidMultWait SysStart test 
//
LOAD_SUITE appfwk_sysstart_test_server

START_TESTCASE 			DEVSRVS-SYSSTART-STARTUP-0076
//! @SYMTestCaseID 		DEVSRVS-SYSSTART-STARTUP-0076
//! @SYMPREQ			PREQ1192
//! @SYMREQ                     REQ5246
//! @SYMTestCaseDesc 	    	SysStart panics when a MULTIPLE_WAIT command is used without any
//!   					deferred commands.
//! @SYMTestPriority   	    	Low
//! @SYMTestType		Component Integration Test
//! @SYMTestStatus 	        Implemented
//! @SYMTestActions  	     	SysStart panics with invalid fail_on_error
//! @SYMTestExpectedResults 	t_app22,23,24 result files do not exist
//!   					and panic result file indicates that sysstart panic'd
//! @SYMTestCaseDependencies 	appfwk_sysstart_test_def_emulator23.rss appfwk_sysstart_test_def_hardware23.rss
RUN_TEST_STEP 100 appfwk_sysstart_test_server DefInvalidMultWait
END_TESTCASE 			DEVSRVS-SYSSTART-STARTUP-0076