//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-AvdtpContentProtectionCapa-PublishedPartner.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-AvdtpHeaderCompressionCapa-PublishedPartner.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-AvdtpMediaTransportCapabilities-PublishedPartner.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-AvdtpRecoveryCapabilities-PublishedPartner.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-AvdtpReportingCapabilities-PublishedPartner.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-AvdtpSEPInfo-PublishedPartner.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-AvdtpServiceCategories-PublishedPartner.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-AvdtpSockAddr-PublishedPartner.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-BluetoothPhysicalLinks-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-BluetoothSynchronousLink-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-BTAccessRequirements-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-BTPhysicalLinkAdapter-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-BTSyncBandWidth-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-BTSyncPackets-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-ConvertToSymbianError-PublishedPartner.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-InquirySockAddr-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-L2CapConfig-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-L2CapSockAddr-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-NonSBCCodecCapabilities-PublishedPartner.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-RfcommRemotePortParams-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-RfcommRPNTransaction-PublicApi.script
RUN_SCRIPT ${SYSDRIVE}\bluetooth\user\BT-USER-SEID-PublishedPartner.script
