//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0001
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UC0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::Attach & RPacketService::Detach
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::Attach(), RPacketService::Detach()
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUseCase0001L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0001

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0002
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UC0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for activation and QoS configuration for R97.
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewContext(), RPacketContext::InitialiseContext(), RPacketContext::SetConfig(), RPacketQoS::OpenNewQoS(), RPacketQoS::SetProfileParameters(), RPacketQoS::NotifyProfileChanged(), RPacketContext::Activate(), RPacketContext::NotifyStatusChange() for R97
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUseCase0002L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0002

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0003
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UC0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for activation and QoS configuration for R99.
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewContext(), RPacketContext::InitialiseContext(), RPacketContext::SetConfig(), RPacketQoS::OpenNewQoS(), RPacketQoS::SetProfileParameters(), RPacketQoS::NotifyProfileChanged(), RPacketContext::Activate(), RPacketContext::NotifyStatusChange() for R99
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUseCase0003L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0003

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0004
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UC0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for modification of an existing context
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::SetConfig(), RPacketContext::ModifyActiveContext()
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUseCase0004L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0004

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0005
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UC0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for activation of two primary contexts (QoS configuration provided only for the first context).
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewContext(), RPacketContext::InitialiseContext(), RPacketContext::SetConfig()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUseCase0005L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0005

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0006
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UC0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for activation of a primary and secondary contexts. 
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewContext(), RPacketContext::InitialiseContext(), RPacketContext::SetDefaultContextParams(), RPacketContext::OpenNewSecondaryContext(), RPacketContext::AddPacketFilter() for R97
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUseCase0006L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0006

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0007
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UC0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for activation and modification of a secondary context with two filters and removal of the first filter.
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewContext(), RPacketContext::InitialiseContext(), RPacketContext::SetDefaultContextParams(), RPacketContext::OpenNewSecondaryContext(), RPacketContext::AddPacketFilter(), RPacketContext::ModifyActiveContext() for R97
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUseCase0007L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UC0007

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0001
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for SetDefaultContextParams
//!@SYMTestPriority High
//!@SYMTestActions Invokes SetDefaultContextParams only for GPRS, R99 and CDMA
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit0001L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0001

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0002
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for InitialiseContext with port
//!@SYMTestPriority High
//!@SYMTestActions Invokes InitialiseContext only, successfully obtaining the port
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit0002L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0002

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0004
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for open the packet service when packet service status is set to EStatusUnattached
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::Open()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit0004L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0004

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0005
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for open the packet service when packet service status is set to EStatusAttached.
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::Open()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit0005L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0005

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0006
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for configuration settings using R99/R4
//!@SYMTestPriority High
//!@SYMTestActions SetConfig for R99R4
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit0006L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0006

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0007
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for configuration settings using R5
//!@SYMTestPriority High
//!@SYMTestActions SetConfig for R5
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit0007L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0007

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0008
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for QoS profile parameters
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::SetProfileParameters() only for GPRS, R99 and R5
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit0008L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0008

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0009
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::RejectActivationRequest
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::RejectActivationRequest()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit0009L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN0009

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00010
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for notification of transfer capability.
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::NotifyDynamicCapsChange()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00010L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00010

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00011A
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00011A
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for NotifyContextActivationRequested GPRS
//!@SYMTestPriority High
//!@SYMTestActions Invokes NotifyContextActivationRequested
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00011AL
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00011A

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00011B
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00011B
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for NotifyContextActivationRequested R99_R4
//!@SYMTestPriority High
//!@SYMTestActions Invokes NotifyContextActivationRequested
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00011BL
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00011B

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00011C
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00011C
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for NotifyContextActivationRequested R5
//!@SYMTestPriority High
//!@SYMTestActions Invokes NotifyContextActivationRequested
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00011CL
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00011C

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00012
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for NotifyMSClassChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes NotifyMSClassChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00012L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00012

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00013
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for NotifyDynamicCapsChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes NotifyDynamicCapsChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00013L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00013

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00014
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for NotifyChangeOfNtwkRegStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes NotifyChangeOfNtwkRegStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00014L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00014

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00015
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00015
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for NotifyContextAdded
//!@SYMTestPriority High
//!@SYMTestActions Invokes NotifyContextAdded
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00015L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00015

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00016
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for NotifyStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes NotifyStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00016L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00016

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00017
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00017
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for getting the network registration status
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::GetNtwkRegStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00017L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00017

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00018
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00018
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for NotifyConnectionSpeedChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes NotifyConnectionSpeedChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00018L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00018

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00019
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00019
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketMbmsContext::InitialiseContext, RPacketMbmsContext::NotifyConfigChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes InitialiseContext, NotifyConfigChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00019L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00019


START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00020
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00020
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::GetMbmsNetworkServiceStatus RPacketService::NotifyMbmsNetworkServiceStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes GetMbmsNetworkServiceStatus, NotifyMbmsNetworkServiceStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00020L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00020


START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00021
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00021
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::UpdateMbmsMonitorServiceListL, RPacketService::NotifyMbmsServiceAvailabilityChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes UpdateMbmsMonitorServiceListL, NotifyMbmsServiceAvailabilityChange, CRetrievePcktMbmsMonitoredServices
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00021L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00021


START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00022
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00022
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketMbmsContext::UpdateMbmsSessionList
//!@SYMTestPriority High
//!@SYMTestActions Invokes UpdateMbmsSessionList
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00022L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00022

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00023
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00023
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::NotifyConnectionInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes NotifyConnectionInfoChange, GetConnectionInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00023L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00023

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00024
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00024
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test conversions function CPacketServicesDispatcher::EtelPcktR99R4NegToEtelPcktR97NegQoS
//!@SYMTestPriority High
//!@SYMTestActions Invokes EtelPcktR99R4NegToEtelPcktR97NegQoS
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00024L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00024

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00025
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00025
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test conversions function CPacketServicesDispatcher::EtelPcktR97NegToEtelPcktR99R4NegQoS
//!@SYMTestPriority High
//!@SYMTestActions Invokes EtelPcktR97NegToEtelPcktR99R4NegQoS
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00025L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00025

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00026
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00026
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::GetPreferredBearer
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::GetPreferredBearer
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFU.TestUnit00026L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00026

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00027
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00027
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::Delete
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Delete
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketContextFU.TestUnit00027L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00027

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00028
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-UN00028
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::Delete
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::Delete
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketContextFU.TestUnit00028L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-UN00028