//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

START_TESTCASE BA-CTSYD-DIS-SIM-UC0001
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UC0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for get, set and notify for MWIS
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyIccMessageWaitingIndicatorsChange, RMobilePhone::GetIccMessageWaitingIndicators, RMobilePhone::SetIccMessageWaitingIndicators
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUseCase0001L
END_TESTCASE BA-CTSYD-DIS-SIM-UC0001


START_TESTCASE BA-CTSYD-DIS-SIM-UC0002
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UC0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for APN Control List operations
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetAPNControlListServiceStatus , RMobilePhone::NotifyAPNControlListServiceStatusChange, RMobilePhone::SetAPNControlListServiceStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUseCase0002L
END_TESTCASE BA-CTSYD-DIS-SIM-UC0002


START_TESTCASE BA-CTSYD-DIS-SIM-UC0003
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UC0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for APN list operations
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::AppendAPNName, RMobilePhone::DeleteAPNName, RMobilePhone::GetAPNname, RMobilePhone::EnumerateAPNEntries, RMobilePhone::NotifyAPNListChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUseCase0003L
END_TESTCASE BA-CTSYD-DIS-SIM-UC0003


START_TESTCASE BA-CTSYD-DIS-SIM-UN0001
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for RMobilePhone::GetServiceTable
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetServiceTable
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0001L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0001


START_TESTCASE BA-CTSYD-DIS-SIM-UN0002
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for RMobilePhone::ChangeSecurityCode
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::ChangeSecurityCode
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0002L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0002


START_TESTCASE BA-CTSYD-DIS-SIM-UN0003
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for RMobilePhone::GetSubscriberId
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetSubscriberId
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0003L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0003


START_TESTCASE BA-CTSYD-DIS-SIM-UN0004
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for RMobilePhone::GetCustomerServiceProfile
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCustomerServiceProfile
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0004L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0004


START_TESTCASE BA-CTSYD-DIS-SIM-UN0005
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for RMobilePhone::SetFdnSetting, RMobilePhone::VerifySecurityCode
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetFdnSetting
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0005L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0005

START_TESTCASE BA-CTSYD-DIS-SIM-UN0006
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for RMobilePhone::SetFdnSetting, RMobilePhone::VerifySecurityCode
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetFdnSetting
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0006L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0006

START_TESTCASE BA-CTSYD-DIS-SIM-UN0007
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for Power SIM On and Off
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::PowerSimOn() and RMmCustomAPI::PowerSimOff()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0007L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0007

START_TESTCASE BA-CTSYD-DIS-SIM-UN0008
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for a send APDU request (async and sync)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SendAPDUReq()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0008L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0008

START_TESTCASE BA-CTSYD-DIS-SIM-UN0009
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for SIM warm reset
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SimWarmReset()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0009L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0009

START_TESTCASE BA-CTSYD-DIS-SIM-UN0010
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for Notify Sim Card Status indicator
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifySimCardStatus()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0010L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0010

START_TESTCASE BA-CTSYD-DIS-SIM-UN0011
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for Set SIM Message Status Read
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetSimMessageStatusRead()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0011L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0011

START_TESTCASE BA-CTSYD-DIS-SIM-UN0012
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for Read Sim File
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadSimFile()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0012L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0012


START_TESTCASE BA-CTSYD-DIS-SIM-UN0013
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for Activate SimLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ActivateSimLock()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0013L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0013


START_TESTCASE BA-CTSYD-DIS-SIM-UN0014
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for DeActivate SimLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::DeActivateSimLock()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0014L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0014


START_TESTCASE BA-CTSYD-DIS-SIM-UN0015
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0015
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for Get Answer to Reset
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetATR()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0015L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0015


START_TESTCASE BA-CTSYD-DIS-SIM-UN0016
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for Get Sim Card Reader Status
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetSimCardReaderStatus()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0016L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0016


START_TESTCASE BA-CTSYD-DIS-SIM-UN0017
//!@SYMTestCaseID BA-CTSYD-DIS-SIM-UN0017
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSYDispatch for Get Wlan Sim Authentication Data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetWlanSimAuthenticationData()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySimFU.TestUnit0017L
END_TESTCASE BA-CTSYD-DIS-SIM-UN0017
