//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0001
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EMobilePhoneGetFdnStatus is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetFdnStatus() (Sync and Async)
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0001L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0001

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0007
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomNetWakeupIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NetWakeup()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0007L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0007

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0008
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomSetSystemNetworkModeIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes customApi::SetSystemNetworkMode() (Sync and Async)
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0008L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0008

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0009
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomGetCurrentSystemNetworkModesIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes customApi::GetCurrentSystemNetworkModes() (Sync and Async)
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0009L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0009


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0010
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomResetNetServerIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes customApi::ResetNetServer()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0010L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0010

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0011
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomSetAlwaysOnMode is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes customApi::SetAlwaysOn()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0011L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0011


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0012
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomSetDriveModeIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes customApi::SetDriveMode()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0012L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0012


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0013
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomReadHSxPAStatusIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes customApi::ReadHSxPAStatus()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0013L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0013

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0014
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomWriteHSxPAStatusIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes customApi::WriteHSxPAStatus()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0014L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0014


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0015
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0015
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomGetNetworkProviderNameIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes customApi::GetNetworkProviderName() (Sync and Async)
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0015L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0015


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0016
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomGetOperatorNameIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes customApi::GetOperatorName()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0016L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0016

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0017
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0017
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomGetCellInfoIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes customApi::GetCellInfo()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0017L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0017


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0018
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0018
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECtsyPhoneTerminateAllCallsReq is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes 
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0018L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0018


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0019
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0019
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EMobilePhoneGetServiceProviderName is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetServiceProviderName()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0019L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0019

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0020
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0020
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EMobilePhoneGetPhoneId is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetPhoneId()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0020L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0020


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0021
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0021
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EMobilePhoneGetDetectedNetworksV2Phase1 is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RetrieveMobilePhoneDetectedNetworks::StartV2()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0021L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0021



START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0022
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0022
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EMobilePhoneGetDetectedNetworksCancel is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes CGetDetectedNetworksAO::Cancel()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0022L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0022

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0023
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0023
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EMobilePhoneSelectNetwork is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SelectNetwork()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0023L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0023


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0024
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0024
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EMobilePhoneSelectNetworkCancel is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::CancelAsyncRequest()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0024L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0024


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0025
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0025
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EMobilePhoneSetNetworkSelectionSetting is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetNetworkSelectionSetting()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0025L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0025

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0026
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0026
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECtsyPhoneCellInfoIndReq is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCellInfo()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0026L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0026


START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0027
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0027
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECtsyPhoneCellInfoReq is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCellInfo()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0027L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0027



START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0028
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0028
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomGetServiceTableSupportbyApplicationIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetUSIMServiceSupport()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0028L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0028

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0029
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0029
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EMobilePhoneGetCurrentActiveUSimApplication is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetCurrentActiveUSimApplication()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0029L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0029

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0030
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0030
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomGetBandSelectionIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetSystemNetworkBand()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0030L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0030

START_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0031
//!@SYMTestCaseID BA-CTSYD-DIS-PHONE-NEGATIVE-UN0031
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECustomSetBandSelectionIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetSystemNetworkBand()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPhoneFUNegative.TestUnit0031L
END_TESTCASE BA-CTSYD-DIS-PHONE-NEGATIVE-UN0031
