//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0001
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketAttach is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::Attach()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0001L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0001

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0002
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketGetAttachMode is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::GetAttachMode()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0002L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0002

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0003
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketGetNtwkRegStatus is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::GetNtwkRegStatus()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0003L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0003

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0004
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketDetach is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::Detach()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0004L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0004

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0005
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketContextSetConfig is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::SetConfig()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0005L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0005

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0006
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketContextModifyActiveContext is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::ModifyActiveContext()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0006L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0006

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0007
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketContextInitialiseContext is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::InitialiseContext()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0007L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0007

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0008
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketContextDelete is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Delete()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0008L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0008

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0009
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketSetAttachMode is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::SetAttachMode()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0009L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0009

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0010
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketNotifyStatusChange - *Notify* NOT NEEDED
//!@SYMTestPriority High
//!@SYMTestActions Invokes 
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0010L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0010

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0011
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketSetDefaultContextParams is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::SetDefaultContextParams()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0011L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0011

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0012
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketContextActivate is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Activate()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0012L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0012

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0013
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketQoSSetProfileParams is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::SetProfileParameters()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0013L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0013

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0014
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketRejectActivationRequest is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::RejectActivationRequest()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0014L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0014

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0015
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0015
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketContextDeactivate is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Deactivate()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0015L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0015

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0016
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketContextAddPacketFilter is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::AddPacketFilter()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0016L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0016

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0018
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0018
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketInitProxiesIPC is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::Open() 
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0018L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0018

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0019
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0019
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketGetStaticCaps is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::GetStaticCaps()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0019L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0019

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0020
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0020
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketEnumerateMbmsMonitorServiceList is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::EnumerateMbmsMonitorServiceList()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0020L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0020

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0021
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0021
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketEnumerateMbmsActiveServiceList is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::EnumerateMbmsActiveServiceList()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0021L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0021

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0022
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0022
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if ECtsyPacketMbmsInitialiseContextReq is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::InitialiseContext()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0022L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0022

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0023
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0023
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketGetMbmsNetworkServiceStatus is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::GetMbmsNetworkServiceStatus()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0023L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0023

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0024
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0024
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketUpdateMbmsMonitorServiceList is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::UpdateMbmsMonitorServiceListL()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0024L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0024

START_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0025
//!@SYMTestCaseID BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0025
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test returned value if EPacketContextUpdateMbmsSessionList is not supported by LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketMbmsContext::UpdateMbmsSessionList()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 15 te_ctsydispatcher_component TEFUnit.CCTsyPacketServicesFUNegative.TestUnit0025L
END_TESTCASE BA-CTSYD-DIS-PACKETSERVICES-NEGATIVE-UN0025
