//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

START_TESTCASE BA-CTSYD-DIS-SAT-UC0001
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UC0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test CTSY/STK initialisation
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::Open()
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUseCase0001L
END_TESTCASE BA-CTSYD-DIS-SAT-UC0001


START_TESTCASE BA-CTSYD-DIS-SAT-UC0002
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UC0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for a representative Proactive Command session involving user interaction
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySetUpMenuPCmd, RSat::NotifyDisplayTextPCmd, RSat::NotifySelectItemPCmd,RSat::TerminalRsp, RSat::MenuSelection
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUseCase0002L
END_TESTCASE BA-CTSYD-DIS-SAT-UC0002


START_TESTCASE BA-CTSYD-DIS-SAT-UC0003
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UC0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for Getting and Icon Ef(Img) Record, Icon instance and CLUT
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::GetIcon , RSat::GetImageInstance, Rsat::GetClut
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUseCase0003L
END_TESTCASE BA-CTSYD-DIS-SAT-UC0003


START_TESTCASE BA-CTSYD-DIS-SAT-UC0004
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UC0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test setting up the event list then an event download (User Activity) from ETel
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySetUpEventListPCmd, Proactive command, RSat::TerminalRsp, RSat::EventDownload
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUseCase0004L
END_TESTCASE BA-CTSYD-DIS-SAT-UC0004


START_TESTCASE BA-CTSYD-DIS-SAT-UC0005
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UC0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for control related functionality - a call is requested via a proactive command and then modified via call control
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySetUpCallPCmd, RCall::OpenNewCall, RSat::TerminalRsp
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUseCase0005L
END_TESTCASE BA-CTSYD-DIS-SAT-UC0005


START_TESTCASE BA-CTSYD-DIS-SAT-UC0006
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UC0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for Timer Managment functionality
//!@SYMTestPriority High
//!@SYMTestActions Invokes Proactive command, Terminal response, Timer Expiration Envelope, (start a timer and wait for it to expire)
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUseCase0006L
END_TESTCASE BA-CTSYD-DIS-SAT-UC0006


START_TESTCASE BA-CTSYD-DIS-SAT-UC0007
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UC0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for Setting the polling interval and turning polling off.
//!@SYMTestPriority High
//!@SYMTestActions Invokes CTSY Internal Proactive command, Set Polling Interval, Terminal Response
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUseCase0007L
END_TESTCASE BA-CTSYD-DIS-SAT-UC0007


START_TESTCASE BA-CTSYD-DIS-SAT-UC0008
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UC0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY Mo Short Message Control
//!@SYMTestPriority High
//!@SYMTestActions Send up a "send sms" proactive command, send the SMS via RSat, then handle the mo sms control envelope 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUseCase0008L
END_TESTCASE BA-CTSYD-DIS-SAT-UC0008


START_TESTCASE BA-CTSYD-DIS-SAT-UC0009
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UC0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for Sms PP & Cell Broadcast Data Download
//!@SYMTestPriority High
//!@SYMTestActions Invokes CTSY Internal, create both SmsPP and Cell Broadcast envelopes
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUseCase0009L
END_TESTCASE BA-CTSYD-DIS-SAT-UC0009


START_TESTCASE BA-CTSYD-DIS-SAT-UC0010
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UC0010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test 
//!@SYMTestPriority High
//!@SYMTestActions Testing of Refresh Commands
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUseCase0010L
END_TESTCASE BA-CTSYD-DIS-SAT-UC0010


START_TESTCASE BA-CTSYD-DIS-SAT-UN0001
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for notify local info Proactive Command sequence
//!@SYMTestPriority High
//!@SYMTestActions Invokes PROVIDE LOCAL INFO proactive command, RSat::NotifyLocalInfoPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0001L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0001


START_TESTCASE BA-CTSYD-DIS-SAT-UN0002
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for notify of a Access Technology change
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::EventDownload, CallbackSatAccessTechnologyChangeInd
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0002L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0002


START_TESTCASE BA-CTSYD-DIS-SAT-UN0003
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc tests EVENT DOWNLOAD (LOCATION STATUS) and (via SET UP EVENT LIST pcmd)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::EventDownload, CallbackSatLocationStatusInd
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0003L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0003


START_TESTCASE BA-CTSYD-DIS-SAT-UN0004
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test of Call Connect and Call Disconnect Events from the LTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::EventDownload, CallbackSatCallConnectedInd, CallbackSatCallDisconnectedInd
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0004L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0004


START_TESTCASE BA-CTSYD-DIS-SAT-UN0005
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test MT Call event IPC
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::EventDownload, CallbackSatMtCallInd
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0005L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0005


START_TESTCASE BA-CTSYD-DIS-SAT-UN0006
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Timezone change IPCs
//!@SYMTestPriority High
//!@SYMTestActions Send an indicator to the CTSY with the new time zone - CallbackSatTimeZoneChangeInd
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0006L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0006


START_TESTCASE BA-CTSYD-DIS-SAT-UN0007
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc SET UP EVENT LIST proactive command
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySetUpEventListPCmd
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0007L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0007


START_TESTCASE BA-CTSYD-DIS-SAT-UN0008
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Testing RSat::NotifyProactiveSimSessionEnd support
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifyProactiveSimSessionEnd
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0008L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0008


START_TESTCASE BA-CTSYD-DIS-SAT-UN0009
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for notify local info (network measurement result) IPC
//!@SYMTestPriority High
//!@SYMTestActions Invokes CallbackSatPcmdInd, CallbackSatLocalInformationNmrComp
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0009L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0009


START_TESTCASE BA-CTSYD-DIS-SAT-UN0010
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for notify local info (timing advance) IPCs
//!@SYMTestPriority High
//!@SYMTestActions Invokes CallbackSatPcmdInd, CallbackSatTimingAdvanceComp
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0010L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0010


START_TESTCASE BA-CTSYD-DIS-SAT-UN0011
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for notify local info access technology ipcs
//!@SYMTestPriority High
//!@SYMTestActions Invokes CallbackSatPcmdInd, CallbackSatAccessTechnologyChangeInd
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0011L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0011


START_TESTCASE BA-CTSYD-DIS-SAT-UN0012
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for ESatTsyEnvelopeError api
//!@SYMTestPriority High
//!@SYMTestActions Invokes CallbackSatLocationStatusInd, CallbackSatCreateCallControlEnvelopeInd, HandleUssdControlEnvelopeErrorReqL
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0012L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0012


START_TESTCASE BA-CTSYD-DIS-SAT-UN0013
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for ESatNotifySetupCall (interaction between setup call proactive command and the call connected event)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifySetUpCallPCmd, RSat::NotifyCallControlRequest
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0013L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0013


START_TESTCASE BA-CTSYD-DIS-SAT-UN0014
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for refresh
//!@SYMTestPriority High
//!@SYMTestActions Invokes RSat::NotifyRefreshRequired, RSat::NotifyRefreshPCmd, RSat::NotifyRefreshAllowed, RSat::TerminalRsp
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0014L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0014


START_TESTCASE BA-CTSYD-DIS-SAT-UN0015
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0015
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for notify local info - location information request (i.e. cell id etc)
//!@SYMTestPriority High
//!@SYMTestActions Invokes CallbackSatProvideLocationInfoComp
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0015L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0015


START_TESTCASE BA-CTSYD-DIS-SAT-UN0016
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for the ESatTsySsStatus api
//!@SYMTestPriority High
//!@SYMTestActions Invokes 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0016L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0016


START_TESTCASE BA-CTSYD-DIS-SAT-UN0017
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-UN0017
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SatRefreshCompleteNotification()
//!@SYMTestPriority High
//!@SYMTestActions Invokes  RMmCustomAPI::SatRefreshCompleteNotification()
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFU.TestUnit0017L
END_TESTCASE BA-CTSYD-DIS-SAT-UN0017


