//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0001
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatGetSmsControlActivated::KLtsyDispatchSatGetSmsControlActivatedApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0001L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0001


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0002
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatPCmdNotification::KLtsyDispatchSatPCmdNotificationApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0002L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0002


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0003
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatGetDefaultBearerCapability::KLtsyDispatchSatGetDefaultBearerCapabilityApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0003L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0003


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0004
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatGetUssdControlSupported::KLtsyDispatchSatGetUssdControlSupportedApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0004L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0004


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0005
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatReady::KLtsyDispatchSatReadyApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0005L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0005


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0006
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatGetSmsPpDownloadSupported::KLtsyDispatchSatGetSmsPpDownloadSupportedApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0006L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0006


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0007
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatMenuSelectionEnvelope::KLtsyDispatchSatMenuSelectionEnvelopeApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0007L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0007


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0008
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatGetIconData::KLtsyDispatchSatGetIconDataApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0008L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0008


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0009
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatGetImageInstance::KLtsyDispatchSatGetImageInstanceApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0009L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0009


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0010
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatGetClut::KLtsyDispatchSatGetClutApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0010L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0010


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0011
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatEventDownloadEnvelope::KLtsyDispatchSatEventDownloadEnvelopeApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0011L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0011


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0013
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSmsSendSatSms::KLtsyDispatchSmsSendSatSmsApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0013L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0013


START_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0014
//!@SYMTestCaseID BA-CTSYD-DIS-SAT-NEGATIVE-UN0014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the MLtsyDispatchSatCallAndSmsControlEnvelope::KLtsyDispatchSatCallAndSmsControlEnvelopeApiId IPC is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySatFUNegative.TestUnit0014L
END_TESTCASE BA-CTSYD-DIS-SAT-NEGATIVE-UN0014


