//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

START_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0001
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-NEGATIVE-UN0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the NackSmsStored API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFUNegative.TestNackSmsStoredL
END_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0001


START_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0002
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-NEGATIVE-UN0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the AckSmsStored API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFUNegative.TestAckSmsStoredL
END_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0002


START_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0003
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-NEGATIVE-UN0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the SendMessage API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFUNegative.TestSendMessageL
END_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0003


START_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0004
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-NEGATIVE-UN0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the GetMessageStoreInfo (a.k.a GetSmsStoreInfo) API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFUNegative.TestGetSmsStoreInfoL
END_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0004


START_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0005
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-NEGATIVE-UN0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the ReadSmspListPhase1L API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API via the CRetrieveMobilePhoneSmspList AO, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFUNegative.TestGetSmspListL
END_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0005


START_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0006
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-NEGATIVE-UN0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the SendMessageNoFdnCheck API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFUNegative.TestSendMessageNoFdnCheckL
END_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0006


START_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0007
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-NEGATIVE-UN0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the ResumeSmsReception API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFUNegative.TestResumeSmsReceptionL
END_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0007


START_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0009
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-NEGATIVE-UN0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in CTSY dispatch when the StoreSmspListEntry API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFUNegative.TestStoreSmspListEntryL
END_TESTCASE BA-CTSYD-DIS-SMS-NEGATIVE-UN0009


