//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

//add use-case tests here

START_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-UC0001
//!@SYMTestCaseID BA-CTSYD-DIS-CELLBROADCAST-UC0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for ReceiveMessage(), CompleteReceiveMessageGsmCbs(), SetFilterSettingL(), GetFilterSetting()
//!@SYMTestPriority High
//!@SYMTestActions Invokes ReceiveMessageL(), CompleteReceiveMessageGsmCbs(), SetFilterSettingL(), GetFilterSetting()
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyCellBroadcastFU.TestUseCase0001L
END_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-UC0001

START_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-UC0002
//!@SYMTestCaseID BA-CTSYD-DIS-CELLBROADCAST-UC0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CompleteReceiveMessageWcdmaCbs()
//!@SYMTestPriority High
//!@SYMTestActions Invokes CompleteReceiveMessageWcdmaCbs()
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyCellBroadcastFU.TestUseCase0002L
END_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-UC0002

//add other unit tests here

START_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-UN0001
//!@SYMTestCaseID BA-CTSYD-DIS-CELLBROADCAST-UN0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for StartSimCbTopicBrowsing
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::StartSimCbTopicBrowsing()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyCellBroadcastFU.TestUnit0001L
END_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-UN0001

START_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-UN0002
//!@SYMTestCaseID BA-CTSYD-DIS-CELLBROADCAST-UN0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for DeleteSimCbTopic
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::DeleteSimCbTopic()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyCellBroadcastFU.TestUnit0002L
END_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-UN0002

START_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-UN0003
//!@SYMTestCaseID BA-CTSYD-DIS-CELLBROADCAST-UN0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CancelAsyncRequest()
//!@SYMTestPriority High
//!@SYMTestActions Invokes CancelAsyncRequest()
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyCellBroadcastFU.TestUnit0003L
END_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-UN0003
