//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

//add use-case tests here

START_TESTCASE BA-CTSYD-DIS-SMS-UC0001
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UC0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::ReceiveMessage()
//!@SYMTestPriority High
//!@SYMTestActions Invokes ReceiveMessage()
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUseCase0001L
END_TESTCASE BA-CTSYD-DIS-SMS-UC0001

START_TESTCASE BA-CTSYD-DIS-SMS-UC0002
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UC0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for successful RMobileSmsMessaging::SendMessage
//!@SYMTestPriority High
//!@SYMTestActions RMobileSmsMessaging::SendMessage
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUseCase0002L
END_TESTCASE BA-CTSYD-DIS-SMS-UC0002

//add other unit tests here

START_TESTCASE BA-CTSYD-DIS-SMS-UN0001
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UN0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::AckSmsStored()
//!@SYMTestPriority High
//!@SYMTestActions Invokes AckSmsStored()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUnit0001L
END_TESTCASE BA-CTSYD-DIS-SMS-UN0001

START_TESTCASE BA-CTSYD-DIS-SMS-UN0002
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UN0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::GetMessageStoreInfo()
//!@SYMTestPriority High
//!@SYMTestActions Invokes GetMessageStoreInfo()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUnit0002L
END_TESTCASE BA-CTSYD-DIS-SMS-UN0002

START_TESTCASE BA-CTSYD-DIS-SMS-UN0003
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UN0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for ReadSmspListPhase1L()
//!@SYMTestPriority High
//!@SYMTestActions Invokes ReadSmspListPhase1L()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUnit0003L
END_TESTCASE BA-CTSYD-DIS-SMS-UN0003

START_TESTCASE BA-CTSYD-DIS-SMS-UN0004
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UN0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::NackSmsStored()
//!@SYMTestPriority High
//!@SYMTestActions Invokes NackSmsStored()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUnit0004L
END_TESTCASE BA-CTSYD-DIS-SMS-UN0004

START_TESTCASE BA-CTSYD-DIS-SMS-UN0005
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UN0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::ReceiveMessage()
//!@SYMTestPriority High
//!@SYMTestActions Invokes ReceiveMessage()
//!@SYMTestExpectedResults Pass
//!@SYMTestType UT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUnit0005L
END_TESTCASE BA-CTSYD-DIS-SMS-UN0005

START_TESTCASE BA-CTSYD-DIS-SMS-UN0006
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UN0006
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::ResumeSmsReception
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmsMessaging::ResumeSmsReception
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUnit0006L
END_TESTCASE BA-CTSYD-DIS-SMS-UN0006

START_TESTCASE BA-CTSYD-DIS-SMS-UN0007
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UN0007
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::SendMessage
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmsMessaging::SendMessage
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUnit0007L
END_TESTCASE BA-CTSYD-DIS-SMS-UN0007

START_TESTCASE BA-CTSYD-DIS-SMS-UN0008
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UN0008
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::SendMessageNoFdnCheck
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmsMessaging::SendMessageNoFdnCheck
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUnit0008L
END_TESTCASE BA-CTSYD-DIS-SMS-UN0008

START_TESTCASE BA-CTSYD-DIS-SMS-UN0009
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UN0009
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileSmsMessaging::SetMoSmsBearer
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileSmsMessaging::SetMoSmsBearer
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUnit0009L
END_TESTCASE BA-CTSYD-DIS-SMS-UN0009

START_TESTCASE BA-CTSYD-DIS-SMS-UN0010
//!@SYMTestCaseID BA-CTSYD-DIS-SMS-UN0010
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::StoreSmspListL 
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileSmsMessaging::StoreSmspListL
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsySmsFU.TestUnit0010L
END_TESTCASE BA-CTSYD-DIS-SMS-UN0010
