//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

START_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0001
//!@SYMTestCaseID BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in SIM CTSY dispatch when the ActivateBroadcastReceiveMessage API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyCellBroadcastFUNegative.TestMessagingReceiveMessageL
END_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0001


START_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0002
//!@SYMTestCaseID BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in SIM CTSY dispatch when the ReceiveMessageCancel API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyCellBroadcastFUNegative.TestMessagingReceiveMessageCancelL
END_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0002


START_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0003
//!@SYMTestCaseID BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in SIM CTSY dispatch when the SetBroadcastFilterSetting API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyCellBroadcastFUNegative.TestSetBroadcastFilterSettingL
END_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0003


START_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0004
//!@SYMTestCaseID BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in SIM CTSY dispatch when the StartSimCbTopicBrowsing API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyCellBroadcastFUNegative.TestStartSimCbTopicBrowsingL
END_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0004


START_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0005
//!@SYMTestCaseID BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test handing in SIM CTSY dispatch when the DeleteSimCbTopic API is disabled 
//!@SYMTestPriority High
//!@SYMTestActions Disable API, call API, check correct error returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsydispatcher_component TEFUnit.CCTsyCellBroadcastFUNegative.TestDeleteSimCbTopicL
END_TESTCASE BA-CTSYD-DIS-CELLBROADCAST-NEGATIVE-UN0005


