//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsydispatcher_component

RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_phone_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_multiparty_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_callcontrol_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_cellbroadcast_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_packetservices_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_phonebook_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_phonebooken_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_phonebookon_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_sat_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_security_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_sim_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_sms_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_suppl_serv_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_timeout.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_phonebooken_negative_individual.script

RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_callcontrol_negative_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_packetservices_neg_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_phonebook_negative_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_phone_negative_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_security_negative_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_suppl_serv_negative_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_phonebookon_neg_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_cellbroadcast_neg_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_sim_neg_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_sms_neg_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_multiparty_neg_individual.script
RUN_SCRIPT z:\TestData\Scripts\te_ctsydispatchcomponent_sat_neg_individual.script
