//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
// This script is intended to be called by a script that manages the set up / shutdown of
// the test environment that will be used to run the tests.

PRINT TE_IPCTest: IPC tests
PRINT ------------------------------
PRINT

LOAD_SUITE TE_IPCTest


START_TESTCASE			COMINF-ESOCK-IPCTest-0101
//! @SYMTestCaseID		COMINF-ESOCK-IPCTest-0101

PRINT Create a client/server connection
RUN_TEST_STEP 10 TE_IPCTest IPCTest01
END_TESTCASE			COMINF-ESOCK-IPCTest-0101


START_TESTCASE			COMINF-ESOCK-IPCTest-0102
//! @SYMTestCaseID		COMINF-ESOCK-IPCTest-0102

PRINT Simple data transfer
RUN_TEST_STEP 10 TE_IPCTest IPCTest02
END_TESTCASE			COMINF-ESOCK-IPCTest-0102


START_TESTCASE			COMINF-ESOCK-IPCTest-0103
//! @SYMTestCaseID		COMINF-ESOCK-IPCTest-0103

PRINT Long data transfer
RUN_TEST_STEP 10 TE_IPCTest IPCTest03
END_TESTCASE			COMINF-ESOCK-IPCTest-0103


START_TESTCASE			COMINF-ESOCK-IPCTest-0104
//! @SYMTestCaseID		COMINF-ESOCK-IPCTest-0104

PRINT Multithreaded data transfer
RUN_TEST_STEP 10 TE_IPCTest IPCTest04
END_TESTCASE			COMINF-ESOCK-IPCTest-0104


START_TESTCASE			COMINF-ESOCK-IPCTest-0105
//! @SYMTestCaseID		COMINF-ESOCK-IPCTest-0105

PRINT Illegal operations
RUN_TEST_STEP 10 TE_IPCTest IPCTest05
END_TESTCASE			COMINF-ESOCK-IPCTest-0105


START_TESTCASE			COMINF-ESOCK-IPCTest-0106
//! @SYMTestCaseID		COMINF-ESOCK-IPCTest-0106

PRINT IOCTL controls
RUN_TEST_STEP 10 TE_IPCTest IPCTest06
END_TESTCASE			COMINF-ESOCK-IPCTest-0106


// Memory leak tests moved to TE_IPCTest_tests-AH.script
