//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
// Ensure that the default config is present if no cleverer one has been put there already
RUN_SCRIPT z:\testdata\scripts\exec_esock_default_to_config_1.script
RUN_SCRIPT z:\TestData\scripts\te_esock_test_unloadesockForced.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script

RUN_SCRIPT z:\testdata\scripts\te_ipctest_tests.script
RUN_SCRIPT z:\testdata\scripts\te_ipctest_tests-mem.script

RUN_SCRIPT z:\TestData\scripts\te_esock_test_unloadesockForced.script


