//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
// This script is intended to be called by a script that manages the set up / shutdown of
// the test environment that will be used to run the tests.

PRINT TE_IPCTest: IPC Alloc Heaven tests
PRINT ------------------------------
PRINT

LOAD_SUITE TE_IPCTest


START_TESTCASE			COMINF-ESOCK-IPCTest-0107
//! @SYMTestCaseID		COMINF-ESOCK-IPCTest-0107

PRINT Data Transfer Memory Leak
RUN_TEST_STEP 10 TE_IPCTest IPCTest07
END_TESTCASE			COMINF-ESOCK-IPCTest-0107


START_TESTCASE			COMINF-ESOCK-IPCTest-0108
//! @SYMTestCaseID		COMINF-ESOCK-IPCTest-0108

PRINT Open Socket Memory Leak
RUN_TEST_STEP 10 TE_IPCTest IPCTest08
END_TESTCASE			COMINF-ESOCK-IPCTest-0108
