// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_UTILS  MkDir c:\ems
RUN_UTILS  CopyFile Z:\ems\anims.mbm 	c:\ems\anims.mbm
RUN_UTILS  CopyFile Z:\ems\pics.mbm 	c:\ems\pics.mbm

LOAD_SUITE te_gsmu_ems

START_TESTCASE SMS-SMSStack-NA-7000
//!@SYMTestCaseID SMS-SMSStack-NA-7000
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testaddingpredefsoundaftermelodyStep

END_TESTCASE SMS-SMSStack-NA-7000

START_TESTCASE SMS-SMSStack-NA-7001
//!@SYMTestCaseID SMS-SMSStack-NA-7001
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testcorruptedinformationelementsStep

END_TESTCASE SMS-SMSStack-NA-7001

START_TESTCASE SMS-SMSStack-NA-7002
//!@SYMTestCaseID SMS-SMSStack-NA-7002
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testcsmsmessageemsapiStep

END_TESTCASE SMS-SMSStack-NA-7002

START_TESTCASE SMS-SMSStack-NA-7003
//!@SYMTestCaseID SMS-SMSStack-NA-7003
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testcsmsmessageemsgetapiStep

END_TESTCASE SMS-SMSStack-NA-7003

START_TESTCASE SMS-SMSStack-NA-7004
//!@SYMTestCaseID SMS-SMSStack-NA-7004
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testemsanimationieStep

END_TESTCASE SMS-SMSStack-NA-7004

START_TESTCASE SMS-SMSStack-NA-7005
//!@SYMTestCaseID SMS-SMSStack-NA-7005
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testemsformatieStep

END_TESTCASE SMS-SMSStack-NA-7005

START_TESTCASE SMS-SMSStack-NA-7006
//!@SYMTestCaseID SMS-SMSStack-NA-7006
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testemsierelativestartpositionStep

END_TESTCASE SMS-SMSStack-NA-7006

START_TESTCASE SMS-SMSStack-NA-7007
//!@SYMTestCaseID SMS-SMSStack-NA-7007
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testemsodiieStep

END_TESTCASE SMS-SMSStack-NA-7007

START_TESTCASE SMS-SMSStack-NA-7008
//!@SYMTestCaseID SMS-SMSStack-NA-7008
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testemsoomStep

END_TESTCASE SMS-SMSStack-NA-7008

START_TESTCASE SMS-SMSStack-NA-7009
//!@SYMTestCaseID SMS-SMSStack-NA-7009
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testemspictureieStep

END_TESTCASE SMS-SMSStack-NA-7009

START_TESTCASE SMS-SMSStack-NA-7010
//!@SYMTestCaseID SMS-SMSStack-NA-7010
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testemspredefanimationieStep

END_TESTCASE SMS-SMSStack-NA-7010

START_TESTCASE SMS-SMSStack-NA-7011
//!@SYMTestCaseID SMS-SMSStack-NA-7011
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testemspredefsoundieStep

END_TESTCASE SMS-SMSStack-NA-7011

START_TESTCASE SMS-SMSStack-NA-7012
//!@SYMTestCaseID SMS-SMSStack-NA-7012
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testemssoundieStep

END_TESTCASE SMS-SMSStack-NA-7012

START_TESTCASE SMS-SMSStack-NA-7013
//!@SYMTestCaseID SMS-SMSStack-NA-7013
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testemsuserpromptieStep

END_TESTCASE SMS-SMSStack-NA-7013

START_TESTCASE SMS-SMSStack-NA-7014
//!@SYMTestCaseID SMS-SMSStack-NA-7014
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testformattingsegmentationStep

END_TESTCASE SMS-SMSStack-NA-7014

START_TESTCASE SMS-SMSStack-NA-7015
//!@SYMTestCaseID SMS-SMSStack-NA-7015
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testinvalidodipositioningStep

END_TESTCASE SMS-SMSStack-NA-7015

START_TESTCASE SMS-SMSStack-NA-7016
//!@SYMTestCaseID SMS-SMSStack-NA-7016
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testinvalidpromptpositioningStep

END_TESTCASE SMS-SMSStack-NA-7016

START_TESTCASE SMS-SMSStack-NA-7017
//!@SYMTestCaseID SMS-SMSStack-NA-7017
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testnumberofmessagesStep

END_TESTCASE SMS-SMSStack-NA-7017

START_TESTCASE SMS-SMSStack-NA-7018
//!@SYMTestCaseID SMS-SMSStack-NA-7018
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testoftextobjectpositioningStep

END_TESTCASE SMS-SMSStack-NA-7018

START_TESTCASE SMS-SMSStack-NA-7019
//!@SYMTestCaseID SMS-SMSStack-NA-7019
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testremovalofmultipleodiandupiesStep

END_TESTCASE SMS-SMSStack-NA-7019

START_TESTCASE SMS-SMSStack-NA-7020
//!@SYMTestCaseID SMS-SMSStack-NA-7020
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testremovalofodiandupiesStep

END_TESTCASE SMS-SMSStack-NA-7020

START_TESTCASE SMS-SMSStack-NA-7021
//!@SYMTestCaseID SMS-SMSStack-NA-7021
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testremovalofodicontrollediesStep

END_TESTCASE SMS-SMSStack-NA-7021

START_TESTCASE SMS-SMSStack-NA-7022
//!@SYMTestCaseID SMS-SMSStack-NA-7022
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testremovenonexistingobjectStep

END_TESTCASE SMS-SMSStack-NA-7022

START_TESTCASE SMS-SMSStack-NA-7023
//!@SYMTestCaseID SMS-SMSStack-NA-7023
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testsamepositionStep

END_TESTCASE SMS-SMSStack-NA-7023

START_TESTCASE SMS-SMSStack-NA-7024
//!@SYMTestCaseID SMS-SMSStack-NA-7024
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems teststreamingStep

END_TESTCASE SMS-SMSStack-NA-7024

START_TESTCASE SMS-SMSStack-NA-7025
//!@SYMTestCaseID SMS-SMSStack-NA-7025
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Simulated Packet Tests
//!@SYMTestPriority critical
//!@SYMTestActions Tests packet functionality using simtsy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_gsmu_ems testtoobigconcatenatedemsmessageStep
END_TESTCASE SMS-SMSStack-NA-7025

