// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run CTestMiscAdaptationPlugin tests

RUN_PROGRAM -1 setcap tiadaptation_plugin.exe 0003FFFE -SID 2000D75B tiadaptation_plugin_WithSSM_SID.exe

LOAD_SUITE tiadaptation_plugin_WithSSM_SID

START_TESTCASE 			DEVSRVS-SSPLUGINS-SAS-0003
//! @SYMTestCaseID  		DEVSRVS-SSPLUGINS-SAS-0003
//! @SYMPREQ 			PREQ1871
//! @SYMREQ			REQ9132
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Test RSsmaMiscAdaptation Functionalities 
//! @SYMTestActions    		1. a) Connect to the RSsmaMiscAdaptation. 
//!                    		   b) Call GetGlobalStartupMode() with Tbool argument set.
//!                    		   C) Call SecurityStateChange().
//!                    		   D) Call GetSimLanguages()
//!                    		2. a) Connect to the RSsmaMiscAdaptation  with client1.
//!                    		   b) Call GetGlobalStartupMode () with Tbool argument set.
//!                    		   c) Connect to the RSsmaMiscAdaptation  with client2.
//!                    		   d) Call GetGlobalStartupMode with TBool argument Set.
//!                    		   e) Debug manually to know that the iQueue value in the server is set.
//! @SYMTestExpectedResults 	Check For the aRequestStatus  value to be KErrNone or KErrNotSupported 
RUN_TEST_STEP 100 tiadaptation_plugin_WithSSM_SID CTestMiscAdaptationPlugin
END_TESTCASE 			DEVSRVS-SSPLUGINS-SAS-0003