// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file

//
RUN_SCRIPT z:\TestData\Scripts\Te_SimSms_setup.script
//
LOAD_SUITE Te_SimSms
//

START_TESTCASE TEL-SIMTSY-NA-3000
//!@SYMTestCaseID TEL-SIMTSY-NA-3000
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms TestUtilClass

END_TESTCASE TEL-SIMTSY-NA-3000

START_TESTCASE TEL-SIMTSY-NA-3001
//!@SYMTestCaseID TEL-SIMTSY-NA-3001
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms GetCaps

END_TESTCASE TEL-SIMTSY-NA-3001

START_TESTCASE TEL-SIMTSY-NA-3002
//!@SYMTestCaseID TEL-SIMTSY-NA-3002
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms TestSmspList

END_TESTCASE TEL-SIMTSY-NA-3002

START_TESTCASE TEL-SIMTSY-NA-3003
//!@SYMTestCaseID TEL-SIMTSY-NA-3003
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms MessageStoreInfo

END_TESTCASE TEL-SIMTSY-NA-3003

START_TESTCASE TEL-SIMTSY-NA-3004
//!@SYMTestCaseID TEL-SIMTSY-NA-3004
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 60 Te_SimSms MessageStoreOps

END_TESTCASE TEL-SIMTSY-NA-3004

START_TESTCASE TEL-SIMTSY-NA-3005
//!@SYMTestCaseID TEL-SIMTSY-NA-3005
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms SendSms

END_TESTCASE TEL-SIMTSY-NA-3005

START_TESTCASE TEL-SIMTSY-NA-3006
//!@SYMTestCaseID TEL-SIMTSY-NA-3006
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms ReceiveUnstoredSms

END_TESTCASE TEL-SIMTSY-NA-3006

START_TESTCASE TEL-SIMTSY-NA-3007
//!@SYMTestCaseID TEL-SIMTSY-NA-3007
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms ReceiveStoredSms

END_TESTCASE TEL-SIMTSY-NA-3007

START_TESTCASE TEL-SIMTSY-NA-3008
//!@SYMTestCaseID TEL-SIMTSY-NA-3008
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms ReceiveStoredSmsAndCancel

END_TESTCASE TEL-SIMTSY-NA-3008

START_TESTCASE TEL-SIMTSY-NA-3009
//!@SYMTestCaseID TEL-SIMTSY-NA-3009
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms SendSmsAndCancel

END_TESTCASE TEL-SIMTSY-NA-3009

START_TESTCASE TEL-SIMTSY-NA-3010
//!@SYMTestCaseID TEL-SIMTSY-NA-3010
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms AckSmsStored

END_TESTCASE TEL-SIMTSY-NA-3010

START_TESTCASE TEL-SIMTSY-NA-3011
//!@SYMTestCaseID TEL-SIMTSY-NA-3011
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms AckSmsStoredCancel

END_TESTCASE TEL-SIMTSY-NA-3011

START_TESTCASE TEL-SIMTSY-NA-3012
//!@SYMTestCaseID TEL-SIMTSY-NA-3012
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms NackSmsStored

END_TESTCASE TEL-SIMTSY-NA-3012

START_TESTCASE TEL-SIMTSY-NA-3013
//!@SYMTestCaseID TEL-SIMTSY-NA-3013
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms NackSmsStoredCancel

END_TESTCASE TEL-SIMTSY-NA-3013

START_TESTCASE TEL-SIMTSY-NA-3014
//!@SYMTestCaseID TEL-SIMTSY-NA-3014
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms AckSmsStoredWithResponse

END_TESTCASE TEL-SIMTSY-NA-3014

START_TESTCASE TEL-SIMTSY-NA-3015
//!@SYMTestCaseID TEL-SIMTSY-NA-3015
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms AckSmsStoredWithResponseCancel

END_TESTCASE TEL-SIMTSY-NA-3015

START_TESTCASE TEL-SIMTSY-NA-3016
//!@SYMTestCaseID TEL-SIMTSY-NA-3016
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms NackSmsStoredWithResponse

END_TESTCASE TEL-SIMTSY-NA-3016

START_TESTCASE TEL-SIMTSY-NA-3017
//!@SYMTestCaseID TEL-SIMTSY-NA-3017
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms NackSmsStoredWithResponseCancel

END_TESTCASE TEL-SIMTSY-NA-3017

START_TESTCASE TEL-SIMTSY-NA-3018
//!@SYMTestCaseID TEL-SIMTSY-NA-3018
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms ResumeSmsReception

END_TESTCASE TEL-SIMTSY-NA-3018

START_TESTCASE TEL-SIMTSY-NA-3019
//!@SYMTestCaseID TEL-SIMTSY-NA-3019
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms NotifySmsEvent

END_TESTCASE TEL-SIMTSY-NA-3019

START_TESTCASE TEL-SIMTSY-NA-3020
//!@SYMTestCaseID TEL-SIMTSY-NA-3020
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc 
//!@SYMTestPriority Critical
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 30 Te_SimSms NotifySmsEventCancel
END_TESTCASE TEL-SIMTSY-NA-3020

