// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// copies the config files for test cases 
// 
//

PRINT Loading TEC32MTConfig18

RUN_UTILS CopyFile z:\testdata\configs\C32\TestC32MTConfig18\C32HeapCheck.ini c:\testdata\configs\TestC32MTConfig18\C32HeapCheck.ini
RUN_UTILS MakeReadWrite c:\testdata\configs\TestC32MTConfig18\C32HeapCheck.ini

