// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run StartupProperties test 

LOAD_SUITE tstartupproperties_server

START_TESTCASE 			DEVSRVS-SYSSTART-STARTUPPROPERTIES-0001
//! @SYMTestCaseID 		DEVSRVS-SYSSTART-STARTUPPROPERTIES-0001
//! @SYMPREQ 			PREQ1089
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Check CStartupProperties is created with correct default values.
//! @SYMTestActions		Verify that correct default values are defined in the 
//! 				structs declared in startup.rh.
//! @SYMTestExpectedResults 	The values should match expected values.
RUN_TEST_STEP 100 tstartupproperties_server DefVal
END_TESTCASE 			DEVSRVS-SYSSTART-STARTUPPROPERTIES-0001
