//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//##########################################################################################################
//-- We need a certain CommsDB to work with DHCP.
//-- So, let's borrow it from rconnectionconfigdaemontests_Connection.script
//-- !!! Will probably need to create ours
//##########################################################################################################

run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
//ced z:\TestData\configs\rconnectionconfigdaemon.xml
//ced  c:\rconnectionconfigdaemon.xml
ced  z:\testdata\configs\te_esock.xml
run_script z:\TestData\scripts\te_esock_test_loadesock.script

//-----------------------------------------------------------------------------------------------------------

START_TESTCASE			COMINF-ESOCK-CapTests-Resolver-0101
//! @SYMTestCaseID		COMINF-ESOCK-CapTests-Resolver-0101

PARAM_FOREACH_CAP_BEGIN
// --------------------
// Use Setcap to change capabilities of harness (MASK = PARAM_FOREACH_HEX_CAPABILITY)
RUN_PROGRAM -1 setcap PARAM_SVR_SUITENAME.exe PARAM_FOREACH_HEX_CAPABILITY C:\sys\bin\PARAM_SVR_SUITENAME_sc.exe
//Please don't ammend the following PRINT Line as it is used by CapToolSumm to generate its report
PRINT --------  capabilities now set to [PARAM_FOREACH_STRING_CAPABILITY] (MASK = PARAM_FOREACH_HEX_CAPABILITY)  --------

RUN_SCRIPT  Z:\TestData\Scripts\Cap_PARAM_FOREACH_HEX_CAPABILITY_RESSub.script
PARAM_FOREACH_CAP_END
// --------------------

END_TESTCASE			COMINF-ESOCK-CapTests-Resolver-0101


//-----------------------------------------------------------------------------------------------------------
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
