// Copyright (c) 2003-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Contains tests to run on a platform where neither PORT 0 or PORT 1 are available.
// 
//

LOAD_SUITE te_c32
LOAD_SUITE te_c32util

//!@file
//!@SYMTestCaseID SERCOM/C32/NA/0001
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Initializes the c32 drivers
//!@SYMTestPriority High
//!@SYMTestActions Loads LDD and PDD files and leaves them in memory at the end of the test
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestInit

//!@SYMTestCaseID SERCOM/C32/NA/0002
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Attempts to start C32 twice
//!@SYMTestPriority High
//!@SYMTestActions Starts c32 - serial communications server twice 
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestDoubleStart
//!@SYMTestCaseID SERCOM/C32/NA/0005
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Tests the information services
//!@SYMTestPriority High
//!@SYMTestActions Gets information on: number of loaded comms modules, and on serial ports  
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestInfo
//!@SYMTestCaseID SERCOM/C32/NA/0015
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test connecting under OOM (Out Of Memory) situation
//!@SYMTestPriority High
//!@SYMTestActions Connects to the comms server in a loop where the heap allocation failure is simulated.
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT 
RUN_TEST_STEP 100 te_c32 TestOOMConnection
//!@SYMTestCaseID SERCOM/C32/NA/0018
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Starting Thread within C32 Process
//!@SYMTestPriority High
//!@SYMTestActions Creates thread in serial communication process
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestStartServerThread
//!@SYMTestCaseID SERCOM/C32/NA/0021
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test that attempts to allocate a timer under OOM conditions
//!@SYMTestPriority High
//!@SYMTestActions Trying to handle a global timer allocation failure, and test global timer allocation success
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestTimerAllocation

//!@SYMTestCaseID SERCOM/C32/NA/0033
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Tests number of loaded CSY modules
//!@SYMTestPriority High
//!@SYMTestActions Gets how many comms module (CSYs) are loaded using NumPort() function call
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 Lsc32ListNumberOfLoadedCSYs

//!@SYMTestCaseID SERCOM/C32/NA/0034
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Tests loading and unloading comms module
//!@SYMTestPriority High
//!@SYMTestActions Loads and unload comms module
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 Lsc32LoadUnloadCsy

//!@SYMTestCaseID SERCOM/C32/NA/0035
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test that gets port info for all comms modules loaded
//!@SYMTestPriority High
//!@SYMTestActions Gets port info for all comms modules loaded
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 Lsc32GetPortInfo

//!@SYMTestCaseID SERCOM/C32/NA/0036
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Calls every C32 API methods as DTE and DCE, will panic if errors occurs on received parameters or return values
//!@SYMTestPriority High
//!@SYMTestActions Calls every C32 API methods DTE and DCE, will panic if errors occurs on received parameters return values
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 300 te_c32 DummyTest

//!@SYMTestCaseID SERCOM/C32/NA/0037
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Tests setting a comm port as a DCE
//!@SYMTestPriority High
//!@SYMTestActions Tests setting a comm port as a DCE 
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestDCEPort

//!@file
//!@SYMTestCaseID SERCOM/C32/NA/0038
//!@SYMREQ CNON-67WJ2G
//!@SYMTestCaseDesc Test Loopback
//!@SYMTestPriority High
//!@SYMTestActions Loads Loopback module, reads and writes some blocks of data
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 200 te_c32 TestLoopback

//!@SYMTestCaseID SERCOM/C32/NA/0039
//!@SYMREQ DEF080077
//!@SYMTestCaseDesc Ensure data written and read match each other
//!@SYMTestPriority High
//!@SYMTestActions Starts c32 - serial communications 
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestCorrectDataRead

//!@SYMTestCaseID SERCOM/C32/NA/0040
//!@SYMREQ DEF080077
//!@SYMTestCaseDesc Test memory is reclaimed when ResetBuffers called
//!@SYMTestPriority High
//!@SYMTestActions Starts c32 - serial communications
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestResetBuffers

//!@SYMTestCaseID SERCOM/C32/NA/0041
//!@SYMREQ DEF080077
//!@SYMTestCaseDesc Allocate new heap memory from heap for write buf 
//!@SYMTestPriority High
//!@SYMTestActions Starts c32 - serial communications 
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestAllocMoreWriteMem

//!@SYMTestCaseID SERCOM/C32/NA/0042
//!@SYMREQ DEF080077
//!@SYMTestCaseDesc Ensures a write fail is handled correctly
//!@SYMTestPriority High
//!@SYMTestActions Starts c32 - serial communications
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestMemoryWriteFail

//!@SYMTestCaseID SERCOM/C32/NA/0043
//!@SYMREQ DEF080077
//!@SYMTestCaseDesc Ensures a write fails once maximum buffer size is
//!@                reached
//!@SYMTestPriority High
//!@SYMTestActions Starts c32 - serial communications
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestMaxBufferOverflow

//!@SYMTestCaseID SERCOM/C32/NA/0044
//!@SYMREQ DEF096709 
//!@SYMTestCaseDesc Test various combinations of OpenWhenAvailable and its cancel function.
//!@SYMTestPriority High
//!@SYMTestActions Starts c32 - serial communications
//!@SYMTestExpectedResults Pass, if any APIs fail the step will leave.
//!@SYMTestType CT
RUN_TEST_STEP 100 te_c32 TestOpenWhenAvailable

//!@SYMTestCaseID SERCOM/C32/NA/0045
//!@SYMREQ DEF128110
//!@SYMTestCaseDesc Check for handle leaks at comms server shutdown
RUN_TEST_STEP 500 te_c32util TE_C32UtilUnloadC32
