//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
//! @SYMTestSuiteName NET-BEARERMOBILITY
//! @SYMScriptTestEnvironment Standard Symbian HRP or emulator environment

// Load the test suite
LOAD_SUITE te_esockteststepsSuite -SharedData

START_TESTCASE			COMINF-ESOCK-RConnection-Mobility-2901
//! @SYMTestCaseID		COMINF-ESOCK-RConnection-Mobility-2901
//!@SYMTestCaseDesc           	TODO_CDG
//!@SYMPREQ                   	PREQ1060
//!@SYMAPI
// TODO_CDG
//!@SYMTestPriority           	Critical
//!@SYMTestActions
// TODO_CDG
//!@SYMTestType               	CIT
//!@SYMTestExpectedResults    	TODO_CDG

// Set up the comms database and start esock in preparation for the test
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
CED -i z:\testdata\configs\BearerMobility\BearerMobility_001.ced.cfg c:\BearerMobility_001.ced.cfg.log
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

// Create and connect socketserver and connectionserver instances
RUN_TEST_STEP 100 te_esockteststepsSuite creatersocketservStep z:\testdata\configs\BearerMobility\Mobility_761110.ini CreateSockSvr
RUN_TEST_STEP 100 te_esockteststepsSuite connectrsocketservStep z:\testdata\configs\BearerMobility\Mobility_761110.ini ConnectSockSvr

// Make both access points available to start with
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\BearerMobility\Mobility_761110.ini MakeAPAvailable_1
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\BearerMobility\Mobility_761110.ini MakeAPAvailable_2

// TODO_CDG plenty to add here yet!

// Close resources we opened
RUN_TEST_STEP 100 te_esockteststepsSuite closersocketservStep z:\testdata\configs\BearerMobility\Mobility_761110.ini CloseSocketSvr1

// Cleanup post test
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep
RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
END_TESTCASE			COMINF-ESOCK-RConnection-Mobility-2901


PRINT Completed NET_BMOBILITY_761120



