// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all te_sysutils Suite Tests

LOAD_SUITE te_sysutiltestsuite

RUN_UTILS MkDir c:\versions

START_TESTCASE				SYSLIB-BAFL-CT-4001
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsGetSWVersion z:\testdata\inifiles\te_sysutildata.ini ResourceFiles
END_TESTCASE				SYSLIB-BAFL-CT-4001


START_TESTCASE				SYSLIB-BAFL-CT-4002
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsGetLangSWVersion z:\testdata\inifiles\te_sysutildata.ini ResourceFiles
END_TESTCASE				SYSLIB-BAFL-CT-4002


START_TESTCASE				SYSLIB-BAFL-CT-4003
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsGetLangVersion z:\testdata\inifiles\te_sysutildata.ini ResourceFiles
END_TESTCASE				SYSLIB-BAFL-CT-4003


START_TESTCASE				SYSLIB-BAFL-CT-4004
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsFFSSpaceBelowCritical
END_TESTCASE				SYSLIB-BAFL-CT-4004


START_TESTCASE				SYSLIB-BAFL-CT-4005
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsMMCSpaceBelowCritical
END_TESTCASE				SYSLIB-BAFL-CT-4005


START_TESTCASE				SYSLIB-BAFL-CT-4006
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsDiskSpaceBelowCritical
END_TESTCASE				SYSLIB-BAFL-CT-4006


START_TESTCASE				SYSLIB-BAFL-CT-4007
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsDisksBelowCritical
END_TESTCASE				SYSLIB-BAFL-CT-4007


START_TESTCASE				SYSLIB-BAFL-CT-4016
RUN_TEST_STEP !PanicString=BAFL !PanicCode=110 1000 te_sysutiltestsuite SysUtilsCheckRFsConnectionDS
RUN_TEST_STEP !PanicString=BAFL !PanicCode=110 1000 te_sysutiltestsuite SysUtilsCheckRFsConnectionFFS
RUN_TEST_STEP !PanicString=BAFL !PanicCode=110 1000 te_sysutiltestsuite SysUtilsCheckRFsConnectionMMC
END_TESTCASE				SYSLIB-BAFL-CT-4016

START_TESTCASE				BASESRVCS-BAFL-CT-4079
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsDiskSpaceBelowCriticalQuery
END_TESTCASE				BASESRVCS-BAFL-CT-4079

START_TESTCASE				BASESRVCS-BAFL-CT-4080
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsMmcSpaceBelowCriticalQuery
END_TESTCASE				BASESRVCS-BAFL-CT-4080

START_TESTCASE				BASESRVCS-BAFL-CT-4081
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsFssSpaceBelowCriticalQuery
END_TESTCASE				BASESRVCS-BAFL-CT-4081

START_TESTCASE				SYSLIB-BAFL-CT-4017
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsDiskSpaceNotFoundBelowCritical
END_TESTCASE				SYSLIB-BAFL-CT-4017


START_TESTCASE				SYSLIB-BAFL-CT-4018
RUN_TEST_STEP !PanicString=BAFL !PanicCode=110 1000 te_sysutiltestsuite SysUtilsFFSSpaceBelowCriticalRfs
END_TESTCASE				SYSLIB-BAFL-CT-4018


START_TESTCASE				SYSLIB-BAFL-CT-4019
RUN_TEST_STEP !PanicString=BAFL !PanicCode=110 1000 te_sysutiltestsuite SysUtilsMMCSpaceBelowCriticalRfs
END_TESTCASE				SYSLIB-BAFL-CT-4019


START_TESTCASE				SYSLIB-BAFL-CT-4020
RUN_TEST_STEP !PanicString=BAFL !PanicCode=110 1000 te_sysutiltestsuite SysUtilsDiskSpaceBelowCriticalLevelLError
END_TESTCASE				SYSLIB-BAFL-CT-4020


START_TESTCASE				SYSLIB-BAFL-CT-4021
RUN_TEST_STEP !OOM 1000 te_sysutiltestsuite SysUtilsOOMTest
END_TESTCASE				SYSLIB-BAFL-CT-4021


START_TESTCASE				SYSLIB-BAFL-CT-4022
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsGetSWVersionInsufficienBuffer
END_TESTCASE				SYSLIB-BAFL-CT-4022


START_TESTCASE				SYSLIB-BAFL-CT-4023
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsDummyAPIs
END_TESTCASE				SYSLIB-BAFL-CT-4023


START_TESTCASE				SYSLIB-BAFL-CT-4038
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsCheckDriveLetterFFS z:\testdata\inifiles\te_sysutildata.ini DriveLetter
RUN_TEST_STEP 1000 te_sysutiltestsuite SysUtilsCheckDriveLetterMMC z:\testdata\inifiles\te_sysutildata.ini DriveLetter
END_TESTCASE				SYSLIB-BAFL-CT-4038

// Manual version of SYSLIB-BAFL-CT-4056. This misses out all cases where a plug-in is used.
START_TESTCASE				SYSLIB-BAFL-CT-4056
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini NoIni

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_empty_file.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini EmptyIni
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_invalid_format.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini InvalidFormat
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_invalid_encoding.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini InvalidEncoding
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_overflow.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini Overflow
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_invalid_os_version_major.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini InvalidOSVersionMajor
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_invalid_os_version_minor.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini InvalidOSVersionMinor
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_missing_os_version_major.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini MissingOSVersionMajor
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_missing_os_version_minor.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini MissingOSVersionMinor
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_invalid_ui_version_major.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini InvalidUIVersionMajor
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_invalid_ui_version_minor.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini InvalidUIVersionMinor
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_Missing_ui_version_major.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini MissingUIVersionMajor
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_missing_ui_version_minor.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini MissingUIVersionMinor
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_valid.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini ValidIni
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_incomplete.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestDeviceTypeInfoStep z:\testdata\inifiles\te_sysutildata.ini IncompleteIni
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini
END_TESTCASE				SYSLIB-BAFL-CT-4056


START_TESTCASE				SYSLIB-BAFL-CT-4057
RUN_UTILS CopyFile z:\resource\versions\deviceattributes_localised.i02 c:\versions\deviceattributes.i02
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestLocalisedIniStep z:\testdata\inifiles\te_sysutildata.ini LocalisedExactMatch
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.i02
RUN_UTILS DeleteFile c:\versions\deviceattributes.i02

RUN_UTILS CopyFile z:\resource\versions\deviceattributes_localised.ini c:\versions\deviceattributes.ini
RUN_TEST_STEP 100 te_sysutiltestsuite SysUtilsTestLocalisedIniStep z:\testdata\inifiles\te_sysutildata.ini LocalisedCloseMatch
RUN_UTILS MakeReadWrite c:\versions\deviceattributes.ini
RUN_UTILS DeleteFile c:\versions\deviceattributes.ini
END_TESTCASE				SYSLIB-BAFL-CT-4057


RUN_UTILS DeleteDirectory c:\versions
