// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_UTILS  DeleteFile c:\config.txt
RUN_UTILS  CopyFile z:\testdata\configs\tsmscaps_config.txt c:\config.txt
RUN_UTILS  MakeReadWrite c:\config.txt

LOAD_SUITE te_smscaps_sc

START_TESTCASE SMS-SMSCAPS-READDEVICE-1000
//!@SYMTestCaseID SMS-SMSCAPS-READDEVICE-1000
//!@SYMREQ 0000
//!@SYMTestCaseDesc Read device caps
//!@SYMTestPriority Critical
//!@SYMTestActions Negative Test of Capabilities 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_smscaps_sc CSmsCapsSmsIoctlReadParamsSms
RUN_TEST_STEP 100 te_smscaps_sc CSmsCapsSmsIoctlCompleteReadParamsSms
END_TESTCASE SMS-SMSCAPS-READDEVICE-1000
