// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Secondary PDP-context UMTS Driver unit tests for SpudTel and SpudFsm.
//


RUN_UTILS  MkDir c:\simtsy\
RUN_UTILS  MakeReadWrite c:\simtsy\config.txt
RUN_UTILS  MakeReadWrite c:\config.txt
RUN_UTILS  DeleteFile c:\simtsy\config.txt
RUN_UTILS  DeleteFile c:\config.txt
RUN_UTILS  CopyFile z:\TestData\Configs\Spud_config.txt c:\simtsy\config.txt
RUN_UTILS  CopyFile z:\TestData\Configs\Spud_config.txt c:\config.txt

LOAD_SUITE TE_SpudUnit


START_TESTCASE			NET-UMTS-Spud-0101
//! @SYMTestCaseID		NET-UMTS-Spud-0101
//! @SYMTestCaseDesc Test all operations on Etel driver under non-failure conditions
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMFssID NETWORKING/Spud/Control Plane/Secondary PDP Context Creation
//! @SYMFssID NETWORKING/Spud/Control Plane/Network initiated PDP Context Modification
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMFssID NETWORKING/Spud/Control Plane/ PDP Context Deactivation
//! @SYMTestActions Create primary and secondary contexts, set their QoS and TFTs, test activating them, and test deleting them
//! @SYMTestExpectedResults Primary context and secondary context are created, with their QoS and TFTs set, and their status is activated. When they are deleted the contexts become deleted.
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitNormalOperation
END_TESTCASE			NET-UMTS-Spud-0101

START_TESTCASE			NET-UMTS-Spud-0102
//! @SYMTestCaseID		NET-UMTS-Spud-0102
//! @SYMTestCaseDesc Test Etel driver notifications
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMTestActions Create a context and change its context configuration and QoS parameters
//! @SYMTestExpectedResults When the context is activated there is a service status change notification, when the context configuration is changed there is a context config change notification, and when the QoS is changed, there is a QoS change notification 
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitNotifications
END_TESTCASE			NET-UMTS-Spud-0102

START_TESTCASE			NET-UMTS-Spud-0103
//! @SYMTestCaseID		NET-UMTS-Spud-0103
//! @SYMTestCaseDesc Test creating a primary context with a SetConfig error
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMTestActions Instruct Etel driver to create a primary context
//! @SYMTestExpectedResults The request completes with an error
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitCreatePrimaryError
END_TESTCASE			NET-UMTS-Spud-0103

START_TESTCASE			NET-UMTS-Spud-0104
//! @SYMTestCaseID		NET-UMTS-Spud-0104
//! @SYMTestCaseDesc Test an error setting QoS
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMTestActions Instruct Etel driver to create a primary context and set its QoS
//! @SYMTestExpectedResults The set QoS request completes with an error
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitSetQosError
END_TESTCASE			NET-UMTS-Spud-0104

START_TESTCASE			NET-UMTS-Spud-0105
//! @SYMTestCaseID		NET-UMTS-Spud-0105
//! @SYMTestCaseDesc Test an error setting TFT
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMTestActions Instruct Etel driver to create a primary context and set its TFT
//! @SYMTestExpectedResults The set TFT request completes with an error
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitSetTftError
END_TESTCASE			NET-UMTS-Spud-0105

START_TESTCASE			NET-UMTS-Spud-0106
//! @SYMTestCaseID		NET-UMTS-Spud-0106
//! @SYMTestCaseDesc Test an error activating a context
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMTestActions Instruct Etel driver to create then activate a primary context
//! @SYMTestExpectedResults The activation completes with an error
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitActivateError1
END_TESTCASE			NET-UMTS-Spud-0106

START_TESTCASE			NET-UMTS-Spud-0107
//! @SYMTestCaseID		NET-UMTS-Spud-0107
//! @SYMTestCaseDesc Test an error activating a context
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMTestActions Instruct Etel driver to create then activate a primary context
//! @SYMTestExpectedResults The activation completes with an error
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitActivateError2
END_TESTCASE			NET-UMTS-Spud-0107

START_TESTCASE			NET-UMTS-Spud-0108
//! @SYMTestCaseID		NET-UMTS-Spud-0108
//! @SYMTestCaseDesc Test deleting a context with a deactivate error
//! @SYMFssID NETWORKING/Spud/Control Plane/ PDP Context Deactivation
//! @SYMTestActions Instruct Etel driver to create then activate then delete a primary context
//! @SYMTestExpectedResults The delete completes with an error, and all resources are still closed
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitDeleteError1
END_TESTCASE			NET-UMTS-Spud-0108

START_TESTCASE			NET-UMTS-Spud-0109
//! @SYMTestCaseID		NET-UMTS-Spud-0109
//! @SYMTestCaseDesc Test deleting a context with a context delete error
//! @SYMFssID NETWORKING/Spud/Control Plane/ PDP Context Deactivation
//! @SYMTestActions Instruct Etel driver to create then activate then delete a primary context
//! @SYMTestExpectedResults The delete completes with an error, and all resources are still closed
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitDeleteError2
END_TESTCASE			NET-UMTS-Spud-0109

START_TESTCASE			NET-UMTS-Spud-0110
//! @SYMTestCaseID		NET-UMTS-Spud-0110
//! @SYMTestCaseDesc Test creating multiple primary contexts
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMFssID NETWORKING/Spud/Control Plane/Secondary PDP Context Creation
//! @SYMFssID NETWORKING/Spud/Control Plane/Network initiated PDP Context Modification
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMFssID NETWORKING/Spud/Control Plane/ PDP Context Deactivation
//! @SYMTestActions Create 2 primary contexts, create secondary contexts on each of them, set all the contexts' QoS and TFTs, activate the contexts and delete them
//! @SYMTestExpectedResults All requests are completed successfully
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitMultipleContexts
END_TESTCASE			NET-UMTS-Spud-0110

START_TESTCASE			NET-SubConnProv-spud-0250
//! @SYMTestCaseID		NET-SubConnProv-spud-0250
//! @SYMTestCaseDesc Test Etel driver notificationsR5/R99R4
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMTestActions Create a context and change its context configuration and QoS parameters
//! @SYMTestExpectedResults When the context is activated there is a service status change notification, when the context configuration is changed there is a context config change notification, and when the QoS is changed, there is a QoS change notification 
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitNotificationsR5OrR99R4
END_TESTCASE			NET-SubConnProv-spud-0250


START_TESTCASE			NET-UMTS-Spud-0111
//! @SYMTestCaseID		NET-UMTS-Spud-0111
//! @SYMTestCaseDesc Test cancelling all Etel driver actions
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMFssID NETWORKING/Spud/Control Plane/Secondary PDP Context Creation
//! @SYMFssID NETWORKING/Spud/Control Plane/Network initiated PDP Context Modification
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMFssID NETWORKING/Spud/Control Plane/ PDP Context Deactivation
//! @SYMTestActions Instruct Etel driver to create a context and cancel the operation. Wait over a second and make sure the request never completed. Do the same for creating secondary context, setting TFT, setting QoS, activating PDP, and deleting PDP
//! @SYMTestExpectedResults The request never completes
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudTelUnitCancel
END_TESTCASE			NET-UMTS-Spud-0111


//
// SPUD FSM Unit tests
//

START_TESTCASE			NET-UMTS-Spud-0112
//! @SYMTestCaseID		NET-UMTS-Spud-0112
//! @SYMTestCaseDesc Test all state transitions in the SPUD FSM
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMFssID NETWORKING/Spud/Control Plane/Secondary PDP Context Creation
//! @SYMFssID NETWORKING/Spud/Control Plane/Network initiated PDP Context Modification
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMFssID NETWORKING/Spud/Control Plane/ PDP Context Deactivation
//! @SYMTestActions Test creating a primay context before and after the phone is already opened, Test creating secondary context, Test setting QOS on secondary, Test setting TFT on secondary, Test activating secondary, Test network suspending/resuming context, Test SpudMan suspending/resuming context, Test changing TFT, Test changing QOS, Test deleting contexts, Test that we can still use a context that has been deleted
//! @SYMTestExpectedResults All operations complete successfully
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudFsmUnitNormalOperation
END_TESTCASE			NET-UMTS-Spud-0112

START_TESTCASE			NET-UMTS-Spud-0113
//! @SYMTestCaseID		NET-UMTS-Spud-0113
//! @SYMTestCaseDesc Test creating a primary context with an error initialising the context
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMTestActions Instruct FSM to create a primary context
//! @SYMTestExpectedResults The create primary completes with an error
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudFsmCreatePrimaryError1
END_TESTCASE			NET-UMTS-Spud-0113

START_TESTCASE			NET-UMTS-Spud-0114
//! @SYMTestCaseID		NET-UMTS-Spud-0114
//! @SYMTestCaseDesc Test creating a primary context with setting QoS
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMTestActions Instruct FSM to create a primary context
//! @SYMTestExpectedResults The create primary completes with an error
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudFsmCreatePrimaryError2
END_TESTCASE			NET-UMTS-Spud-0114

START_TESTCASE			NET-UMTS-Spud-0115
//! @SYMTestCaseID		NET-UMTS-Spud-0115
//! @SYMTestCaseDesc Test creating a primary context with an error activating
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMTestActions Instruct FSM to create a primary context
//! @SYMTestExpectedResults The create primary completes with an error
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudFsmCreatePrimaryError3
END_TESTCASE			NET-UMTS-Spud-0115

START_TESTCASE			NET-UMTS-Spud-0116
//! @SYMTestCaseID		NET-UMTS-Spud-0116
//! @SYMTestCaseDesc Test error setting QoS, TFT and activating secondary context
//! @SYMFssID NETWORKING/Spud/Control Plane/Primary PDP Context Creation
//! @SYMTestActions Instruct FSM to create a primary then secondary context. Instruct FSM to set the secondary context's QoS then TFT, then instruct FSM to activate the secondary context.
//! @SYMTestExpectedResults The contexts are created successfully. The set QoS, set TFT and activate fail with an error
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudFsmSetQosAndTftError
END_TESTCASE			NET-UMTS-Spud-0116

START_TESTCASE			NET-UMTS-Spud-0117
//! @SYMTestCaseID		NET-UMTS-Spud-0117
//! @SYMTestCaseDesc Test error changing QoS and TFT
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMTestActions Instruct FSM to create a primary then secondary context, then to activate the secondary. Instruct FSM to change the secondary context's QoS then TFT
//! @SYMTestExpectedResults The contexts are created/activated successfully. The change QoS, and change TFT fail with an error
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudFsmChangeQosAndTftError
END_TESTCASE			NET-UMTS-Spud-0117

START_TESTCASE			NET-UMTS-Spud-0118
//! @SYMTestCaseID		NET-UMTS-Spud-0118
//! @SYMTestCaseDesc Test FSM notifications
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMTestActions Instruct FSM to create a primary context. Call SetConfig on the RPacketContext and SetProfileParameters on its RPacketQoS
//! @SYMTestExpectedResults Creating the context generates a packet service status change notification. SetConfig generates a context config change notification. SetProfileParameters generates a QoS change notification
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudFsmTestNotifications
END_TESTCASE			NET-UMTS-Spud-0118

START_TESTCASE			NET-SubConnProv-spud-0251
//! @SYMTestCaseID		NET-SubConnProv-spud-0251
//! @SYMTestCaseDesc Test FSM notifications
//! @SYMFssID NETWORKING/Spud/Control Plane/MS initiated PDP Context Modification
//! @SYMTestActions Instruct FSM to create a primary context. Call SetConfig on the RPacketContext and SetProfileParameters on its RPacketQoS
//! @SYMTestExpectedResults Creating the context generates a packet service status change notification. SetConfig generates a context config change notification. SetProfileParameters generates a QoS change notification
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudFsmTestNotificationsR5OrR99R4
END_TESTCASE			NET-SubConnProv-spud-0251

START_TESTCASE			NET-UMTS-Spud-0119
//! @SYMTestCaseID		NET-UMTS-Spud-0119
//! @SYMFssID NETWORKING/Spud/Control Plane/Network initiated PDP Context Modification
//! @SYMFssID NETWORKING/Spud/Control Plane/ PDP Context Deactivation
//! @SYMTestActions Instruct FSM to create a primary context. Trigger a deletion of the context from Etel while the context is activating. Instruct FSM to create another primary context. Trigger a deletion of the context from Etel when the context is open.
//! @SYMTestExpectedResults Context delete events are generated, and resources associated with the contexts are cleaned up
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType UT
RUN_TEST_STEP 100 TE_SpudUnit SpudFsmNetworkDelete
END_TESTCASE			NET-UMTS-Spud-0119


RUN_UTILS  MakeReadWrite c:\simtsy\config.txt
RUN_UTILS  MakeReadWrite c:\config.txt
RUN_UTILS  DeleteFile c:\simtsy\config.txt
RUN_UTILS  DeleteFile c:\config.txt

