// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//


LOAD_SUITE TE_RConnectionSuite

// Standard test prefix
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script

// The tests use the same configuration as RConnection UDP tests.
ced z:\TestData\configs\rconnectionudp.xml
run_script z:\TestData\scripts\te_esock_test_loadesock.script


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0101
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0101

heap_mark
RUN_TEST_STEP 180, TE_RConnectionSuite Test68 z:\TestData\configs\rconnectiontest_vlan7.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0101


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0102
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0102

heap_mark
RUN_TEST_STEP 180, TE_RConnectionSuite Test69 z:\TestData\configs\rconnectiontest_vlan7.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0102


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0103
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0103

heap_mark
RUN_TEST_STEP 180, TE_RConnectionSuite Test70 z:\TestData\configs\rconnectiontest_vlan7.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0103


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0104
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0104

heap_mark
RUN_TEST_STEP 180, TE_RConnectionSuite Test71 z:\TestData\configs\rconnectiontest_vlan7.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-OOM-NifmanIdleTimeoutUpdate-0104


//  Standard test suffix
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
