//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//
//! @file
//! @SYMTestSuiteName		MM-MMF-VCLNT-PLYR-PublicAPI
//! @SYMScriptTestEnvironment	This test script requires a basic ROM.
/////////////////////////////////////////////////////////////////////
// MM-MMF-VCLNT-PLYR-PublicAPI.script
//
// Tests all public elements of the CVideoPlayerUtility class
// as a means of confidence that the APIs work as expected.
//
// The purpose is to provide a regression test suite of PublishedAll APIs for CVideoPlayerUtility.
// Negative testing is performed to confirm that correct errors are returned when incorrect parameters are given.
// The tests are fully automated.
/////////////////////////////////////////////////////////////////////

LOAD_SUITE	T_VideoPlayerUtility


START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0001
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0001
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		05/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open and play video file without specifying controller plugin.
//!				Uses API elements: NewL(),
//!				OpenFileL(const TDesC aFileName, TUid aControllerUid=TUid::Null()),
//!				Prepare(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video file is opened and played without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0001-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0001-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0001

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0002
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0002
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		05/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open and play video file using certain controller plugin.
//!				Uses API elements: NewL(),
//!				OpenFileL(const TDesC aFileName, TUid aControllerUid=TUid::Null()),
//!				Prepare(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video file is opened and played without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0002-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0002-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0002

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0003
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0003
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		05/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open and play video file using RFile.
//!				Uses API elements: NewL(),
//!				OpenFileL(const RFile aFileName, TUid aControllerUid=TUid::Null()),
//!				Prepare(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video file is opened and played without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0003-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0003-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0003

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0004
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0004
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		05/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open and play video file using TMMSource.
//!				Uses API elements: NewL(),
//!				OpenFileL(const TMMSource aSource, TUid aControllerUid=TUid::Null()),
//!				Prepare(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video file is opened and played without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0004-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0004-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0004

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0005
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0005
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		05/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open and play video file from descriptor.
//!				Uses API elements: NewL(), OpenDesL(), Prepare(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open video clip in a descriptor.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video file is opened and played without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0005-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenDesL	MM-MMF-VCLNT-PLYR-PublicAPI-0005-001-OpenDesL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0005

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0006
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0006
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		05/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open and play video file from URL.
//!				Uses API elements: NewL(), OpenUrlL(), Prepare(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from a URL.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video file is opened and played without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0006-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenUrlL	MM-MMF-VCLNT-PLYR-PublicAPI-0006-001-OpenUrlL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0006

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0007
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0007
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		05/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Play video from file at the specified start and end points.
//!				Uses API elements: NewL(), OpenUrlL(), Prepare(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video file is played without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0007-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenUrlL	MM-MMF-VCLNT-PLYR-PublicAPI-0007-001-OpenUrlL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play		MM-MMF-VCLNT-PLYR-PublicAPI-0007-001-Play_command04
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0007

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0008
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0008
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		05/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Play the video from file and stop it.
//!				Uses API elements: NewL(), OpneFileL(), Prepare(), Play(), Stop(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Stop play.
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Play of video is stopped.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0008-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0008-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		ASYNC_DELAY	5000
		COMMAND		VideoPlayerUtility1	Stop
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0008

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0009
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0009
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		05/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Play the video from file, pause it. Start playing againg and stop it.
//!				Uses API elements: NewL(), OpneFileL(), Prepare(), Play(), PauseL(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Pause playing.
//!				6. Start playing.
//!				7. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The video playing is paused and continued without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0009-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0009-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		ASYNC_DELAY	5000
		COMMAND		VideoPlayerUtility1	PauseL
		COMMAND		VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0009

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0010
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0010
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open the videofile and set the playback priority.
//!				Uses API elements: NewL(), OpneFileL(), SetPriorityL(), PriorityL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Set the playback priority.
//!				4. Check the playback priority.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The playback priority is set.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0010-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0010-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetPriorityL	MM-MMF-VCLNT-PLYR-PublicAPI-0010-001-SetPriorityL_command03
		COMMAND		VideoPlayerUtility1	PriorityL		MM-MMF-VCLNT-PLYR-PublicAPI-0010-001-PriorityL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0010

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0011
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0011
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open the videofile and set the display window.
//!				Uses API elements: NewL(), OpneFileL(), SetDisplayWindowL(), Prepare(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Set the display windowy.
//!				4. Prepare playing.
//!				5. Start playing.
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The display window is set and video is played at new window.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0011-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0011-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetDisplayWindowL	MM-MMF-VCLNT-PLYR-PublicAPI-0011-001-SetDisplayWindowL_command03
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0011

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0012
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0012
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Register to receive notifications of video clip loading. Open video clip from URL.
//!				Get video loading progress and start playing the video.
//!				Uses API elements: NewL(), RegisterForVideoLoadingNotification(), OpenUrlL(),
//!				Prepare(), GetVideoLoadingProgressL(), Play(), GetVideoLoadingProgressL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Register to receive notifications of video clip loading/rebuffering
//!				3. Open a video clip from a URL.
//!				4. Prepare playing.
//!				5. Gets the progress of video clip loading/rebuffering
//!				6. Start playing.
//!				7. Gets the progress of video clip loading/rebuffering
//!				8. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The video loading notifications are received and video loading progress is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL									MM-MMF-VCLNT-PLYR-PublicAPI-0012-001-NewL_command01
		COMMAND		VideoPlayerUtility1	RegisterForVideoLoadingNotification
		COMMAND		VideoPlayerUtility1	OpenUrlL								MM-MMF-VCLNT-PLYR-PublicAPI-0012-001-OpenUrlL_command03
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	GetVideoLoadingProgressL				MM-MMF-VCLNT-PLYR-PublicAPI-0012-001-GetVideoLoadingProgressL_command05
		COMMAND		VideoPlayerUtility1	Play
		ASYNC_DELAY	10000
		COMMAND		VideoPlayerUtility1	GetVideoLoadingProgressL
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0012

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0013
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0013
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the current frame without DRM Intent.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), Play(), GetFrameL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Get the current frame.
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The current frame is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0013-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0013-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		ASYNC_DELAY	10000
		COMMAND		VideoPlayerUtility1	GetFrameL	MM-MMF-VCLNT-PLYR-PublicAPI-0013-001-GetFrameL_command06
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0013

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0014
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0014
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the current frame with DRM Intent.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), Play(), GetFrameL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Get the current frame.
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The current frame is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0014-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0014-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		ASYNC_DELAY	10000
		COMMAND		VideoPlayerUtility1	GetFrameL	MM-MMF-VCLNT-PLYR-PublicAPI-0014-001-GetFrameL_command06
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0014

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0015
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0015
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Refresh (redraw) the current frame.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), Play(), RefreshFrameL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Redraw the current frame.
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The current frame is refreshed.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0015-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0015-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		COMMAND		VideoPlayerUtility1	RefreshFrameL
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0015

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0016
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0016
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set video frame rate.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), Play(),
//!				VideoFrameRateL(), SetVideoFrameRateL(), VideoFrameRateL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Query video frame rate
//!				6. Set the video frame rate.
//!				7. Query video frame rate
//!				8. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The frame rate is set.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0016-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0016-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	VideoFrameRateL
		COMMAND		VideoPlayerUtility1	SetVideoFrameRateL	MM-MMF-VCLNT-PLYR-PublicAPI-0016-001-SetVideoFrameRateL_command06
		COMMAND		VideoPlayerUtility1	VideoFrameRateL		MM-MMF-VCLNT-PLYR-PublicAPI-0016-001-VideoFrameRateL_command07
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0016

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0017
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0017
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video frame size.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), VideoFrameSizeL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip
//!				4. Get the video frame size.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The video frame size is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0017-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0017-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	VideoFrameSizeL	MM-MMF-VCLNT-PLYR-PublicAPI-0017-001-VideoFrameSizeL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0017

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0018
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0018
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video format's MIME type.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), VideoFormatMimeType(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip
//!				4. Get the video format's MIME type.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The video format's MIME type is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0018-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0018-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	VideoFormatMimeType	MM-MMF-VCLNT-PLYR-PublicAPI-0018-001-VideoFormatMimeType_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0018

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0019
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0019
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video bit rate.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), VideoBitRateL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip
//!				4. Get the video bit rate.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The video bit rate is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0019-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0019-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	VideoBitRateL	MM-MMF-VCLNT-PLYR-PublicAPI-0019-001-VideoBitRateL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0019

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0020
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0020
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the audio bit rate in bits/second.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), AudioBitRateL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip
//!				4. Get the audio bit rate.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The audio bit rate is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0020-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0020-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	AudioBitRateL	MM-MMF-VCLNT-PLYR-PublicAPI-0020-001-AudioBitRateL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0020

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0021
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0021
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the codec used for the audio component of the video clip.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), AudioTypeL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip
//!				4. Get the codec used for the audio.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The audio codec is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0021-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0021-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	AudioTypeL	MM-MMF-VCLNT-PLYR-PublicAPI-0021-001-AudioTypeL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0021

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0022
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0022
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get whether the current clip has an audio stream.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), AudioEnabledL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip
//!				4. Get whether the current clip has an audio stream.
//!				5. Close file.
//! @SYMTestStatus		Not Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The audio enabled value (TRUE/FALSE) is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0022-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0022-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	AudioEnabledL		MM-MMF-VCLNT-PLYR-PublicAPI-0022-001-AudioEnabledL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0022

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0023
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0023
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set and check the position within the video clip from where to start playback.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), SetPositionL(), PositionL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip
//!				4. Set the position within the video clip.
//!				5. Get the current playback position
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The position is set within the audio clip.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0023-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0023-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetPositionL	MM-MMF-VCLNT-PLYR-PublicAPI-0023-001-SetPositionL_command04
		COMMAND		VideoPlayerUtility1	PositionL		MM-MMF-VCLNT-PLYR-PublicAPI-0023-001-PositionL_command05
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0023

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0024
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0024
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the duration of video clip in mircoseconds.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), DurationL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip
//!				4. Get the duration of video clip.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The video clip duration is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0024-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0024-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	DurationL	MM-MMF-VCLNT-PLYR-PublicAPI-0024-001-DurationL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0024

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0025
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0025
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get max. volume. Set and check volume for the audio track.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), MaxVolume(), SetVolumeL(), Volume(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Get the maximum volume that the audio track can support.
//!				5. Sets the playback volume for the audio track of the video clip.
//!				6. Get the current playback volume for the audio track of the video clip.
//!				7. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The max. volume is queried and custom volume is set for the audio track.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0025-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0025-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	MaxVolume		MM-MMF-VCLNT-PLYR-PublicAPI-0025-001-MaxVolume_command03
		COMMAND		VideoPlayerUtility1	SetVolumeL		MM-MMF-VCLNT-PLYR-PublicAPI-0025-001-SetVolumeL_command04
		COMMAND		VideoPlayerUtility1	Volume			MM-MMF-VCLNT-PLYR-PublicAPI-0025-001-Volume_command05
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0025

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0026
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0026
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set and check the current playback balance for the audio track of the video clip.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), Balance(), SetBalanceL(), Balance(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Get the current balance setting for the audio track.
//!				5. Set the current playback balance.
//!				6. Get the current balance setting for the audio track.
//!				7. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The custom balance setting for the audio track is set.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0026-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0026-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Balance
		COMMAND		VideoPlayerUtility1	SetBalanceL		MM-MMF-VCLNT-PLYR-PublicAPI-0026-001-SetBalanceL_command04
		COMMAND		VideoPlayerUtility1	Balance			MM-MMF-VCLNT-PLYR-PublicAPI-0026-001-Balance_command05
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0026

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0027
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0027
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set and check the rotation of the video image on the screen.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), SetRotationL(), RotationL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Change the video image rotation on the screen.
//!				5. Get the rotation that is currently applied to the video image.
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The custom rotation is applied to the video image.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0027-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0027-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetRotationL	MM-MMF-VCLNT-PLYR-PublicAPI-0027-001-SetRotationL_command04
		COMMAND		VideoPlayerUtility1	RotationL		MM-MMF-VCLNT-PLYR-PublicAPI-0027-001-RotationL_command05
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0027

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0028
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0028
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set and check the scale of the video image (percentage of its original size).
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), SetScaleFactorL(), GetScaleFactorL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Set the scale of the video image.
//!				5. Get the scale of the video image.
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The custom scale is applied to the video image.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0028-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0028-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetScaleFactorL		MM-MMF-VCLNT-PLYR-PublicAPI-0028-001-SetScaleFactorL_command04
		COMMAND		VideoPlayerUtility1	GetScaleFactorL		MM-MMF-VCLNT-PLYR-PublicAPI-0028-001-GetScaleFactorL_command05
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0028

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0029
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0029
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set and check a region of the video image to be displayed.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), SetCropRegionL(), GetCropRegionL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Set a region of the video image to be displayed.
//!				5. Get the crop region currently applied to the image.
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The custom region of the video image to be displayed is set.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0029-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0029-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetCropRegionL	MM-MMF-VCLNT-PLYR-PublicAPI-0029-001-SetCropRegionL_command04
		COMMAND		VideoPlayerUtility1	GetCropRegionL	MM-MMF-VCLNT-PLYR-PublicAPI-0029-001-GetCropRegionL_command05
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0029

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0030
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0030
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		08/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the number of meta data entries associated with this clip.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), NumberOfMetaDataEntriesL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Get the number of meta data entries.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The number of meta data entries is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL						MM-MMF-VCLNT-PLYR-PublicAPI-0030-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL					MM-MMF-VCLNT-PLYR-PublicAPI-0030-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	NumberOfMetaDataEntriesL	MM-MMF-VCLNT-PLYR-PublicAPI-0030-001-NumberOfMetaDataEntriesL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0030

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0031
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0031
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get a meta data entry from the clip.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), MetaDataEntryL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Get a meta data entry.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The meta data entry is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0031-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0031-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	MetaDataEntryL		MM-MMF-VCLNT-PLYR-PublicAPI-0031-001-MetaDataEntryL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0031

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0032
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0032
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the controller implementation information associated with the current controller.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), ControllerImplementationInformationL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Get the controller implementation information.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The controller implementation information is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL									MM-MMF-VCLNT-PLYR-PublicAPI-0032-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL								MM-MMF-VCLNT-PLYR-PublicAPI-0032-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	ControllerImplementationInformationL
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0032

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0033
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0033
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Send a synchronous custom command to the controller with respond (aDataFrom).
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), CustomCommandSync(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Send a synchronous custom command.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CustomCommandSync will return the error KErrNotSupported.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0033-001-NewL_command01
		COMMAND			VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0033-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!Error=-5	VideoPlayerUtility1	CustomCommandSync	MM-MMF-VCLNT-PLYR-PublicAPI-0033-001-CustomCommandSync_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0033

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0034
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0034
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Send a synchronous custom command to the controller without respond.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), CustomCommandSync(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Send a synchronous custom command.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CustomCommandSync will return the error KErrNotSupported.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0034-001-NewL_command01
		COMMAND			VideoPlayerUtility1	OpenFileL				MM-MMF-VCLNT-PLYR-PublicAPI-0034-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!Error=-5 VideoPlayerUtility1	CustomCommandSync	MM-MMF-VCLNT-PLYR-PublicAPI-0034-001-CustomCommandSync_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0034

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0035
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0035
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Send an asynchronous custom command to the controller with respond (aDataFrom).
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), CustomCommandAsync(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Send an asynchronous custom command.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CustomCommandAsync will return the error KErrNotSupported.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL						MM-MMF-VCLNT-PLYR-PublicAPI-0035-001-NewL_command01
		COMMAND			VideoPlayerUtility1	OpenFileL					MM-MMF-VCLNT-PLYR-PublicAPI-0035-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!AsyncError=-5	VideoPlayerUtility1	CustomCommandAsync	MM-MMF-VCLNT-PLYR-PublicAPI-0035-001-CustomCommandAsync_command04
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0035

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0036
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0036
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Send an asynchronous custom command to the controller without respond.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), CustomCommandAsync(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Send an asynchronous custom command.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CustomCommandAsync will return the error KErrNotSupported.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL						MM-MMF-VCLNT-PLYR-PublicAPI-0036-001-NewL_command01
		COMMAND			VideoPlayerUtility1	OpenFileL					MM-MMF-VCLNT-PLYR-PublicAPI-0036-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!AsyncError=-5	VideoPlayerUtility1	CustomCommandAsync	MM-MMF-VCLNT-PLYR-PublicAPI-0036-001-CustomCommandAsync_command04
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0036

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0037
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0037
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get a controller's DRM custom command implementation.
//!				Uses API elements: NewL(), OpenFileL(), GetDRMCustomCommand(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get a controller's DRM custom command implementation.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The controller's DRM custom command implementation is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0037-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL				MM-MMF-VCLNT-PLYR-PublicAPI-0037-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	GetDRMCustomCommand
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0037

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0038
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0038
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Stop the video player from using direct screen access (DSA).
//!				Uses API elements: NewL(), StopDirectScreenAccessL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Stop the video player from using direct screen access.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The video player is not using direct screen access anymore.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0038-001-NewL_command01
		COMMAND		VideoPlayerUtility1	StopDirectScreenAccessL
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0038

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0039
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0039
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Start the video player to use direct screen access (DSA).
//!				Uses API elements: NewL(), StopDirectScreenAccessL(), StartDirectScreenAccessL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Stop the video player from using direct screen access.
//!				3. Start the video player to use direct screen access.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The video player is using direct screen access.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL						MM-MMF-VCLNT-PLYR-PublicAPI-0039-001-NewL_command01
		COMMAND		VideoPlayerUtility1	StopDirectScreenAccessL
		COMMAND		VideoPlayerUtility1	StartDirectScreenAccessL
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0039

//////////////////******************************************************//////////////////////////
//
//			Phase 2 (negative tests) are beginning here
//
/////////////////******************************************************///////////////////////////

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0040
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0040
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Construct a new instance of the video player utility with aPriority lower than EMdaPriorityMin.
//!				Uses API elements: NewL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returns no errors. Object is created
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0040-001-NewL_command01
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0040

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0041
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0041
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Construct a new instance of the video player utility with aPriority hihger than EMdaPriorityMax.
//!				Uses API elements: NewL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returns no errors. Object is created
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0041-001-NewL_command01
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0041

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0042
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0042
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Construct a new instance of the video player utility with invalid window server session id.
//!				Uses API elements: NewL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KERN-EXEC panic (3) is raised because of dereferencing NULL
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0042-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=3
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0042

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0043
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0043
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Construct a new instance of the video player utility with invalid software device screen.
//!				Uses API elements: NewL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KERN-EXEC panic (3) is raised because of dereferencing NULL
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0043-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=3
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0043

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0044
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0044
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Construct a new instance of the video player utility with invalid display window.
//!				Uses API elements: NewL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	WSERV panic (6) is raised because of invalid window handle.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0044-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=6
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0044

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0045
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0045
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Construct a new instance of the video player utility with negative dimensions of the display window.
//!				Uses API elements: NewL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returns no errors. Object is created
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0045-001-NewL_command01
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0045

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0046
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0046
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Construct a new instance of the video player utility with negative dimensions area of the video clip to display.
//!				Uses API elements: NewL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returns no errors. Object is created
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0046-001-NewL_command01
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0046

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0047
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0047
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open nonexisting video clip from a file.
//!				Uses API elements: NewL(), OpenFileL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const TDesC aFileName, TUid aControllerUid=TUid::Null())
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() will return the error KErrNotFound.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0047-001-NewL_command01
		COMMAND	!AsyncError=-1	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0047-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0047

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0048
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0048
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open corrupted video clip from a file.
//!				Uses API elements: NewL(), OpenFileL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const TDesC aFileName, TUid aControllerUid=TUid::Null())
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20)
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0048-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0048-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0048

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0049
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0049
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open corrupted video clip from a file and prepare it.
//!				Uses API elements: NewL(), OpenFileL(), Prepare()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const TDesC aFileName, TUid aControllerUid=TUid::Null())
//!				3. Call Prepare().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20) and Prepare() returns KErrNotReady(-18);
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0049-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0049-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0049

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0050
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0050
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open corrupted video clip from a file and play it.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), Play()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const TDesC aFileName, TUid aControllerUid=TUid::Null())
//!				3. Prepare the video clip.
//!				4. Start playing.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20) and Prepare() and Play() returns KErrNotReady(-18);
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0050-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0050-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0050

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0051
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0051
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open video clip from a file with invalid controller id.
//!				Uses API elements: NewL(), OpenFileL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const TDesC aFileName, TUid aControllerUid=TUid::Null())
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() will return the error KErrNotFound.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0051-001-NewL_command01
		COMMAND	!AsyncError=-1	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0051-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0051

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0052
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0052
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open video clip from a file with not initialised RFile object.
//!				Uses API elements: NewL(), OpenFileL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const RFile aFileName, TUid aControllerUid=TUid::Null())
//!				3. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL will raise panic.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0052-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0052-001-OpenFileL_command02
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	Close
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=0
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0052

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0053
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0053
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open corrupted video clip from a file using RFile.
//!				Uses API elements: NewL(), OpenFileL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const RFile aFileName, TUid aControllerUid=TUid::Null()).
//!				3. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20)
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0053-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0053-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0053

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0054
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0054
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open video clip from a file with invalid controller id using RFile.
//!				Uses API elements: NewL(), OpenFileL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const RFile aFileName, TUid aControllerUid=TUid::Null()).
//!				3. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() will return the error KErrNotFound.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0054-001-NewL_command01
		COMMAND	!AsyncError=-1	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0054-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0054

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0055
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0055
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open nonexisting video clip from a file using TMMSource.
//!				Uses API elements: NewL(), OpenFileL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const TMMSource aSource, TUid aControllerUid=TUid::Null()).
//!				3. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() will return the error KErrNotFound.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0055-001-NewL_command01
		COMMAND	!AsyncError=-1	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0055-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0055

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0056
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0056
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open corrupted video clip from a file using TMMSource.
//!				Uses API elements: NewL(), OpenFileL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const TMMSource aSource, TUid aControllerUid=TUid::Null()).
//!				3. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20)
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0056-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0056-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0056

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0057
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0057
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open video clip from a file with invalid controller id using TMMSource.
//!				Uses API elements: NewL(), OpenFileL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Call OpenFileL(const TMMSource aSource, TUid aControllerUid=TUid::Null()).
//!				3. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() will return the error KErrNotFound.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0057-001-NewL_command01
		COMMAND	!AsyncError=-1	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0057-001-OpenFileL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0057

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0058
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0058
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open an corrupted video clip contained in a descriptor.
//!				Uses API elements: NewL(), OpenDesL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip contained in a descriptor.
//!				3. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returns no errors. File is opened.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0058-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenDesL	MM-MMF-VCLNT-PLYR-PublicAPI-0058-001-OpenDesL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0058

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0059
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0059
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open a video clip contained in a descriptor with invalid controller id.
//!				Uses API elements: NewL(), OpenDesL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip contained in a descriptor.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenDesL() will return the error KErrNotFound.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0059-001-NewL_command01
		COMMAND	!AsyncError=-1	VideoPlayerUtility1	OpenDesL	MM-MMF-VCLNT-PLYR-PublicAPI-0059-001-OpenDesL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0059

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0060
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0060
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open a video clip from a wrong URL.
//!				Uses API elements: NewL(), OpenUrlL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from a URL.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenUrlL() will return the error KErrNotFound.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0060-001-NewL_command01
		COMMAND	!AsyncError=-1	VideoPlayerUtility1	OpenUrlL	MM-MMF-VCLNT-PLYR-PublicAPI-0060-001-OpenUrlL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0060

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0061
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0061
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open corrupted video clip from a URL.
//!				Uses API elements: NewL(), OpenUrlL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from a URL.
//!				3. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returns no errors. File is opened.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0061-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenUrlL	MM-MMF-VCLNT-PLYR-PublicAPI-0061-001-OpenUrlL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0061

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0062
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0062
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		09/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open a video clip from a URL with invalid controller id.
//!				Uses API elements: NewL(), OpenUrlL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from a URL.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenUrlL() will return the error KErrNotFound.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0062-001-NewL_command01
		COMMAND	!AsyncError=-1	VideoPlayerUtility1	OpenUrlL	MM-MMF-VCLNT-PLYR-PublicAPI-0062-001-OpenUrlL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0062

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0063
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0063
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open a video clip from a URL with invalid internet access point.
//!				Uses API elements: NewL(), OpenUrlL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from a URL.
//!				3. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returns no errors. File is opened.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0063-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenUrlL	MM-MMF-VCLNT-PLYR-PublicAPI-0063-001-OpenUrlL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0063

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0064
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0064
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Open a video clip from a URL with invalid MIME type.
//!				Uses API elements: NewL(), OpenUrlL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from a URL.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returns no errors. File is opened.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0064-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenUrlL	MM-MMF-VCLNT-PLYR-PublicAPI-0064-001-OpenUrlL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0064

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0065
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0065
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Prepare playing without opening video clip first.
//!				Uses API elements: NewL(), Prepare()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Prepare playing.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Prepare() will return error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0065-001-NewL_command01
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0065

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0066
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0066
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Close the video clip without opening video clip first.
//!				Uses API elements: NewL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Close video clip.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Close function will be called without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0066-001-NewL_command01
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0066

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0067
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0067
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Play the video clip without preparing it first.
//!				Uses API elements: NewL(), OpenFileL(), Play()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Start playing.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Play() will return error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0067-001-NewL_command01
		COMMAND			VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0067-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0067

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0068
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0068
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Play the video clip without opening it first.
//!				Uses API elements: NewL(), Play()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Start playing.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Play() will return error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0068-001-NewL_command01
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0068

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0070
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0070
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Play the video clip with specific start and end points without opening it first.
//!				Uses API elements: NewL(), Play()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Start playing.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Play() will return error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0070-001-NewL_command01
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Play	MM-MMF-VCLNT-PLYR-PublicAPI-0070-001-Play_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0070

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0071
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0071
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Start playing the video clip from negative position.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video clip will play without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0071-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0071-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play		MM-MMF-VCLNT-PLYR-PublicAPI-0071-001-Play_command04
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0071

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0073
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0073
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Start to play the video clip starting with very big position and ending with negative position.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), Play(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video clip will play without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0073-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0073-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play		MM-MMF-VCLNT-PLYR-PublicAPI-0073-001-Play_command04
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0073

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0074
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0074
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Stop the play without starting playing the video clip first.
//!				Uses API elements: NewL(), Stop()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Stop playback of the video clip.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Stop() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0074-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	Stop
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0074

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0075
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0075
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Pause the play without starting playing the video clip first.
//!				Uses API elements: NewL(), PauseL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Pause playing.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Pause() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0075-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	PauseL
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0075

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0076
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0076
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set playback priority lower than EMdaPriorityMin (-100).
//!				Uses API elements: NewL(), OpenFileL(), SetPriorityL(),
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Set the playback priority.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	New priority is set without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0076-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0076-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetPriorityL	MM-MMF-VCLNT-PLYR-PublicAPI-0076-001-SetPriorityL_command03
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0076

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0077
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0077
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set playback priority higher than EMdaPriorityMax (100).
//!				Uses API elements: NewL(), OpenFileL(), SetPriorityL(),
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Set the playback priority.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	New priority is set without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0077-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0077-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetPriorityL	MM-MMF-VCLNT-PLYR-PublicAPI-0077-001-SetPriorityL_command03
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0077

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0078
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0078
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set invalid playback time and quality preference.
//!				Uses API elements: NewL(), OpenFileL(), SetPriorityL(),
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open file to be played.
//!				3. Set the playback priority.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	New priority is set without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0078-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0078-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetPriorityL		MM-MMF-VCLNT-PLYR-PublicAPI-0078-001-SetPriorityL_command03
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0078

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0079
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0079
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		15/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set play priority without opening files first.
//!				Uses API elements: NewL(), SetPriorityL(),
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Set the playback priority.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetPriorityL() will return without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50			T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0079-001-NewL_command01
		COMMAND		VideoPlayerUtility1	SetPriorityL		MM-MMF-VCLNT-PLYR-PublicAPI-0079-001-SetPriorityL_command02
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0079

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0080
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0080
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		16/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Query playing priority without opening files first.
//!				Uses API elements: NewL(), PriorityL(),
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the current playback priority
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Current priority will be queried without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0080-001-NewL_command01
		COMMAND		VideoPlayerUtility1	PriorityL
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0080

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0081
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0081
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		16/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set display window with invalid window server session id.
//!				Uses API elements: NewL(), SetDisplayWindowL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Set the display window.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetDisplayWindowL() will raise panic.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0081-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	SetDisplayWindowL	MM-MMF-VCLNT-PLYR-PublicAPI-0081-001-SetDisplayWindowL_command02
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=3
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0081

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0082
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0082
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		16/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set display window with invalid software device screen.
//!				Uses API elements: NewL(), SetDisplayWindowL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Set the display window.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetDisplayWindowL() will raise panic.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0082-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	SetDisplayWindowL	MM-MMF-VCLNT-PLYR-PublicAPI-0082-001-SetDisplayWindowL_command02
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=3
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0082

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0083
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0083
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		16/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set display window with invalid window to display.
//!				Uses API elements: NewL(), SetDisplayWindowL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Set the display window.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetDisplayWindowL() will raise panic.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0083-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	SetDisplayWindowL	MM-MMF-VCLNT-PLYR-PublicAPI-0083-001-SetDisplayWindowL_command02
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=6
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0083

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0084
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0084
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		16/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set display window with negative dimensions of the display window.
//!				Uses API elements: NewL(), SetDisplayWindowL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Set the display window.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	New display window is set without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0084-001-NewL_command01
		COMMAND		VideoPlayerUtility1	SetDisplayWindowL	MM-MMF-VCLNT-PLYR-PublicAPI-0084-001-SetDisplayWindowL_command02
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0084

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0085
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0085
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		16/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set display window with negative dimensions area of the video clip to display.
//!				Uses API elements: NewL(), SetDisplayWindowL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Set the display window.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	New display window is set without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0085-001-NewL_command01
		COMMAND		VideoPlayerUtility1	SetDisplayWindowL		MM-MMF-VCLNT-PLYR-PublicAPI-0085-001-SetDisplayWindowL_command02
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0085

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0086
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0086
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		16/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get video loading progress without opening video clip first.
//!				Uses API elements: NewL(), RegisterForVideoLoadingNotification(), GetVideoLoadingProgressL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Register to receive notifications of video clip loading/rebuffering
//!				3. Get the progress of video clip loading/rebuffering.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	GetVideoLoadingProgressL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL									MM-MMF-VCLNT-PLYR-PublicAPI-0086-001-NewL_command01
		COMMAND			VideoPlayerUtility1	RegisterForVideoLoadingNotification
		COMMAND	!Error=-18	VideoPlayerUtility1	GetVideoLoadingProgressL			MM-MMF-VCLNT-PLYR-PublicAPI-0086-001-GetVideoLoadingProgressL_command03
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0086

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0087
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0087
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		16/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get frame without opening video clip first.
//!				Uses API elements: NewL(), GetFrameL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the current frame.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	GetFrameL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0087-001-NewL_command01
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	GetFrameL		MM-MMF-VCLNT-PLYR-PublicAPI-0087-001-GetFrameL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0087

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0089
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0089
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		16/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get frame with DRM intent and without opening video clip first.
//!				Uses API elements: NewL(), GetFrameL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the current frame.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	GetFrameL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0089-001-NewL_command01
		COMMAND	!ASyncError=-18	VideoPlayerUtility1	GetFrameL		MM-MMF-VCLNT-PLYR-PublicAPI-0089-001-GetFrameL_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0089

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0091
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0091
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Refresh (redraw) the current frame when video clip is not opened.
//!				Uses API elements: NewL(), RefreshFrameL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Redraw the current frame.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	RefreshFrameL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0091-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	RefreshFrameL
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0091

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0092
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0092
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Refresh (redraw) the current frame when video clip is paused.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), Play(), PauseL(), RefreshFrameL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Pause playing.
//!				6. Redraw the current frame.
//!				7. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The current frame will be redrawn without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0092-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0092-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		ASYNC_DELAY	100
		COMMAND		VideoPlayerUtility1	PauseL
		COMMAND		VideoPlayerUtility1	RefreshFrameL
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0092

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0093
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0093
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video frame rate in frames/second when video clip is not opened.
//!				Uses API elements: NewL(), VideoFrameRateL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get video frame rate
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	VideoFrameRateL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0093-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	VideoFrameRateL		MM-MMF-VCLNT-PLYR-PublicAPI-0093-001-VideoFrameRateL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0093

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0094
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0094
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video frame rate in frames/second in corrupted video file.
//!				Uses API elements: NewL(), OpenFileL(), VideoFrameRateL(), Close()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get video frame rate.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and VideoFrameRateL() KErrNotReady(-18).
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0094-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0094-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!Error=-18	VideoPlayerUtility1	VideoFrameRateL		MM-MMF-VCLNT-PLYR-PublicAPI-0094-001-VideoFrameRateL_command03
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0094

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0095
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0095
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the video frame rate in frames/second when video clip is not opened.
//!				Uses API elements: NewL(), SetVideoFrameRateL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Set video frame rate
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetVideoFrameRateL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL						MM-MMF-VCLNT-PLYR-PublicAPI-0095-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	SetVideoFrameRateL		MM-MMF-VCLNT-PLYR-PublicAPI-0095-001-SetVideoFrameRateL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0095

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0096
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0096
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the video frame rate in frames/second with negative number of frames per second.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), SetVideoFrameRateL(), VideoFrameRateL(), 					Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare video clip
//!				4. Set video frame rate
//!				5. Check video frame rate
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetVideoFrameRateL will set frame rate without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0096-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0096-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetVideoFrameRateL	MM-MMF-VCLNT-PLYR-PublicAPI-0096-001-SetVideoFrameRateL_command04
		COMMAND		VideoPlayerUtility1	VideoFrameRateL		MM-MMF-VCLNT-PLYR-PublicAPI-0096-001-VideoFrameRateL_command05
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0096

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0097
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0097
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the video frame rate in frames/second when video clip are played.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), Play(), SetVideoFrameRateL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare playing.
//!				4. Start playing.
//!				5. Set the video frame rate.
//!				6. Query video frame rate
//!				7. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetVideoFrameRateL() will set frame rate without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0097-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0097-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Play
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetVideoFrameRateL	MM-MMF-VCLNT-PLYR-PublicAPI-0097-001-SetVideoFrameRateL_command05
		COMMAND		VideoPlayerUtility1	VideoFrameRateL		MM-MMF-VCLNT-PLYR-PublicAPI-0097-001-VideoFrameRateL_command06
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0097

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0098
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0098
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video frame size when video clip is not opened.
//!				Uses API elements: NewL(), VideoFrameSizeL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the video frame size.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	VideoFrameSizeL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0098-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	VideoFrameSizeL		MM-MMF-VCLNT-PLYR-PublicAPI-0098-001-VideoFrameSizeL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0098

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0099
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0099
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video frame size in corrupted video file.
//!				Uses API elements: NewL(), OpenFileL(), VideoFrameSizeL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get the video frame size.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and Prepare() and VideoFrameRateL() KErrNotReady(-18).
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0099-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0099-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!Error=-18	VideoPlayerUtility1	VideoFrameSizeL		MM-MMF-VCLNT-PLYR-PublicAPI-0099-001-VideoFrameSizeL_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0099

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0100
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0100
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video format's MIME type when video clip is not opened.
//!				Uses API elements: NewL(), VideoFormatMimeType().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get MIME type.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	VideoFormatMimeType will return empty string.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0100-001-NewL_command01
		COMMAND		VideoPlayerUtility1	VideoFormatMimeType		MM-MMF-VCLNT-PLYR-PublicAPI-0100-001-VideoFormatMimeType_command02
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0100

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0101
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0101
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video format's MIME type in corrupted video file.
//!				Uses API elements: NewL(), OpenFileL(), VideoFormatMimeType(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get MIME type
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and Prepare() KErrNotReady(-18),
//!				VideoFormatMimeType will return empty string.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0101-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0101-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	VideoFormatMimeType	MM-MMF-VCLNT-PLYR-PublicAPI-0101-001-VideoFormatMimeType_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0101

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0102
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0102
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video bit rate when video clip is not opened.
//!				Uses API elements: NewL(), VideoBitRateL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the video bit rate.
//! @SYMTestStatus		Not Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	VideoBitRateL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0102-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	VideoBitRateL		MM-MMF-VCLNT-PLYR-PublicAPI-0102-001-VideoBitRateL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0102

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0103
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0103
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the video bit rate in corrupted video file.
//!				Uses API elements: NewL(), OpenFileL(), VideoBitRateL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get the video bit rate.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and Prepare() and VideoBitRateL() KErrNotReady(-18),
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0103-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0103-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!Error=-18	VideoPlayerUtility1	VideoBitRateL	MM-MMF-VCLNT-PLYR-PublicAPI-0103-001-VideoBitRateL_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0103

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0104
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0104
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the audio bit rate when video clip is not opened.
//!				Uses API elements: NewL(), AudioBitRateL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the audio bit rate.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	AudioBitRateL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0104-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	AudioBitRateL	MM-MMF-VCLNT-PLYR-PublicAPI-0104-001-AudioBitRateL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0104

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0105
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0105
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the audio bit rate in corrupted video file.
//!				Uses API elements: NewL(), OpenFileL(), AudioBitRateL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get the audio bit rate.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and Prepare() and AudioBitRateL() KErrNotReady(-18),
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0105-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0105-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!Error=-18	VideoPlayerUtility1	AudioBitRateL	MM-MMF-VCLNT-PLYR-PublicAPI-0105-001-AudioBitRateL_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0105

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0106
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0106
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the codec used for the audio component of the video clip when video clip is not opened.
//!				Uses API elements: NewL(), AudioTypeL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the codec used for the audio component of the video.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	AudioTypeL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0106-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	AudioTypeL		MM-MMF-VCLNT-PLYR-PublicAPI-0106-001-AudioTypeL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0106

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0107
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0107
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the codec used for the audio component of the video clip in corrupted video file.
//!				Uses API elements: NewL(), OpenFileL(), AudioTypeL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get the codec used for the audio component of the video.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and Prepare() and AudioTypeL() KErrNotReady(-18),
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0107-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0107-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!Error=-18	VideoPlayerUtility1	AudioTypeL	MM-MMF-VCLNT-PLYR-PublicAPI-0107-001-AudioTypeL_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0107

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0108
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0108
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Checking an audio stream in the current clip when video clip is not opened.
//!				Uses API elements: NewL(), AudioEnabledL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Returns whether the current clip has an audio stream.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	AudioEnabledL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0108-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	AudioEnabledL		MM-MMF-VCLNT-PLYR-PublicAPI-0108-001-AudioEnabledL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0108

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0109
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0109
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the position when video clip is not opened.
//!				Uses API elements: NewL(), SetPositionL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Set the position within the video clip.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetPositionL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0109-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	SetPositionL		MM-MMF-VCLNT-PLYR-PublicAPI-0109-001-SetPositionL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0109

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0110
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0110
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the position above duration of video clip.
//!				Uses API elements: NewL(), OpenFileL(), DurationL(), PositionL(), SetPositionL(), PositionL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get the duration of video clip in mircoseconds.
//!				5. Get the current playback position
//!				4. Set the position within the video clip.
//!				5. Get the current playback position
//!				6. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	New position will be set to maximum (position = duration).
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0110-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0110-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	DurationL
		COMMAND		VideoPlayerUtility1	PositionL		MM-MMF-VCLNT-PLYR-PublicAPI-0110-001-PositionL_command05
		COMMAND		VideoPlayerUtility1	SetPositionL	MM-MMF-VCLNT-PLYR-PublicAPI-0110-001-SetPositionL_command06
		COMMAND		VideoPlayerUtility1	PositionL		MM-MMF-VCLNT-PLYR-PublicAPI-0110-001-PositionL_command07
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0110

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0111
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0111
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the position to negative number.
//!				Uses API elements: NewL(), OpenFileL(), SetPositionL(), PositionL(), SetPositionL(), PositionL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Set the position within the video clip.
//!				4. Get the current playback position.
//!				5. Set the position within the video clip.
//!				6. Get the current playback position.
//!				7. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	New position will be set to minimum (0).
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0111-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0111-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetPositionL	MM-MMF-VCLNT-PLYR-PublicAPI-0111-001-SetPositionL_command04
		COMMAND		VideoPlayerUtility1	PositionL		MM-MMF-VCLNT-PLYR-PublicAPI-0111-001-PositionL_command05
		COMMAND		VideoPlayerUtility1	SetPositionL	MM-MMF-VCLNT-PLYR-PublicAPI-0111-001-SetPositionL_command06
		COMMAND		VideoPlayerUtility1	PositionL		MM-MMF-VCLNT-PLYR-PublicAPI-0111-001-PositionL_command07
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0111

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0112
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0112
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the position when video clip is not opened.
//!				Uses API elements: NewL(), PositionL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the current playback position
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	PositionL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0112-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	PositionL		MM-MMF-VCLNT-PLYR-PublicAPI-0112-001-PositionL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0112

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0113
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0113
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the duration of video clip in mircoseconds when video clip is not opened.
//!				Uses API elements: NewL(), DurationL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the duration of video clip in mircoseconds.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	DurationL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0113-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	DurationL		MM-MMF-VCLNT-PLYR-PublicAPI-0113-001-DurationL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0113

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0114
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0114
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the duration of video clip in mircoseconds in corrupted video file.
//!				Uses API elements: NewL(), OpenFileL(), DurationL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get the duration of video clip in mircoseconds.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and Prepare() and DurationL() KErrNotReady(-18),
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0114-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0114-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!Error=-18	VideoPlayerUtility1	DurationL	MM-MMF-VCLNT-PLYR-PublicAPI-0114-001-DurationL_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0114

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0115
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0115
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the volume when video clip is not opened.
//!				Uses API elements: NewL(), SetVolumeL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Set the playback volume for the audio track of the video clip.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetVolumeL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0115-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	SetVolumeL		MM-MMF-VCLNT-PLYR-PublicAPI-0115-001-SetVolumeL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0115

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0116
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0116
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the volume above maximum volume.
//!				Uses API elements: NewL(), OpenFileL(), MaxVolume(), VolumeL(), SetVolumeL(), VolumeL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get the maximum volume that the audio track can support.
//!				4. Get current playback volume for the audio track of the video clip.
//!				5. Set the playback volume for the audio track of the video clip.
//!				6. Get current playback volume for the audio track of the video clip.
//!				7. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors are returned.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0116-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0116-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	MaxVolume
		COMMAND		VideoPlayerUtility1	Volume
		COMMAND		VideoPlayerUtility1	SetVolumeL		MM-MMF-VCLNT-PLYR-PublicAPI-0116-001-SetVolumeL_command05
		COMMAND		VideoPlayerUtility1	Volume
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0116

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0117
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0117
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the volume with negative number.
//!				Uses API elements: NewL(), OpenFileL(), SetVolumeL(), VolumeL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Set the playback volume for the audio track of the video clip.
//!				4. Get current playback volume for the audio track of the video clip.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors are returned.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0117-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0117-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetVolumeL		MM-MMF-VCLNT-PLYR-PublicAPI-0117-001-SetVolumeL_command03
		COMMAND		VideoPlayerUtility1	Volume
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0117

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0118
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0118
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the current volume when video clip is not opened.
//!				Uses API elements: NewL(), VolumeL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get current playback volume for the audio track of the video clip.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	VolumeL will return zero (0).
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0118-001-NewL_command01
		COMMAND		VideoPlayerUtility1	Volume		MM-MMF-VCLNT-PLYR-PublicAPI-0118-001-Volume_command02
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0118

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0119
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0119
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the maximum volume when video clip is not opened.
//!				Uses API elements: NewL(), MaxVolume().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the maximum volume that the audio track can support.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0119-001-NewL_command01
		COMMAND		VideoPlayerUtility1	MaxVolume
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0119

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0120
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0120
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the current playback balance for the audio track when video clip is not opened.
//!				Uses API elements: NewL(), SetBalanceL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Sets the current playback balance for the audio track of the video clip.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetBalanceL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0120-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	SetBalanceL		MM-MMF-VCLNT-PLYR-PublicAPI-0120-001-SetBalanceL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0120

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0121
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0121
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the current playback balance for the audio track above maximum.
//!				Uses API elements: NewL(), OpenFileL(), SetBalanceL(), BalanceL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Sets the current playback balance for the audio track of the video clip.
//!				4. Get the current balance setting for the audio track of the video clip.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Balance will be set without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0121-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0121-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetBalanceL		MM-MMF-VCLNT-PLYR-PublicAPI-0121-001-SetBalanceL_command03
		COMMAND		VideoPlayerUtility1	Balance			MM-MMF-VCLNT-PLYR-PublicAPI-0121-001-Balance_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0121

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0122
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0122
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Set the current playback balance for the audio track with negative number.
//!				Uses API elements: NewL(), OpenFileL(), SetBalanceL(), BalanceL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Sets the current playback balance for the audio track of the video clip.
//!				4. Get the current balance setting for the audio track of the video clip.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Balance will be set without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0122-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0122-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetBalanceL		MM-MMF-VCLNT-PLYR-PublicAPI-0122-001-SetBalanceL_command03
		COMMAND		VideoPlayerUtility1	Balance			MM-MMF-VCLNT-PLYR-PublicAPI-0122-001-Balance_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0122

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0123
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0123
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the current playback balance for the audio track when video clip is not opened.
//!				Uses API elements: NewL(), BalanceL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the current playback balance for the audio track of the video clip.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Balance will be queried without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0123-001-NewL_command01
		COMMAND		VideoPlayerUtility1	Balance		MM-MMF-VCLNT-PLYR-PublicAPI-0123-001-Balance_command02
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0123

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0124
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0124
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Rotates the video image on the screen when video clip is not opened.
//!				Uses API elements: NewL(), SetRotationL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Rotates the video image on the screen.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetRotationL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0124-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	SetRotationL	MM-MMF-VCLNT-PLYR-PublicAPI-0124-001-SetRotationL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0124

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0125
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0125
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Rotates the video image on the screen in corrupted video file.
//!				Uses API elements: NewL(), OpenFileL(), SetRotationL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Rotates the video image on the screen.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and Prepare() and SetRotationL() KErrNotReady(-18),
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0125-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0125-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!Error=-18	VideoPlayerUtility1	SetRotationL	MM-MMF-VCLNT-PLYR-PublicAPI-0125-001-SetRotationL_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0125

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0126
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0126
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Rotates the video image on the screen with invalid value.
//!				Uses API elements: NewL(), OpenFileL(), SetRotationL(), RotationL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				2. Sets the current playback balance for the audio track of the video clip.
//!				4. Get the rotation that is currently applied to the video image.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video is rotated without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0126-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0126-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetRotationL	MM-MMF-VCLNT-PLYR-PublicAPI-0126-001-SetRotationL_command04
		COMMAND		VideoPlayerUtility1	RotationL		MM-MMF-VCLNT-PLYR-PublicAPI-0126-001-RotationL_command05
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0126

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0127
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0127
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the rotation that is currently applied to the video image when video clip is not opened.
//!				Uses API elements: NewL(), RotationL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the rotation that is currently applied to the video image.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	RotationL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0127-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	RotationL	MM-MMF-VCLNT-PLYR-PublicAPI-0127-001-RotationL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0127

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0128
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0128
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the rotation in corrupted file.
//!				Uses API elements: NewL(), OpenFileL(), RotationL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get the rotation that is currently applied to the video image.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and RotationL() KErrNotReady(-18),
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0128-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0128-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!Error=-18	VideoPlayerUtility1	RotationL	MM-MMF-VCLNT-PLYR-PublicAPI-0128-001-RotationL_command03
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0128

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0129
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0129
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the rotation if no rotation has been set before.
//!				Uses API elements: NewL(), OpenFileL(), RotationL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get the rotation that is currently applied to the video image.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Rotation will be queried without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0129-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0129-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	RotationL	MM-MMF-VCLNT-PLYR-PublicAPI-0129-001-RotationL_command03
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0129

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0130
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0130
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Scales the video image to a specified percentage of its original size when video clip is not opened.
//!				Uses API elements: NewL(), SetScaleFactorL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Scales the video image to a specified percentage of its original size.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetScaleFactorL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0130-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	SetScaleFactorL		MM-MMF-VCLNT-PLYR-PublicAPI-0130-001-SetScaleFactorL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0130

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0131
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0131
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Trying to scale the video image with negative width and height scale of the video image with using anti-aliasing.
//!				Uses API elements: NewL(), OpenFileL(), SetScaleFactorL(), GetScaleFactorL, Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Scales the video image to a specified percentage of its original size.
//!				4. Gets the scale factor currently applied to the video image.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video is scaled without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0131-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0131-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetScaleFactorL		MM-MMF-VCLNT-PLYR-PublicAPI-0131-001-SetScaleFactorL_command04
		COMMAND		VideoPlayerUtility1	GetScaleFactorL		MM-MMF-VCLNT-PLYR-PublicAPI-0131-001-GetScaleFactorL_command05
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0131

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0132
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0132
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Trying to scale the video image with negative width and height scale of the video image without using anti-aliasing.
//!				Uses API elements: NewL(), OpenFileL(), SetScaleFactorL(), GetScaleFactorL, Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Scales the video image to a specified percentage of its original size.
//!				4. Gets the scale factor currently applied to the video image.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Video is scaled without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0132-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0132-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetScaleFactorL		MM-MMF-VCLNT-PLYR-PublicAPI-0132-001-SetScaleFactorL_command04
		COMMAND		VideoPlayerUtility1	GetScaleFactorL		MM-MMF-VCLNT-PLYR-PublicAPI-0132-001-GetScaleFactorL_command05
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0132

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0133
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0133
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Gets the scale factor currently applied to the video image when video clip is not opened.
//!				Uses API elements: NewL(), GetScaleFactorL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Gets the scale factor currently applied to the video image.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	GetScaleFactorL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0133-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	GetScaleFactorL		MM-MMF-VCLNT-PLYR-PublicAPI-0133-001-GetScaleFactorL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0133

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0134
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0134
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Gets the scale factor if no scale factor has been set before.
//!				Uses API elements: NewL(), OpenFileL(), GetScaleFactorL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Gets the scale factor currently applied to the video image.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The scale factor is queried without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0134-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0134-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	GetScaleFactorL		MM-MMF-VCLNT-PLYR-PublicAPI-0134-001-GetScaleFactorL_command03
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0134

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0135
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0135
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Trying to select a region of the video image to be displayed when video clip is not opened.
//!				Uses API elements: NewL(), SetCropRegionL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Selects a region of the video image to be displayed.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	SetCropRegionL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0135-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	SetCropRegionL		MM-MMF-VCLNT-PLYR-PublicAPI-0135-001-SetCropRegionL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0135

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0136
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0136
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Tryng to select a region of the video image to be displayed with negative dimensions.
//!				Uses API elements: NewL(), OpenFileL(), SetCropRegionL(), GetCropRegionL, Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Selects a region of the video image to be displayed.
//!				4. Gets the crop region currently applied to the image.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The region is selected witout errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0136-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0136-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	SetCropRegionL		MM-MMF-VCLNT-PLYR-PublicAPI-0136-001-SetCropRegionL_command04
		COMMAND		VideoPlayerUtility1	GetCropRegionL		MM-MMF-VCLNT-PLYR-PublicAPI-0136-001-GetCropRegionL_command05
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0136

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0137
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0137
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Tryng to get the crop region currently applied to the image when video clip is not opened.
//!				Uses API elements: NewL(), GetCropRegionL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Gets the crop region currently applied to the image
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	GetCropRegionL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0137-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	GetCropRegionL	MM-MMF-VCLNT-PLYR-PublicAPI-0137-001-GetCropRegionL_command02
		COMMAND			VideoPlayerUtility1	~					MM-MMF-VCLNT-PLYR-PublicAPI-0137-001-~_command03
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0137

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0138
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0138
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Trying to get the crop region if no crop region has been applied before.
//!				Uses API elements: NewL(), OpenFileL(), GetCropRegionL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Gets the crop region currently applied to the image
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The region is queried without errors.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0138-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0138-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	GetCropRegionL	MM-MMF-VCLNT-PLYR-PublicAPI-0138-001-GetCropRegionL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0138

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0139
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0139
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the number of meta data entries associated with this clip when video clip is not opened.
//!				Uses API elements: NewL(), NumberOfMetaDataEntriesL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the number of meta data entries associated with this clip.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	NumberOfMetaDataEntriesL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL							MM-MMF-VCLNT-PLYR-PublicAPI-0139-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	NumberOfMetaDataEntriesL	MM-MMF-VCLNT-PLYR-PublicAPI-0139-001-NumberOfMetaDataEntriesL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0139

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0140
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0140
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the number of meta data entries associated with this clip in corrupted file.
//!				Uses API elements: NewL(), OpenFileL(), NumberOfMetaDataEntriesL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Get the number of meta data entries associated with this clip.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and Prepare() and NumberOfMetaDataEntriesL() KErrNotReady(-18),
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0140-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0140-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!Error=-18	VideoPlayerUtility1	NumberOfMetaDataEntriesL	MM-MMF-VCLNT-PLYR-PublicAPI-0140-001-NumberOfMetaDataEntriesL_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0140

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0141
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0141
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the meta data entry when video clip is not opened.
//!				Uses API elements: NewL(), MetaDataEntryL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get a meta data entry from the clip.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	MetaDataEntryL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0141-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	MetaDataEntryL		MM-MMF-VCLNT-PLYR-PublicAPI-0141-001-MetaDataEntryL_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0141

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0142
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0142
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the meta data entry with negative index from the clip.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), MetaDataEntryL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Get a meta data entry from the clip.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	MetaDataEntryL will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL			MM-MMF-VCLNT-PLYR-PublicAPI-0142-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL		MM-MMF-VCLNT-PLYR-PublicAPI-0142-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	MetaDataEntryL	MM-MMF-VCLNT-PLYR-PublicAPI-0142-001-MetaDataEntryL_command04
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0142

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0143
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0143
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the meta data entry with negative index from corrupted video clip.
//!				Uses API elements: NewL(), OpenFileL(), Prepare(), MetaDataEntryL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Prepare the video clip.
//!				4. Get a meta data entry from the clip.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	OpenFileL() returns KErrCorrupt(-20), and Prepare() and MetaDataEntryL() KErrNotReady(-18),
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL		MM-MMF-VCLNT-PLYR-PublicAPI-0143-001-NewL_command01
		COMMAND	!AsyncError=-20	VideoPlayerUtility1	OpenFileL	MM-MMF-VCLNT-PLYR-PublicAPI-0143-001-OpenFileL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	Prepare
		OUTSTANDING
		COMMAND	!Error=-18	VideoPlayerUtility1	MetaDataEntryL	MM-MMF-VCLNT-PLYR-PublicAPI-0143-001-MetaDataEntryL_command04
		COMMAND			VideoPlayerUtility1	Close
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0143

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0144
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0144
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get the controller implementation information associated with the current controller when video clip is not opened.
//!				Uses API elements: NewL(), ControllerImplementationInformationL().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get the controller implementation information associated with the current controller.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	ControllerImplementationInformationL() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL										MM-MMF-VCLNT-PLYR-PublicAPI-0144-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	ControllerImplementationInformationL
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0144

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0145
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0145
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Sends a synchronous custom command to the controller when video clip is not opened.
//!				Uses API elements: NewL(), CustomCommandSync().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Sends a synchronous custom command to the controller.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CustomCommandSync() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL						MM-MMF-VCLNT-PLYR-PublicAPI-0145-001-NewL_command01
		COMMAND	!Error=-18	VideoPlayerUtility1	CustomCommandSync		MM-MMF-VCLNT-PLYR-PublicAPI-0145-001-CustomCommandSync_command02
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0145

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0146
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0146
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Send a synchronous custom command to the controller with negative function number with reference to an "DataFrom".
//!				Uses API elements: NewL(), OpenFileL(), CustomCommandSync(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Sends a synchronous custom command to the controller
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CustomCommandSync() will raise panic.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0146-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	OpenFileL				MM-MMF-VCLNT-PLYR-PublicAPI-0146-001-OpenFileL_command02
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	Prepare
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	CustomCommandSync		MM-MMF-VCLNT-PLYR-PublicAPI-0146-001-CustomCommandSync_command04
//! 		COMMAND		VideoPlayerUtility1	Close
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=72
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0146

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0147
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0147
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Send a synchronous custom command to the controller with negative function number without reference to an "DataFrom".
//!				Uses API elements: NewL(), OpenFileL(), CustomCommandSync(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Sends a synchronous custom command to the controller
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CustomCommandSync() will raise panic.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0147-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0147-001-OpenFileL_command02
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	Prepare
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	CustomCommandSync	MM-MMF-VCLNT-PLYR-PublicAPI-0147-001-CustomCommandSync_command04
//! 		COMMAND		VideoPlayerUtility1	Close
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=72
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0147

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0148
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0148
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Sends an asynchronous custom command to the controller when video clip is not opened.
//!				Uses API elements: NewL(), CustomCommandAsync().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Sends an asynchronous custom command to the controller.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CustomCommandASync() will return the error KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND			VideoPlayerUtility1	NewL							MM-MMF-VCLNT-PLYR-PublicAPI-0148-001-NewL_command01
		COMMAND	!AsyncError=-18	VideoPlayerUtility1	CustomCommandAsync		MM-MMF-VCLNT-PLYR-PublicAPI-0148-001-CustomCommandAsync_command02
		OUTSTANDING
		COMMAND			VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0148

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0149
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0149
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Send an asynchronous custom command to the controller with negative function number with reference to an "DataFrom".
//!				Uses API elements: NewL(), OpenFileL(), CustomCommandAsync(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Sends an asynchronous custom command to the controller
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CustomCommandASync() will raise panic.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0149-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	OpenFileL				MM-MMF-VCLNT-PLYR-PublicAPI-0149-001-OpenFileL_command02
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	Prepare
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	CustomCommandAsync		MM-MMF-VCLNT-PLYR-PublicAPI-0149-001-CustomCommandAsync_command04
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	Close
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=72
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0149

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0150
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0150
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Send an asynchronous custom command to the controller with negative function number without reference to an "DataFrom".
//!				Uses API elements: NewL(), OpenFileL(), CustomCommandAsync(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Sends an asynchronous custom command to the controller
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CustomCommandASync() will raise panic.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL				MM-MMF-VCLNT-PLYR-PublicAPI-0150-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	OpenFileL			MM-MMF-VCLNT-PLYR-PublicAPI-0150-001-OpenFileL_command02
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	Prepare
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	CustomCommandAsync	MM-MMF-VCLNT-PLYR-PublicAPI-0150-001-CustomCommandAsync_command04
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	Close
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=72
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0150

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0151
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0151
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Get a controller's DRM custom command implementation when video clip is not opened.
//!				Uses API elements: NewL(), GetDRMCustomCommand().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Get a controller's DRM custom command implementation.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The controller's DRM custom command implementation is queried.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL					MM-MMF-VCLNT-PLYR-PublicAPI-0151-001-NewL_command01
		COMMAND		VideoPlayerUtility1	GetDRMCustomCommand
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0151

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0152
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0152
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Stop the video player from using direct screen access (DSA) when video clip is not opened.
//!				Uses API elements: NewL(), OpenFileL(), StopDirectScreenAccessL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Stop the video player from using direct screen access.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The video player is not using direct screen access anymore.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL						MM-MMF-VCLNT-PLYR-PublicAPI-0152-001-NewL_command01
		COMMAND		VideoPlayerUtility1	StopDirectScreenAccessL
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0152

START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0153
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0153
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Stop the video player from using direct screen access (DSA) without start using direct screen access (DSA) it before.
//!				Uses API elements: NewL(), StopDirectScreenAccessL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Stop the video player from using direct screen access.
//!				4. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	The video player is not using direct screen access anymore.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
		COMMAND		VideoPlayerUtility1	NewL						MM-MMF-VCLNT-PLYR-PublicAPI-0153-001-NewL_command01
		COMMAND		VideoPlayerUtility1	OpenFileL					MM-MMF-VCLNT-PLYR-PublicAPI-0153-001-OpenFileL_command02
		OUTSTANDING
		COMMAND		VideoPlayerUtility1	StopDirectScreenAccessL
		COMMAND		VideoPlayerUtility1	Close
		COMMAND		VideoPlayerUtility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0153

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0154
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0154
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Start the video player to use direct screen access (DSA) when video clip is not opened..
//!				Uses API elements: NewL(), StartDirectScreenAccessL()
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Start the video player to use direct screen access.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	StartDirectScreenAccessL() will raise panic.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL							MM-MMF-VCLNT-PLYR-PublicAPI-0154-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	StartDirectScreenAccessL
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=59
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0154

//! START_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0155
//! @SYMTestCaseID		MM-MMF-VCLNT-PLYR-PublicAPI-0155
//! @SYMAPI			CVideoPlayerUtility
//! @SYMAuthor			Sergei Tveritin
//! @SYMCreationDate		11/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-VCLNT-PLYR-PublicAPI.script
//! @SYMTestCaseDesc		Start twice the video player to use direct screen access (DSA).
//!				Uses API elements: NewL(), OpenFileL(), StartDirectScreenAccessL(),  StartDirectScreenAccessL(), Close().
//! @SYMTestActions		1. Create CVideoPlayerUtility object.
//!				2. Open a video clip from file.
//!				3. Start the video player to use direct screen access.
//!				4. Start the video player to use direct screen access.
//!				5. Close file.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	StartDirectScreenAccessL() will raise panic after second attempt.
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK	50	T_VideoPlayerUtility	\multimedia\MM-MMF-VCLNT-PLYR-PublicAPI.ini
//! 		CREATE_OBJECT	CVideoPlayerUtility	VideoPlayerUtility1
//! 		COMMAND		VideoPlayerUtility1	NewL							MM-MMF-VCLNT-PLYR-PublicAPI-0155-001-NewL_command01
//! 		COMMAND		VideoPlayerUtility1	OpenFileL						MM-MMF-VCLNT-PLYR-PublicAPI-0155-001-OpenFileL_command02
//! 		OUTSTANDING
//! 		COMMAND		VideoPlayerUtility1	StartDirectScreenAccessL
//! 		COMMAND		VideoPlayerUtility1	StartDirectScreenAccessL
//! 		COMMAND		VideoPlayerUtility1	Close
//! 		COMMAND		VideoPlayerUtility1	~
//! 	END_TEST_BLOCK	!PanicCode=59
//! END_TESTCASE 			MM-MMF-VCLNT-PLYR-PublicAPI-0155
