//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

RUN_SCRIPT z:\TestData\Scripts\mockltsy_copy_ini_file.script

LOAD_SUITE te_ctsy_component

START_TESTCASE BA-CTSY-FXD-CDNFC-0001
//!@SYMTestCaseID BA-CTSY-FXD-CDNFC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::DialNoFdnCheck for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::DialNoFdnCheck for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestDialNoFdnCheck0001L
END_TESTCASE BA-CTSY-FXD-CDNFC-0001

START_TESTCASE BA-CTSY-FXD-CDNFC-0001c
//!@SYMTestCaseID BA-CTSY-FXD-CDNFC-0001c
//!@SYMComponent telephony_ctsy
@SYMTestCaseDesc Test support in CTSY for RMobileCall::DialNoFdnCheck for voice calls with minimal parameters (RCall::TCallParams)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::DialNoFdnCheck for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestDialNoFdnCheck0001cL
END_TESTCASE BA-CTSY-FXD-CDNFC-0001c

START_TESTCASE BA-CTSY-FXD-CDNFC-0001d
//!@SYMTestCaseID BA-CTSY-FXD-CDNFC-0001d
//!@SYMComponent telephony_ctsy
@SYMTestCaseDesc est support in CTSY for RMobileCall::DialNoFdnCheck for voice calls with extended parameters (RMobileCall::TCallParamsV7)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::DialNoFdnCheck for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestDialNoFdnCheck0001dL
END_TESTCASE BA-CTSY-FXD-CDNFC-0001d

START_TESTCASE BA-CTSY-FXD-CDNFC-0002
//!@SYMTestCaseID BA-CTSY-FXD-CDNFC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::DialNoFdnCheck for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::DialNoFdnCheck for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestDialNoFdnCheck0002L
END_TESTCASE BA-CTSY-FXD-CDNFC-0002

START_TESTCASE BA-CTSY-FXD-CDNFC-0006b
//!@SYMTestCaseID BA-CTSY-FXD-CDNFC-0006b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::DialNoFdnCheck for data calls with minimal parameters (RCall::TCallParams)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::DialNoFdnCheck for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestDialNoFdnCheck0006bL
END_TESTCASE BA-CTSY-FXD-CDNFC-0006b

START_TESTCASE BA-CTSY-FXD-CDNFC-00011
//!@SYMTestCaseID BA-CTSY-FXD-CDNFC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::DialNoFdnCheck for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::DialNoFdnCheck for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestDialNoFdnCheck00011L
END_TESTCASE BA-CTSY-FXD-CDNFC-00011

START_TESTCASE BA-CTSY-FXD-MGFS-0001
//!@SYMTestCaseID BA-CTSY-FXD-MGFS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetFdnStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetFdnStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestGetFdnStatus0001L
END_TESTCASE BA-CTSY-FXD-MGFS-0001

START_TESTCASE BA-CTSY-FXD-MGFS-0002
//!@SYMTestCaseID BA-CTSY-FXD-MGFS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::GetFdnStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::GetFdnStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestGetFdnStatus0002L
END_TESTCASE BA-CTSY-FXD-MGFS-0002


START_TESTCASE BA-CTSY-FXD-MGFS-0004
//!@SYMTestCaseID BA-CTSY-FXD-MGFS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetFdnStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetFdnStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestGetFdnStatus0004L
END_TESTCASE BA-CTSY-FXD-MGFS-0004



START_TESTCASE BA-CTSY-FXD-MSFS-0001
//!@SYMTestCaseID BA-CTSY-FXD-MSFS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetFdnSetting
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetFdnSetting
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestSetFdnSetting0001L
END_TESTCASE BA-CTSY-FXD-MSFS-0001

START_TESTCASE BA-CTSY-FXD-MSFS-0002
//!@SYMTestCaseID BA-CTSY-FXD-MSFS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::SetFdnSetting
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::SetFdnSetting
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestSetFdnSetting0002L
END_TESTCASE BA-CTSY-FXD-MSFS-0002


START_TESTCASE BA-CTSY-FXD-MSFS-0004
//!@SYMTestCaseID BA-CTSY-FXD-MSFS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::SetFdnSetting
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::SetFdnSetting
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestSetFdnSetting0004L
END_TESTCASE BA-CTSY-FXD-MSFS-0004




START_TESTCASE BA-CTSY-FXD-MNFSC-0001
//!@SYMTestCaseID BA-CTSY-FXD-MNFSC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyFdnStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyFdnStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestNotifyFdnStatusChange0001L
END_TESTCASE BA-CTSY-FXD-MNFSC-0001

START_TESTCASE BA-CTSY-FXD-MNFSC-0002
//!@SYMTestCaseID BA-CTSY-FXD-MNFSC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::NotifyFdnStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::NotifyFdnStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestNotifyFdnStatusChange0002L
END_TESTCASE BA-CTSY-FXD-MNFSC-0002


START_TESTCASE BA-CTSY-FXD-MNFSC-0004
//!@SYMTestCaseID BA-CTSY-FXD-MNFSC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::NotifyFdnStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::NotifyFdnStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestNotifyFdnStatusChange0004L
END_TESTCASE BA-CTSY-FXD-MNFSC-0004

RUN_SCRIPT z:\TestData\Scripts\mockltsy_remove_ini_file.script
