//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

RUN_SCRIPT z:\TestData\Scripts\mockltsy_copy_ini_file.script

LOAD_SUITE te_ctsy_component


START_TESTCASE BA-CTSY-PBSTR-PBSD-0001
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete0001L
END_TESTCASE BA-CTSY-PBSTR-PBSD-0001

START_TESTCASE BA-CTSY-PBSTR-PBSR-0001c
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0001c
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support for Read after GetInfo requested before phonebook is ready
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0001cL
END_TESTCASE BA-CTSY-PBSTR-PBSR-0001c

START_TESTCASE BA-CTSY-PBSTR-PBSD-0002
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Delete for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Delete for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete0002L
END_TESTCASE BA-CTSY-PBSTR-PBSD-0002

START_TESTCASE BA-CTSY-PBSTR-PBSD-0003
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with bad parameter data for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete with bad parameter data for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete0003L
END_TESTCASE BA-CTSY-PBSTR-PBSD-0003

START_TESTCASE BA-CTSY-PBSTR-PBSD-0004
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Delete for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Delete for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete0004L
END_TESTCASE BA-CTSY-PBSTR-PBSD-0004

START_TESTCASE BA-CTSY-PBSTR-PBSD-0006
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete0006L
END_TESTCASE BA-CTSY-PBSTR-PBSD-0006

START_TESTCASE BA-CTSY-PBSTR-PBSD-0007
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Delete for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Delete for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete0007L
END_TESTCASE BA-CTSY-PBSTR-PBSD-0007

START_TESTCASE BA-CTSY-PBSTR-PBSD-0008
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with bad parameter data for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete with bad parameter data for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete0008L
END_TESTCASE BA-CTSY-PBSTR-PBSD-0008

START_TESTCASE BA-CTSY-PBSTR-PBSD-0009
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Delete for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Delete for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete0009L
END_TESTCASE BA-CTSY-PBSTR-PBSD-0009

START_TESTCASE BA-CTSY-PBSTR-PBSD-00011
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00011L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00011

START_TESTCASE BA-CTSY-PBSTR-PBSD-00016
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00016L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00016

START_TESTCASE BA-CTSY-PBSTR-PBSD-00017
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00017
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Delete for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Delete for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00017L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00017

START_TESTCASE BA-CTSY-PBSTR-PBSD-00018
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00018
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with bad parameter data for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete with bad parameter data for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00018L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00018

START_TESTCASE BA-CTSY-PBSTR-PBSD-00019
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00019
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Delete for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Delete for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00019L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00019

START_TESTCASE BA-CTSY-PBSTR-PBSD-00021
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00021
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00021L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00021

START_TESTCASE BA-CTSY-PBSTR-PBSD-00022
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00022
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Delete for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Delete for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00022L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00022

START_TESTCASE BA-CTSY-PBSTR-PBSD-00023
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00023
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with bad parameter data for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete with bad parameter data for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00023L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00023

START_TESTCASE BA-CTSY-PBSTR-PBSD-00024
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00024
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Delete for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Delete for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00024L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00024

START_TESTCASE BA-CTSY-PBSTR-PBSD-00026
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00026
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00026L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00026

START_TESTCASE BA-CTSY-PBSTR-PBSD-00027
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00027
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Delete for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Delete for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00027L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00027

START_TESTCASE BA-CTSY-PBSTR-PBSD-00028
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00028
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with bad parameter data for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete with bad parameter data for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00028L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00028

START_TESTCASE BA-CTSY-PBSTR-PBSD-00029
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00029
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Delete for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Delete for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00029L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00029



START_TESTCASE BA-CTSY-PBSTR-PBSR-0001
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0001L
END_TESTCASE BA-CTSY-PBSTR-PBSR-0001

START_TESTCASE BA-CTSY-PBSTR-PBSR-0001b
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0001b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support with SIM refresh register Off in CTSY for RMobilePhoneBookStore::Read for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0001bL
END_TESTCASE BA-CTSY-PBSTR-PBSR-0001b

START_TESTCASE BA-CTSY-PBSTR-PBSR-0002
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Read for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Read for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0002L
END_TESTCASE BA-CTSY-PBSTR-PBSR-0002

START_TESTCASE BA-CTSY-PBSTR-PBSR-0003
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with bad parameter data for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read with bad parameter data for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0003L
END_TESTCASE BA-CTSY-PBSTR-PBSR-0003

START_TESTCASE BA-CTSY-PBSTR-PBSR-0004
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Read for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Read for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0004L
END_TESTCASE BA-CTSY-PBSTR-PBSR-0004

START_TESTCASE BA-CTSY-PBSTR-PBSR-0004b
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0004b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Read for ADN phonebook while SIM refresh register is off
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Read for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0004bL
END_TESTCASE BA-CTSY-PBSTR-PBSR-0004b

START_TESTCASE BA-CTSY-PBSTR-PBSR-0005
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0005
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for ADN phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for ADN phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0005L
END_TESTCASE BA-CTSY-PBSTR-PBSR-0005

START_TESTCASE BA-CTSY-PBSTR-PBSR-0006
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0006L
END_TESTCASE BA-CTSY-PBSTR-PBSR-0006

START_TESTCASE BA-CTSY-PBSTR-PBSR-0007
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Read for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Read for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0007L
END_TESTCASE BA-CTSY-PBSTR-PBSR-0007

START_TESTCASE BA-CTSY-PBSTR-PBSR-0008
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with bad parameter data for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read with bad parameter data for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0008L
END_TESTCASE BA-CTSY-PBSTR-PBSR-0008

START_TESTCASE BA-CTSY-PBSTR-PBSR-0009
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Read for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Read for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0009L
END_TESTCASE BA-CTSY-PBSTR-PBSR-0009

START_TESTCASE BA-CTSY-PBSTR-PBSR-00010
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00010
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for FDN phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for FDN phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00010L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00010


START_TESTCASE BA-CTSY-PBSTR-PBSR-00011
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00011L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00011

START_TESTCASE BA-CTSY-PBSTR-PBSR-00012
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Read for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Read for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00012L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00012

START_TESTCASE BA-CTSY-PBSTR-PBSR-00013
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with bad parameter data for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read with bad parameter data for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00013L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00013

START_TESTCASE BA-CTSY-PBSTR-PBSR-00014
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Read for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Read for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00014L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00014

START_TESTCASE BA-CTSY-PBSTR-PBSR-00015
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00015
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for SDN phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for SDN phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00015L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00015


START_TESTCASE BA-CTSY-PBSTR-PBSR-00016
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00016L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00016

START_TESTCASE BA-CTSY-PBSTR-PBSR-00017
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00017
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Read for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Read for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00017L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00017

START_TESTCASE BA-CTSY-PBSTR-PBSR-00018
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00018
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with bad parameter data for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read with bad parameter data for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00018L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00018

START_TESTCASE BA-CTSY-PBSTR-PBSR-00019
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00019
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Read for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Read for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00019L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00019

START_TESTCASE BA-CTSY-PBSTR-PBSR-00020
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00020
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for VMBX phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for VMBX phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00020L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00020


START_TESTCASE BA-CTSY-PBSTR-PBSR-00021
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00021
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00021L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00021

START_TESTCASE BA-CTSY-PBSTR-PBSR-00022
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00022
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Read for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Read for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00022L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00022

START_TESTCASE BA-CTSY-PBSTR-PBSR-00023
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00023
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with bad parameter data for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read with bad parameter data for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00023L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00023

START_TESTCASE BA-CTSY-PBSTR-PBSR-00024
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00024
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Read for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Read for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00024L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00024

START_TESTCASE BA-CTSY-PBSTR-PBSR-00025
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00025
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for BDN phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for BDN phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00025L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00025


START_TESTCASE BA-CTSY-PBSTR-PBSR-00026
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00026
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00026L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00026

START_TESTCASE BA-CTSY-PBSTR-PBSR-00027
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00027
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Read for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Read for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00027L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00027

START_TESTCASE BA-CTSY-PBSTR-PBSR-00028
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00028
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with bad parameter data for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Read with bad parameter data for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00028L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00028

START_TESTCASE BA-CTSY-PBSTR-PBSR-00029
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00029
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Read for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Read for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00029L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00029

START_TESTCASE BA-CTSY-PBSTR-PBSR-00030
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00030
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for MBDN phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for MBDN phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00030L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00030


START_TESTCASE BA-CTSY-PBSTR-PBSW-0001
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite0001L
END_TESTCASE BA-CTSY-PBSTR-PBSW-0001

START_TESTCASE BA-CTSY-PBSTR-PBSW-0002
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Write for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Write for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite0002L
END_TESTCASE BA-CTSY-PBSTR-PBSW-0002

START_TESTCASE BA-CTSY-PBSTR-PBSW-0003
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with bad parameter data for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write with bad parameter data for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite0003L
END_TESTCASE BA-CTSY-PBSTR-PBSW-0003

START_TESTCASE BA-CTSY-PBSTR-PBSW-0004
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Write for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Write for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite0004L
END_TESTCASE BA-CTSY-PBSTR-PBSW-0004

START_TESTCASE BA-CTSY-PBSTR-PBSW-0005
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with timeout for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write and tests for timeout for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite0005L
END_TESTCASE BA-CTSY-PBSTR-PBSW-0005


START_TESTCASE BA-CTSY-PBSTR-PBSW-0006
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite0006L
END_TESTCASE BA-CTSY-PBSTR-PBSW-0006

START_TESTCASE BA-CTSY-PBSTR-PBSW-0007
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Write for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Write for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite0007L
END_TESTCASE BA-CTSY-PBSTR-PBSW-0007

START_TESTCASE BA-CTSY-PBSTR-PBSW-0008
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with bad parameter data for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write with bad parameter data for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite0008L
END_TESTCASE BA-CTSY-PBSTR-PBSW-0008

START_TESTCASE BA-CTSY-PBSTR-PBSW-0009
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Write for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Write for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite0009L
END_TESTCASE BA-CTSY-PBSTR-PBSW-0009

START_TESTCASE BA-CTSY-PBSTR-PBSW-00010
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00010
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with timeout for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write and tests for timeout for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00010L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00010


START_TESTCASE BA-CTSY-PBSTR-PBSW-00011
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00011L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00011

START_TESTCASE BA-CTSY-PBSTR-PBSW-00016
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00016L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00016

START_TESTCASE BA-CTSY-PBSTR-PBSW-00017
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00017
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Write for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Write for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00017L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00017

START_TESTCASE BA-CTSY-PBSTR-PBSW-00018
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00018
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with bad parameter data for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write with bad parameter data for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00018L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00018

START_TESTCASE BA-CTSY-PBSTR-PBSW-00019
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00019
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Write for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Write for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00019L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00019

START_TESTCASE BA-CTSY-PBSTR-PBSW-00020
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00020
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with timeout for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write and tests for timeout for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00020L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00020


START_TESTCASE BA-CTSY-PBSTR-PBSW-00022
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00022
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Write for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Write for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00022L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00022

START_TESTCASE BA-CTSY-PBSTR-PBSW-00023
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00023
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with bad parameter data for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write with bad parameter data for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00023L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00023

START_TESTCASE BA-CTSY-PBSTR-PBSW-00024
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00024
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Write for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Write for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00024L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00024

START_TESTCASE BA-CTSY-PBSTR-PBSW-00025
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00025
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with timeout for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write and tests for timeout for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00025L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00025


START_TESTCASE BA-CTSY-PBSTR-PBSW-00026
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00026
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00026L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00026

START_TESTCASE BA-CTSY-PBSTR-PBSW-00027
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00027
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::Write for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::Write for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00027L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00027

START_TESTCASE BA-CTSY-PBSTR-PBSW-00028
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00028
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with bad parameter data for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write with bad parameter data for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00028L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00028

START_TESTCASE BA-CTSY-PBSTR-PBSW-00029
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00029
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::Write for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::Write for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00029L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00029

START_TESTCASE BA-CTSY-PBSTR-PBSW-00030
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00030
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with timeout for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write and tests for timeout for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00030L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00030

START_TESTCASE BA-CTSY-PBSTR-PBSD-0005
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with timeout for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete and tests for timeout for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete0005L
END_TESTCASE BA-CTSY-PBSTR-PBSD-0005

START_TESTCASE BA-CTSY-PBSTR-PBSD-00010
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00010
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with timeout for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete and tests for timeout for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00010L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00010

START_TESTCASE BA-CTSY-PBSTR-PBSD-00020
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00020
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with timeout for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete and tests for timeout for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00020L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00020

START_TESTCASE BA-CTSY-PBSTR-PBSD-00025
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00025
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with timeout for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete and tests for timeout for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00025L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00025

START_TESTCASE BA-CTSY-PBSTR-PBSD-00030
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00030
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with timeout for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete and tests for timeout for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00030L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00030


START_TESTCASE BA-CTSY-PBSTR-PBSNSE-0001
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::NotifyStoreEvent for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::NotifyStoreEvent for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent0001L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-0001

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-0002
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::NotifyStoreEvent for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::NotifyStoreEvent for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent0002L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-0002


START_TESTCASE BA-CTSY-PBSTR-PBSNSE-0004
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::NotifyStoreEvent for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::NotifyStoreEvent for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent0004L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-0004

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-0006
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::NotifyStoreEvent for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::NotifyStoreEvent for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent0006L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-0006

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-0007
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::NotifyStoreEvent for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::NotifyStoreEvent for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent0007L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-0007


START_TESTCASE BA-CTSY-PBSTR-PBSNSE-0009
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::NotifyStoreEvent for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::NotifyStoreEvent for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent0009L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-0009

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00011
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::NotifyStoreEvent for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::NotifyStoreEvent for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00011L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00011

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00012
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::NotifyStoreEvent for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::NotifyStoreEvent for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00012L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00012


START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00016
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::NotifyStoreEvent for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::NotifyStoreEvent for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00016L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00016

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00017
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00017
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::NotifyStoreEvent for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::NotifyStoreEvent for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00017L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00017


START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00019
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00019
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::NotifyStoreEvent for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::NotifyStoreEvent for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00019L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00019

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00021
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00021
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::NotifyStoreEvent for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::NotifyStoreEvent for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00021L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00021

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00022
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00022
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::NotifyStoreEvent for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::NotifyStoreEvent for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00022L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00022


START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00024
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00024
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::NotifyStoreEvent for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::NotifyStoreEvent for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00024L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00024

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00026
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00026
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::NotifyStoreEvent for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::NotifyStoreEvent for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00026L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00026

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00027
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00027
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::NotifyStoreEvent for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::NotifyStoreEvent for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00027L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00027

START_TESTCASE BA-CTSY-PBSTR-PBSNSE-00029
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSNSE-00029
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::NotifyStoreEvent for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::NotifyStoreEvent for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestNotifyStoreEvent00029L
END_TESTCASE BA-CTSY-PBSTR-PBSNSE-00029




START_TESTCASE BA-CTSY-PBSTR-PBSGI-0001
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo0001L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-0001

START_TESTCASE BA-CTSY-PBSTR-PBSGI-0001b
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-0001b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for ADN phonebook with slow SIM
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo0001bL
END_TESTCASE BA-CTSY-PBSTR-PBSGI-0001b

START_TESTCASE BA-CTSY-PBSTR-PBSGI-0003
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo with bad parameter data for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo with bad parameter data for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo0003L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-0003

START_TESTCASE BA-CTSY-PBSTR-PBSGI-0004
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::GetInfo for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::GetInfo for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo0004L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-0004

START_TESTCASE BA-CTSY-PBSTR-PBSGI-0006
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo0006L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-0006

START_TESTCASE BA-CTSY-PBSTR-PBSGI-0006b
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-0006b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for FDN phonebook when ADN is de-activated and ADN phonebook name is returned
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo0006bL
END_TESTCASE BA-CTSY-PBSTR-PBSGI-0006b

START_TESTCASE BA-CTSY-PBSTR-PBSGI-0006c
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-0006c
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for FDN phonebook with slow SIM
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo0006cL
END_TESTCASE BA-CTSY-PBSTR-PBSGI-0006c

START_TESTCASE BA-CTSY-PBSTR-PBSGI-0008
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo with bad parameter data for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo with bad parameter data for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo0008L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-0008

START_TESTCASE BA-CTSY-PBSTR-PBSGI-0009
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::GetInfo for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::GetInfo for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo0009L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-0009

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00011
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00011L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00011

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00011b
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00011b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for SDN phonebook with slow SIM
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00011bL
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00011b

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00011c
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00011c
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for SDN phonebook when multiple phonebooks are opened simultaneously
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00011cL
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00011c

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00012
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test cancel support in CTSY for RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00012L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00012

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00013
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo with bad parameter data for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo with bad parameter data for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00013L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00013

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00014
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00014L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00014

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00015
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00015
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test timout support in CTSY for RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout of RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 130 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00015L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00015

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00016
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00016L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00016

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00016b
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00016b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for VMBX phonebook with slow SIM
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00016bL
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00016b

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00017
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00017
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test cancel support in CTSY for RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancel of RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00017L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00017

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00018
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00018
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo with bad parameter data for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo with bad parameter data for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00018L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00018

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00019
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00019
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00019L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00019

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00020
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00020
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test timeout support in CTSY for RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout of RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 130 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00020L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00020

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00021
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00021
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00021L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00021

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00021b
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00021b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for BDN phonebook with slow SIM
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00021bL
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00021b

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00023
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00023
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo with bad parameter data for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo with bad parameter data for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00023L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00023

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00024
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00024
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::GetInfo for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::GetInfo for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00024L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00024

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00026
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00026
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00026L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00026

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00026b
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00026b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo for MBDN phonebook with slow SIM
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00026bL
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00026b

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00028
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00028
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::GetInfo with bad parameter data for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::GetInfo with bad parameter data for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00028L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00028

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00029
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00029
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::GetInfo for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::GetInfo for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00029L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00029




START_TESTCASE BA-CTSY-PBSTR-PBSDA-0001
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll0001L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-0001

START_TESTCASE BA-CTSY-PBSTR-PBSDA-0002
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::DeleteAll for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::DeleteAll for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll0002L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-0002

START_TESTCASE BA-CTSY-PBSTR-PBSDA-0004
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::DeleteAll for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::DeleteAll for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll0004L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-0004

START_TESTCASE BA-CTSY-PBSTR-PBSDA-0005
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll with timeout for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll and tests for timeout for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll0005L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-0005

START_TESTCASE BA-CTSY-PBSTR-PBSDA-0006
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll0006L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-0006

START_TESTCASE BA-CTSY-PBSTR-PBSDA-0007
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::DeleteAll for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::DeleteAll for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll0007L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-0007

START_TESTCASE BA-CTSY-PBSTR-PBSDA-0009
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::DeleteAll for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::DeleteAll for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll0009L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-0009

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00010
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00010
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll with timeout for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll and tests for timeout for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00010L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00010

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00011
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00011L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00011

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00016
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00016
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00016L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00016

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00017
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00017
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::DeleteAll for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::DeleteAll for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00017L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00017

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00019
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00019
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::DeleteAll for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::DeleteAll for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00019L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00019

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00020
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00020
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll with timeout for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll and tests for timeout for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00020L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00020

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00021
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00021
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00021L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00021

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00022
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00022
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::DeleteAll for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::DeleteAll for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00022L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00022

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00024
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00024
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::DeleteAll for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::DeleteAll for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00024L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00024

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00025
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00025
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll with timeout for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll and tests for timeout for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00025L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00025

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00026
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00026
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00026L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00026

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00027
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00027
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhoneBookStore::DeleteAll for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhoneBookStore::DeleteAll for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00027L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00027

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00029
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00029
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhoneBookStore::DeleteAll for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhoneBookStore::DeleteAll for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00029L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00029

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00030
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00030
//!@SYMComponent  telephony_ctsy         
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll with timeout for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll and tests for timeout for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00030L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00030





START_TESTCASE BA-CTSY-PBSTR-PBSR2-0001
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR2-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Read for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Read for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Read0001L
END_TESTCASE BA-CTSY-PBSTR-PBSR2-0001

START_TESTCASE BA-CTSY-PBSTR-PBSR2-0002
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR2-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Read for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Read for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Read0002L
END_TESTCASE BA-CTSY-PBSTR-PBSR2-0002

START_TESTCASE BA-CTSY-PBSTR-PBSR2-0003
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR2-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Read for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Read for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Read0003L
END_TESTCASE BA-CTSY-PBSTR-PBSR2-0003

START_TESTCASE BA-CTSY-PBSTR-PBSR2-0004
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR2-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Read for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Read for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Read0004L
END_TESTCASE BA-CTSY-PBSTR-PBSR2-0004

START_TESTCASE BA-CTSY-PBSTR-PBSR2-0005
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR2-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Read for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Read for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Read0005L
END_TESTCASE BA-CTSY-PBSTR-PBSR2-0005

START_TESTCASE BA-CTSY-PBSTR-PBSR2-0006
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR2-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Read for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Read for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Read0006L
END_TESTCASE BA-CTSY-PBSTR-PBSR2-0006

START_TESTCASE BA-CTSY-PBSTR-PBSW2-0001
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW2-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Write for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Write for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Write0001L
END_TESTCASE BA-CTSY-PBSTR-PBSW2-0001

START_TESTCASE BA-CTSY-PBSTR-PBSW2-0002
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW2-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Write for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Write for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Write0002L
END_TESTCASE BA-CTSY-PBSTR-PBSW2-0002

START_TESTCASE BA-CTSY-PBSTR-PBSW2-0003
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW2-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Write for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Write for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Write0003L
END_TESTCASE BA-CTSY-PBSTR-PBSW2-0003

START_TESTCASE BA-CTSY-PBSTR-PBSW2-0004
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW2-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Write for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Write for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Write0004L
END_TESTCASE BA-CTSY-PBSTR-PBSW2-0004

START_TESTCASE BA-CTSY-PBSTR-PBSW2-0005
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW2-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Write for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Write for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Write0005L
END_TESTCASE BA-CTSY-PBSTR-PBSW2-0005

START_TESTCASE BA-CTSY-PBSTR-PBSW2-0006
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW2-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Write for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Write for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test2Write0006L
END_TESTCASE BA-CTSY-PBSTR-PBSW2-0006




START_TESTCASE BA-CTSY-PBSTR-PBSR3-0001
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR3-0001
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CMmPhoneBookStoreTsy::ContinueReadL()
//!@SYMTestPriority High
//!@SYMTestActions Invokes CMmPhoneBookStoreTsy::ContinueReadL()
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test3Read0001L
END_TESTCASE BA-CTSY-PBSTR-PBSR3-0001


START_TESTCASE BA-CTSY-PBSTR-PBSR3-0002
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR3-0002
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for read without SIM register and caching
//!@SYMTestPriority High
//!@SYMTestActions Test support in CTSY for read without SIM register and caching
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test3Read0002L
END_TESTCASE BA-CTSY-PBSTR-PBSR3-0002

START_TESTCASE BA-CTSY-PBSTR-PBSR3-0003
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSR3-0003
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for SDN entry read without SIM register and caching
//!@SYMTestPriority High
//!@SYMTestActions Test support in CTSY for SDN entry read without SIM register and caching
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.Test3Read0003L
END_TESTCASE BA-CTSY-PBSTR-PBSR3-0003

START_TESTCASE BA-CTSY-PBSTR-PBSO2-0001
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSO2-0001
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneStore::Open 2 phonebooks of different types
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneStore::Open 2 phonebooks of different types
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestOpen0001L
END_TESTCASE BA-CTSY-PBSTR-PBSO2-0001

RUN_SCRIPT z:\TestData\Scripts\mockltsy_remove_ini_file.script
