//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

RUN_SCRIPT z:\TestData\Scripts\mockltsy_copy_ini_file.script

LOAD_SUITE te_ctsy_component

START_TESTCASE BA-CTSY-SYSS-SYSSPLG-0001
//!@SYMTestCaseID BA-CTSY-SYSS-SYSSPLG-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test that System State plugin is loaded correctly
//!@SYMTestPriority High
//!@SYMTestActions Attempts to dial an emergency call. This will cause the System State plugin to be loaded.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySystemState.TestSystemState0001L
END_TESTCASE BA-CTSY-SYSS-SYSSPLG-0001

RUN_SCRIPT z:\TestData\Scripts\mockltsy_remove_ini_file.script
