//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

RUN_SCRIPT z:\TestData\Scripts\mockltsy_copy_ini_file.script

LOAD_SUITE te_ctsy_component

START_TESTCASE BA-CTSY-PKTC-PCNSC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCNSC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::NotifyStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::NotifyStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyStatusChange0001L
END_TESTCASE BA-CTSY-PKTC-PCNSC-0001

START_TESTCASE BA-CTSY-PKTC-PCNSC-0002
//!@SYMTestCaseID BA-CTSY-PKTC-PCNSC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::NotifyStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::NotifyStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyStatusChange0002L
END_TESTCASE BA-CTSY-PKTC-PCNSC-0002

START_TESTCASE BA-CTSY-PKTC-PCNSC-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCNSC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::NotifyStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::NotifyStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyStatusChange0004L
END_TESTCASE BA-CTSY-PKTC-PCNSC-0004

START_TESTCASE BA-CTSY-PKTC-PCD-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCD-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::Deactivate
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Deactivate
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestDeactivate0001L
END_TESTCASE BA-CTSY-PKTC-PCD-0001

START_TESTCASE BA-CTSY-PKTC-PCD-0002
//!@SYMTestCaseID BA-CTSY-PKTC-PCD-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::Deactivate
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::Deactivate
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestDeactivate0002L
END_TESTCASE BA-CTSY-PKTC-PCD-0002

START_TESTCASE BA-CTSY-PKTC-PCD-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCD-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::Deactivate
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::Deactivate
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestDeactivate0004L
END_TESTCASE BA-CTSY-PKTC-PCD-0004

START_TESTCASE BA-CTSY-PKTC-PCGDI-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCGDI-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetDnsInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetDnsInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetDnsInfo0001L
END_TESTCASE BA-CTSY-PKTC-PCGDI-0001

START_TESTCASE BA-CTSY-PKTC-PCGDI-0003
//!@SYMTestCaseID BA-CTSY-PKTC-PCGDI-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetDnsInfo with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetDnsInfo with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetDnsInfo0003L
END_TESTCASE BA-CTSY-PKTC-PCGDI-0003

START_TESTCASE BA-CTSY-PKTC-PCLCP-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCLCP-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::LoanCommPort
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::LoanCommPort
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestLoanCommPort0001L
END_TESTCASE BA-CTSY-PKTC-PCLCP-0001

START_TESTCASE BA-CTSY-PKTC-PCGPN-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCGPN-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetProfileName
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetProfileName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetProfileName0001L
END_TESTCASE BA-CTSY-PKTC-PCGPN-0001

START_TESTCASE BA-CTSY-PKTC-PCRCP-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCRCP-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::RecoverCommPort
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::RecoverCommPort
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestRecoverCommPort0001L
END_TESTCASE BA-CTSY-PKTC-PCRCP-0001


START_TESTCASE BA-CTSY-PKTC-PCGLEC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCGLEC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetLastErrorCause
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetLastErrorCause
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetLastErrorCause0001L
END_TESTCASE BA-CTSY-PKTC-PCGLEC-0001

START_TESTCASE BA-CTSY-PKTC-PCIC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCIC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::InitialiseContext
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::InitialiseContext
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestInitialiseContext0001L
END_TESTCASE BA-CTSY-PKTC-PCIC-0001

START_TESTCASE BA-CTSY-PKTC-PCIC-0002
//!@SYMTestCaseID BA-CTSY-PKTC-PCIC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::InitialiseContext
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::InitialiseContext
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestInitialiseContext0002L
END_TESTCASE BA-CTSY-PKTC-PCIC-0002

START_TESTCASE BA-CTSY-PKTC-PCIC-0003
//!@SYMTestCaseID BA-CTSY-PKTC-PCIC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::InitialiseContext with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::InitialiseContext with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestInitialiseContext0003L
END_TESTCASE BA-CTSY-PKTC-PCIC-0003

START_TESTCASE BA-CTSY-PKTC-PCIC-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCIC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::InitialiseContext
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::InitialiseContext
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestInitialiseContext0004L
END_TESTCASE BA-CTSY-PKTC-PCIC-0004

START_TESTCASE BA-CTSY-PKTC-PCGCS-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCGCS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetConnectionSpeed
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetConnectionSpeed
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetConnectionSpeed0001L
END_TESTCASE BA-CTSY-PKTC-PCGCS-0001

START_TESTCASE BA-CTSY-PKTC-PCMAC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCMAC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::ModifyActiveContext
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::ModifyActiveContext
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestModifyActiveContext0001L
END_TESTCASE BA-CTSY-PKTC-PCMAC-0001

START_TESTCASE BA-CTSY-PKTC-PCMAC-0002
//!@SYMTestCaseID BA-CTSY-PKTC-PCMAC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::ModifyActiveContext
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::ModifyActiveContext
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestModifyActiveContext0002L
END_TESTCASE BA-CTSY-PKTC-PCMAC-0002

START_TESTCASE BA-CTSY-PKTC-PCMAC-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCMAC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::ModifyActiveContext
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::ModifyActiveContext
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestModifyActiveContext0004L
END_TESTCASE BA-CTSY-PKTC-PCMAC-0004

START_TESTCASE BA-CTSY-PKTC-PCNCC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCNCC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::NotifyConfigChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::NotifyConfigChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyConfigChanged0001L
END_TESTCASE BA-CTSY-PKTC-PCNCC-0001

START_TESTCASE BA-CTSY-PKTC-PCNCC-0001b
//!@SYMTestCaseID BA-CTSY-PKTC-PCNCC-0001b
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::NotifyConfigChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes CMmPacketServiceTsy::DialUpContext via RPacketContext::NotifyConfigChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyConfigChanged0001bL
END_TESTCASE BA-CTSY-PKTC-PCNCC-0001b

START_TESTCASE BA-CTSY-PKTC-PCNCC-0001c
//!@SYMTestCaseID BA-CTSY-PKTC-PCNCC-0001c
//!@SYMDEF DEF126915
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::NotifyConfigChanged using R99/R4 Context params
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::NotifyConfigChange. R99/R4 Context params returned
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyConfigChanged0001cL
END_TESTCASE BA-CTSY-PKTC-PCNCC-0001c

START_TESTCASE BA-CTSY-PKTC-PCNCC-0002
//!@SYMTestCaseID BA-CTSY-PKTC-PCNCC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::NotifyConfigChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::NotifyConfigChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyConfigChanged0002L
END_TESTCASE BA-CTSY-PKTC-PCNCC-0002

START_TESTCASE BA-CTSY-PKTC-PCNCC-0003
//!@SYMTestCaseID BA-CTSY-PKTC-PCNCC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::NotifyConfigChanged with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::NotifyConfigChanged with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyConfigChanged0003L
END_TESTCASE BA-CTSY-PKTC-PCNCC-0003

START_TESTCASE BA-CTSY-PKTC-PCNCC-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCNCC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::NotifyConfigChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::NotifyConfigChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyConfigChanged0004L
END_TESTCASE BA-CTSY-PKTC-PCNCC-0004

START_TESTCASE BA-CTSY-PKTC-PCNDT-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCNDT-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::NotifyDataTransferred
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::NotifyDataTransferred
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyDataTransferred0001L
END_TESTCASE BA-CTSY-PKTC-PCNDT-0001

START_TESTCASE BA-CTSY-PKTC-PCEPF-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCEPF-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::EnumeratePacketFilters
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::EnumeratePacketFilters
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestEnumeratePacketFilters0001L
END_TESTCASE BA-CTSY-PKTC-PCEPF-0001

START_TESTCASE BA-CTSY-PKTC-PCEPF-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCEPF-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::EnumeratePacketFilters
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::EnumeratePacketFilters
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestEnumeratePacketFilters0004L
END_TESTCASE BA-CTSY-PKTC-PCEPF-0004

START_TESTCASE BA-CTSY-PKTC-PCGDVT-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCGDVT-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetDataVolumeTransferred
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetDataVolumeTransferred
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetDataVolumeTransferred0001L
END_TESTCASE BA-CTSY-PKTC-PCGDVT-0001

START_TESTCASE BA-CTSY-PKTC-PCGDVT-0002
//!@SYMTestCaseID BA-CTSY-PKTC-PCGDVT-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::GetDataVolumeTransferred
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::GetDataVolumeTransferred
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetDataVolumeTransferred0002L
END_TESTCASE BA-CTSY-PKTC-PCGDVT-0002

START_TESTCASE BA-CTSY-PKTC-PCGDVT-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCGDVT-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::GetDataVolumeTransferred
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::GetDataVolumeTransferred
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetDataVolumeTransferred0004L
END_TESTCASE BA-CTSY-PKTC-PCGDVT-0004

START_TESTCASE BA-CTSY-PKTC-PCNCSC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCNCSC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::NotifyConnectionSpeedChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::NotifyConnectionSpeedChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyConnectionSpeedChange0001L
END_TESTCASE BA-CTSY-PKTC-PCNCSC-0001

START_TESTCASE BA-CTSY-PKTC-PCNCSC-0002
//!@SYMTestCaseID BA-CTSY-PKTC-PCNCSC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::NotifyConnectionSpeedChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::NotifyConnectionSpeedChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyConnectionSpeedChange0002L
END_TESTCASE BA-CTSY-PKTC-PCNCSC-0002

START_TESTCASE BA-CTSY-PKTC-PCNCSC-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCNCSC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::NotifyConnectionSpeedChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::NotifyConnectionSpeedChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestNotifyConnectionSpeedChange0004L
END_TESTCASE BA-CTSY-PKTC-PCNCSC-0004

START_TESTCASE BA-CTSY-PKTC-PCDL-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCDL-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::Delete
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Delete
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestDelete0001L
END_TESTCASE BA-CTSY-PKTC-PCDL-0001


START_TESTCASE BA-CTSY-PKTC-PCDL-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCDL-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::Delete
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::Delete
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestDelete0004L
END_TESTCASE BA-CTSY-PKTC-PCDL-0004

START_TESTCASE BA-CTSY-PKTC-PCA-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCA-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::Activate
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Activate
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestActivate0001L
END_TESTCASE BA-CTSY-PKTC-PCA-0001

START_TESTCASE BA-CTSY-PKTC-PCA-0001b
//!@SYMTestCaseID BA-CTSY-PKTC-PCA-0001b
//!@SYMDEF DEF126915
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::Activate with R99/R4 params
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Activate with R99/R4 context config params
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestActivate0001bL
END_TESTCASE BA-CTSY-PKTC-PCA-0001b

START_TESTCASE BA-CTSY-PKTC-PCA-0002
//!@SYMTestCaseID BA-CTSY-PKTC-PCA-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::Activate
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::Activate
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestActivate0002L
END_TESTCASE BA-CTSY-PKTC-PCA-0002

START_TESTCASE BA-CTSY-PKTC-PCA-0003
//!@SYMTestCaseID BA-CTSY-PKTC-PCA-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::Activate with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Activate with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestActivate0003L
END_TESTCASE BA-CTSY-PKTC-PCA-0003

START_TESTCASE BA-CTSY-PKTC-PCA-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCA-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::Activate
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::Activate
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestActivate0004L
END_TESTCASE BA-CTSY-PKTC-PCA-0004

START_TESTCASE BA-CTSY-PKTC-PCGC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCGC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetConfig
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetConfig
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetConfig0001L
END_TESTCASE BA-CTSY-PKTC-PCGC-0001

START_TESTCASE BA-CTSY-PKTC-PCGC-0003
//!@SYMTestCaseID BA-CTSY-PKTC-PCGC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetConfig with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetConfig with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetConfig0003L
END_TESTCASE BA-CTSY-PKTC-PCGC-0003

START_TESTCASE BA-CTSY-PKTC-PCGC-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCGC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::GetConfig
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::GetConfig
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetConfig0004L
END_TESTCASE BA-CTSY-PKTC-PCGC-0004

START_TESTCASE BA-CTSY-PKTC-PCGS-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCGS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetStatus0001L
END_TESTCASE BA-CTSY-PKTC-PCGS-0001

START_TESTCASE BA-CTSY-PKTC-PCSC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCSC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::SetConfig
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::SetConfig
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestSetConfig0001L
END_TESTCASE BA-CTSY-PKTC-PCSC-0001

START_TESTCASE BA-CTSY-PKTC-PCSC-0002
//!@SYMTestCaseID BA-CTSY-PKTC-PCSC-0002
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::SetConfig
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::SetConfig
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestSetConfig0002L
END_TESTCASE BA-CTSY-PKTC-PCSC-0002

START_TESTCASE BA-CTSY-PKTC-PCSC-0003
//!@SYMTestCaseID BA-CTSY-PKTC-PCSC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::SetConfig with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::SetConfig with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestSetConfig0003L
END_TESTCASE BA-CTSY-PKTC-PCSC-0003

START_TESTCASE BA-CTSY-PKTC-PCSC-0004
//!@SYMTestCaseID BA-CTSY-PKTC-PCSC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::SetConfig
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::SetConfig
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestSetConfig0004L
END_TESTCASE BA-CTSY-PKTC-PCSC-0004

START_TESTCASE BA-CTSY-PKTC-PCONSC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCONSC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::OpenNewSecondaryContext
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewSecondaryContext
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestOpenNewSecondaryContext0001L
END_TESTCASE BA-CTSY-PKTC-PCONSC-0001

START_TESTCASE BA-CTSY-PKTC-PCONSC-0001b
//!@SYMTestCaseID BA-CTSY-PKTC-PCONSC-0001b
//!@SYMDEF DEF125564
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for Activation of RPacketContext::OpenNewSecondaryContext
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Activate after RPacketContext::RemovePacketFilter for SecondaryContext
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestOpenNewSecondaryContext0001bL
END_TESTCASE BA-CTSY-PKTC-PCONSC-0001b


START_TESTCASE BA-CTSY-PKTC-PCONSC-0003
//!@SYMTestCaseID BA-CTSY-PKTC-PCONSC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::OpenNewSecondaryContext with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewSecondaryContext with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestOpenNewSecondaryContext0003L
END_TESTCASE BA-CTSY-PKTC-PCONSC-0003

START_TESTCASE BA-CTSY-PKTC-PCONSC-0003b
//!@SYMTestCaseID BA-CTSY-PKTC-PCONSC-0003b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::OpenNewSecondaryContext with wrong ContextId
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewSecondaryContext with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestOpenNewSecondaryContext0003bL
END_TESTCASE BA-CTSY-PKTC-PCONSC-0003b

START_TESTCASE BA-CTSY-PKTC-PCONSC-0003c
//!@SYMTestCaseID BA-CTSY-PKTC-PCONSC-0003c
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::OpenNewSecondaryContext with empty RPacketService
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewSecondaryContext with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP !PanicCode=8 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestOpenNewSecondaryContext0003cL
END_TESTCASE BA-CTSY-PKTC-PCONSC-0003c


START_TESTCASE BA-CTSY-PKTC-PCONC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCONC-0001
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::OpenNewContext
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewContext
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestOpenNewContext0001L
END_TESTCASE BA-CTSY-PKTC-PCONC-0001

START_TESTCASE BA-CTSY-PKTC-PCONC-0003
//!@SYMTestCaseID BA-CTSY-PKTC-PCONC-0003
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::OpenNewContext with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenNewContext with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP !PanicCode=8 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestOpenNewContext0003L
END_TESTCASE BA-CTSY-PKTC-PCONC-0003

START_TESTCASE BA-CTSY-PKTC-PCONEC-0001
//!@SYMTestCaseID BA-CTSY-PKTC-PCONEC-0001
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::OpenExistingContext
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenExistingContext
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestOpenExistingContext0001L
END_TESTCASE BA-CTSY-PKTC-PCONEC-0001

START_TESTCASE BA-CTSY-PKTC-PCONEC-0003
//!@SYMTestCaseID BA-CTSY-PKTC-PCONEC-0003
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::OpenExistingContext with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::OpenExistingContext with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP !PanicCode=-28 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestOpenExistingContext0003L
END_TESTCASE BA-CTSY-PKTC-PCONEC-0003

RUN_SCRIPT z:\TestData\Scripts\mockltsy_remove_ini_file.script

