//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

RUN_SCRIPT z:\TestData\Scripts\mockltsy_copy_ini_file.script

LOAD_SUITE te_ctsy_component

START_TESTCASE BA-CTSY-PRI-CSP-0001
//!@SYMTestCaseID BA-CTSY-PRI-CSP-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::SetPrivacy for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::SetPrivacy for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestSetPrivacy0001L
END_TESTCASE BA-CTSY-PRI-CSP-0001

START_TESTCASE BA-CTSY-PRI-CSP-0006
//!@SYMTestCaseID BA-CTSY-PRI-CSP-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::SetPrivacy for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::SetPrivacy for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestSetPrivacy0006L
END_TESTCASE BA-CTSY-PRI-CSP-0006

START_TESTCASE BA-CTSY-PRI-CSP-0011
//!@SYMTestCaseID BA-CTSY-PRI-CSP-0011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::SetPrivacy for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::SetPrivacy for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestSetPrivacy0011L
END_TESTCASE BA-CTSY-PRI-CSP-0011

START_TESTCASE BA-CTSY-PRI-CNPC-0001
//!@SYMTestCaseID BA-CTSY-PRI-CNPC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyPrivacyConfirmation for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyPrivacyConfirmation for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestNotifyPrivacyConfirmation0001L
END_TESTCASE BA-CTSY-PRI-CNPC-0001

START_TESTCASE BA-CTSY-PRI-CNPC-0002
//!@SYMTestCaseID BA-CTSY-PRI-CNPC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyPrivacyConfirmation for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyPrivacyConfirmation for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestNotifyPrivacyConfirmation0002L
END_TESTCASE BA-CTSY-PRI-CNPC-0002

START_TESTCASE BA-CTSY-PRI-CNPC-0004
//!@SYMTestCaseID BA-CTSY-PRI-CNPC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyPrivacyConfirmation for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyPrivacyConfirmation for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestNotifyPrivacyConfirmation0004L
END_TESTCASE BA-CTSY-PRI-CNPC-0004

START_TESTCASE BA-CTSY-PRI-CNPC-0006
//!@SYMTestCaseID BA-CTSY-PRI-CNPC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyPrivacyConfirmation for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyPrivacyConfirmation for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestNotifyPrivacyConfirmation0006L
END_TESTCASE BA-CTSY-PRI-CNPC-0006

START_TESTCASE BA-CTSY-PRI-CNPC-0007
//!@SYMTestCaseID BA-CTSY-PRI-CNPC-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyPrivacyConfirmation with bad parameter data for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyPrivacyConfirmation with bad parameter data for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestNotifyPrivacyConfirmation0007L
END_TESTCASE BA-CTSY-PRI-CNPC-0007

START_TESTCASE BA-CTSY-PRI-CNPC-0009
//!@SYMTestCaseID BA-CTSY-PRI-CNPC-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyPrivacyConfirmation for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyPrivacyConfirmation for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestNotifyPrivacyConfirmation0009L
END_TESTCASE BA-CTSY-PRI-CNPC-0009

START_TESTCASE BA-CTSY-PRI-CNPC-00011
//!@SYMTestCaseID BA-CTSY-PRI-CNPC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyPrivacyConfirmation with bad parameter data for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyPrivacyConfirmation with bad parameter data for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestNotifyPrivacyConfirmation00011L
END_TESTCASE BA-CTSY-PRI-CNPC-00011

START_TESTCASE BA-CTSY-PRI-CNPC-00012
//!@SYMTestCaseID BA-CTSY-PRI-CNPC-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyPrivacyConfirmation for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyPrivacyConfirmation for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestNotifyPrivacyConfirmation00012L
END_TESTCASE BA-CTSY-PRI-CNPC-00012

START_TESTCASE BA-CTSY-PRI-MGDP-0001
//!@SYMTestCaseID BA-CTSY-PRI-MGDP-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetDefaultPrivacy
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetDefaultPrivacy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestGetDefaultPrivacy0001L
END_TESTCASE BA-CTSY-PRI-MGDP-0001

START_TESTCASE BA-CTSY-PRI-MSDP-0001
//!@SYMTestCaseID BA-CTSY-PRI-MSDP-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetDefaultPrivacy
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetDefaultPrivacy
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestSetDefaultPrivacy0001L
END_TESTCASE BA-CTSY-PRI-MSDP-0001

START_TESTCASE BA-CTSY-PRI-MNDPC-0001
//!@SYMTestCaseID BA-CTSY-PRI-MNDPC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyDefaultPrivacyChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyDefaultPrivacyChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPrivacyFU.TestNotifyDefaultPrivacyChange0001L
END_TESTCASE BA-CTSY-PRI-MNDPC-0001

RUN_SCRIPT z:\TestData\Scripts\mockltsy_remove_ini_file.script
