//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

RUN_SCRIPT z:\TestData\Scripts\mockltsy_copy_ini_file.script

LOAD_SUITE te_ctsy_component

RUN_UTILS Delete c:\private\101f7989\rand_db.cur

START_TESTCASE BA-CTSY-CIPC-MCSDM-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSDM-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SetDriveMode
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetDriveMode
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetDriveMode0001L
END_TESTCASE BA-CTSY-CIPC-MCSDM-0001

START_TESTCASE BA-CTSY-CIPC-MCSDM-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCSDM-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::SetDriveMode
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::SetDriveMode
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetDriveMode0002L
END_TESTCASE BA-CTSY-CIPC-MCSDM-0002

START_TESTCASE BA-CTSY-CIPC-MCSDM-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCSDM-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::SetDriveMode
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::SetDriveMode
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetDriveMode0004L
END_TESTCASE BA-CTSY-CIPC-MCSDM-0004

START_TESTCASE BA-CTSY-CIPC-MCASL-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCASL-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ActivateSimLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ActivateSimLock
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestActivateSimLock0001L
END_TESTCASE BA-CTSY-CIPC-MCASL-0001

START_TESTCASE BA-CTSY-CIPC-MCASL-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCASL-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::ActivateSimLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::ActivateSimLock
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestActivateSimLock0002L
END_TESTCASE BA-CTSY-CIPC-MCASL-0002

START_TESTCASE BA-CTSY-CIPC-MCASL-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCASL-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ActivateSimLock with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ActivateSimLock with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestActivateSimLock0003L
END_TESTCASE BA-CTSY-CIPC-MCASL-0003

START_TESTCASE BA-CTSY-CIPC-MCASL-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCASL-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::ActivateSimLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::ActivateSimLock
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestActivateSimLock0004L
END_TESTCASE BA-CTSY-CIPC-MCASL-0004

START_TESTCASE BA-CTSY-CIPC-MCDASL-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCDASL-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::DeActivateSimLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::DeActivateSimLock
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDeActivateSimLock0001L
END_TESTCASE BA-CTSY-CIPC-MCDASL-0001

START_TESTCASE BA-CTSY-CIPC-MCDASL-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCDASL-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::DeActivateSimLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::DeActivateSimLock
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDeActivateSimLock0002L
END_TESTCASE BA-CTSY-CIPC-MCDASL-0002

START_TESTCASE BA-CTSY-CIPC-MCDASL-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCDASL-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::DeActivateSimLock with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::DeActivateSimLock with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDeActivateSimLock0003L
END_TESTCASE BA-CTSY-CIPC-MCDASL-0003

START_TESTCASE BA-CTSY-CIPC-MCDASL-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCDASL-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::DeActivateSimLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::DeActivateSimLock
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDeActivateSimLock0004L
END_TESTCASE BA-CTSY-CIPC-MCDASL-0004

START_TESTCASE BA-CTSY-CIPC-MCNDE-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNDE-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyDtmfEvent
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyDtmfEvent
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyDtmfEvent0001L
END_TESTCASE BA-CTSY-CIPC-MCNDE-0001

START_TESTCASE BA-CTSY-CIPC-MCNDE-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNDE-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyDtmfEvent
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyDtmfEvent
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyDtmfEvent0002L
END_TESTCASE BA-CTSY-CIPC-MCNDE-0002

START_TESTCASE BA-CTSY-CIPC-MCNDE-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNDE-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyDtmfEvent
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyDtmfEvent
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyDtmfEvent0004L
END_TESTCASE BA-CTSY-CIPC-MCNDE-0004

START_TESTCASE BA-CTSY-CIPC-MCGDO-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGDO-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetDiagnosticInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetDiagnosticInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetDiagnosticInfo0001L
END_TESTCASE BA-CTSY-CIPC-MCGDO-0001

START_TESTCASE BA-CTSY-CIPC-MCSAB-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAB-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SetAlsBlocked
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetAlsBlocked
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetAlsBlocked0001L
END_TESTCASE BA-CTSY-CIPC-MCSAB-0001

START_TESTCASE BA-CTSY-CIPC-MCSAB-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAB-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::SetAlsBlocked
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::SetAlsBlocked
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetAlsBlocked0002L
END_TESTCASE BA-CTSY-CIPC-MCSAB-0002

START_TESTCASE BA-CTSY-CIPC-MCSAB-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAB-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::SetAlsBlocked
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::SetAlsBlocked
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetAlsBlocked0004L
END_TESTCASE BA-CTSY-CIPC-MCSAB-0004

START_TESTCASE BA-CTSY-CIPC-MCGAB-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGAB-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetAlsBlocked
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetAlsBlocked
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetAlsBlocked0001L
END_TESTCASE BA-CTSY-CIPC-MCGAB-0001

START_TESTCASE BA-CTSY-CIPC-MCGAB-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGAB-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetAlsBlocked
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetAlsBlocked
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetAlsBlocked0002L
END_TESTCASE BA-CTSY-CIPC-MCGAB-0002

START_TESTCASE BA-CTSY-CIPC-MCGAB-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGAB-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetAlsBlocked
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetAlsBlocked
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetAlsBlocked0004L
END_TESTCASE BA-CTSY-CIPC-MCGAB-0004

START_TESTCASE BA-CTSY-CIPC-MCCAPS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCCAPS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::CheckAlsPpSupport
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::CheckAlsPpSupport
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckAlsPpSupport0001L
END_TESTCASE BA-CTSY-CIPC-MCCAPS-0001

START_TESTCASE BA-CTSY-CIPC-MCCAPS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCCAPS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::CheckAlsPpSupport
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::CheckAlsPpSupport
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckAlsPpSupport0002L
END_TESTCASE BA-CTSY-CIPC-MCCAPS-0002

START_TESTCASE BA-CTSY-CIPC-MCCAPS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCCAPS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::CheckAlsPpSupport
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::CheckAlsPpSupport
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckAlsPpSupport0004L
END_TESTCASE BA-CTSY-CIPC-MCCAPS-0004

START_TESTCASE BA-CTSY-CIPC-MCGRATS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGRATS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetRemoteAlertingToneStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetRemoteAlertingToneStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetRemoteAlertingToneStatus0001L
END_TESTCASE BA-CTSY-CIPC-MCGRATS-0001

START_TESTCASE BA-CTSY-CIPC-MCCO-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCCO-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::CallOrigin
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::CallOrigin
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCallOrigin0001L
END_TESTCASE BA-CTSY-CIPC-MCCO-0001

START_TESTCASE BA-CTSY-CIPC-MCTC-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCTC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::TerminateCall
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::TerminateCall
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestTerminateCall0001L
END_TESTCASE BA-CTSY-CIPC-MCTC-0001

START_TESTCASE BA-CTSY-CIPC-MCTC-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCTC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::TerminateCall
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::TerminateCall
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestTerminateCall0002L
END_TESTCASE BA-CTSY-CIPC-MCTC-0002

START_TESTCASE BA-CTSY-CIPC-MCTC-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCTC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::TerminateCall with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::TerminateCall with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestTerminateCall0003L
END_TESTCASE BA-CTSY-CIPC-MCTC-0003

START_TESTCASE BA-CTSY-CIPC-MCTC-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCTC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::TerminateCall
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::TerminateCall
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestTerminateCall0004L
END_TESTCASE BA-CTSY-CIPC-MCTC-0004

START_TESTCASE BA-CTSY-CIPC-MCBABC-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCBABC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyAlsBlockedChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyAlsBlockedChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyAlsBlockedChanged0001L
END_TESTCASE BA-CTSY-CIPC-MCBABC-0001

START_TESTCASE BA-CTSY-CIPC-MCBABC-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCBABC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyAlsBlockedChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyAlsBlockedChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyAlsBlockedChanged0002L
END_TESTCASE BA-CTSY-CIPC-MCBABC-0002

START_TESTCASE BA-CTSY-CIPC-MCBABC-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCBABC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyAlsBlockedChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyAlsBlockedChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyAlsBlockedChanged0004L
END_TESTCASE BA-CTSY-CIPC-MCBABC-0004

START_TESTCASE BA-CTSY-CIPC-MCGCI-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCI-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetCipheringInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetCipheringInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCipheringInfo0001L
END_TESTCASE BA-CTSY-CIPC-MCGCI-0001

START_TESTCASE BA-CTSY-CIPC-MCGCI-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCI-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetCipheringInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetCipheringInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCipheringInfo0002L
END_TESTCASE BA-CTSY-CIPC-MCGCI-0002

START_TESTCASE BA-CTSY-CIPC-MCGCI-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCI-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetCipheringInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetCipheringInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCipheringInfo0004L
END_TESTCASE BA-CTSY-CIPC-MCGCI-0004

START_TESTCASE BA-CTSY-CIPC-MCNCIC-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNCIC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyCipheringInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyCipheringInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyCipheringInfoChange0001L
END_TESTCASE BA-CTSY-CIPC-MCNCIC-0001

START_TESTCASE BA-CTSY-CIPC-MCNCIC-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNCIC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyCipheringInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyCipheringInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyCipheringInfoChange0002L
END_TESTCASE BA-CTSY-CIPC-MCNCIC-0002

START_TESTCASE BA-CTSY-CIPC-MCNCIC-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNCIC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyCipheringInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyCipheringInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyCipheringInfoChange0004L
END_TESTCASE BA-CTSY-CIPC-MCNCIC-0004

START_TESTCASE BA-CTSY-CIPC-MCNNS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNNS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyNSPSStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyNSPSStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyNSPSStatus0001L
END_TESTCASE BA-CTSY-CIPC-MCNNS-0001

START_TESTCASE BA-CTSY-CIPC-MCNNS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNNS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyNSPSStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyNSPSStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyNSPSStatus0002L
END_TESTCASE BA-CTSY-CIPC-MCNNS-0002

START_TESTCASE BA-CTSY-CIPC-MCNNS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNNS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyNSPSStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyNSPSStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyNSPSStatus0004L
END_TESTCASE BA-CTSY-CIPC-MCNNS-0004

START_TESTCASE BA-CTSY-CIPC-MCNW-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNW-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NetWakeup
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NetWakeup
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNetWakeup0001L
END_TESTCASE BA-CTSY-CIPC-MCNW-0001

START_TESTCASE BA-CTSY-CIPC-MCNW-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNW-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NetWakeup
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NetWakeup
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNetWakeup0002L
END_TESTCASE BA-CTSY-CIPC-MCNW-0002

START_TESTCASE BA-CTSY-CIPC-MCNW-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNW-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NetWakeup
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NetWakeup
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNetWakeup0004L
END_TESTCASE BA-CTSY-CIPC-MCNW-0004

START_TESTCASE BA-CTSY-CIPC-MCRVHZP-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZP-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadViagHomeZoneParams
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadViagHomeZoneParams
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneParams0001L
END_TESTCASE BA-CTSY-CIPC-MCRVHZP-0001

START_TESTCASE BA-CTSY-CIPC-MCRVHZP-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZP-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::ReadViagHomeZoneParams
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::ReadViagHomeZoneParams
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneParams0002L
END_TESTCASE BA-CTSY-CIPC-MCRVHZP-0002

START_TESTCASE BA-CTSY-CIPC-MCRVHZP-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZP-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadViagHomeZoneParams with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadViagHomeZoneParams with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneParams0003L
END_TESTCASE BA-CTSY-CIPC-MCRVHZP-0003

START_TESTCASE BA-CTSY-CIPC-MCRVHZP-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZP-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::ReadViagHomeZoneParams
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::ReadViagHomeZoneParams
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneParams0004L
END_TESTCASE BA-CTSY-CIPC-MCRVHZP-0004

START_TESTCASE BA-CTSY-CIPC-MCRVHZC-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadViagHomeZoneCache
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadViagHomeZoneCache
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneCache0001L
END_TESTCASE BA-CTSY-CIPC-MCRVHZC-0001

START_TESTCASE BA-CTSY-CIPC-MCRVHZC-0001b
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZC-0001b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadViagHomeZoneCache when request failed by NTSY
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadViagHomeZoneCache
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneCache0001bL
END_TESTCASE BA-CTSY-CIPC-MCRVHZC-0001b

START_TESTCASE BA-CTSY-CIPC-MCRVHZC-0001c
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZC-0001c
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadViagHomeZoneCache when request complete when customAPI is dead
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadViagHomeZoneCache
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneCache0001cL
END_TESTCASE BA-CTSY-CIPC-MCRVHZC-0001c

START_TESTCASE BA-CTSY-CIPC-MCRVHZC-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::ReadViagHomeZoneCache
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::ReadViagHomeZoneCache
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneCache0002L
END_TESTCASE BA-CTSY-CIPC-MCRVHZC-0002

START_TESTCASE BA-CTSY-CIPC-MCRVHZC-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadViagHomeZoneCache with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadViagHomeZoneCache with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneCache0003L
END_TESTCASE BA-CTSY-CIPC-MCRVHZC-0003

START_TESTCASE BA-CTSY-CIPC-MCRVHZC-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::ReadViagHomeZoneCache
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::ReadViagHomeZoneCache
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneCache0004L
END_TESTCASE BA-CTSY-CIPC-MCRVHZC-0004

START_TESTCASE BA-CTSY-CIPC-MCWVHZC-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCWVHZC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::WriteViagHomeZoneCache
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::WriteViagHomeZoneCache
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteViagHomeZoneCache0001L
END_TESTCASE BA-CTSY-CIPC-MCWVHZC-0001

START_TESTCASE BA-CTSY-CIPC-MCWVHZC-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCWVHZC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::WriteViagHomeZoneCache
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::WriteViagHomeZoneCache
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteViagHomeZoneCache0002L
END_TESTCASE BA-CTSY-CIPC-MCWVHZC-0002

START_TESTCASE BA-CTSY-CIPC-MCWVHZC-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCWVHZC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::WriteViagHomeZoneCache with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::WriteViagHomeZoneCache with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteViagHomeZoneCache0003L
END_TESTCASE BA-CTSY-CIPC-MCWVHZC-0003

START_TESTCASE BA-CTSY-CIPC-MCWVHZC-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCWVHZC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::WriteViagHomeZoneCache
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::WriteViagHomeZoneCache
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteViagHomeZoneCache0004L
END_TESTCASE BA-CTSY-CIPC-MCWVHZC-0004

START_TESTCASE BA-CTSY-CIPC-MCCCBL-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCCCBL-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ClearCallBlackList
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ClearCallBlackList
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestClearCallBlackList0001L
END_TESTCASE BA-CTSY-CIPC-MCCCBL-0001

START_TESTCASE BA-CTSY-CIPC-MCCCBL-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCCCBL-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::ClearCallBlackList
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::ClearCallBlackList
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestClearCallBlackList0002L
END_TESTCASE BA-CTSY-CIPC-MCCCBL-0002

START_TESTCASE BA-CTSY-CIPC-MCCCBL-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCCCBL-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::ClearCallBlackList
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::ClearCallBlackList
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestClearCallBlackList0004L
END_TESTCASE BA-CTSY-CIPC-MCCCBL-0004

START_TESTCASE BA-CTSY-CIPC-MCSAIN-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAIN-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SsAdditionalInfoNotification
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SsAdditionalInfoNotification
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSsAdditionalInfoNotification0001L
END_TESTCASE BA-CTSY-CIPC-MCSAIN-0001

START_TESTCASE BA-CTSY-CIPC-MCSAIN-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAIN-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::SsAdditionalInfoNotification
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::SsAdditionalInfoNotification
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSsAdditionalInfoNotification0002L
END_TESTCASE BA-CTSY-CIPC-MCSAIN-0002

START_TESTCASE BA-CTSY-CIPC-MCSAIN-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAIN-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::SsAdditionalInfoNotification
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::SsAdditionalInfoNotification
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSsAdditionalInfoNotification0004L
END_TESTCASE BA-CTSY-CIPC-MCSAIN-0004

START_TESTCASE BA-CTSY-CIPC-MCSRCN-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSRCN-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SsRequestCompleteNotification
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SsRequestCompleteNotification
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSsRequestCompleteNotification0001L
END_TESTCASE BA-CTSY-CIPC-MCSRCN-0001

START_TESTCASE BA-CTSY-CIPC-MCSRCN-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCSRCN-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::SsRequestCompleteNotification
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::SsRequestCompleteNotification
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSsRequestCompleteNotification0002L
END_TESTCASE BA-CTSY-CIPC-MCSRCN-0002

START_TESTCASE BA-CTSY-CIPC-MCSRCN-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCSRCN-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::SsRequestCompleteNotification
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::SsRequestCompleteNotification
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSsRequestCompleteNotification0004L
END_TESTCASE BA-CTSY-CIPC-MCSRCN-0004

START_TESTCASE BA-CTSY-CIPC-MCIB-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCIB-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::IsBlocked
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::IsBlocked
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestIsBlocked0001L
END_TESTCASE BA-CTSY-CIPC-MCIB-0001

START_TESTCASE BA-CTSY-CIPC-MCCSC-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCCSC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::CheckSecurityCode
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::CheckSecurityCode
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckSecurityCode0001L
END_TESTCASE BA-CTSY-CIPC-MCCSC-0001

START_TESTCASE BA-CTSY-CIPC-MCCSC-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCCSC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::CheckSecurityCode
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::CheckSecurityCode
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckSecurityCode0002L
END_TESTCASE BA-CTSY-CIPC-MCCSC-0002

START_TESTCASE BA-CTSY-CIPC-MCCSC-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCCSC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::CheckSecurityCode
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::CheckSecurityCode
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckSecurityCode0004L
END_TESTCASE BA-CTSY-CIPC-MCCSC-0004

START_TESTCASE BA-CTSY-CIPC-MCGAP-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGAP-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetActivePin
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetActivePin
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetActivePin0001L
END_TESTCASE BA-CTSY-CIPC-MCGAP-0001

START_TESTCASE BA-CTSY-CIPC-MCGATD-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGATD-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetAirTimeDuration
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetAirTimeDuration
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetAirTimeDuration0001L
END_TESTCASE BA-CTSY-CIPC-MCGATD-0001

START_TESTCASE BA-CTSY-CIPC-MCGNPN-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGNPN-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetNetworkProviderName
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetNetworkProviderName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetNetworkProviderName0001L
END_TESTCASE BA-CTSY-CIPC-MCGNPN-0001

START_TESTCASE BA-CTSY-CIPC-MCGNPN-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGNPN-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetNetworkProviderName
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetNetworkProviderName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetNetworkProviderName0002L
END_TESTCASE BA-CTSY-CIPC-MCGNPN-0002

START_TESTCASE BA-CTSY-CIPC-MCGNPN-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCGNPN-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetNetworkProviderName with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetNetworkProviderName with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetNetworkProviderName0003L
END_TESTCASE BA-CTSY-CIPC-MCGNPN-0003

START_TESTCASE BA-CTSY-CIPC-MCGNPN-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGNPN-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetNetworkProviderName
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetNetworkProviderName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetNetworkProviderName0004L
END_TESTCASE BA-CTSY-CIPC-MCGNPN-0004

START_TESTCASE BA-CTSY-CIPC-MCCEN-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCCEN-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::CheckEmergencyNumber
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::CheckEmergencyNumber
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckEmergencyNumber0001L
END_TESTCASE BA-CTSY-CIPC-MCCEN-0001

START_TESTCASE BA-CTSY-CIPC-MCCEN-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCCEN-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::CheckEmergencyNumber
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::CheckEmergencyNumber
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckEmergencyNumber0002L
END_TESTCASE BA-CTSY-CIPC-MCCEN-0002

START_TESTCASE BA-CTSY-CIPC-MCCEN-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCCEN-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::CheckEmergencyNumber
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::CheckEmergencyNumber
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckEmergencyNumber0004L
END_TESTCASE BA-CTSY-CIPC-MCCEN-0004

START_TESTCASE BA-CTSY-CIPC-MCNPCR-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNPCR-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyPndCacheReady
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyPndCacheReady
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyPndCacheReady0001L
END_TESTCASE BA-CTSY-CIPC-MCNPCR-0001

START_TESTCASE BA-CTSY-CIPC-MCNPCR-0001b
//!@SYMTestCaseID BA-CTSY-CIPC-MCNPCR-0001b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyPndCacheReady when caching has been originated from SIM.
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyPndCacheReady
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyPndCacheReady0001bL
END_TESTCASE BA-CTSY-CIPC-MCNPCR-0001b

START_TESTCASE BA-CTSY-CIPC-MCNPCR-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNPCR-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyPndCacheReady
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyPndCacheReady
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyPndCacheReady0002L
END_TESTCASE BA-CTSY-CIPC-MCNPCR-0002

START_TESTCASE BA-CTSY-CIPC-MCNPCR-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCNPCR-0003
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyPndCacheReady with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyPndCacheReady with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyPndCacheReady0003L
END_TESTCASE BA-CTSY-CIPC-MCNPCR-0003

START_TESTCASE BA-CTSY-CIPC-MCNPCR-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNPCR-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyPndCacheReady
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyPndCacheReady
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyPndCacheReady0004L
END_TESTCASE BA-CTSY-CIPC-MCNPCR-0004

START_TESTCASE BA-CTSY-CIPC-MCGPCS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGPCS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetPndCacheStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetPndCacheStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetPndCacheStatus0001L
END_TESTCASE BA-CTSY-CIPC-MCGPCS-0001

START_TESTCASE BA-CTSY-CIPC-MCGPCS-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCGPCS-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetPndCacheStatus with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetPndCacheStatus with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetPndCacheStatus0003L
END_TESTCASE BA-CTSY-CIPC-MCGPCS-0003

START_TESTCASE BA-CTSY-CIPC-MCGON-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGON-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetOperatorName
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetOperatorName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetOperatorName0001L
END_TESTCASE BA-CTSY-CIPC-MCGON-0001

START_TESTCASE BA-CTSY-CIPC-MCGON-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGON-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetOperatorName
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetOperatorName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetOperatorName0002L
END_TESTCASE BA-CTSY-CIPC-MCGON-0002

START_TESTCASE BA-CTSY-CIPC-MCGON-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGON-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetOperatorName
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetOperatorName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetOperatorName0004L
END_TESTCASE BA-CTSY-CIPC-MCGON-0004

START_TESTCASE BA-CTSY-CIPC-MCNSNE-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNSNE-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifySsNetworkEvent
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifySsNetworkEvent
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifySsNetworkEvent0001L
END_TESTCASE BA-CTSY-CIPC-MCNSNE-0001

START_TESTCASE BA-CTSY-CIPC-MCNSNE-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNSNE-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifySsNetworkEvent
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifySsNetworkEvent
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifySsNetworkEvent0002L
END_TESTCASE BA-CTSY-CIPC-MCNSNE-0002

START_TESTCASE BA-CTSY-CIPC-MCNSNE-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNSNE-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifySsNetworkEvent
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifySsNetworkEvent
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifySsNetworkEvent0004L
END_TESTCASE BA-CTSY-CIPC-MCNSNE-0004

START_TESTCASE BA-CTSY-CIPC-MCCUS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCCUS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::CancelUssdSession
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::CancelUssdSession
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCancelUssdSession0001L
END_TESTCASE BA-CTSY-CIPC-MCCUS-0001

START_TESTCASE BA-CTSY-CIPC-MCSRCN2-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSRCN2-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SatRefreshCompleteNotification
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SatRefreshCompleteNotification
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSatRefreshCompleteNotification0001L
END_TESTCASE BA-CTSY-CIPC-MCSRCN2-0001

START_TESTCASE BA-CTSY-CIPC-MCSRCN2-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCSRCN2-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::SatRefreshCompleteNotification
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::SatRefreshCompleteNotification
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSatRefreshCompleteNotification0002L
END_TESTCASE BA-CTSY-CIPC-MCSRCN2-0002

START_TESTCASE BA-CTSY-CIPC-MCSRCN2-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCSRCN2-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::SatRefreshCompleteNotification
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::SatRefreshCompleteNotification
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSatRefreshCompleteNotification0004L
END_TESTCASE BA-CTSY-CIPC-MCSRCN2-0004

START_TESTCASE BA-CTSY-CIPC-MCCTDDS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCCTDDS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::CheckTwoDigitDialSupport
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::CheckTwoDigitDialSupport
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckTwoDigitDialSupport0001L
END_TESTCASE BA-CTSY-CIPC-MCCTDDS-0001

START_TESTCASE BA-CTSY-CIPC-MCCTDDS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCCTDDS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::CheckTwoDigitDialSupport
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::CheckTwoDigitDialSupport
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckTwoDigitDialSupport0002L
END_TESTCASE BA-CTSY-CIPC-MCCTDDS-0002

START_TESTCASE BA-CTSY-CIPC-MCCTDDS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCCTDDS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::CheckTwoDigitDialSupport
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::CheckTwoDigitDialSupport
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckTwoDigitDialSupport0004L
END_TESTCASE BA-CTSY-CIPC-MCCTDDS-0004

START_TESTCASE BA-CTSY-CIPC-MCRNS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCRNS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ResetNetServer
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ResetNetServer
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestResetNetServer0001L
END_TESTCASE BA-CTSY-CIPC-MCRNS-0001

START_TESTCASE BA-CTSY-CIPC-MCRNS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCRNS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::ResetNetServer
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::ResetNetServer
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestResetNetServer0002L
END_TESTCASE BA-CTSY-CIPC-MCRNS-0002

START_TESTCASE BA-CTSY-CIPC-MCRNS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCRNS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::ResetNetServer
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::ResetNetServer
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestResetNetServer0004L
END_TESTCASE BA-CTSY-CIPC-MCRNS-0004

START_TESTCASE BA-CTSY-CIPC-MCRF-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCRF-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReleaseFile
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReleaseFile
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReleaseFile0001L
END_TESTCASE BA-CTSY-CIPC-MCRF-0001

START_TESTCASE BA-CTSY-CIPC-MCREF-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCREF-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::RestartFile
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::RestartFile
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestRestartFile0001L
END_TESTCASE BA-CTSY-CIPC-MCREF-0001

START_TESTCASE BA-CTSY-CIPC-MCSSCTB-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSCTB-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::StartSimCbTopicBrowsing
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::StartSimCbTopicBrowsing
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestStartSimCbTopicBrowsing0001L
END_TESTCASE BA-CTSY-CIPC-MCSSCTB-0001

START_TESTCASE BA-CTSY-CIPC-MCSSCTB-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSCTB-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::StartSimCbTopicBrowsing with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::StartSimCbTopicBrowsing with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestStartSimCbTopicBrowsing0003L
END_TESTCASE BA-CTSY-CIPC-MCSSCTB-0003

START_TESTCASE BA-CTSY-CIPC-MCGNSCT-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGNSCT-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetNextSimCbTopic
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetNextSimCbTopic
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetNextSimCbTopic0001L
END_TESTCASE BA-CTSY-CIPC-MCGNSCT-0001

START_TESTCASE BA-CTSY-CIPC-MCDSCT-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCDSCT-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::DeleteSimCbTopic
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::DeleteSimCbTopic
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDeleteSimCbTopic0001L
END_TESTCASE BA-CTSY-CIPC-MCDSCT-0001

START_TESTCASE BA-CTSY-CIPC-MCDSCT-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCDSCT-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::DeleteSimCbTopic
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::DeleteSimCbTopic
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDeleteSimCbTopic0002L
END_TESTCASE BA-CTSY-CIPC-MCDSCT-0002

START_TESTCASE BA-CTSY-CIPC-MCDSCT-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCDSCT-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::DeleteSimCbTopic with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::DeleteSimCbTopic with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDeleteSimCbTopic0003L
END_TESTCASE BA-CTSY-CIPC-MCDSCT-0003

START_TESTCASE BA-CTSY-CIPC-MCDSCT-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCDSCT-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::DeleteSimCbTopic
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::DeleteSimCbTopic
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDeleteSimCbTopic0004L
END_TESTCASE BA-CTSY-CIPC-MCDSCT-0004

START_TESTCASE BA-CTSY-CIPC-MCNNCF-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNNCF-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyNetworkConnectionFailure
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyNetworkConnectionFailure
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyNetworkConnectionFailure0001L
END_TESTCASE BA-CTSY-CIPC-MCNNCF-0001

START_TESTCASE BA-CTSY-CIPC-MCNNCF-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNNCF-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyNetworkConnectionFailure
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyNetworkConnectionFailure
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyNetworkConnectionFailure0002L
END_TESTCASE BA-CTSY-CIPC-MCNNCF-0002

START_TESTCASE BA-CTSY-CIPC-MCNNCF-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNNCF-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyNetworkConnectionFailure
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyNetworkConnectionFailure
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyNetworkConnectionFailure0004L
END_TESTCASE BA-CTSY-CIPC-MCNNCF-0004

START_TESTCASE BA-CTSY-CIPC-MCSAR-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAR-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SendAPDUReq
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SendAPDUReq
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSendAPDUReq0001L
END_TESTCASE BA-CTSY-CIPC-MCSAR-0001

START_TESTCASE BA-CTSY-CIPC-MCSAR-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAR-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::SendAPDUReq
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::SendAPDUReq
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSendAPDUReq0002L
END_TESTCASE BA-CTSY-CIPC-MCSAR-0002

START_TESTCASE BA-CTSY-CIPC-MCSAR-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAR-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SendAPDUReq with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SendAPDUReq with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSendAPDUReq0003L
END_TESTCASE BA-CTSY-CIPC-MCSAR-0003

START_TESTCASE BA-CTSY-CIPC-MCSAR-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAR-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::SendAPDUReq
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::SendAPDUReq
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSendAPDUReq0004L
END_TESTCASE BA-CTSY-CIPC-MCSAR-0004

START_TESTCASE BA-CTSY-CIPC-MCDPL-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCDPL-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::DisablePhoneLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::DisablePhoneLock
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDisablePhoneLock0001L
END_TESTCASE BA-CTSY-CIPC-MCDPL-0001

START_TESTCASE BA-CTSY-CIPC-MCDPL-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCDPL-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::DisablePhoneLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::DisablePhoneLock
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDisablePhoneLock0002L
END_TESTCASE BA-CTSY-CIPC-MCDPL-0002

START_TESTCASE BA-CTSY-CIPC-MCDPL-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCDPL-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::DisablePhoneLock
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::DisablePhoneLock
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDisablePhoneLock0004L
END_TESTCASE BA-CTSY-CIPC-MCDPL-0004

START_TESTCASE BA-CTSY-CIPC-MCNEIC-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNEIC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyEGprsInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyEGprsInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyEGprsInfoChange0001L
END_TESTCASE BA-CTSY-CIPC-MCNEIC-0001

START_TESTCASE BA-CTSY-CIPC-MCNEIC-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNEIC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyEGprsInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyEGprsInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyEGprsInfoChange0002L
END_TESTCASE BA-CTSY-CIPC-MCNEIC-0002

START_TESTCASE BA-CTSY-CIPC-MCNEIC-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCNEIC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyEGprsInfoChange with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyEGprsInfoChange with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyEGprsInfoChange0003L
END_TESTCASE BA-CTSY-CIPC-MCNEIC-0003

START_TESTCASE BA-CTSY-CIPC-MCNEIC-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNEIC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyEGprsInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyEGprsInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyEGprsInfoChange0004L
END_TESTCASE BA-CTSY-CIPC-MCNEIC-0004

START_TESTCASE BA-CTSY-CIPC-MCGEI-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGEI-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetEGprsInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetEGprsInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetEGprsInfo0001L
END_TESTCASE BA-CTSY-CIPC-MCGEI-0001

START_TESTCASE BA-CTSY-CIPC-MCGEI-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCGEI-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetEGprsInfo with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetEGprsInfo with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetEGprsInfo0003L
END_TESTCASE BA-CTSY-CIPC-MCGEI-0003

START_TESTCASE BA-CTSY-CIPC-MCRSF-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCRSF-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadSimFile
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadSimFile
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadSimFile0001L
END_TESTCASE BA-CTSY-CIPC-MCRSF-0001

START_TESTCASE BA-CTSY-CIPC-MCRSF-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCRSF-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::ReadSimFile
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::ReadSimFile
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadSimFile0002L
END_TESTCASE BA-CTSY-CIPC-MCRSF-0002

START_TESTCASE BA-CTSY-CIPC-MCRSF-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCRSF-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadSimFile with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadSimFile with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadSimFile0003L
END_TESTCASE BA-CTSY-CIPC-MCRSF-0003

START_TESTCASE BA-CTSY-CIPC-MCRSF-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCRSF-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::ReadSimFile
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::ReadSimFile
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadSimFile0004L
END_TESTCASE BA-CTSY-CIPC-MCRSF-0004

START_TESTCASE BA-CTSY-CIPC-MCGLT-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGLT-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetLifeTime
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetLifeTime
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetLifeTime0001L
END_TESTCASE BA-CTSY-CIPC-MCGLT-0001

START_TESTCASE BA-CTSY-CIPC-MCGLT-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGLT-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetLifeTime
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetLifeTime
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetLifeTime0002L
END_TESTCASE BA-CTSY-CIPC-MCGLT-0002

START_TESTCASE BA-CTSY-CIPC-MCGLT-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCGLT-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetLifeTime with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetLifeTime with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetLifeTime0003L
END_TESTCASE BA-CTSY-CIPC-MCGLT-0003

START_TESTCASE BA-CTSY-CIPC-MCGLT-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGLT-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetLifeTime
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetLifeTime
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetLifeTime0004L
END_TESTCASE BA-CTSY-CIPC-MCGLT-0004

START_TESTCASE BA-CTSY-CIPC-MCGB-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGB-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::Get3GPBInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::Get3GPBInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGet3GPBInfo0001L
END_TESTCASE BA-CTSY-CIPC-MCGB-0001

START_TESTCASE BA-CTSY-CIPC-MCGSNM-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSNM-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetSystemNetworkModes
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetSystemNetworkModes
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSystemNetworkModes0001L
END_TESTCASE BA-CTSY-CIPC-MCGSNM-0001

START_TESTCASE BA-CTSY-CIPC-MCGSNM-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSNM-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetSystemNetworkModes
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetSystemNetworkModes
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSystemNetworkModes0002L
END_TESTCASE BA-CTSY-CIPC-MCGSNM-0002

START_TESTCASE BA-CTSY-CIPC-MCGSNM-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSNM-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetSystemNetworkModes
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetSystemNetworkModes
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSystemNetworkModes0004L
END_TESTCASE BA-CTSY-CIPC-MCGSNM-0004

START_TESTCASE BA-CTSY-CIPC-MCSSNM-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSNM-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SetSystemNetworkMode
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetSystemNetworkMode
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetSystemNetworkMode0001L
END_TESTCASE BA-CTSY-CIPC-MCSSNM-0001

START_TESTCASE BA-CTSY-CIPC-MCSSNM-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSNM-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::SetSystemNetworkMode
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::SetSystemNetworkMode
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetSystemNetworkMode0002L
END_TESTCASE BA-CTSY-CIPC-MCSSNM-0002

START_TESTCASE BA-CTSY-CIPC-MCSSNM-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSNM-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::SetSystemNetworkMode
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::SetSystemNetworkMode
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetSystemNetworkMode0004L
END_TESTCASE BA-CTSY-CIPC-MCSSNM-0004

START_TESTCASE BA-CTSY-CIPC-MCGCSNM-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCSNM-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetCurrentSystemNetworkModes
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetCurrentSystemNetworkModes
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCurrentSystemNetworkModes0001L
END_TESTCASE BA-CTSY-CIPC-MCGCSNM-0001

START_TESTCASE BA-CTSY-CIPC-MCGCSNM-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCSNM-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetCurrentSystemNetworkModes
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetCurrentSystemNetworkModes
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCurrentSystemNetworkModes0002L
END_TESTCASE BA-CTSY-CIPC-MCGCSNM-0002

START_TESTCASE BA-CTSY-CIPC-MCGCSNM-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCSNM-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetCurrentSystemNetworkModes
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetCurrentSystemNetworkModes
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCurrentSystemNetworkModes0004L
END_TESTCASE BA-CTSY-CIPC-MCGCSNM-0004

START_TESTCASE BA-CTSY-CIPC-MCPSON-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCPSON-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::PowerSimOn
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::PowerSimOn
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestPowerSimOn0001L
END_TESTCASE BA-CTSY-CIPC-MCPSON-0001

START_TESTCASE BA-CTSY-CIPC-MCPSON-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCPSON-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::PowerSimOn
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::PowerSimOn
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestPowerSimOn0002L
END_TESTCASE BA-CTSY-CIPC-MCPSON-0002

START_TESTCASE BA-CTSY-CIPC-MCPSON-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCPSON-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::PowerSimOn
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::PowerSimOn
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestPowerSimOn0004L
END_TESTCASE BA-CTSY-CIPC-MCPSON-0004

START_TESTCASE BA-CTSY-CIPC-MCPSOF-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCPSOF-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::PowerSimOff
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::PowerSimOff
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestPowerSimOff0001L
END_TESTCASE BA-CTSY-CIPC-MCPSOF-0001

START_TESTCASE BA-CTSY-CIPC-MCPSOF-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCPSOF-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::PowerSimOff
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::PowerSimOff
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestPowerSimOff0002L
END_TESTCASE BA-CTSY-CIPC-MCPSOF-0002

START_TESTCASE BA-CTSY-CIPC-MCPSOF-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCPSOF-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::PowerSimOff
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::PowerSimOff
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestPowerSimOff0004L
END_TESTCASE BA-CTSY-CIPC-MCPSOF-0004

START_TESTCASE BA-CTSY-CIPC-MCSWR-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSWR-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SimWarmReset
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SimWarmReset
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSimWarmReset0001L
END_TESTCASE BA-CTSY-CIPC-MCSWR-0001

START_TESTCASE BA-CTSY-CIPC-MCSWR-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCSWR-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::SimWarmReset
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::SimWarmReset
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSimWarmReset0002L
END_TESTCASE BA-CTSY-CIPC-MCSWR-0002

START_TESTCASE BA-CTSY-CIPC-MCSWR-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCSWR-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::SimWarmReset
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::SimWarmReset
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSimWarmReset0004L
END_TESTCASE BA-CTSY-CIPC-MCSWR-0004

START_TESTCASE BA-CTSY-CIPC-MCGATR-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGATR-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetATR
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetATR
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetATR0001L
END_TESTCASE BA-CTSY-CIPC-MCGATR-0001

START_TESTCASE BA-CTSY-CIPC-MCGATR-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGATR-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetATR
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetATR
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetATR0002L
END_TESTCASE BA-CTSY-CIPC-MCGATR-0002

START_TESTCASE BA-CTSY-CIPC-MCGATR-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCGATR-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetATR with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetATR with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetATR0003L
END_TESTCASE BA-CTSY-CIPC-MCGATR-0003

START_TESTCASE BA-CTSY-CIPC-MCGATR-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGATR-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetATR
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetATR
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetATR0004L
END_TESTCASE BA-CTSY-CIPC-MCGATR-0004

START_TESTCASE BA-CTSY-CIPC-MCGSCRS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSCRS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetSimCardReaderStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetSimCardReaderStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSimCardReaderStatus0001L
END_TESTCASE BA-CTSY-CIPC-MCGSCRS-0001

START_TESTCASE BA-CTSY-CIPC-MCGSCRS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSCRS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetSimCardReaderStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetSimCardReaderStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSimCardReaderStatus0002L
END_TESTCASE BA-CTSY-CIPC-MCGSCRS-0002

START_TESTCASE BA-CTSY-CIPC-MCGSCRS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSCRS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetSimCardReaderStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetSimCardReaderStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSimCardReaderStatus0004L
END_TESTCASE BA-CTSY-CIPC-MCGSCRS-0004

START_TESTCASE BA-CTSY-CIPC-MCNSCS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNSCS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifySimCardStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifySimCardStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifySimCardStatus0001L
END_TESTCASE BA-CTSY-CIPC-MCNSCS-0001

START_TESTCASE BA-CTSY-CIPC-MCNSCS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNSCS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifySimCardStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifySimCardStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifySimCardStatus0002L
END_TESTCASE BA-CTSY-CIPC-MCNSCS-0002

START_TESTCASE BA-CTSY-CIPC-MCNSCS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNSCS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifySimCardStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifySimCardStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifySimCardStatus0004L
END_TESTCASE BA-CTSY-CIPC-MCNSCS-0004

START_TESTCASE BA-CTSY-CIPC-MCGWSAD-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGWSAD-0001
//!@SYMComponent telephony_ctsy
//!@SYMPREQ PREQ1551
//!@SYMCR CR1596
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetWlanSimAuthenticationData
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetWlanSimAuthenticationData
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetWlanSimAuthenticationData0001L
END_TESTCASE BA-CTSY-CIPC-MCGWSAD-0001

START_TESTCASE BA-CTSY-CIPC-MCGWSAD-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGWSAD-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetWlanSimAuthenticationData
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetWlanSimAuthenticationData
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetWlanSimAuthenticationData0002L
END_TESTCASE BA-CTSY-CIPC-MCGWSAD-0002

START_TESTCASE BA-CTSY-CIPC-MCGWSAD-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCGWSAD-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetWlanSimAuthenticationData with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetWlanSimAuthenticationData with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetWlanSimAuthenticationData0003L
END_TESTCASE BA-CTSY-CIPC-MCGWSAD-0003

START_TESTCASE BA-CTSY-CIPC-MCGWSAD-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGWSAD-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetWlanSimAuthenticationData
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetWlanSimAuthenticationData
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetWlanSimAuthenticationData0004L
END_TESTCASE BA-CTSY-CIPC-MCGWSAD-0004


START_TESTCASE BA-CTSY-CIPC-MCSSMSR-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSMSR-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SetSimMessageStatusRead
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetSimMessageStatusRead
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetSimMessageStatusRead0001L
END_TESTCASE BA-CTSY-CIPC-MCSSMSR-0001

START_TESTCASE BA-CTSY-CIPC-MCWVHZUS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCWVHZUS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::WriteViagHomeZoneUHZIUESettings
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::WriteViagHomeZoneUHZIUESettings
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteViagHomeZoneUHZIUESettings0001L
END_TESTCASE BA-CTSY-CIPC-MCWVHZUS-0001

START_TESTCASE BA-CTSY-CIPC-MCWVHZUS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCWVHZUS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::WriteViagHomeZoneUHZIUESettings
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::WriteViagHomeZoneUHZIUESettings
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteViagHomeZoneUHZIUESettings0002L
END_TESTCASE BA-CTSY-CIPC-MCWVHZUS-0002

START_TESTCASE BA-CTSY-CIPC-MCWVHZUS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCWVHZUS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::WriteViagHomeZoneUHZIUESettings
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::WriteViagHomeZoneUHZIUESettings
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteViagHomeZoneUHZIUESettings0004L
END_TESTCASE BA-CTSY-CIPC-MCWVHZUS-0004

START_TESTCASE BA-CTSY-CIPC-MCSAO-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAO-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SetAlwaysOn
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetAlwaysOn
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetAlwaysOn0001L
END_TESTCASE BA-CTSY-CIPC-MCSAO-0001

START_TESTCASE BA-CTSY-CIPC-MCSAO-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAO-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::SetAlwaysOn
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::SetAlwaysOn
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetAlwaysOn0002L
END_TESTCASE BA-CTSY-CIPC-MCSAO-0002

START_TESTCASE BA-CTSY-CIPC-MCSAO-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAO-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SetAlwaysOn with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetAlwaysOn with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetAlwaysOn0003L
END_TESTCASE BA-CTSY-CIPC-MCSAO-0003

START_TESTCASE BA-CTSY-CIPC-MCSAO-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAO-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::SetAlwaysOn
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::SetAlwaysOn
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetAlwaysOn0004L
END_TESTCASE BA-CTSY-CIPC-MCSAO-0004

START_TESTCASE BA-CTSY-CIPC-MCNRE-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNRE-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyRauEvent
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyRauEvent
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyRauEvent0001L
END_TESTCASE BA-CTSY-CIPC-MCNRE-0001

START_TESTCASE BA-CTSY-CIPC-MCNRE-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNRE-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyRauEvent
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyRauEvent
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyRauEvent0002L
END_TESTCASE BA-CTSY-CIPC-MCNRE-0002

START_TESTCASE BA-CTSY-CIPC-MCNRE-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNRE-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyRauEvent
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyRauEvent
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyRauEvent0004L
END_TESTCASE BA-CTSY-CIPC-MCNRE-0004

START_TESTCASE BA-CTSY-CIPC-MCRHS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCRHS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadHSxPAStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadHSxPAStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadHSxPAStatus0001L
END_TESTCASE BA-CTSY-CIPC-MCRHS-0001

START_TESTCASE BA-CTSY-CIPC-MCRHS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCRHS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::ReadHSxPAStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::ReadHSxPAStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadHSxPAStatus0002L
END_TESTCASE BA-CTSY-CIPC-MCRHS-0002

START_TESTCASE BA-CTSY-CIPC-MCRHS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCRHS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::ReadHSxPAStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::ReadHSxPAStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadHSxPAStatus0004L
END_TESTCASE BA-CTSY-CIPC-MCRHS-0004

START_TESTCASE BA-CTSY-CIPC-MCWHS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCWHS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::WriteHSxPAStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::WriteHSxPAStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteHSxPAStatus0001L
END_TESTCASE BA-CTSY-CIPC-MCWHS-0001

START_TESTCASE BA-CTSY-CIPC-MCWHS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCWHS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::WriteHSxPAStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::WriteHSxPAStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteHSxPAStatus0002L
END_TESTCASE BA-CTSY-CIPC-MCWHS-0002

START_TESTCASE BA-CTSY-CIPC-MCWHS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCWHS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::WriteHSxPAStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::WriteHSxPAStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteHSxPAStatus0004L
END_TESTCASE BA-CTSY-CIPC-MCWHS-0004
 
START_TESTCASE BA-CTSY-CIPC-MCNHS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNHS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyHSxPAStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyHSxPAStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyHSxPAStatus0001L
END_TESTCASE BA-CTSY-CIPC-MCNHS-0001

START_TESTCASE BA-CTSY-CIPC-MCNHS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNHS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyHSxPAStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyHSxPAStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyHSxPAStatus0002L
END_TESTCASE BA-CTSY-CIPC-MCNHS-0002

START_TESTCASE BA-CTSY-CIPC-MCNHS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNHS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyHSxPAStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyHSxPAStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyHSxPAStatus0004L
END_TESTCASE BA-CTSY-CIPC-MCNHS-0004

START_TESTCASE BA-CTSY-CIPC-MCGICFIS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGICFIS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetIccCallForwardingIndicatorStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetIccCallForwardingIndicatorStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetIccCallForwardingIndicatorStatus0001L
END_TESTCASE BA-CTSY-CIPC-MCGICFIS-0001

START_TESTCASE BA-CTSY-CIPC-MCGICFIS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGICFIS-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetIccCallForwardingIndicatorStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetIccCallForwardingIndicatorStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetIccCallForwardingIndicatorStatus0002L
END_TESTCASE BA-CTSY-CIPC-MCGICFIS-0002

START_TESTCASE BA-CTSY-CIPC-MCGICFIS-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCGICFIS-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetIccCallForwardingIndicatorStatus with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetIccCallForwardingIndicatorStatus with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetIccCallForwardingIndicatorStatus0003L
END_TESTCASE BA-CTSY-CIPC-MCGICFIS-0003

START_TESTCASE BA-CTSY-CIPC-MCGICFIS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGICFIS-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetIccCallForwardingIndicatorStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetIccCallForwardingIndicatorStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetIccCallForwardingIndicatorStatus0004L
END_TESTCASE BA-CTSY-CIPC-MCGICFIS-0004

START_TESTCASE BA-CTSY-CIPC-MCNICFSC-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNICFSC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyIccCallForwardingStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyIccCallForwardingStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyIccCallForwardingStatusChange0001L
END_TESTCASE BA-CTSY-CIPC-MCNICFSC-0001

START_TESTCASE BA-CTSY-CIPC-MCNICFSC-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNICFSC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyIccCallForwardingStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyIccCallForwardingStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyIccCallForwardingStatusChange0002L
END_TESTCASE BA-CTSY-CIPC-MCNICFSC-0002

START_TESTCASE BA-CTSY-CIPC-MCNICFSC-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCNICFSC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyIccCallForwardingStatusChange with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyIccCallForwardingStatusChange with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyIccCallForwardingStatusChange0003L
END_TESTCASE BA-CTSY-CIPC-MCNICFSC-0003

START_TESTCASE BA-CTSY-CIPC-MCNICFSC-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNICFSC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyIccCallForwardingStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyIccCallForwardingStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyIccCallForwardingStatusChange0004L
END_TESTCASE BA-CTSY-CIPC-MCNICFSC-0004

START_TESTCASE BA-CTSY-CIPC-MCGCI2-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCI2-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetCellInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetCellInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCellInfo0001L
END_TESTCASE BA-CTSY-CIPC-MCGCI2-0001

START_TESTCASE BA-CTSY-CIPC-MCGCI2-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCI2-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetCellInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetCellInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCellInfo0002L
END_TESTCASE BA-CTSY-CIPC-MCGCI2-0002

START_TESTCASE BA-CTSY-CIPC-MCGCI2-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCI2-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetCellInfo with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetCellInfo with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCellInfo0003L
END_TESTCASE BA-CTSY-CIPC-MCGCI2-0003

START_TESTCASE BA-CTSY-CIPC-MCGCI2-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCI2-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetCellInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetCellInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCellInfo0004L
END_TESTCASE BA-CTSY-CIPC-MCGCI2-0004

START_TESTCASE BA-CTSY-CIPC-MCNCIC2-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCNCIC2-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyCellInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyCellInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyCellInfoChange0001L
END_TESTCASE BA-CTSY-CIPC-MCNCIC2-0001

START_TESTCASE BA-CTSY-CIPC-MCNCIC2-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCNCIC2-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::NotifyCellInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::NotifyCellInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyCellInfoChange0002L
END_TESTCASE BA-CTSY-CIPC-MCNCIC2-0002

START_TESTCASE BA-CTSY-CIPC-MCNCIC2-0003
//!@SYMTestCaseID BA-CTSY-CIPC-MCNCIC2-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NotifyCellInfoChange with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NotifyCellInfoChange with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyCellInfoChange0003L
END_TESTCASE BA-CTSY-CIPC-MCNCIC2-0003

START_TESTCASE BA-CTSY-CIPC-MCNCIC2-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCNCIC2-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::NotifyCellInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::NotifyCellInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNotifyCellInfoChange0004L
END_TESTCASE BA-CTSY-CIPC-MCNCIC2-0004

START_TESTCASE BA-CTSY-CIPC-MCGSNB-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSNB-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetSystemNetworkBand
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetSystemNetworkBand
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSystemNetworkBand0001L
END_TESTCASE BA-CTSY-CIPC-MCGSNB-0001

START_TESTCASE BA-CTSY-CIPC-MCGSNB-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSNB-0002
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::GetSystemNetworkBand
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::GetSystemNetworkBand
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSystemNetworkBand0002L
END_TESTCASE BA-CTSY-CIPC-MCGSNB-0002

START_TESTCASE BA-CTSY-CIPC-MCGSNB-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSNB-0004
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::GetSystemNetworkBand
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::GetSystemNetworkBand
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSystemNetworkBand0004L
END_TESTCASE BA-CTSY-CIPC-MCGSNB-0004

START_TESTCASE BA-CTSY-CIPC-MCSSNB-0001
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSNB-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SetSystemNetworkBand
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetSystemNetworkBand
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetSystemNetworkBand0001L
END_TESTCASE BA-CTSY-CIPC-MCSSNB-0001

START_TESTCASE BA-CTSY-CIPC-MCSSNB-0002
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSNB-0002
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMmCustomAPI::SetSystemNetworkBand
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMmCustomAPI::SetSystemNetworkBand
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetSystemNetworkBand0002L
END_TESTCASE BA-CTSY-CIPC-MCSSNB-0002

START_TESTCASE BA-CTSY-CIPC-MCSSNB-0004
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSNB-0004
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMmCustomAPI::SetSystemNetworkBand
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMmCustomAPI::SetSystemNetworkBand
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetSystemNetworkBand0004L
END_TESTCASE BA-CTSY-CIPC-MCSSNB-0004

START_TESTCASE BA-CTSY-CIPC-GUSS-0001
//!@SYMTestCaseID BA-CTSY-CIPC-GUSS-0001
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for getting USIM Service Support
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetUSIMServiceSupport
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetUSIMServiceSupport0001L
END_TESTCASE BA-CTSY-CIPC-GUSS-0001

START_TESTCASE BA-CTSY-CIPC-GUSS-0002
//!@SYMTestCaseID BA-CTSY-CIPC-GUSS-0002
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support for Cancel of getting USIM Service Support
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::Cancel for ECustomGetServiceTableSupportbyApplicationIPC
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetUSIMServiceSupport0002L
END_TESTCASE BA-CTSY-CIPC-GUSS-0002

START_TESTCASE BA-CTSY-CIPC-GUSS-0003
//!@SYMTestCaseID BA-CTSY-CIPC-GUSS-0003
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support for negative application numbers
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetUSIMServiceSupport
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetUSIMServiceSupport0003L
END_TESTCASE BA-CTSY-CIPC-GUSS-0003

START_TESTCASE BA-CTSY-CIPC-GUSS-0004
//!@SYMTestCaseID BA-CTSY-CIPC-GUSS-0004
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support for multiple client requests
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetUSIMServiceSupport
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetUSIMServiceSupport0004L
END_TESTCASE BA-CTSY-CIPC-GUSS-0004


RUN_SCRIPT z:\TestData\Scripts\mockltsy_remove_ini_file.script
