//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

RUN_SCRIPT z:\TestData\Scripts\mockltsy_copy_ini_file.script

LOAD_SUITE te_ctsy_component

START_TESTCASE BA-CTSY-IND-MGI-0001
//!@SYMTestCaseID BA-CTSY-IND-MGI-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetIndicator
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetIndicator
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyIndicatorFU.TestGetIndicator0001L
END_TESTCASE BA-CTSY-IND-MGI-0001

START_TESTCASE BA-CTSY-IND-MGI-0002
//!@SYMTestCaseID BA-CTSY-IND-MGI-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::GetIndicator
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::GetIndicator
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyIndicatorFU.TestGetIndicator0002L
END_TESTCASE BA-CTSY-IND-MGI-0002

START_TESTCASE BA-CTSY-IND-MGI-0004
//!@SYMTestCaseID BA-CTSY-IND-MGI-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetIndicator
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetIndicator
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyIndicatorFU.TestGetIndicator0004L
END_TESTCASE BA-CTSY-IND-MGI-0004

START_TESTCASE BA-CTSY-IND-MGIC-0001
//!@SYMTestCaseID BA-CTSY-IND-MGIC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetIndicatorCaps
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetIndicatorCaps
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyIndicatorFU.TestGetIndicatorCaps0001L
END_TESTCASE BA-CTSY-IND-MGIC-0001

START_TESTCASE BA-CTSY-IND-MNIC-0001
//!@SYMTestCaseID BA-CTSY-IND-MNIC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyIndicatorChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyIndicatorChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyIndicatorFU.TestNotifyIndicatorChange0001L
END_TESTCASE BA-CTSY-IND-MNIC-0001

START_TESTCASE BA-CTSY-IND-MNIC-0002
//!@SYMTestCaseID BA-CTSY-IND-MNIC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::NotifyIndicatorChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::NotifyIndicatorChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyIndicatorFU.TestNotifyIndicatorChange0002L
END_TESTCASE BA-CTSY-IND-MNIC-0002

START_TESTCASE BA-CTSY-IND-MNIC-0004
//!@SYMTestCaseID BA-CTSY-IND-MNIC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::NotifyIndicatorChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::NotifyIndicatorChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyIndicatorFU.TestNotifyIndicatorChange0004L
END_TESTCASE BA-CTSY-IND-MNIC-0004

RUN_SCRIPT z:\TestData\Scripts\mockltsy_remove_ini_file.script
