//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

RUN_SCRIPT z:\TestData\Scripts\mockltsy_copy_ini_file.script

LOAD_SUITE te_ctsy_component

START_TESTCASE BA-CTSY-PKTQ-PCAMA-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-PCAMA-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::AddMediaAuthorizationL
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::AddMediaAuthorizationL
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestAddMediaAuthorizationL0001L
END_TESTCASE BA-CTSY-PKTQ-PCAMA-0001

START_TESTCASE BA-CTSY-PKTQ-PCAMA-0002
//!@SYMTestCaseID BA-CTSY-PKTQ-PCAMA-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::AddMediaAuthorizationL
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::AddMediaAuthorizationL
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestAddMediaAuthorizationL0002L
END_TESTCASE BA-CTSY-PKTQ-PCAMA-0002

START_TESTCASE BA-CTSY-PKTQ-PCAMA-0004
//!@SYMTestCaseID BA-CTSY-PKTQ-PCAMA-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::AddMediaAuthorizationL
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::AddMediaAuthorizationL
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestAddMediaAuthorizationL0004L
END_TESTCASE BA-CTSY-PKTQ-PCAMA-0004

START_TESTCASE BA-CTSY-PKTQ-PCRMA-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-PCRMA-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::RemoveMediaAuthorization
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::RemoveMediaAuthorization
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestRemoveMediaAuthorization0001L
END_TESTCASE BA-CTSY-PKTQ-PCRMA-0001

START_TESTCASE BA-CTSY-PKTQ-PCRMA-0003
//!@SYMTestCaseID BA-CTSY-PKTQ-PCRMA-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::RemoveMediaAuthorization with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::RemoveMediaAuthorization with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestRemoveMediaAuthorization0003L
END_TESTCASE BA-CTSY-PKTQ-PCRMA-0003

START_TESTCASE BA-CTSY-PKTQ-PCRMA-0004
//!@SYMTestCaseID BA-CTSY-PKTQ-PCRMA-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::RemoveMediaAuthorization
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::RemoveMediaAuthorization
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestRemoveMediaAuthorization0004L
END_TESTCASE BA-CTSY-PKTQ-PCRMA-0004

START_TESTCASE BA-CTSY-PKTQ-QGPP-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-QGPP-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::GetProfileParameters
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::GetProfileParameters
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestGetProfileParameters0001L
END_TESTCASE BA-CTSY-PKTQ-QGPP-0001

START_TESTCASE BA-CTSY-PKTQ-QGPP-0003
//!@SYMTestCaseID BA-CTSY-PKTQ-QGPP-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::GetProfileParameters with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::GetProfileParameters with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestGetProfileParameters0003L
END_TESTCASE BA-CTSY-PKTQ-QGPP-0003

START_TESTCASE BA-CTSY-PKTQ-QGPP-0004
//!@SYMTestCaseID BA-CTSY-PKTQ-QGPP-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketQoS::GetProfileParameters
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketQoS::GetProfileParameters
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestGetProfileParameters0004L
END_TESTCASE BA-CTSY-PKTQ-QGPP-0004

START_TESTCASE BA-CTSY-PKTQ-QNPC-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-QNPC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::NotifyProfileChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::NotifyProfileChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestNotifyProfileChanged0001L
END_TESTCASE BA-CTSY-PKTQ-QNPC-0001

START_TESTCASE BA-CTSY-PKTQ-QNPC-0002
//!@SYMTestCaseID BA-CTSY-PKTQ-QNPC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketQoS::NotifyProfileChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketQoS::NotifyProfileChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestNotifyProfileChanged0002L
END_TESTCASE BA-CTSY-PKTQ-QNPC-0002

START_TESTCASE BA-CTSY-PKTQ-QNPC-0003
//!@SYMTestCaseID BA-CTSY-PKTQ-QNPC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::NotifyProfileChanged with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::NotifyProfileChanged with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestNotifyProfileChanged0003L
END_TESTCASE BA-CTSY-PKTQ-QNPC-0003

START_TESTCASE BA-CTSY-PKTQ-QNPC-0004
//!@SYMTestCaseID BA-CTSY-PKTQ-QNPC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketQoS::NotifyProfileChanged
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketQoS::NotifyProfileChanged
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestNotifyProfileChanged0004L
END_TESTCASE BA-CTSY-PKTQ-QNPC-0004

START_TESTCASE BA-CTSY-PKTQ-QSPP-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-QSPP-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::SetProfileParameters
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::SetProfileParameters
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestSetProfileParameters0001L
END_TESTCASE BA-CTSY-PKTQ-QSPP-0001

START_TESTCASE BA-CTSY-PKTQ-QSPP-0002
//!@SYMTestCaseID BA-CTSY-PKTQ-QSPP-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketQoS::SetProfileParameters
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketQoS::SetProfileParameters
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestSetProfileParameters0002L
END_TESTCASE BA-CTSY-PKTQ-QSPP-0002

START_TESTCASE BA-CTSY-PKTQ-QSPP-0003
//!@SYMTestCaseID BA-CTSY-PKTQ-QSPP-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::SetProfileParameters with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::SetProfileParameters with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestSetProfileParameters0003L
END_TESTCASE BA-CTSY-PKTQ-QSPP-0003

START_TESTCASE BA-CTSY-PKTQ-QSPP-0004
//!@SYMTestCaseID BA-CTSY-PKTQ-QSPP-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketQoS::SetProfileParameters
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketQoS::SetProfileParameters
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestSetProfileParameters0004L
END_TESTCASE BA-CTSY-PKTQ-QSPP-0004

START_TESTCASE BA-CTSY-PKTQ-QGPC-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-QGPC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::GetProfileCapabilities
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::GetProfileCapabilities
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestGetProfileCapabilities0001L
END_TESTCASE BA-CTSY-PKTQ-QGPC-0001

START_TESTCASE BA-CTSY-PKTQ-QGPC-0003
//!@SYMTestCaseID BA-CTSY-PKTQ-QGPC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::GetProfileCapabilities with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::GetProfileCapabilities with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestGetProfileCapabilities0003L
END_TESTCASE BA-CTSY-PKTQ-QGPC-0003

START_TESTCASE BA-CTSY-PKTQ-QGPC-0004
//!@SYMTestCaseID BA-CTSY-PKTQ-QGPC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketQoS::GetProfileCapabilities
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketQoS::GetProfileCapabilities
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestGetProfileCapabilities0004L
END_TESTCASE BA-CTSY-PKTQ-QGPC-0004

START_TESTCASE BA-CTSY-PKTQ-PCCNT-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-PCCNT-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::CreateNewTFT
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::CreateNewTFT
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestCreateNewTFT0001L
END_TESTCASE BA-CTSY-PKTQ-PCCNT-0001

START_TESTCASE BA-CTSY-PKTQ-PCAPF-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-PCAPF-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::AddPacketFilter
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::AddPacketFilter
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestAddPacketFilter0001L
END_TESTCASE BA-CTSY-PKTQ-PCAPF-0001

START_TESTCASE BA-CTSY-PKTQ-PCAPF-0002
//!@SYMTestCaseID BA-CTSY-PKTQ-PCAPF-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RPacketContext::AddPacketFilter
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RPacketContext::AddPacketFilter
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestAddPacketFilter0002L
END_TESTCASE BA-CTSY-PKTQ-PCAPF-0002

START_TESTCASE BA-CTSY-PKTQ-PCAPF-0003
//!@SYMTestCaseID BA-CTSY-PKTQ-PCAPF-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::AddPacketFilter with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::AddPacketFilter with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestAddPacketFilter0003L
END_TESTCASE BA-CTSY-PKTQ-PCAPF-0003

START_TESTCASE BA-CTSY-PKTQ-PCAPF-0004
//!@SYMTestCaseID BA-CTSY-PKTQ-PCAPF-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::AddPacketFilter
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::AddPacketFilter
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestAddPacketFilter0004L
END_TESTCASE BA-CTSY-PKTQ-PCAPF-0004

START_TESTCASE BA-CTSY-PKTQ-PCRPF-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-PCRPF-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::RemovePacketFilter
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::RemovePacketFilter
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestRemovePacketFilter0001L
END_TESTCASE BA-CTSY-PKTQ-PCRPF-0001

START_TESTCASE BA-CTSY-PKTQ-PCRPF-0003
//!@SYMTestCaseID BA-CTSY-PKTQ-PCRPF-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::RemovePacketFilter with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::RemovePacketFilter with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestRemovePacketFilter0003L
END_TESTCASE BA-CTSY-PKTQ-PCRPF-0003

START_TESTCASE BA-CTSY-PKTQ-PCGPFI-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-PCGPFI-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetPacketFilterInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetPacketFilterInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestGetPacketFilterInfo0001L
END_TESTCASE BA-CTSY-PKTQ-PCGPFI-0001

START_TESTCASE BA-CTSY-PKTQ-PCGPFI-0003
//!@SYMTestCaseID BA-CTSY-PKTQ-PCGPFI-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetPacketFilterInfo with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetPacketFilterInfo with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestGetPacketFilterInfo0003L
END_TESTCASE BA-CTSY-PKTQ-PCGPFI-0003

START_TESTCASE BA-CTSY-PKTQ-PCGPFI-0004
//!@SYMTestCaseID BA-CTSY-PKTQ-PCGPFI-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RPacketContext::GetPacketFilterInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RPacketContext::GetPacketFilterInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestGetPacketFilterInfo0004L
END_TESTCASE BA-CTSY-PKTQ-PCGPFI-0004

START_TESTCASE BA-CTSY-PKTQ-PCDT-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-PCDT-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::DeleteTFT
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::DeleteTFT
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestDeleteTFT0001L
END_TESTCASE BA-CTSY-PKTQ-PCDT-0001

START_TESTCASE BA-CTSY-PKTQ-QONQ-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-QONQ-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::OpenNewQoS
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::OpenNewQoS
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP !PanicCode=11 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestOpenNewQoS0001L
END_TESTCASE BA-CTSY-PKTQ-QONQ-0001

START_TESTCASE BA-CTSY-PKTQ-QONQ-0003
//!@SYMTestCaseID BA-CTSY-PKTQ-QONQ-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::OpenNewQoS with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::OpenNewQoS with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestOpenNewQoS0003L
END_TESTCASE BA-CTSY-PKTQ-QONQ-0003

START_TESTCASE BA-CTSY-PKTQ-QOEQ-0001
//!@SYMTestCaseID BA-CTSY-PKTQ-QOEQ-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::OpenExistingQoS
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::OpenExistingQoS
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestOpenExistingQoS0001L
END_TESTCASE BA-CTSY-PKTQ-QOEQ-0001

START_TESTCASE BA-CTSY-PKTQ-QOEQ-0003
//!@SYMTestCaseID BA-CTSY-PKTQ-QOEQ-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::OpenExistingQoS with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::OpenExistingQoS with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP !PanicCode=-28 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestOpenExistingQoS0003L
END_TESTCASE BA-CTSY-PKTQ-QOEQ-0003

START_TESTCASE BA-CTSY-PKTQ-QOEQ-0004
//!@SYMTestCaseID BA-CTSY-PKTQ-QOEQ-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::OpenExistingQoS with out of bounds parameters
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::OpenExistingQoS with out of bounds parameters
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestOpenExistingQoS0004L
END_TESTCASE BA-CTSY-PKTQ-QOEQ-0004

RUN_SCRIPT z:\TestData\Scripts\mockltsy_remove_ini_file.script
