//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

RUN_SCRIPT z:\TestData\Scripts\mockltsy_copy_ini_file.script

LOAD_SUITE te_ctsy_component



START_TESTCASE BA-CTSY-CALLI-CGCP-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CGCP-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCallParams for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCallParams for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallParams0001L
END_TESTCASE BA-CTSY-CALLI-CGCP-0001


START_TESTCASE BA-CTSY-CALLI-CGCP-0003
//!@SYMTestCaseID BA-CTSY-CALLI-CGCP-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCallParams with bad parameter data for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCallParams with bad parameter data for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallParams0003L
END_TESTCASE BA-CTSY-CALLI-CGCP-0003


START_TESTCASE BA-CTSY-CALLI-CGCP-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CGCP-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCallParams for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCallParams for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallParams0006L
END_TESTCASE BA-CTSY-CALLI-CGCP-0006

START_TESTCASE BA-CTSY-CALLI-CGCP-0006b
//!@SYMTestCaseID BA-CTSY-CALLI-CGCP-0006b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCallParams for data calls with HscsdCallParams. It is in connection to BA-CTSY-CALLI-CGCP-0006
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCallParams for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallParams0006bL
END_TESTCASE BA-CTSY-CALLI-CGCP-0006b

START_TESTCASE BA-CTSY-CALLI-CGCP-0006c
//!@SYMTestCaseID BA-CTSY-CALLI-CGCP-0006c
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCallParams for data calls with HscsdCallParamsV8. It is in connection to BA-CTSY-CALLI-CGCP-0006b
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCallParams for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallParams0006cL
END_TESTCASE BA-CTSY-CALLI-CGCP-0006c

START_TESTCASE BA-CTSY-CALLI-CGCP-0008
//!@SYMTestCaseID BA-CTSY-CALLI-CGCP-0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCallParams with bad parameters data for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCallParams with bad parameters for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallParams0008L
END_TESTCASE BA-CTSY-CALLI-CGCP-0008

START_TESTCASE BA-CTSY-CALLI-CGCP-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CGCP-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCallParams for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCallParams for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallParams00011L
END_TESTCASE BA-CTSY-CALLI-CGCP-00011

START_TESTCASE BA-CTSY-CALLI-CGCD-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CGCD-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCallDuration for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCallDuration for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallDuration0001L
END_TESTCASE BA-CTSY-CALLI-CGCD-0001

START_TESTCASE BA-CTSY-CALLI-CGCD-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CGCD-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCallDuration for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCallDuration for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallDuration0006L
END_TESTCASE BA-CTSY-CALLI-CGCD-0006

START_TESTCASE BA-CTSY-CALLI-CGCD-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CGCD-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCallDuration for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCallDuration for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallDuration00011L
END_TESTCASE BA-CTSY-CALLI-CGCD-00011

START_TESTCASE BA-CTSY-CALLI-CGOS-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CGOS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetOwnershipStatus for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetOwnershipStatus for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetOwnershipStatus0001L
END_TESTCASE BA-CTSY-CALLI-CGOS-0001

START_TESTCASE BA-CTSY-CALLI-CGOS-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CGOS-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetOwnershipStatus for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetOwnershipStatus for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetOwnershipStatus0006L
END_TESTCASE BA-CTSY-CALLI-CGOS-0006

START_TESTCASE BA-CTSY-CALLI-CGOS-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CGOS-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetOwnershipStatus for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetOwnershipStatus for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetOwnershipStatus00011L
END_TESTCASE BA-CTSY-CALLI-CGOS-00011

START_TESTCASE BA-CTSY-CALLI-CGC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CGC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCaps for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCaps for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCaps0001L
END_TESTCASE BA-CTSY-CALLI-CGC-0001

START_TESTCASE BA-CTSY-CALLI-CGC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CGC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCaps for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCaps for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCaps0006L
END_TESTCASE BA-CTSY-CALLI-CGC-0006

START_TESTCASE BA-CTSY-CALLI-CGC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CGC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetCaps for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetCaps for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCaps00011L
END_TESTCASE BA-CTSY-CALLI-CGC-00011

START_TESTCASE BA-CTSY-CALLI-CGI-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CGI-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetInfo for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetInfo for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetInfo0001L
END_TESTCASE BA-CTSY-CALLI-CGI-0001

START_TESTCASE BA-CTSY-CALLI-CGI-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CGI-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetInfo for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetInfo for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetInfo0006L
END_TESTCASE BA-CTSY-CALLI-CGI-0006

START_TESTCASE BA-CTSY-CALLI-CGI-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CGI-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetInfo for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetInfo for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetInfo00011L
END_TESTCASE BA-CTSY-CALLI-CGI-00011

START_TESTCASE BA-CTSY-CALLI-CGS-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CGS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetStatus for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetStatus for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetStatus0001L
END_TESTCASE BA-CTSY-CALLI-CGS-0001

START_TESTCASE BA-CTSY-CALLI-CGS-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CGS-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetStatus for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetStatus for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetStatus0006L
END_TESTCASE BA-CTSY-CALLI-CGS-0006

START_TESTCASE BA-CTSY-CALLI-CGS-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CGS-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::GetStatus for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::GetStatus for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetStatus00011L
END_TESTCASE BA-CTSY-CALLI-CGS-00011

START_TESTCASE BA-CTSY-CALLI-LGCI-0001
//!@SYMTestCaseID BA-CTSY-CALLI-LGCI-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::GetCallInfo for voice lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::GetCallInfo for voice lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallInfo0001L
END_TESTCASE BA-CTSY-CALLI-LGCI-0001

START_TESTCASE BA-CTSY-CALLI-LGCI-0003
//!@SYMTestCaseID BA-CTSY-CALLI-LGCI-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::GetCallInfo with bad parameter data for voice lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::GetCallInfo with bad parameter data for voice lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallInfo0003L
END_TESTCASE BA-CTSY-CALLI-LGCI-0003

START_TESTCASE BA-CTSY-CALLI-LGCI-0006
//!@SYMTestCaseID BA-CTSY-CALLI-LGCI-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::GetCallInfo for data lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::GetCallInfo for data lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallInfo0006L
END_TESTCASE BA-CTSY-CALLI-LGCI-0006

START_TESTCASE BA-CTSY-CALLI-LGCI-0008
//!@SYMTestCaseID BA-CTSY-CALLI-LGCI-0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::GetCallInfo with bad parameter data for data lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::GetCallInfo with bad parameter data for data lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallInfo0008L
END_TESTCASE BA-CTSY-CALLI-LGCI-0008

START_TESTCASE BA-CTSY-CALLI-LGCI-00011
//!@SYMTestCaseID BA-CTSY-CALLI-LGCI-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::GetCallInfo for fax lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::GetCallInfo for fax lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallInfo00011L
END_TESTCASE BA-CTSY-CALLI-LGCI-00011

START_TESTCASE BA-CTSY-CALLI-LGCI-00013
//!@SYMTestCaseID BA-CTSY-CALLI-LGCI-00013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::GetCallInfo with bad parameter data for fax lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::GetCallInfo with bad parameter data for fax lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetCallInfo00013L
END_TESTCASE BA-CTSY-CALLI-LGCI-00013

START_TESTCASE BA-CTSY-CALLI-LEC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-LEC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::EnumerateCall for voice lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::EnumerateCall for voice lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestEnumerateCall0001L
END_TESTCASE BA-CTSY-CALLI-LEC-0001

START_TESTCASE BA-CTSY-CALLI-LEC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-LEC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::EnumerateCall for data lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::EnumerateCall for data lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestEnumerateCall0006L
END_TESTCASE BA-CTSY-CALLI-LEC-0006

START_TESTCASE BA-CTSY-CALLI-LEC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-LEC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::EnumerateCall for fax lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::EnumerateCall for fax lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestEnumerateCall00011L
END_TESTCASE BA-CTSY-CALLI-LEC-00011

START_TESTCASE BA-CTSY-CALLI-CNCC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CNCC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyCapsChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyCapsChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCapsChange0001L
END_TESTCASE BA-CTSY-CALLI-CNCC-0001

START_TESTCASE BA-CTSY-CALLI-CNCC-0002
//!@SYMTestCaseID BA-CTSY-CALLI-CNCC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RCall::NotifyCapsChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RCall::NotifyCapsChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCapsChange0002L
END_TESTCASE BA-CTSY-CALLI-CNCC-0002

START_TESTCASE BA-CTSY-CALLI-CNCC-0004
//!@SYMTestCaseID BA-CTSY-CALLI-CNCC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RCall::NotifyCapsChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RCall::NotifyCapsChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCapsChange0004L
END_TESTCASE BA-CTSY-CALLI-CNCC-0004

START_TESTCASE BA-CTSY-CALLI-CNCC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CNCC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyCapsChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyCapsChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCapsChange0006L
END_TESTCASE BA-CTSY-CALLI-CNCC-0006

START_TESTCASE BA-CTSY-CALLI-CNCC-0007
//!@SYMTestCaseID BA-CTSY-CALLI-CNCC-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RCall::NotifyCapsChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RCall::NotifyCapsChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCapsChange0007L
END_TESTCASE BA-CTSY-CALLI-CNCC-0007

START_TESTCASE BA-CTSY-CALLI-CNCC-0009
//!@SYMTestCaseID BA-CTSY-CALLI-CNCC-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RCall::NotifyCapsChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RCall::NotifyCapsChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCapsChange0009L
END_TESTCASE BA-CTSY-CALLI-CNCC-0009

START_TESTCASE BA-CTSY-CALLI-CNCC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CNCC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyCapsChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyCapsChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCapsChange00011L
END_TESTCASE BA-CTSY-CALLI-CNCC-00011

START_TESTCASE BA-CTSY-CALLI-CNCC-00012
//!@SYMTestCaseID BA-CTSY-CALLI-CNCC-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RCall::NotifyCapsChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RCall::NotifyCapsChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCapsChange00012L
END_TESTCASE BA-CTSY-CALLI-CNCC-00012

START_TESTCASE BA-CTSY-CALLI-CNCC-00014
//!@SYMTestCaseID BA-CTSY-CALLI-CNCC-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RCall::NotifyCapsChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RCall::NotifyCapsChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCapsChange00014L
END_TESTCASE BA-CTSY-CALLI-CNCC-00014


START_TESTCASE BA-CTSY-CALLI-CNHCC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CNHCC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyHookChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyHookChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyHookChange0001L
END_TESTCASE BA-CTSY-CALLI-CNHCC-0001

START_TESTCASE BA-CTSY-CALLI-CNHCC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CNHCC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyHookChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyHookChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyHookChange0006L
END_TESTCASE BA-CTSY-CALLI-CNHCC-0006

START_TESTCASE BA-CTSY-CALLI-CNHCC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CNHCC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyHookChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyHookChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyHookChange00011L
END_TESTCASE BA-CTSY-CALLI-CNHCC-00011

START_TESTCASE BA-CTSY-CALLI-CNSC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CNSC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyStatusChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyStatusChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyStatusChange0001L
END_TESTCASE BA-CTSY-CALLI-CNSC-0001

START_TESTCASE BA-CTSY-CALLI-CNSC-0002
//!@SYMTestCaseID BA-CTSY-CALLI-CNSC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RCall::NotifyStatusChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RCall::NotifyStatusChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyStatusChange0002L
END_TESTCASE BA-CTSY-CALLI-CNSC-0002

START_TESTCASE BA-CTSY-CALLI-CNSC-0004
//!@SYMTestCaseID BA-CTSY-CALLI-CNSC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RCall::NotifyStatusChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RCall::NotifyStatusChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyStatusChange0004L
END_TESTCASE BA-CTSY-CALLI-CNSC-0004

START_TESTCASE BA-CTSY-CALLI-CNSC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CNSC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyStatusChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyStatusChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyStatusChange0006L
END_TESTCASE BA-CTSY-CALLI-CNSC-0006

START_TESTCASE BA-CTSY-CALLI-CNSC-0007
//!@SYMTestCaseID BA-CTSY-CALLI-CNSC-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RCall::NotifyStatusChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RCall::NotifyStatusChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyStatusChange0007L
END_TESTCASE BA-CTSY-CALLI-CNSC-0007

START_TESTCASE BA-CTSY-CALLI-CNSC-0009
//!@SYMTestCaseID BA-CTSY-CALLI-CNSC-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RCall::NotifyStatusChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RCall::NotifyStatusChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyStatusChange0009L
END_TESTCASE BA-CTSY-CALLI-CNSC-0009

START_TESTCASE BA-CTSY-CALLI-CNSC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CNSC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyStatusChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyStatusChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyStatusChange00011L
END_TESTCASE BA-CTSY-CALLI-CNSC-00011

START_TESTCASE BA-CTSY-CALLI-CNSC-00012
//!@SYMTestCaseID BA-CTSY-CALLI-CNSC-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RCall::NotifyStatusChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RCall::NotifyStatusChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyStatusChange00012L
END_TESTCASE BA-CTSY-CALLI-CNSC-00012

START_TESTCASE BA-CTSY-CALLI-CNSC-00014
//!@SYMTestCaseID BA-CTSY-CALLI-CNSC-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RCall::NotifyStatusChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RCall::NotifyStatusChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyStatusChange00014L
END_TESTCASE BA-CTSY-CALLI-CNSC-00014


START_TESTCASE BA-CTSY-CALLI-CNCDCC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CNCDCC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyCallDurationChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyCallDurationChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallDurationChange0001L
END_TESTCASE BA-CTSY-CALLI-CNCDCC-0001

START_TESTCASE BA-CTSY-CALLI-CNCDCC-0002
//!@SYMTestCaseID BA-CTSY-CALLI-CNCDCC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RCall::NotifyCallDurationChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RCall::NotifyCallDurationChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallDurationChange0002L
END_TESTCASE BA-CTSY-CALLI-CNCDCC-0002

START_TESTCASE BA-CTSY-CALLI-CNCDCC-0004
//!@SYMTestCaseID BA-CTSY-CALLI-CNCDCC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RCall::NotifyCallDurationChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RCall::NotifyCallDurationChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallDurationChange0004L
END_TESTCASE BA-CTSY-CALLI-CNCDCC-0004

START_TESTCASE BA-CTSY-CALLI-CNCDCC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CNCDCC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyCallDurationChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyCallDurationChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallDurationChange0006L
END_TESTCASE BA-CTSY-CALLI-CNCDCC-0006

START_TESTCASE BA-CTSY-CALLI-CNCDCC-0007
//!@SYMTestCaseID BA-CTSY-CALLI-CNCDCC-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RCall::NotifyCallDurationChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RCall::NotifyCallDurationChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallDurationChange0007L
END_TESTCASE BA-CTSY-CALLI-CNCDCC-0007

START_TESTCASE BA-CTSY-CALLI-CNCDCC-0009
//!@SYMTestCaseID BA-CTSY-CALLI-CNCDCC-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RCall::NotifyCallDurationChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RCall::NotifyCallDurationChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallDurationChange0009L
END_TESTCASE BA-CTSY-CALLI-CNCDCC-0009

START_TESTCASE BA-CTSY-CALLI-CNCDCC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CNCDCC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::NotifyCallDurationChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyCallDurationChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallDurationChange00011L
END_TESTCASE BA-CTSY-CALLI-CNCDCC-00011

START_TESTCASE BA-CTSY-CALLI-CNCDCC-00012
//!@SYMTestCaseID BA-CTSY-CALLI-CNCDCC-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RCall::NotifyCallDurationChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RCall::NotifyCallDurationChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallDurationChange00012L
END_TESTCASE BA-CTSY-CALLI-CNCDCC-00012

START_TESTCASE BA-CTSY-CALLI-CNCDCC-00014
//!@SYMTestCaseID BA-CTSY-CALLI-CNCDCC-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RCall::NotifyCallDurationChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RCall::NotifyCallDurationChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallDurationChange00014L
END_TESTCASE BA-CTSY-CALLI-CNCDCC-00014



START_TESTCASE BA-CTSY-CALLI-LNCA-0001
//!@SYMTestCaseID BA-CTSY-CALLI-LNCA-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::NotifyCallAdded for voice lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::NotifyCallAdded for voice lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallAdded0001L
END_TESTCASE BA-CTSY-CALLI-LNCA-0001

START_TESTCASE BA-CTSY-CALLI-LNCA-0002
//!@SYMTestCaseID BA-CTSY-CALLI-LNCA-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RLine::NotifyCallAdded for voice lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RLine::NotifyCallAdded for voice lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallAdded0002L
END_TESTCASE BA-CTSY-CALLI-LNCA-0002

START_TESTCASE BA-CTSY-CALLI-LNCA-0004
//!@SYMTestCaseID BA-CTSY-CALLI-LNCA-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RLine::NotifyCallAdded for voice lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RLine::NotifyCallAdded for voice lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallAdded0004L
END_TESTCASE BA-CTSY-CALLI-LNCA-0004

START_TESTCASE BA-CTSY-CALLI-LNCA-0006
//!@SYMTestCaseID BA-CTSY-CALLI-LNCA-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::NotifyCallAdded for data lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::NotifyCallAdded for data lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallAdded0006L
END_TESTCASE BA-CTSY-CALLI-LNCA-0006

START_TESTCASE BA-CTSY-CALLI-LNCA-0007
//!@SYMTestCaseID BA-CTSY-CALLI-LNCA-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RLine::NotifyCallAdded for data lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RLine::NotifyCallAdded for data lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallAdded0007L
END_TESTCASE BA-CTSY-CALLI-LNCA-0007

START_TESTCASE BA-CTSY-CALLI-LNCA-0009
//!@SYMTestCaseID BA-CTSY-CALLI-LNCA-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RLine::NotifyCallAdded for data lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RLine::NotifyCallAdded for data lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallAdded0009L
END_TESTCASE BA-CTSY-CALLI-LNCA-0009

START_TESTCASE BA-CTSY-CALLI-LNCA-00011
//!@SYMTestCaseID BA-CTSY-CALLI-LNCA-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::NotifyCallAdded for fax lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::NotifyCallAdded for fax lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallAdded00011L
END_TESTCASE BA-CTSY-CALLI-LNCA-00011

START_TESTCASE BA-CTSY-CALLI-LNCA-00012
//!@SYMTestCaseID BA-CTSY-CALLI-LNCA-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RLine::NotifyCallAdded for fax lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RLine::NotifyCallAdded for fax lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallAdded00012L
END_TESTCASE BA-CTSY-CALLI-LNCA-00012

START_TESTCASE BA-CTSY-CALLI-LNCA-00014
//!@SYMTestCaseID BA-CTSY-CALLI-LNCA-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RLine::NotifyCallAdded for fax lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RLine::NotifyCallAdded for fax lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallAdded00014L
END_TESTCASE BA-CTSY-CALLI-LNCA-00014



START_TESTCASE BA-CTSY-CALLI-LNIC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-LNIC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::NotifyIncomingCall for voice lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::NotifyIncomingCall for voice lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyIncomingCall0001L
END_TESTCASE BA-CTSY-CALLI-LNIC-0001

START_TESTCASE BA-CTSY-CALLI-LNIC-0002
//!@SYMTestCaseID BA-CTSY-CALLI-LNIC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RLine::NotifyIncomingCall for voice lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RLine::NotifyIncomingCall for voice lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyIncomingCall0002L
END_TESTCASE BA-CTSY-CALLI-LNIC-0002

START_TESTCASE BA-CTSY-CALLI-LNIC-0004
//!@SYMTestCaseID BA-CTSY-CALLI-LNIC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RLine::NotifyIncomingCall for voice lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RLine::NotifyIncomingCall for voice lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyIncomingCall0004L
END_TESTCASE BA-CTSY-CALLI-LNIC-0004

START_TESTCASE BA-CTSY-CALLI-LNIC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-LNIC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::NotifyIncomingCall for data lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::NotifyIncomingCall for data lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyIncomingCall0006L
END_TESTCASE BA-CTSY-CALLI-LNIC-0006

START_TESTCASE BA-CTSY-CALLI-LNIC-0007
//!@SYMTestCaseID BA-CTSY-CALLI-LNIC-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RLine::NotifyIncomingCall for data lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RLine::NotifyIncomingCall for data lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyIncomingCall0007L
END_TESTCASE BA-CTSY-CALLI-LNIC-0007

START_TESTCASE BA-CTSY-CALLI-LNIC-0009
//!@SYMTestCaseID BA-CTSY-CALLI-LNIC-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RLine::NotifyIncomingCall for data lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RLine::NotifyIncomingCall for data lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyIncomingCall0009L
END_TESTCASE BA-CTSY-CALLI-LNIC-0009

START_TESTCASE BA-CTSY-CALLI-LNIC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-LNIC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::NotifyIncomingCall for fax lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::NotifyIncomingCall for fax lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyIncomingCall00011L
END_TESTCASE BA-CTSY-CALLI-LNIC-00011

START_TESTCASE BA-CTSY-CALLI-LNIC-00012
//!@SYMTestCaseID BA-CTSY-CALLI-LNIC-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RLine::NotifyIncomingCall for fax lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RLine::NotifyIncomingCall for fax lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyIncomingCall00012L
END_TESTCASE BA-CTSY-CALLI-LNIC-00012

START_TESTCASE BA-CTSY-CALLI-LNIC-00014
//!@SYMTestCaseID BA-CTSY-CALLI-LNIC-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RLine::NotifyIncomingCall for fax lines
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RLine::NotifyIncomingCall for fax lines
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyIncomingCall00014L
END_TESTCASE BA-CTSY-CALLI-LNIC-00014

START_TESTCASE BA-CTSY-CALLI-CNCE-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CNCE-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyCallEvent for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyCallEvent for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallEvent0001L
END_TESTCASE BA-CTSY-CALLI-CNCE-0001

START_TESTCASE BA-CTSY-CALLI-CNCE-0002
//!@SYMTestCaseID BA-CTSY-CALLI-CNCE-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyCallEvent for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyCallEvent for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallEvent0002L
END_TESTCASE BA-CTSY-CALLI-CNCE-0002

START_TESTCASE BA-CTSY-CALLI-CNCE-0004
//!@SYMTestCaseID BA-CTSY-CALLI-CNCE-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyCallEvent for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyCallEvent for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallEvent0004L
END_TESTCASE BA-CTSY-CALLI-CNCE-0004

START_TESTCASE BA-CTSY-CALLI-CNCE-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CNCE-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyCallEvent for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyCallEvent for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallEvent0006L
END_TESTCASE BA-CTSY-CALLI-CNCE-0006

START_TESTCASE BA-CTSY-CALLI-CNCE-0007
//!@SYMTestCaseID BA-CTSY-CALLI-CNCE-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyCallEvent for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyCallEvent for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallEvent0007L
END_TESTCASE BA-CTSY-CALLI-CNCE-0007

START_TESTCASE BA-CTSY-CALLI-CNCE-0009
//!@SYMTestCaseID BA-CTSY-CALLI-CNCE-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyCallEvent for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyCallEvent for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallEvent0009L
END_TESTCASE BA-CTSY-CALLI-CNCE-0009

START_TESTCASE BA-CTSY-CALLI-CNCE-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CNCE-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyCallEvent for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyCallEvent for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallEvent00011L
END_TESTCASE BA-CTSY-CALLI-CNCE-00011

START_TESTCASE BA-CTSY-CALLI-CNCE-00012
//!@SYMTestCaseID BA-CTSY-CALLI-CNCE-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyCallEvent for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyCallEvent for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallEvent00012L
END_TESTCASE BA-CTSY-CALLI-CNCE-00012

START_TESTCASE BA-CTSY-CALLI-CNCE-00014
//!@SYMTestCaseID BA-CTSY-CALLI-CNCE-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyCallEvent for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyCallEvent for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyCallEvent00014L
END_TESTCASE BA-CTSY-CALLI-CNCE-00014


START_TESTCASE BA-CTSY-CALLI-CGMCC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallCaps for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallCaps for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallCaps0001L
END_TESTCASE BA-CTSY-CALLI-CGMCC-0001

START_TESTCASE BA-CTSY-CALLI-CGMCC-0003
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallCaps with bad parameter data for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallCaps with bad parameter data for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallCaps0003L
END_TESTCASE BA-CTSY-CALLI-CGMCC-0003

START_TESTCASE BA-CTSY-CALLI-CGMCC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallCaps for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallCaps for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallCaps0006L
END_TESTCASE BA-CTSY-CALLI-CGMCC-0006

START_TESTCASE BA-CTSY-CALLI-CGMCC-0008
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCC-0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallCaps with bad parameter data for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallCaps with bad parameter data for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallCaps0008L
END_TESTCASE BA-CTSY-CALLI-CGMCC-0008

START_TESTCASE BA-CTSY-CALLI-CGMCC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallCaps for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallCaps for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallCaps00011L
END_TESTCASE BA-CTSY-CALLI-CGMCC-00011

START_TESTCASE BA-CTSY-CALLI-CGMCC-00013
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCC-00013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallCaps with bad parameter data for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallCaps with bad parameter data for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallCaps00013L
END_TESTCASE BA-CTSY-CALLI-CGMCC-00013

START_TESTCASE BA-CTSY-CALLI-CGMCI-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCI-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallInfo for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallInfo for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallInfo0001L
END_TESTCASE BA-CTSY-CALLI-CGMCI-0001

START_TESTCASE BA-CTSY-CALLI-CGMCI-0003
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCI-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallInfo with bad parameter data for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallInfo with bad parameter data for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallInfo0003L
END_TESTCASE BA-CTSY-CALLI-CGMCI-0003

START_TESTCASE BA-CTSY-CALLI-CGMCI-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCI-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallInfo for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallInfo for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallInfo0006L
END_TESTCASE BA-CTSY-CALLI-CGMCI-0006

START_TESTCASE BA-CTSY-CALLI-CGMCI-0006b
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCI-0006b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallInfo for data calls with MobileCallInfoV8. It is in connection to BA-CTSY-CALLI-CGMCI-0006.
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallInfo for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallInfo0006bL
END_TESTCASE BA-CTSY-CALLI-CGMCI-0006b

START_TESTCASE BA-CTSY-CALLI-CGMCI-0008
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCI-0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallInfo with bad parameter data for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallInfo with bad parameter data for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallInfo0008L
END_TESTCASE BA-CTSY-CALLI-CGMCI-0008

START_TESTCASE BA-CTSY-CALLI-CGMCI-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCI-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallInfo for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallInfo for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallInfo00011L
END_TESTCASE BA-CTSY-CALLI-CGMCI-00011

START_TESTCASE BA-CTSY-CALLI-CGMCI-00013
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCI-00013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallInfo with bad parameter data for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallInfo with bad parameter data for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallInfo00013L
END_TESTCASE BA-CTSY-CALLI-CGMCI-00013

START_TESTCASE BA-CTSY-CALLI-CGMCS-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCS-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallStatus for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallStatus for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallStatus0001L
END_TESTCASE BA-CTSY-CALLI-CGMCS-0001

START_TESTCASE BA-CTSY-CALLI-CGMCS-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCS-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallStatus for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallStatus for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallStatus0006L
END_TESTCASE BA-CTSY-CALLI-CGMCS-0006

START_TESTCASE BA-CTSY-CALLI-CGMCS-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CGMCS-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GetMobileCallStatus for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GetMobileCallStatus for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetMobileCallStatus00011L
END_TESTCASE BA-CTSY-CALLI-CGMCS-00011

START_TESTCASE BA-CTSY-CALLI-CNATE-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CNATE-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyAudioToneEvent for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyAudioToneEvent for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyAudioToneEvent0001L
END_TESTCASE BA-CTSY-CALLI-CNATE-0001

START_TESTCASE BA-CTSY-CALLI-CNATE-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CNATE-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyAudioToneEvent for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyAudioToneEvent for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyAudioToneEvent0006L
END_TESTCASE BA-CTSY-CALLI-CNATE-0006

START_TESTCASE BA-CTSY-CALLI-CNATE-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CNATE-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyAudioToneEvent for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyAudioToneEvent for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyAudioToneEvent00011L
END_TESTCASE BA-CTSY-CALLI-CNATE-00011

START_TESTCASE BA-CTSY-CALLI-CNMCCC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyMobileCallCapsChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyMobileCallCapsChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange0001L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-0001

START_TESTCASE BA-CTSY-CALLI-CNMCCC-0002
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyMobileCallCapsChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyMobileCallCapsChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange0002L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-0002

START_TESTCASE BA-CTSY-CALLI-CNMCCC-0003
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyMobileCallCapsChange with bad parameter data for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyMobileCallCapsChange with bad parameter data for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange0003L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-0003

START_TESTCASE BA-CTSY-CALLI-CNMCCC-0004
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyMobileCallCapsChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyMobileCallCapsChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange0004L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-0004

START_TESTCASE BA-CTSY-CALLI-CNMCCC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyMobileCallCapsChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyMobileCallCapsChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange0006L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-0006

START_TESTCASE BA-CTSY-CALLI-CNMCCC-0007
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyMobileCallCapsChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyMobileCallCapsChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange0007L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-0007

START_TESTCASE BA-CTSY-CALLI-CNMCCC-0008
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyMobileCallCapsChange with bad parameter data for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyMobileCallCapsChange with bad parameter data for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange0008L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-0008

START_TESTCASE BA-CTSY-CALLI-CNMCCC-0009
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyMobileCallCapsChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyMobileCallCapsChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange0009L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-0009

START_TESTCASE BA-CTSY-CALLI-CNMCCC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyMobileCallCapsChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyMobileCallCapsChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange00011L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-00011

START_TESTCASE BA-CTSY-CALLI-CNMCCC-00012
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyMobileCallCapsChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyMobileCallCapsChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange00012L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-00012

START_TESTCASE BA-CTSY-CALLI-CNMCCC-00013
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-00013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyMobileCallCapsChange with bad parameter data for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyMobileCallCapsChange with bad parameter data for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange00013L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-00013

START_TESTCASE BA-CTSY-CALLI-CNMCCC-00014
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCCC-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyMobileCallCapsChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyMobileCallCapsChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallCapsChange00014L
END_TESTCASE BA-CTSY-CALLI-CNMCCC-00014


START_TESTCASE BA-CTSY-CALLI-CNRPIC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyRemotePartyInfoChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyRemotePartyInfoChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange0001L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-0001

START_TESTCASE BA-CTSY-CALLI-CNRPIC-0002
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyRemotePartyInfoChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyRemotePartyInfoChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange0002L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-0002

START_TESTCASE BA-CTSY-CALLI-CNRPIC-0003
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-0003
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyRemotePartyInfoChange with bad parameter data for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyRemotePartyInfoChange with bad parameter data for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange0003L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-0003

START_TESTCASE BA-CTSY-CALLI-CNRPIC-0004
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyRemotePartyInfoChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyRemotePartyInfoChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange0004L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-0004

START_TESTCASE BA-CTSY-CALLI-CNRPIC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyRemotePartyInfoChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyRemotePartyInfoChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange0006L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-0006

START_TESTCASE BA-CTSY-CALLI-CNRPIC-0007
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyRemotePartyInfoChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyRemotePartyInfoChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange0007L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-0007

START_TESTCASE BA-CTSY-CALLI-CNRPIC-0008
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-0008
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyRemotePartyInfoChange with bad parameter data for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyRemotePartyInfoChange with bad parameter data for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange0008L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-0008

START_TESTCASE BA-CTSY-CALLI-CNRPIC-0009
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyRemotePartyInfoChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyRemotePartyInfoChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange0009L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-0009

START_TESTCASE BA-CTSY-CALLI-CNRPIC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyRemotePartyInfoChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyRemotePartyInfoChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange00011L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-00011

START_TESTCASE BA-CTSY-CALLI-CNRPIC-00012
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyRemotePartyInfoChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyRemotePartyInfoChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange00012L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-00012

START_TESTCASE BA-CTSY-CALLI-CNRPIC-00013
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-00013
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyRemotePartyInfoChange with bad parameter data for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyRemotePartyInfoChange with bad parameter data for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange00013L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-00013

START_TESTCASE BA-CTSY-CALLI-CNRPIC-00014
//!@SYMTestCaseID BA-CTSY-CALLI-CNRPIC-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyRemotePartyInfoChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyRemotePartyInfoChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyRemotePartyInfoChange00014L
END_TESTCASE BA-CTSY-CALLI-CNRPIC-00014

START_TESTCASE BA-CTSY-CALLI-CNMCSC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCSC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyMobileCallStatusChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyMobileCallStatusChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallStatusChange0001L
END_TESTCASE BA-CTSY-CALLI-CNMCSC-0001

START_TESTCASE BA-CTSY-CALLI-CNMCSC-0002
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCSC-0002
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyMobileCallStatusChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyMobileCallStatusChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallStatusChange0002L
END_TESTCASE BA-CTSY-CALLI-CNMCSC-0002

START_TESTCASE BA-CTSY-CALLI-CNMCSC-0004
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCSC-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyMobileCallStatusChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyMobileCallStatusChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallStatusChange0004L
END_TESTCASE BA-CTSY-CALLI-CNMCSC-0004

START_TESTCASE BA-CTSY-CALLI-CNMCSC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCSC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyMobileCallStatusChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyMobileCallStatusChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallStatusChange0006L
END_TESTCASE BA-CTSY-CALLI-CNMCSC-0006

START_TESTCASE BA-CTSY-CALLI-CNMCSC-0007
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCSC-0007
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyMobileCallStatusChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyMobileCallStatusChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallStatusChange0007L
END_TESTCASE BA-CTSY-CALLI-CNMCSC-0007

START_TESTCASE BA-CTSY-CALLI-CNMCSC-0009
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCSC-0009
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyMobileCallStatusChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyMobileCallStatusChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallStatusChange0009L
END_TESTCASE BA-CTSY-CALLI-CNMCSC-0009

START_TESTCASE BA-CTSY-CALLI-CNMCSC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCSC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::NotifyMobileCallStatusChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::NotifyMobileCallStatusChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallStatusChange00011L
END_TESTCASE BA-CTSY-CALLI-CNMCSC-00011

START_TESTCASE BA-CTSY-CALLI-CNMCSC-00012
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCSC-00012
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobileCall::NotifyMobileCallStatusChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobileCall::NotifyMobileCallStatusChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallStatusChange00012L
END_TESTCASE BA-CTSY-CALLI-CNMCSC-00012

START_TESTCASE BA-CTSY-CALLI-CNMCSC-00014
//!@SYMTestCaseID BA-CTSY-CALLI-CNMCSC-00014
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobileCall::NotifyMobileCallStatusChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobileCall::NotifyMobileCallStatusChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyMobileCallStatusChange00014L
END_TESTCASE BA-CTSY-CALLI-CNMCSC-00014

START_TESTCASE BA-CTSY-CALLI-MGICT-0001
//!@SYMTestCaseID BA-CTSY-CALLI-MGICT-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetIncomingCallType
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetIncomingCallType
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetIncomingCallType0001L
END_TESTCASE BA-CTSY-CALLI-MGICT-0001

START_TESTCASE BA-CTSY-CALLI-MGICT-0006
//!@SYMTestCaseID BA-CTSY-CALLI-MGICT-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetIncomingCallType
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetIncomingCallType
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetIncomingCallType0006L
END_TESTCASE BA-CTSY-CALLI-MGICT-0006

START_TESTCASE BA-CTSY-CALLI-MGICT-00011
//!@SYMTestCaseID BA-CTSY-CALLI-MGICT-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetIncomingCallType
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetIncomingCallType
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestGetIncomingCallType00011L
END_TESTCASE BA-CTSY-CALLI-MGICT-00011

START_TESTCASE BA-CTSY-CALLI-MNICTC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-MNICTC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyIncomingCallTypeChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyIncomingCallTypeChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyIncomingCallTypeChange0001L
END_TESTCASE BA-CTSY-CALLI-MNICTC-0001

START_TESTCASE BA-CTSY-CALLI-LNHCC-0001
//!@SYMTestCaseID BA-CTSY-CALLI-LNHCC-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::NotifyHookChange for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::NotifyHookChange for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyLineHookChange0001L
END_TESTCASE BA-CTSY-CALLI-LNHCC-0001

START_TESTCASE BA-CTSY-CALLI-LNHCC-0006
//!@SYMTestCaseID BA-CTSY-CALLI-LNHCC-0006
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::NotifyLineHookChange for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RLine::NotifyLineHookChange for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyLineHookChange0006L
END_TESTCASE BA-CTSY-CALLI-LNHCC-0006

START_TESTCASE BA-CTSY-CALLI-LNHCC-00011
//!@SYMTestCaseID BA-CTSY-CALLI-LNHCC-00011
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RLine::NotifyLineHookChange for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::NotifyLineHookChange for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallInformationFU.TestNotifyLineHookChange00011L
END_TESTCASE BA-CTSY-CALLI-LNHCC-00011

RUN_SCRIPT z:\TestData\Scripts\mockltsy_remove_ini_file.script
