//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

RUN_SCRIPT z:\TestData\Scripts\mockltsy_copy_ini_file.script

LOAD_SUITE te_ctsy_component

START_TESTCASE BA-CTSY-ALLS-MGAL-0005
//!@SYMTestCaseID BA-CTSY-ALLS-MGAL-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetALSLine with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetALSLine and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyAlternateLineServiceFU.TestGetALSLine0005L
END_TESTCASE BA-CTSY-ALLS-MGAL-0005

START_TESTCASE BA-CTSY-ALLS-MSL-0005
//!@SYMTestCaseID BA-CTSY-ALLS-MSL-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetALSLine with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetALSLine and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyAlternateLineServiceFU.TestSetALSLine0005L
END_TESTCASE BA-CTSY-ALLS-MSL-0005

START_TESTCASE BA-CTSY-ACL-MGAN-0005
//!@SYMTestCaseID BA-CTSY-ACL-MGAN-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetAPNname with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetAPNname and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyAPNControlListFU.TestGetAPNname0005L
END_TESTCASE BA-CTSY-ACL-MGAN-0005

START_TESTCASE BA-CTSY-ACL-MEAE-0005
//!@SYMTestCaseID BA-CTSY-ACL-MEAE-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::EnumerateAPNEntries with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::EnumerateAPNEntries and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyAPNControlListFU.TestEnumerateAPNEntries0005L
END_TESTCASE BA-CTSY-ACL-MEAE-0005

START_TESTCASE BA-CTSY-ACL-MAAN-0005
//!@SYMTestCaseID BA-CTSY-ACL-MAAN-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::AppendAPNName with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::AppendAPNName and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyAPNControlListFU.TestAppendAPNName0005L
END_TESTCASE BA-CTSY-ACL-MAAN-0005

START_TESTCASE BA-CTSY-ACL-MDAN-0005
//!@SYMTestCaseID BA-CTSY-ACL-MDAN-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::DeleteAPNName with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::DeleteAPNName and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyAPNControlListFU.TestDeleteAPNName0005L
END_TESTCASE BA-CTSY-ACL-MDAN-0005

START_TESTCASE BA-CTSY-ACL-MGACLSS-0005
//!@SYMTestCaseID BA-CTSY-ACL-MGACLSS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetAPNControlListServiceStatus with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetAPNControlListServiceStatus and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyAPNControlListFU.TestGetAPNControlListServiceStatus0005L
END_TESTCASE BA-CTSY-ACL-MGACLSS-0005

START_TESTCASE BA-CTSY-ACL-MSACLSS-0005
//!@SYMTestCaseID BA-CTSY-ACL-MSACLSS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetAPNControlListServiceStatus with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetAPNControlListServiceStatus and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyAPNControlListFU.TestSetAPNControlListServiceStatus0005L
END_TESTCASE BA-CTSY-ACL-MSACLSS-0005

START_TESTCASE BA-CTSY-AAA-ARAI-0005
//!@SYMTestCaseID BA-CTSY-AAA-ARAI-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CAsyncRetrieveAuthorizationInfo::Start with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes CAsyncRetrieveAuthorizationInfo::Start and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyAuthorisationAndAuthenticationFU.TestStart0005L
END_TESTCASE BA-CTSY-AAA-ARAI-0005

START_TESTCASE BA-CTSY-BRMSG-BSBIL-0005
//!@SYMTestCaseID BA-CTSY-BRMSG-BSBIL-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileBroadcastMessaging::StoreBroadcastIdListL cancelling with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileBroadcastMessaging::StoreBroadcastIdListL cancel and tests for timeout
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyBroadcastMessagingFU.TestStoreBroadcastIdListL0005L
END_TESTCASE BA-CTSY-BRMSG-BSBIL-0005

START_TESTCASE BA-CTSY-BRMSG-RMPBLN-0005
//!@SYMTestCaseID BA-CTSY-BRMSG-RMPBLN-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneBroadcastIdList::Start with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes CRetrieveMobilePhoneBroadcastIdList::Start and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 300 te_ctsy_component TEFUnit.CCTsyBroadcastMessagingFU.TestStart0005L
END_TESTCASE BA-CTSY-BRMSG-RMPBLN-0005

START_TESTCASE BA-CTSY-BRMSG-BRM-0005
//!@SYMTestCaseID BA-CTSY-BRMSG-BRM-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileBroadcastMessaging::ReceiveMessage cancelling with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileBroadcastMessaging::ReceiveMessage cancel and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyBroadcastMessagingFU.TestReceiveMessage0005L
END_TESTCASE BA-CTSY-BRMSG-BRM-0005

START_TESTCASE BA-CTSY-BRMSG-BSFS-0005
//!@SYMTestCaseID BA-CTSY-BRMSG-BSFS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileBroadcastMessaging::SetFilterSetting with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileBroadcastMessaging::SetFilterSetting and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyBroadcastMessagingFU.TestSetFilterSetting0005L
END_TESTCASE BA-CTSY-BRMSG-BSFS-0005

START_TESTCASE BA-CTSY-CBAR-RMPCB-0005
//!@SYMTestCaseID BA-CTSY-CBAR-RMPCB-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneCBList::Start with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes CRetrieveMobilePhoneCBList::Start and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallBarringFU.TestStart0005L
END_TESTCASE BA-CTSY-CBAR-RMPCB-0005

START_TESTCASE BA-CTSY-CBAR-MSSP-0005
//!@SYMTestCaseID BA-CTSY-CBAR-MSSP-0005
//!@SYMComponent telephony_ctsy  
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetSSPassword with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetSSPassword and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallBarringFU.TestSetSSPassword0005L
END_TESTCASE BA-CTSY-CBAR-MSSP-0005

START_TESTCASE BA-CTSY-CBAR-MSCBS-0005
//!@SYMTestCaseID BA-CTSY-CBAR-MSCBS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetCallBarringStatus with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetCallBarringStatus and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallBarringFU.TestSetCallBarringStatus0005L
END_TESTCASE BA-CTSY-CBAR-MSCBS-0005

START_TESTCASE BA-CTSY-CCON-CAIC-0005
//!@SYMTestCaseID BA-CTSY-CCON-CAIC-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::AnswerIncomingCall with timeout for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::AnswerIncomingCall and tests for timeout for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestAnswerIncomingCall0005L
END_TESTCASE BA-CTSY-CCON-CAIC-0005

START_TESTCASE BA-CTSY-CCON-CAIC-00010
//!@SYMTestCaseID BA-CTSY-CCON-CAIC-00010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::AnswerIncomingCall with timeout for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::AnswerIncomingCall and tests for timeout for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestAnswerIncomingCall00010L
END_TESTCASE BA-CTSY-CCON-CAIC-00010

START_TESTCASE BA-CTSY-CCON-CD-0005
//!@SYMTestCaseID BA-CTSY-CCON-CD-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::Dial with timeout for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::Dial and tests for timeout for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestDial0005L
END_TESTCASE BA-CTSY-CCON-CD-0005

START_TESTCASE BA-CTSY-CCON-CD-00010
//!@SYMTestCaseID BA-CTSY-CCON-CD-00010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::Dial with timeout for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::Dial and tests for timeout for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestDial00010L
END_TESTCASE BA-CTSY-CCON-CD-00010

START_TESTCASE BA-CTSY-CCON-CHU-0005
//!@SYMTestCaseID BA-CTSY-CCON-CHU-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::HangUp with timeout for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::HangUp  and tests for timeout for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestHangUp0005L
END_TESTCASE BA-CTSY-CCON-CHU-0005

START_TESTCASE BA-CTSY-CCON-CHU-00010
//!@SYMTestCaseID BA-CTSY-CCON-CHU-00010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::HangUp  with timeout for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::HangUp and tests for timeout for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestHangUp00010L
END_TESTCASE BA-CTSY-CCON-CHU-00010

START_TESTCASE BA-CTSY-CCON-CHU-00015
//!@SYMTestCaseID BA-CTSY-CCON-CHU-00015
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RCall::HangUp with timeout for fax calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RCall::HangUp and tests for timeout for fax calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestHangUp00015L
END_TESTCASE BA-CTSY-CCON-CHU-00015

START_TESTCASE BA-CTSY-CCON-CH-0005
//!@SYMTestCaseID BA-CTSY-CCON-CH-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::Hold with timeout for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::Hold and tests for timeout for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestHold0005L
END_TESTCASE BA-CTSY-CCON-CH-0005

START_TESTCASE BA-CTSY-CCON-CS-0005
//!@SYMTestCaseID BA-CTSY-CCON-CS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::Swap with timeout for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::Swap and tests for timeout for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestSwap0005L
END_TESTCASE BA-CTSY-CCON-CS-0005

START_TESTCASE BA-CTSY-CCON-CR-0005
//!@SYMTestCaseID BA-CTSY-CCON-CR-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::Resume with timeout for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::Resume and tests for timeout for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestResume0005L
END_TESTCASE BA-CTSY-CCON-CR-0005

START_TESTCASE BA-CTSY-CCON-CT-0005
//!@SYMTestCaseID BA-CTSY-CCON-CT-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::Transfer with timeout for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::Transfer and tests for timeout for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestTransfer0005L
END_TESTCASE BA-CTSY-CCON-CT-0005

START_TESTCASE BA-CTSY-CCON-CAICI-0005
//!@SYMTestCaseID BA-CTSY-CCON-CAICI-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::AnswerIncomingCallISV with timeout for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::AnswerIncomingCallISV and tests for timeout for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallControlFU.TestAnswerIncomingCallISV0005L
END_TESTCASE BA-CTSY-CCON-CAICI-0005

START_TESTCASE BA-CTSY-CEMG-CDEC-0005
//!@SYMTestCaseID BA-CTSY-CEMG-CDEC-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::DialEmergencyCall with timeout for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::DialEmergencyCall and tests for timeout for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 450 te_ctsy_component TEFUnit.CCTsyCallEmergencyFU.TestDialEmergencyCall0005L
END_TESTCASE BA-CTSY-CEMG-CDEC-0005

START_TESTCASE BA-CTSY-CFOR-RMPCFLN-0005
//!@SYMTestCaseID BA-CTSY-CFOR-RMPCFLN-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneCFList::Start with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes CRetrieveMobilePhoneCFList::Start and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallForwardingFU.TestStart0005L
END_TESTCASE BA-CTSY-CFOR-RMPCFLN-0005

START_TESTCASE BA-CTSY-CFOR-MSCFS-0005
//!@SYMTestCaseID BA-CTSY-CFOR-MSCFS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetCallForwardingStatus with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetCallForwardingStatus and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallForwardingFU.TestSetCallForwardingStatus0005L
END_TESTCASE BA-CTSY-CFOR-MSCFS-0005

START_TESTCASE BA-CTSY-CWAT-RMPCWLN-0005
//!@SYMTestCaseID BA-CTSY-CWAT-RMPCWLN-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneCWList::Start with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes CRetrieveMobilePhoneCWList::Start and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallWaitingFU.TestStart0005L
END_TESTCASE BA-CTSY-CWAT-RMPCWLN-0005

START_TESTCASE BA-CTSY-CWAT-MSCWS-0005
//!@SYMTestCaseID BA-CTSY-CWAT-MSCWS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetCallWaitingStatus with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetCallWaitingStatus and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallWaitingFU.TestSetCallWaitingStatus0005L
END_TESTCASE BA-CTSY-CWAT-MSCWS-0005

START_TESTCASE BA-CTSY-DTMF-MSDT-0005
//!@SYMTestCaseID BA-CTSY-DTMF-MSDT-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SendDTMFTones with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SendDTMFTones and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 300 te_ctsy_component TEFUnit.CCTsyDTMFFU.TestSendDTMFTones0005L
END_TESTCASE BA-CTSY-DTMF-MSDT-0005

START_TESTCASE BA-CTSY-DTMF-MCDSS-0005
//!@SYMTestCaseID BA-CTSY-DTMF-MCDSS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::ContinueDTMFStringSending with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::ContinueDTMFStringSending and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 200 te_ctsy_component TEFUnit.CCTsyDTMFFU.TestContinueDTMFStringSending0005L
END_TESTCASE BA-CTSY-DTMF-MCDSS-0005

START_TESTCASE BA-CTSY-PBEN-ESR-0005
//!@SYMTestCaseID BA-CTSY-PBEN-ESR-0004
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY of RMobileENStore::Read for timout
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout of a request to RMobileENStore::Read
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyENStoreFU.TestRead0005L
END_TESTCASE BA-CTSY-PBEN-ESR-0005

START_TESTCASE BA-CTSY-PBEN-ESGI-0005
//!@SYMTestCaseID BA-CTSY-PBEN-ESGI-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support of RMobileENStore::GetInfo for timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes timout to RMobileENStore::GetInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyENStoreFU.TestGetInfo0005L
END_TESTCASE BA-CTSY-PBEN-ESGI-0005

START_TESTCASE BA-CTSY-PBEN-ESS-0005
//@SYMTestCaseID BA-CTSY-PBEN-ESS-0005
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneENList::Start with timeout
//@SYMTestPriority High
//@SYMTestActions Invokes CRetrieveMobilePhoneENList::Start and tests for timeout
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyENStoreFU.TestStart0005L
END_TESTCASE BA-CTSY-PBEN-ESS-0005

START_TESTCASE BA-CTSY-FXD-MSFS-0005
//!@SYMTestCaseID BA-CTSY-FXD-MSFS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetFdnSetting with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetFdnSetting and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyFixedDiallingFU.TestSetFdnSetting0005L
END_TESTCASE BA-CTSY-FXD-MSFS-0005

START_TESTCASE BA-CTSY-IMS-MIA-0005
//!@SYMTestCaseID BA-CTSY-IMS-MIA-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::ImsAuthenticate with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::ImsAuthenticate and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 300 te_ctsy_component TEFUnit.CCTsyIMSFU.TestImsAuthenticate0005L
END_TESTCASE BA-CTSY-IMS-MIA-0005

START_TESTCASE BA-CTSY-MBXN-MGMN-0005
//!@SYMTestCaseID BA-CTSY-MBXN-MGMN-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetMailboxNumbers with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetMailboxNumbers and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyMailboxNumbersFU.TestGetMailboxNumbers0005L
END_TESTCASE BA-CTSY-MBXN-MGMN-0005

START_TESTCASE BA-CTSY-MSGW-MGIMWI-0005
//!@SYMTestCaseID BA-CTSY-MSGW-MGIMWI-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetIccMessageWaitingIndicators with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetIccMessageWaitingIndicators and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyMessageWaitingFU.TestGetIccMessageWaitingIndicators0005L
END_TESTCASE BA-CTSY-MSGW-MGIMWI-0005

START_TESTCASE BA-CTSY-MSGW-MSIMWI-0005
//!@SYMTestCaseID BA-CTSY-MSGW-MSIMWI-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetIccMessageWaitingIndicators with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetIccMessageWaitingIndicators and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyMessageWaitingFU.TestSetIccMessageWaitingIndicators0005L
END_TESTCASE BA-CTSY-MSGW-MSIMWI-0005

START_TESTCASE BA-CTSY-NTWC-RMPDNS-0005
//!@SYMTestCaseID BA-CTSY-NTWC-RMPDNS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneDetectedNetworks::StartV2 with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to CRetrieveMobilePhoneDetectedNetworks::StartV2
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 300 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStartV20005L
END_TESTCASE BA-CTSY-NTWC-RMPDNS-0005

START_TESTCASE BA-CTSY-NTWC-MSN-0005
//!@SYMTestCaseID BA-CTSY-NTWC-MSN-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SelectNetwork with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SelectNetwork and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestSelectNetwork0005L
END_TESTCASE BA-CTSY-NTWC-MSN-0005

START_TESTCASE BA-CTSY-NTWC-MGSPN-0005
//!@SYMTestCaseID BA-CTSY-NTWC-MGSPN-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetServiceProviderName with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetServiceProviderName and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetServiceProviderName0005L
END_TESTCASE BA-CTSY-NTWC-MGSPN-0005

START_TESTCASE BA-CTSY-NTWC-MSNSS-0005
//!@SYMTestCaseID BA-CTSY-NTWC-MSNSS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetNetworkSelectionSetting with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetNetworkSelectionSetting and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 200 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestSetNetworkSelectionSetting0005L
END_TESTCASE BA-CTSY-NTWC-MSNSS-0005

START_TESTCASE BA-CTSY-PBON-OSA-0005
//!@SYMTestCaseID BA-CTSY-PBON-OSA-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for timeout to RMobileONStore::StoreAllL
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout to RMobileONStore::StoreAllL
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyONStoreFU.TestStoreAllL0005L
END_TESTCASE BA-CTSY-PBON-OSA-0005

START_TESTCASE BA-CTSY-PBON-OSR-0005
//!@SYMTestCaseID BA-CTSY-PBON-OSR-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for timout to RMobileONStore::Read
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout to RMobileONStore::Read
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyONStoreFU.TestRead0005L
END_TESTCASE BA-CTSY-PBON-OSR-0005

START_TESTCASE BA-CTSY-PBON-OSW-0005
//!@SYMTestCaseID BA-CTSY-PBON-OSW-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for timeout requests to RMobileONStore::Write
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout to RMobileONStore::Write
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyONStoreFU.TestWrite0005L
END_TESTCASE BA-CTSY-PBON-OSW-0005

START_TESTCASE BA-CTSY-PBON-OSD-0005
//!@SYMTestCaseID BA-CTSY-PBON-OSD-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for timeout requests to RMobileONStore::Delete
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout to RMobileONStore::Delete
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyONStoreFU.TestDelete0005L
END_TESTCASE BA-CTSY-PBON-OSD-0005

START_TESTCASE BA-CTSY-PBON-OSGI-0005
//!@SYMTestCaseID BA-CTSY-PBON-OSGI-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for timeout to RMobileONStore::GetInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout to RMobileONStore::GetInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyONStoreFU.TestGetInfo0005L
END_TESTCASE BA-CTSY-PBON-OSGI-0005

START_TESTCASE BA-CTSY-PBON-OSDA-0005
//!@SYMTestCaseID BA-CTSY-PBON-OSDA-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for timeout to RMobileONStore::DeleteAll
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout to RMobileONStore::DeleteAll
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyONStoreFU.TestDeleteAll0005L
END_TESTCASE BA-CTSY-PBON-OSDA-0005

START_TESTCASE BA-CTSY-PBON-OSS-0005
//@SYMTestCaseID BA-CTSY-PBON-OSS-0005
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneONList::Start with timeout
//@SYMTestPriority High
//@SYMTestActions Invokes CRetrieveMobilePhoneONList::Start and tests for timeout
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyONStoreFU.TestStart0005L
END_TESTCASE BA-CTSY-PBON-OSS-0005

START_TESTCASE BA-CTSY-PKTC-PCD-0005
//!@SYMTestCaseID BA-CTSY-PKTC-PCD-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::Deactivate with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Deactivate and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestDeactivate0005L
END_TESTCASE BA-CTSY-PKTC-PCD-0005

START_TESTCASE BA-CTSY-PKTC-PCIC-0005
//!@SYMTestCaseID BA-CTSY-PKTC-PCIC-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::InitialiseContext with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::InitialiseContext and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestInitialiseContext0005L
END_TESTCASE BA-CTSY-PKTC-PCIC-0005

START_TESTCASE BA-CTSY-PKTC-PCMAC-0005
//!@SYMTestCaseID BA-CTSY-PKTC-PCMAC-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::ModifyActiveContext with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::ModifyActiveContext and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestModifyActiveContext0005L
END_TESTCASE BA-CTSY-PKTC-PCMAC-0005

START_TESTCASE BA-CTSY-PKTC-PCGDVT-0005
//!@SYMTestCaseID BA-CTSY-PKTC-PCGDVT-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::GetDataVolumeTransferred with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::GetDataVolumeTransferred and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestGetDataVolumeTransferred0005L
END_TESTCASE BA-CTSY-PKTC-PCGDVT-0005

START_TESTCASE BA-CTSY-PKTC-PCDL-0005
//!@SYMTestCaseID BA-CTSY-PKTC-PCDL-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::Delete with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Delete and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestDelete0005L
END_TESTCASE BA-CTSY-PKTC-PCDL-0005

START_TESTCASE BA-CTSY-PKTC-PCA-0005
//!@SYMTestCaseID BA-CTSY-PKTC-PCA-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::Activate with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::Activate and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestActivate0005L
END_TESTCASE BA-CTSY-PKTC-PCA-0005

START_TESTCASE BA-CTSY-PKTC-PCSC-0005
//!@SYMTestCaseID BA-CTSY-PKTC-PCSC-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support for timeout in RPacketContext::SetConfig
//!@SYMTestPriority High
//!@SYMTestActions Invokes  support for timeout in RPacketContext::SetConfig
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketContextFU.TestSetConfig0005L
END_TESTCASE BA-CTSY-PKTC-PCSC-0005


START_TESTCASE BA-CTSY-PKTQ-PCAMA-0005
//!@SYMTestCaseID BA-CTSY-PKTQ-PCAMA-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketContext::AddMediaAuthorizationL with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketContext::AddMediaAuthorizationL and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestAddMediaAuthorizationL0005L
END_TESTCASE BA-CTSY-PKTQ-PCAMA-0005

START_TESTCASE BA-CTSY-PKTQ-QSPP-0005
//!@SYMTestCaseID BA-CTSY-PKTQ-QSPP-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketQoS::SetProfileParameters with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketQoS::SetProfileParameters and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketQoSFU.TestSetProfileParameters0005L
END_TESTCASE BA-CTSY-PKTQ-QSPP-0005

START_TESTCASE BA-CTSY-PKTS-PSSPB-0005
//!@SYMTestCaseID BA-CTSY-PKTS-PSSPB-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::SetPreferredBearer with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::SetPreferredBearer and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketServiceFU.TestSetPreferredBearer0005L
END_TESTCASE BA-CTSY-PKTS-PSSPB-0005

START_TESTCASE BA-CTSY-PKTS-PSRAR-0005
//!@SYMTestCaseID BA-CTSY-PKTS-PSRAR-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::RejectActivationRequest with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::RejectActivationRequest and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketServiceFU.TestRejectActivationRequest0005L
END_TESTCASE BA-CTSY-PKTS-PSRAR-0005

START_TESTCASE BA-CTSY-PKTS-PSSDCP-0005
//!@SYMTestCaseID BA-CTSY-PKTS-PSSDCP-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::SetDefaultContextParams with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::SetDefaultContextParams and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketServiceFU.TestSetDefaultContextParams0005L
END_TESTCASE BA-CTSY-PKTS-PSSDCP-0005

START_TESTCASE BA-CTSY-PKTS-PSA-0005
//!@SYMTestCaseID BA-CTSY-PKTS-PSA-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::Attach with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::Attach and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketServiceFU.TestAttach0005L
END_TESTCASE BA-CTSY-PKTS-PSA-0005

START_TESTCASE BA-CTSY-PKTS-PSD-0005
//!@SYMTestCaseID BA-CTSY-PKTS-PSD-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for timeout requests to RPacketService::Detach
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout in requests to RPacketService::Detach
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketServiceFU.TestDetach0005L
END_TESTCASE BA-CTSY-PKTS-PSD-0005

START_TESTCASE BA-CTSY-PKTS-PSGAM-0005
//!@SYMTestCaseID BA-CTSY-PKTS-PSGAM-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::GetAttachMode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::GetAttachMode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketServiceFU.TestGetAttachMode0005L
END_TESTCASE BA-CTSY-PKTS-PSGAM-0005

START_TESTCASE BA-CTSY-PKTS-PSSAM-0005
//!@SYMTestCaseID BA-CTSY-PKTS-PSSAM-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RPacketService::SetAttachMode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RPacketService::SetAttachMode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketServiceFU.TestSetAttachMode0005L
END_TESTCASE BA-CTSY-PKTS-PSSAM-0005

START_TESTCASE BA-CTSY-PKTS-PSGNRS-0005
//!@SYMTestCaseID BA-CTSY-PKTS-PSGNRS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for timeout to RPacketService::GetNtwkRegStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes timed out request to RPacketService::GetNtwkRegStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPacketServiceFU.TestGetNtwkRegStatus0005L
END_TESTCASE BA-CTSY-PKTS-PSGNRS-0005

START_TESTCASE BA-CTSY-PBSTR-PBSD-0005
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with timeout for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete and tests for timeout for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete0005L
END_TESTCASE BA-CTSY-PBSTR-PBSD-0005

START_TESTCASE BA-CTSY-PBSTR-PBSD-00010
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00010
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with timeout for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete and tests for timeout for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00010L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00010

START_TESTCASE BA-CTSY-PBSTR-PBSD-00020
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00020
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with timeout for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete and tests for timeout for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00020L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00020

START_TESTCASE BA-CTSY-PBSTR-PBSD-00025
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00025
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with timeout for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete and tests for timeout for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00025L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00025

START_TESTCASE BA-CTSY-PBSTR-PBSD-00030
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSD-00030
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Delete with timeout for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Delete and tests for timeout for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDelete00030L
END_TESTCASE BA-CTSY-PBSTR-PBSD-00030

START_TESTCASE BA-CTSY-PBSTR-PBSR-0005
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-0005
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for ADN phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for ADN phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead0005L
END_TESTCASE BA-CTSY-PBSTR-PBSR-0005

START_TESTCASE BA-CTSY-PBSTR-PBSR-00010
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00010
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for FDN phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for FDN phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00010L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00010

START_TESTCASE BA-CTSY-PBSTR-PBSR-00015
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00015
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for SDN phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for SDN phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00015L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00015

START_TESTCASE BA-CTSY-PBSTR-PBSR-00020
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00020
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for VMBX phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for VMBX phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00020L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00020

START_TESTCASE BA-CTSY-PBSTR-PBSR-00025
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00025
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for BDN phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for BDN phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00025L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00025

START_TESTCASE BA-CTSY-PBSTR-PBSR-00030
//@SYMTestCaseID BA-CTSY-PBSTR-PBSR-00030
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Read with timeout for MBDN phonebook
//@SYMTestPriority High
//@SYMTestActions Invokes RMobilePhoneBookStore::Read and tests for timeout for MBDN phonebook
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestRead00030L
END_TESTCASE BA-CTSY-PBSTR-PBSR-00030

START_TESTCASE BA-CTSY-PBSTR-PBSW-0005
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with timeout for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write and tests for timeout for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite0005L
END_TESTCASE BA-CTSY-PBSTR-PBSW-0005

START_TESTCASE BA-CTSY-PBSTR-PBSW-00010
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00010
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with timeout for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write and tests for timeout for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00010L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00010

START_TESTCASE BA-CTSY-PBSTR-PBSW-00020
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00020
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with timeout for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write and tests for timeout for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00020L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00020

START_TESTCASE BA-CTSY-PBSTR-PBSW-00025
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00025
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with timeout for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write and tests for timeout for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00025L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00025

START_TESTCASE BA-CTSY-PBSTR-PBSW-00030
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSW-00030
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::Write with timeout for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::Write and tests for timeout for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestWrite00030L
END_TESTCASE BA-CTSY-PBSTR-PBSW-00030

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00015
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00015
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test timout support in CTSY for RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout of RMobilePhoneBookStore::GetInfo for SDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 130 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00015L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00015

START_TESTCASE BA-CTSY-PBSTR-PBSGI-00020
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSGI-00020
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test timeout support in CTSY for RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout of RMobilePhoneBookStore::GetInfo for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 130 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestGetInfo00020L
END_TESTCASE BA-CTSY-PBSTR-PBSGI-00020

START_TESTCASE BA-CTSY-PBSTR-PBSDA-0005
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll with timeout for ADN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll and tests for timeout for ADN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll0005L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-0005

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00010
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00010
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll with timeout for FDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll and tests for timeout for FDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00010L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00010

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00020
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00020
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll with timeout for VMBX phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll and tests for timeout for VMBX phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00020L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00020

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00025
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00025
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll with timeout for BDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll and tests for timeout for BDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00025L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00025

START_TESTCASE BA-CTSY-PBSTR-PBSDA-00030
//!@SYMTestCaseID BA-CTSY-PBSTR-PBSDA-00030
//!@SYMComponent  telephony_ctsy         
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhoneBookStore::DeleteAll with timeout for MBDN phonebook
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhoneBookStore::DeleteAll and tests for timeout for MBDN phonebook
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneBookStoreFU.TestDeleteAll00030L
END_TESTCASE BA-CTSY-PBSTR-PBSDA-00030

START_TESTCASE BA-CTSY-PID-MGPI-0005
//!@SYMTestCaseID BA-CTSY-PID-MGPI-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetPhoneId with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetPhoneId and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneIdentityFU.TestGetPhoneId0005L
END_TESTCASE BA-CTSY-PID-MGPI-0005

START_TESTCASE BA-CTSY-PID-MGISS-0005
//!@SYMTestCaseID BA-CTSY-PID-MGISS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetIdentityServiceStatus with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetIdentityServiceStatus and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneIdentityFU.TestGetIdentityServiceStatus0005L
END_TESTCASE BA-CTSY-PID-MGISS-0005

START_TESTCASE BA-CTSY-PSEC-MGLI-0005
//!@SYMTestCaseID BA-CTSY-PSEC-MGLI-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetLockInfo with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetLockInfo and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestGetLockInfo0005L
END_TESTCASE BA-CTSY-PSEC-MGLI-0005

START_TESTCASE BA-CTSY-PSEC-MSLS-0005
//!@SYMTestCaseID BA-CTSY-PSEC-MSLS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetLockSetting with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetLockSetting and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestSetLockSetting0005L
END_TESTCASE BA-CTSY-PSEC-MSLS-0005

START_TESTCASE BA-CTSY-PSEC-MASC-0005
//!@SYMTestCaseID BA-CTSY-PSEC-MASC-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::AbortSecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::AbortSecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestAbortSecurityCode0005L
END_TESTCASE BA-CTSY-PSEC-MASC-0005

START_TESTCASE BA-CTSY-PSEC-MCSC-0005
//!@SYMTestCaseID BA-CTSY-PSEC-MCSC-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::ChangeSecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::ChangeSecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestChangeSecurityCode0005L
END_TESTCASE BA-CTSY-PSEC-MCSC-0005

START_TESTCASE BA-CTSY-PSEC-MVSC-0005
//!@SYMTestCaseID BA-CTSY-PSEC-MVSC-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::VerifySecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::VerifySecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestVerifySecurityCode0005L
END_TESTCASE BA-CTSY-PSEC-MVSC-0005

START_TESTCASE BA-CTSY-PSEC-MVSC-0007
//!@SYMTestCaseID BA-CTSY-PSEC-MVSC-0007
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::VerifySecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::VerifySecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestVerifySecurityCode0007L
END_TESTCASE BA-CTSY-PSEC-MVSC-0007

START_TESTCASE BA-CTSY-PSEC-MVSC-0008
//!@SYMTestCaseID BA-CTSY-PSEC-MVSC-0008
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::VerifySecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::VerifySecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestVerifySecurityCode0008L
END_TESTCASE BA-CTSY-PSEC-MVSC-0008

START_TESTCASE BA-CTSY-PSEC-MVSC-0009
//!@SYMTestCaseID BA-CTSY-PSEC-MVSC-0009
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::VerifySecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::VerifySecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestVerifySecurityCode0009L
END_TESTCASE BA-CTSY-PSEC-MVSC-0009

START_TESTCASE BA-CTSY-PSEC-MVSC-0010
//!@SYMTestCaseID BA-CTSY-PSEC-MVSC-0010
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::VerifySecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::VerifySecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestVerifySecurityCode0010L
END_TESTCASE BA-CTSY-PSEC-MVSC-0010

START_TESTCASE BA-CTSY-PSEC-MVSC-0011
//!@SYMTestCaseID BA-CTSY-PSEC-MVSC-0011
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::VerifySecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::VerifySecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestVerifySecurityCode0011L
END_TESTCASE BA-CTSY-PSEC-MVSC-0011

START_TESTCASE BA-CTSY-PSEC-MVSC-0012
//!@SYMTestCaseID BA-CTSY-PSEC-MVSC-0012
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::VerifySecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::VerifySecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestVerifySecurityCode0012L
END_TESTCASE BA-CTSY-PSEC-MVSC-0012

START_TESTCASE BA-CTSY-PSEC-MVSC-0013
//!@SYMTestCaseID BA-CTSY-PSEC-MVSC-0013
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::VerifySecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::VerifySecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestVerifySecurityCode0013L
END_TESTCASE BA-CTSY-PSEC-MVSC-0013

START_TESTCASE BA-CTSY-PSEC-MVSC-0014
//!@SYMTestCaseID BA-CTSY-PSEC-MVSC-0014
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::VerifySecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::VerifySecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestVerifySecurityCode0014L
END_TESTCASE BA-CTSY-PSEC-MVSC-0014

START_TESTCASE BA-CTSY-PSEC-MGSCI-0005
//!@SYMTestCaseID BA-CTSY-PSEC-MGSCI-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetSecurityCodeInfo with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetSecurityCodeInfo and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyPhoneSecurityFU.TestGetSecurityCodeInfo0005L
END_TESTCASE BA-CTSY-PSEC-MGSCI-0005

START_TESTCASE BA-CTSY-SMSP-CRMPSL-0005
//!@SYMTestCaseID BA-CTSY-SMSP-CRMPSL-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneSmspList::Start with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes CRetrieveMobilePhoneSmspList::Start and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySMSPStoreFU.TestStart0005L
END_TESTCASE BA-CTSY-SMSP-CRMPSL-0005

START_TESTCASE BA-CTSY-PBSMS-SMSSS-0005
//!@SYMTestCaseID BA-CTSY-PBSMS-SMSSS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneSmsList::Start with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes CRetrieveMobilePhoneSmsList::Start and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsStoreFU.TestStart0005L
END_TESTCASE BA-CTSY-PBSMS-SMSSS-0005

START_TESTCASE BA-CTSY-USNA-MSNSR-0005
//!@SYMTestCaseID BA-CTSY-USNA-MSNSR-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SendNetworkServiceRequest with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SendNetworkServiceRequest and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyUserNetworkAccessFU.TestSendNetworkServiceRequest0005L
END_TESTCASE BA-CTSY-USNA-MSNSR-0005

START_TESTCASE BA-CTSY-USNA-MSNSRNFC-0005
//!@SYMTestCaseID BA-CTSY-USNA-MSNSRNFC-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SendNetworkServiceRequestNoFdnCheck with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SendNetworkServiceRequestNoFdnCheck and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyUserNetworkAccessFU.TestSendNetworkServiceRequestNoFdnCheck0005L
END_TESTCASE BA-CTSY-USNA-MSNSRNFC-0005

START_TESTCASE BA-CTSY-DATC-CSDHP-00010
//!@SYMTestCaseID BA-CTSY-DATC-CSDHP-00010
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::SetDynamicHscsdParams with timeout for data calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::SetDynamicHscsdParams and tests for timeout for data calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyDataCallControlFU.TestSetDynamicHscsdParams00010L
END_TESTCASE BA-CTSY-DATC-CSDHP-00010

START_TESTCASE BA-CTSY-SUBI-MGCSP-0005
//!@SYMTestCaseID BA-CTSY-SUBI-MGCSP-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetCustomerServiceProfile with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCustomerServiceProfile and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 150 te_ctsy_component TEFUnit.CCTsySubscriberInfoFU.TestGetCustomerServiceProfile0005L
END_TESTCASE BA-CTSY-SUBI-MGCSP-0005

START_TESTCASE BA-CTSY-SUBI-MGST-0005
//!@SYMTestCaseID BA-CTSY-SUBI-MGST-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetServiceTable with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetServiceTable and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 150 te_ctsy_component TEFUnit.CCTsySubscriberInfoFU.TestGetServiceTable0005L
END_TESTCASE BA-CTSY-SUBI-MGST-0005

START_TESTCASE BA-CTSY-CONC-CGOTO-0005
//!@SYMTestCaseID BA-CTSY-CONC-CGOTO-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileCall::GoOneToOne with timeout for voice calls
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileCall::GoOneToOne and tests for timeout for voice calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyConferenceCallControlFU.TestGoOneToOne0005L
END_TESTCASE BA-CTSY-CONC-CGOTO-0005

START_TESTCASE BA-CTSY-CONC-COCC-0005
//!@SYMTestCaseID BA-CTSY-CONC-COCC-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileConferenceCall::CreateConference with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileConferenceCall::CreateConference and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyConferenceCallControlFU.TestCreateConference0005L
END_TESTCASE BA-CTSY-CONC-COCC-0005

START_TESTCASE BA-CTSY-CONC-COS-0005
//!@SYMTestCaseID BA-CTSY-CONC-COS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileConferenceCall::Swap with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileConferenceCall::Swap and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyConferenceCallControlFU.TestSwap0005L
END_TESTCASE BA-CTSY-CONC-COS-0005

START_TESTCASE BA-CTSY-CONC-COHU-0005
//!@SYMTestCaseID BA-CTSY-CONC-COHU-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileConferenceCall::HangUp with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileConferenceCall::HangUp and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyConferenceCallControlFU.TestHangUp0005L
END_TESTCASE BA-CTSY-CONC-COHU-0005

START_TESTCASE BA-CTSY-CONC-COAC-0005
//!@SYMTestCaseID BA-CTSY-CONC-COAC-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileConferenceCall::AddCall with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileConferenceCall::AddCall and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyConferenceCallControlFU.TestAddCall0005L
END_TESTCASE BA-CTSY-CONC-COAC-0005

START_TESTCASE BA-CTSY-CBAR-MSCBS-0005
//!@SYMTestCaseID BA-CTSY-CBAR-MSCBS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetCallBarringStatus with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetCallBarringStatus and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCallBarringFU.TestSetCallBarringStatus0005L
END_TESTCASE BA-CTSY-CBAR-MSCBS-0005

START_TESTCASE BA-CTSY-PSTR-MGPSI-0005
//!@SYMTestCaseID BA-CTSY-PSTR-MGPSI-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetPhoneStoreInfo with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetPhoneStoreInfo and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 150 te_ctsy_component TEFUnit.CCTsyPhoneStoreFU.TestGetPhoneStoreInfo0005L
END_TESTCASE BA-CTSY-PSTR-MGPSI-0005

START_TESTCASE BA-CTSY-PBSMS-SMSSR-0005
//!@SYMTestCaseID BA-CTSY-PBSMS-SMSSR-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsStore::Read with timeout for KETelIccSmsStore
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmsStore::Read and tests for timeout for KETelIccSmsStore
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsStoreFU.TestRead0005L
END_TESTCASE BA-CTSY-PBSMS-SMSSR-0005

START_TESTCASE BA-CTSY-PBSMS-SMSSD-0005
//!@SYMTestCaseID BA-CTSY-PBSMS-SMSSD-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsStore::Delete with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmsStore::Delete and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsStoreFU.TestDelete0005L
END_TESTCASE BA-CTSY-PBSMS-SMSSD-0005

START_TESTCASE BA-CTSY-PBSMS-SMSSGI-0005
//!@SYMTestCaseID BA-CTSY-PBSMS-SMSSGI-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsStore::GetInfo with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmsStore::GetInfo and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsStoreFU.TestGetInfo0005L
END_TESTCASE BA-CTSY-PBSMS-SMSSGI-0005

START_TESTCASE BA-CTSY-PBSMS-SMSSDA-0005
//!@SYMTestCaseID BA-CTSY-PBSMS-SMSSDA-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsStore::DeleteAll with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmsStore::DeleteAll and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsStoreFU.TestDeleteAll0005L
END_TESTCASE BA-CTSY-PBSMS-SMSSDA-0005

START_TESTCASE BA-CTSY-PBSMS-SMSSW-0005
//!@SYMTestCaseID BA-CTSY-PBSMS-SMSSW-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsStore::Write with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmsStore::Write and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsStoreFU.TestWrite0005L
END_TESTCASE BA-CTSY-PBSMS-SMSSW-0005

START_TESTCASE BA-CTSY-PBSMS-SMSSS-0005
//!@SYMTestCaseID BA-CTSY-PBSMS-SMSSS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneSmsList::Start with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes CRetrieveMobilePhoneSmsList::Start and tests for timeout
//!@SYMTestExpectedResults Pass
@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsStoreFU.TestStart0005L
END_TESTCASE BA-CTSY-PBSMS-SMSSS-0005

START_TESTCASE BA-CTSY-NTWC-MGNRS-0005
//!@SYMTestCaseID BA-CTSY-NTWC-MGNRS-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetNetworkRegistrationStatus with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetNetworkRegistrationStatus and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetNetworkRegistrationStatus0005L
END_TESTCASE BA-CTSY-NTWC-MGNRS-0005

START_TESTCASE BA-CTSY-USSDM-USM-0005
//!@SYMTestCaseID BA-CTSY-USSDM-USM-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileUssdMessaging::SendMessage with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileUssdMessaging::SendMessage and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyUssdMessagingFU.TestSendMessage0005L
END_TESTCASE BA-CTSY-USSDM-USM-0005

START_TESTCASE BA-CTSY-USSDM-USR-0005
//!@SYMTestCaseID BA-CTSY-USSDM-USR-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileUssdMessaging::SendRelease with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileUssdMessaging::SendRelease and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyUssdMessagingFU.TestSendRelease0005L
END_TESTCASE BA-CTSY-USSDM-USR-0005

START_TESTCASE BA-CTSY-CIPC-MCTC-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCTC-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::TerminateCall with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::TerminateCall and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestTerminateCall0005L
END_TESTCASE BA-CTSY-CIPC-MCTC-0005

START_TESTCASE BA-CTSY-CIPC-MCGCI-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCI-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetCipheringInfo with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetCipheringInfo and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCipheringInfo0005L
END_TESTCASE BA-CTSY-CIPC-MCGCI-0005

START_TESTCASE BA-CTSY-CIPC-MCNW-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCNW-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::NetWakeup with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::NetWakeup and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestNetWakeup0005L
END_TESTCASE BA-CTSY-CIPC-MCNW-0005

START_TESTCASE BA-CTSY-CIPC-MCRVHZP-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCRVHZP-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadViagHomeZoneParams with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadViagHomeZoneParams and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneParams0005L
END_TESTCASE BA-CTSY-CIPC-MCRVHZP-0005

START_TESTCASE BA-CTSY-CIPC-MCRVHZC-0005
//@SYMTestCaseID BA-CTSY-CIPC-MCRVHZC-0005
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadViagHomeZoneCache with timeout
//@SYMTestPriority High
//@SYMTestActions Invokes RMmCustomAPI::ReadViagHomeZoneCache and tests for timeout
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadViagHomeZoneCache0005L
END_TESTCASE BA-CTSY-CIPC-MCRVHZC-0005

START_TESTCASE BA-CTSY-CIPC-MCWVHZC-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCWVHZC-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::WriteViagHomeZoneCache with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::WriteViagHomeZoneCache and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteViagHomeZoneCache0005L
END_TESTCASE BA-CTSY-CIPC-MCWVHZC-0005

START_TESTCASE BA-CTSY-SMSM-SSM-0005
//!@SYMTestCaseID BA-CTSY-SMSM-SSM-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::SendMessage with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmsMessaging::SendMessage and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsMessagingFU.TestSendMessage0005L
END_TESTCASE BA-CTSY-SMSM-SSM-0005

START_TESTCASE BA-CTSY-SMSM-SSSL-0005
//!@SYMTestCaseID BA-CTSY-SMSM-SSSL-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support for timeout to RMobileSmsMessaging::StoreSmspListL
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout to RMobileSmsMessaging::StoreSmspListL
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsMessagingFU.TestStoreSmspListL0005L
END_TESTCASE BA-CTSY-SMSM-SSSL-0005

START_TESTCASE BA-CTSY-SMSM-SRSR-0005
//!@SYMTestCaseID BA-CTSY-SMSM-SRSR-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support for timeout RMobileSmsMessaging::ResumeSmsReception
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout to RMobileSmsMessaging::ResumeSmsReception
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsMessagingFU.TestResumeSmsReception0005L
END_TESTCASE BA-CTSY-SMSM-SRSR-0005

START_TESTCASE BA-CTSY-SMSM-SGMSI-0005
//!@SYMTestCaseID BA-CTSY-SMSM-SGMSI-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support for timeout of RMobileSmsMessaging::GetMessageStoreInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes timeout to RMobileSmsMessaging::GetMessageStoreInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 130 te_ctsy_component TEFUnit.CCTsySmsMessagingFU.TestGetMessageStoreInfo0005L
END_TESTCASE BA-CTSY-SMSM-SGMSI-0005

START_TESTCASE BA-CTSY-SMSM-SSMNFC-0005
//!@SYMTestCaseID BA-CTSY-SMSM-SSMNFC-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmsMessaging::SendMessageNoFdnCheck with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmsMessaging::SendMessageNoFdnCheck and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsySmsMessagingFU.TestSendMessageNoFdnCheck0005L
END_TESTCASE BA-CTSY-SMSM-SSMNFC-0005

START_TESTCASE BA-CTSY-USSDM-USMNFC-0005
//!@SYMTestCaseID BA-CTSY-USSDM-USMNFC-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileUssdMessaging::SendMessageNoFdnCheck with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileUssdMessaging::SendMessageNoFdnCheck and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyUssdMessagingFU.TestSendMessageNoFdnCheck0005L
END_TESTCASE BA-CTSY-USSDM-USMNFC-0005

START_TESTCASE BA-CTSY-CIPC-MCSAB-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAB-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SetAlsBlocked with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetAlsBlocked and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetAlsBlocked0005L
END_TESTCASE BA-CTSY-CIPC-MCSAB-0005

START_TESTCASE BA-CTSY-CIPC-MCGAB-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCGAB-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetAlsBlocked with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetAlsBlocked and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetAlsBlocked0005L
END_TESTCASE BA-CTSY-CIPC-MCGAB-0005

START_TESTCASE BA-CTSY-CIPC-MCCAPS-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCCAPS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::CheckAlsPpSupport with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::CheckAlsPpSupport and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckAlsPpSupport0005L
END_TESTCASE BA-CTSY-CIPC-MCCAPS-0005

START_TESTCASE BA-CTSY-CIPC-MCCCBL-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCCCBL-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ClearCallBlackList with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ClearCallBlackList and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestClearCallBlackList0005L
END_TESTCASE BA-CTSY-CIPC-MCCCBL-0005

START_TESTCASE BA-CTSY-CIPC-MCIB-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCIB-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::IsBlocked with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::IsBlocked and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestIsBlocked0005L
END_TESTCASE BA-CTSY-CIPC-MCIB-0005

START_TESTCASE BA-CTSY-CIPC-MCCSC-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCCSC-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::CheckSecurityCode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::CheckSecurityCode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckSecurityCode0005L
END_TESTCASE BA-CTSY-CIPC-MCCSC-0005

START_TESTCASE BA-CTSY-CIPC-MCGNPN-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCGNPN-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetNetworkProviderName with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetNetworkProviderName and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetNetworkProviderName0005L
END_TESTCASE BA-CTSY-CIPC-MCGNPN-0005

START_TESTCASE BA-CTSY-CIPC-MCCEN-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCCEN-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::CheckEmergencyNumber with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::CheckEmergencyNumber and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckEmergencyNumber0005L
END_TESTCASE BA-CTSY-CIPC-MCCEN-0005

START_TESTCASE BA-CTSY-CIPC-MCGON-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCGON-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetOperatorName with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetOperatorName and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetOperatorName0005L
END_TESTCASE BA-CTSY-CIPC-MCGON-0005

START_TESTCASE BA-CTSY-CIPC-MCGPOL-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCGPOL-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetProgrammableOperatorLogo with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetProgrammableOperatorLogo and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetProgrammableOperatorLogo0005L
END_TESTCASE BA-CTSY-CIPC-MCGPOL-0005

START_TESTCASE BA-CTSY-CIPC-MCCTDDS-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCCTDDS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::CheckTwoDigitDialSupport with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::CheckTwoDigitDialSupport and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestCheckTwoDigitDialSupport0005L
END_TESTCASE BA-CTSY-CIPC-MCCTDDS-0005

START_TESTCASE BA-CTSY-CIPC-MCRNS-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCRNS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ResetNetServer with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ResetNetServer and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestResetNetServer0005L
END_TESTCASE BA-CTSY-CIPC-MCRNS-0005

START_TESTCASE BA-CTSY-CIPC-MCSSCTB-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSCTB-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::StartSimCbTopicBrowsing with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::StartSimCbTopicBrowsing and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestStartSimCbTopicBrowsing0005L
END_TESTCASE BA-CTSY-CIPC-MCSSCTB-0005

START_TESTCASE BA-CTSY-CIPC-MCDSCT-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCDSCT-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::DeleteSimCbTopic with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::DeleteSimCbTopic and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDeleteSimCbTopic0005L
END_TESTCASE BA-CTSY-CIPC-MCDSCT-0005

START_TESTCASE BA-CTSY-CIPC-MCSAR-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCSAR-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SendAPDUReq with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SendAPDUReq and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSendAPDUReq0005L
END_TESTCASE BA-CTSY-CIPC-MCSAR-0005

START_TESTCASE BA-CTSY-CIPC-MCDPL-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCDPL-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::DisablePhoneLock with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::DisablePhoneLock and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestDisablePhoneLock0005L
END_TESTCASE BA-CTSY-CIPC-MCDPL-0005

START_TESTCASE BA-CTSY-CIPC-MCRSF-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCRSF-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadSimFile with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::ReadSimFile and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadSimFile0005L
END_TESTCASE BA-CTSY-CIPC-MCRSF-0005


START_TESTCASE BA-CTSY-CIPC-MCGSNM-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSNM-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetSystemNetworkModes with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetSystemNetworkModes and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSystemNetworkModes0005L
END_TESTCASE BA-CTSY-CIPC-MCGSNM-0005

START_TESTCASE BA-CTSY-CIPC-MCSSNM-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSNM-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SetSystemNetworkMode with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetSystemNetworkMode and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetSystemNetworkMode0005L
END_TESTCASE BA-CTSY-CIPC-MCSSNM-0005

START_TESTCASE BA-CTSY-CIPC-MCGCSNM-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCGCSNM-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetCurrentSystemNetworkModes with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetCurrentSystemNetworkModes and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCurrentSystemNetworkModes0005L
END_TESTCASE BA-CTSY-CIPC-MCGCSNM-0005

START_TESTCASE BA-CTSY-CIPC-MCPSON-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCPSON-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::PowerSimOn with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::PowerSimOn and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestPowerSimOn0005L
END_TESTCASE BA-CTSY-CIPC-MCPSON-0005

START_TESTCASE BA-CTSY-CIPC-MCPSOF-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCPSOF-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::PowerSimOff with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::PowerSimOff and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestPowerSimOff0005L
END_TESTCASE BA-CTSY-CIPC-MCPSOF-0005

START_TESTCASE BA-CTSY-CIPC-MCSWR-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCSWR-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SimWarmReset with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SimWarmReset and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSimWarmReset0005L
END_TESTCASE BA-CTSY-CIPC-MCSWR-0005

START_TESTCASE BA-CTSY-CIPC-MCGATR-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCGATR-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetATR with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetATR and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetATR0005L
END_TESTCASE BA-CTSY-CIPC-MCGATR-0005

START_TESTCASE BA-CTSY-CIPC-MCGSCRS-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSCRS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetSimCardReaderStatus with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetSimCardReaderStatus and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSimCardReaderStatus0005L
END_TESTCASE BA-CTSY-CIPC-MCGSCRS-0005

START_TESTCASE BA-CTSY-CIPC-MCWVHZUS-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCWVHZUS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::WriteViagHomeZoneUHZIUESettings with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::WriteViagHomeZoneUHZIUESettings and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteViagHomeZoneUHZIUESettings0005L
END_TESTCASE BA-CTSY-CIPC-MCWVHZUS-0005

START_TESTCASE BA-CTSY-CIPC-MCRHS-0005
//@SYMTestCaseID BA-CTSY-CIPC-MCRHS-0005
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::ReadHSxPAStatus with timeout
//@SYMTestPriority High
//@SYMTestActions Invokes RMmCustomAPI::ReadHSxPAStatus and tests for timeout
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestReadHSxPAStatus0005L
END_TESTCASE BA-CTSY-CIPC-MCRHS-0005

START_TESTCASE BA-CTSY-CIPC-MCWHS-0005
//@SYMTestCaseID BA-CTSY-CIPC-MCWHS-0005
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::WriteHSxPAStatus with timeout
//@SYMTestPriority High
//@SYMTestActions Invokes RMmCustomAPI::WriteHSxPAStatus and tests for timeout
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestWriteHSxPAStatus0005L
END_TESTCASE BA-CTSY-CIPC-MCWHS-0005

START_TESTCASE BA-CTSY-CIPC-MCGICFIS-0005
//@SYMTestCaseID BA-CTSY-CIPC-MCGICFIS-0005
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetIccCallForwardingIndicatorStatus with timeout
//@SYMTestPriority High
//@SYMTestActions Invokes RMmCustomAPI::GetIccCallForwardingIndicatorStatus and tests for timeout
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetIccCallForwardingIndicatorStatus0005L
END_TESTCASE BA-CTSY-CIPC-MCGICFIS-0005

START_TESTCASE BA-CTSY-CIPC-MCGCI2-0005
//@SYMTestCaseID BA-CTSY-CIPC-MCGCI2-0005
//@SYMComponent  telephony_ctsy
//@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetCellInfo with timeout
//@SYMTestPriority High
//@SYMTestActions Invokes RMmCustomAPI::GetCellInfo and tests for timeout
//@SYMTestExpectedResults Pass
//@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetCellInfo0005L
END_TESTCASE BA-CTSY-CIPC-MCGCI2-0005

START_TESTCASE BA-CTSY-CIPC-MCGSNB-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCGSNB-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::GetSystemNetworkBand with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetSystemNetworkBand and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetSystemNetworkBand0005L
END_TESTCASE BA-CTSY-CIPC-MCGSNB-0005

START_TESTCASE BA-CTSY-CIPC-MCSSNB-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCSSNB-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMmCustomAPI::SetSystemNetworkBand with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::SetSystemNetworkBand and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestSetSystemNetworkBand0005L
END_TESTCASE BA-CTSY-CIPC-MCSSNB-0005

START_TESTCASE BA-CTSY-CIPC-MCNG-0005
//!@SYMTestCaseID BA-CTSY-CIPC-MCNG-0005
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetCurrentActiveUSimApplication with timeout
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCurrentActiveUSimApplication and tests for timeout
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyUSIMApplicationFU.TestGetCurrentActiveUSimApplication0005L
END_TESTCASE BA-CTSY-CIPC-MCNG-0005

START_TESTCASE BA-CTSY-CIPC-GUSS-0005
//!@SYMTestCaseID BA-CTSY-CIPC-GUSS-0005
//!@SYMComponent  telephony_ctsy
//!@SYMTestCaseDesc Test support for TimeOut for request RMmCustomAPI::GetUSIMServiceSupport
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMmCustomAPI::GetUSIMServiceSupport
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyCustomIPCFU.TestGetUSIMServiceSupport0005L
END_TESTCASE BA-CTSY-CIPC-GUSS-0005

RUN_SCRIPT z:\TestData\Scripts\mockltsy_remove_ini_file.script
