//
PRINT Run all te_integration_stltsy Suite Tests

//
LOAD_SUITE te_integration_stltsySuite  -SharedData
//
//Please add or make change of you test steps, here is sample only:
RUN_TEST_STEP 10 te_integration_stltsySuite TestLtsyOpenPhone
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsyOpenSms 
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsyOpenSmsStore
RUN_TEST_STEP 20 te_integration_stltsySuite CTestLtsySmsSend 
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsyGetMessageStoreInfo
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsySmsStoreGetInfo
RUN_TEST_STEP 200 te_integration_stltsySuite CTestLtsySmsReceive
delay 2000
RUN_TEST_STEP 30 te_integration_stltsySuite CTestLtsySmsAck
RUN_TEST_STEP 30 te_integration_stltsySuite CTestLtsySmsNack
RUN_TEST_STEP 100 te_integration_stltsySuite CTestLtsySmsSendInvalidParam
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsySmsRead
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsySmsReadInvalidIndex
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsySmsDelete
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsySmsDeleteInvalidIndex
delay 5000
RUN_TEST_STEP 200 te_integration_stltsySuite CTestLtsySmsDeleteAll
delay 5000
RUN_TEST_STEP 200 te_integration_stltsySuite CTestLtsySmsStore
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsySmsWrite
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsySmsWriteInvalidParam
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsyCloseSms  
RUN_TEST_STEP 10 te_integration_stltsySuite CTestLtsyCloseSmsStore                             
                             

PRINT Complate_te_integration_stltsy_Tests
