//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Run WServ NONNGA screen device tests on screen 0

LOAD_SUITE tautoserver_nonnga

RUN_TEST_STEP 100 tautoserver_nonnga TScreenDevice

// Run at the end and it will trigger a Wserv memory leak check
RUN_TEST_STEP 100 tautoserver_nonnga TMemLeakCheckOneShot
