//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//
PRINT Run auto tests
//
LOAD_SUITE tautoserver_nga

PRINT Run Final WServ tests on screen 0
DELAY 5000
RUN_TEST_STEP 1500 tautoserver_nga TEventTest
RUN_TEST_STEP 100 tautoserver_nga TAdvancedPointerEvent
RUN_TEST_STEP 200 tautoserver_nga TMultiPtrEventTest
RUN_TEST_STEP 100 tautoserver_nga TPntKey
RUN_TEST_STEP 100 tautoserver_nga TRectList
RUN_TEST_STEP 100 tautoserver_nga TBlank
RUN_TEST_STEP 100 tautoserver_nga TOOMDRAW
RUN_TEST_STEP 100 tautoserver_nga TBitmap
RUN_TEST_STEP 100 tautoserver_nga TOrdinal
RUN_TEST_STEP 600 tautoserver_nga TScreenDevice
RUN_TEST_STEP 100 tautoserver_nga TMessage
RUN_TEST_STEP 600 tautoserver_nga TRedrawStoring
RUN_TEST_STEP 100 tautoserver_nga TScreenModePositioning
RUN_TEST_STEP 200 tautoserver_nga TFade
RUN_TEST_STEP 100 tautoserver_nga TModifiersChanged
RUN_TEST_STEP 600 tautoserver_nga TCursorTest
RUN_TEST_STEP 500 tautoserver_nga TPanic
RUN_TEST_STEP 1200 tautoserver_nga TGdi
RUN_TEST_STEP 100 tautoserver_nga TRedrawTest
RUN_TEST_STEP 100 tautoserver_nga TDerived
RUN_TEST_STEP 100 tautoserver_nga TAlphaWin	
RUN_TEST_STEP 100 tautoserver_nga TMultiCon
RUN_TEST_STEP 100 tautoserver_nga TScrMode
RUN_TEST_STEP 200 tautoserver_nga TPointerCapture
//RUN_TEST_STEP 500 tautoserver_nga TCapability	Hangs the H4
RUN_TEST_STEP 100 tautoserver_nga TPointer
RUN_TEST_STEP 1500 tautoserver_nga TMultipleTrans
RUN_TEST_STEP 500 tautoserver_nga TWindowTest
RUN_TEST_STEP 100 tautoserver_nga TKRepeat
RUN_TEST_STEP 1500 tautoserver_nga TKey
RUN_TEST_STEP 100 tautoserver_nga TWsGraphs
RUN_TEST_STEP 1000 tautoserver_nga TCaptureKey
//RUN_TEST_STEP 100 tautoserver_nga TScroll		Hangs the H4
RUN_TEST_STEP 100 tautoserver_nga TGetPixel
RUN_TEST_STEP 100 tautoserver_nga TProcPri
//RUN_TEST_STEP 500 tautoserver_nga TOom		Hangs the H4
RUN_TEST_STEP 2000 tautoserver_nga TAlphaChannel
RUN_TEST_STEP 600 tautoserver_nga TAnimDll
// TCrpAnim needs 800 for extended test
RUN_TEST_STEP 4000 tautoserver_nga TCrpAnim
RUN_TEST_STEP 200 tautoserver_nga TScreenModeScaling
RUN_TEST_STEP 500 tautoserver_nga TGwHandle
RUN_TEST_STEP 500 tautoserver_nga TDirect
RUN_TEST_STEP 100 tautoserver_nga TFlickerFree
RUN_TEST_STEP 500 tautoserver_nga TW32CmdBuf
//RUN_TEST_STEP 500 tautoserver_nga TBufferSecurity Causes test harness to hang DEF094034
RUN_TEST_STEP 100 tautoserver_nga TGc
RUN_TEST_STEP 100 tautoserver_nga TGraphicsDrawer
RUN_TEST_STEP 100 tautoserver_nga TDrawResource

PRINT Run Final WServ tests on screen 1
DELAY 5000
RUN_TEST_STEP 100 tautoserver_nga TMultiDisplay
RUN_TEST_STEP 100 tautoserver_nga TPntKey
RUN_TEST_STEP 100 tautoserver_nga TRectList
RUN_TEST_STEP 100 tautoserver_nga TBlank
RUN_TEST_STEP 100 tautoserver_nga TOOMDRAW
RUN_TEST_STEP 100 tautoserver_nga TBitmap
RUN_TEST_STEP 100 tautoserver_nga TOrdinal
RUN_TEST_STEP 600 tautoserver_nga TScreenDevice
RUN_TEST_STEP 100 tautoserver_nga TMessage
RUN_TEST_STEP 600 tautoserver_nga TRedrawStoring
RUN_TEST_STEP 100 tautoserver_nga TScreenModePositioning
RUN_TEST_STEP 200 tautoserver_nga TFade
RUN_TEST_STEP 100 tautoserver_nga TModifiersChanged
RUN_TEST_STEP 600 tautoserver_nga TCursorTest
RUN_TEST_STEP 500 tautoserver_nga TPanic
RUN_TEST_STEP 1200 tautoserver_nga TGdi
RUN_TEST_STEP 100 tautoserver_nga TRedrawTest
RUN_TEST_STEP 100 tautoserver_nga TDerived
RUN_TEST_STEP 100 tautoserver_nga TAlphaWin	
RUN_TEST_STEP 100 tautoserver_nga TScrMode
// RUN_TEST_STEP 500 tautoserver_nga TCapability        Hangs the H4
RUN_TEST_STEP 100 tautoserver_nga TPointer
RUN_TEST_STEP 1500 tautoserver_nga TMultipleTrans
RUN_TEST_STEP 500 tautoserver_nga TWindowTest
RUN_TEST_STEP 100 tautoserver_nga TKRepeat
RUN_TEST_STEP 1500 tautoserver_nga TKey
RUN_TEST_STEP 100 tautoserver_nga TWsGraphs
RUN_TEST_STEP 1000 tautoserver_nga TCaptureKey
RUN_TEST_STEP 100 tautoserver_nga TScroll
RUN_TEST_STEP 100 tautoserver_nga TGetPixel
RUN_TEST_STEP 100 tautoserver_nga TProcPri
//RUN_TEST_STEP 500 tautoserver_nga TOom		Hangs the H4
RUN_TEST_STEP 2000 tautoserver_nga TAlphaChannel
RUN_TEST_STEP 600 tautoserver_nga TAnimDll
// TCrpAnim needs 800 for extended test
RUN_TEST_STEP 4000 tautoserver_nga TCrpAnim
RUN_TEST_STEP 200 tautoserver_nga TScreenModeScaling
RUN_TEST_STEP 500 tautoserver_nga TGwHandle
RUN_TEST_STEP 500 tautoserver_nga TDirect
RUN_TEST_STEP 500 tautoserver_nga TDirect2
RUN_TEST_STEP 100 tautoserver_nga TFlickerFree
RUN_TEST_STEP 500 tautoserver_nga TW32CmdBuf
//RUN_TEST_STEP 500 tautoserver_nga TBufferSecurity Causes test harness to hang DEF094034
RUN_TEST_STEP 100 tautoserver_nga TGc
RUN_TEST_STEP 100 tautoserver_nga TGraphicsDrawer
RUN_TEST_STEP 100 tautoserver_nga TDrawResource
//
// Run at the end and it will trigger a Wserv memory leak check
RUN_TEST_STEP 100 tautoserver_nga TMemLeakCheckOneShot
