// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//
PRINT Run SetNativePixmapType tests
//
LOAD_SUITE egltestserver

// SetNativePixmapType tests
RUN_TEST_STEP 100 egltestserver NativePixmapType_SingleThread_Positive_RSgImage
RUN_TEST_STEP 100 egltestserver NativePixmapType_MultiThread_Positive_RSgImage_InitTwice
RUN_TEST_STEP 100 egltestserver NativePixmapType_MultiThread_Positive_RSgImage_InitTwice_NoRendezvous
RUN_TEST_STEP 100 egltestserver NativePixmapType_MultiThread_Positive_RSgImage_InitOneThreadOnly
RUN_TEST_STEP 100 egltestserver NativePixmapType_MultiProcess_Both_RSgImage
RUN_TEST_STEP 300 egltestserver ChooseConfig_EGL_MATCH_NATIVE_PIXMAP_KHR
RUN_TEST_STEP 300 egltestserver CFbsBitmap_EGL_MATCH_NATIVE_PIXMAP_KHR