// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// WsGcePerformance.script
//

LOAD_SUITE wsgcecscserver

// Run the tests as specified by the wrapping script
// RUN_TEST_STEP 100 wsgcecscserver TEFUnit.CGlobalSettings.Report

////////////////
// CSC NGA tests
////////////////

//COMMENTED OUT FOR 10T38 ZERO TOLERANCE TEST STRATEGY
//RUN_TEST_STEP 500 wsgcecscserver TEFUnit.CWSGceCsc.GRAPHICS_WSERV_CSC_101L
//RUN_TEST_STEP 500 wsgcecscserver TEFUnit.CWSGceCsc.GRAPHICS_WSERV_CSC_102L

RUN_TEST_STEP 500 wsgcecscserver TEFUnit.CWSGceCsc.GRAPHICS_WSERV_CSC_103L
// Negative test cases
RUN_TEST_STEP 500 wsgcecscserver TEFUnit.CWSGceCsc.GRAPHICS_WSERV_CSC_104L
// Defect test cases

//COMMENTED OUT FOR 10T38 ZERO TOLERANCE TEST STRATEGY
//RUN_TEST_STEP 500 wsgcecscserver TEFUnit.CWSGceCsc.GRAPHICS_WSERV_CSC_105L
