// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run AmaStarterStandalone tests

// We need to set the SID of the server to the correct one KSysStartSID, so we are able to launch AmaStarter.exe.
//	0003FFFE ==> All -Tcb capabilities
//  10205C44 ==> KSysStartSID
RUN_PROGRAM -1 setcap tamastarter_server.exe 0003FFFE -SID 10205C44 tamastarter_server_KSysStartSID.exe


LOAD_SUITE tamastarter_server_KSysStartSID

START_TESTCASE 			DEVSRVS-SYSSTART-AMASTARTER-0007
//! @SYMTestCaseID 		DEVSRVS-SYSSTART-AMASTARTER-0007
//! @SYMTestCaseDesc		To check correct launch of AMCs when AmaStarter is used standalone..
//! @SYMPREQ 			PREQ871
//! @SYMREQ			REQ9141
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDependencies	The SID of the launching server has been changed to KSysStartSID in the script using SETCAP
//!   				The appropriate database has been created.
//! @SYMTestActions		Use the same DSC store database as per the AmaStarter SysStart test cases.
//! 				Launch separate AmaStarter.exe's each time that will use all the DSC items in the database.
//! @SYMTestExpectedResults 	The test AMC EXE should be launched successfully with the same results as per when launched
RUN_TEST_STEP 1000 tamastarter_server_KSysStartSID AmaStarterStandalone
END_TESTCASE 			DEVSRVS-SYSSTART-AMASTARTER-0007