// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run SsmRepeatedPublishStateStep tests

LOAD_SUITE tssm_server

START_TESTCASE 			DEVSRVS-SSMA-SSM-0022
//! @SYMTestCaseID 		DEVSRVS-SSMA-SSM-0022
//! @SYMPREQ 			PREQ1871
//! @SYMREQ			REQ9126
//! @SYMTestCaseDesc		Checks repeated publish system state commands work in the presence of a fire and forget command
//! @SYMTestType		CIT	
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies	See tssm_statepolicy_repeatedpublishstate.cpp file
//! @SYMTestActions		The test will attempt to do repeated publish state commands in the presense of a fire and forget custom command.
//! @SYMTestExpectedResults 	SsmServer correctly handles the combination of requests and does not deadlock, panic or fail any publish states.
RUN_TEST_STEP 100 tssm_server SsmRepeatedPublishStateStep
END_TESTCASE 			DEVSRVS-SSMA-SSM-0022