// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run SsmPanicCleStep tests

LOAD_SUITE tssm_server

START_TESTCASE 			DEVSRVS-SSMA-SSM-0017
//! @SYMTestCaseID 		DEVSRVS-SSMA-SSM-0017
//! @SYMPREQ 			PREQ1871
//! @SYMREQ			REQ9136
//! @SYMTestCaseDesc		Check that same a cmd list that panics Cle does not affect ssmserver.
//! @SYMTestType		CIT	
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies	See tssm_statepolicy_paniccle.cpp file
//! 				See tssm_swppolicy_paniccle.cpp file
//! @SYMTestActions		The test will define two (statePluginPanicCle, one swpPluginPanicCle) plug-in dll which will just consist on one single command to publish the swp or state, plus another custom command tthat will simple panic (and with it, panic Cle).
//! 				1.The test will map a test swp to this swpPluginPanicCle plugin, and will request a change to its value. 
//! 				2.The test will request a change that will load statePluginDependency.  
//! @SYMTestExpectedResults 	In both cases, the cmd list panics with the known panic code in the custom command, panic'ing the Cle with it. 
//! 				Despite the panic, SsmServer is able to internally reconnect and further swp or state transitions work as expected.
RUN_TEST_STEP 100 tssm_server SsmPanicCleStep
END_TESTCASE 			DEVSRVS-SSMA-SSM-0017