// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run SsmSwpDependenciesStep tests

LOAD_SUITE tssm_server

START_TESTCASE 			DEVSRVS-SSMA-SSM-0016
//! @SYMTestCaseID 		DEVSRVS-SSMA-SSM-0016
//! @SYMPREQ 			PREQ1871
//! @SYMREQ			REQ9122
//! @SYMTestCaseDesc		Check that same a plug-in dll can include a cmd to request a swp change.
//! @SYMTestType		CIT	
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies	See tssm_statepolicy_swpdependency.cpp file
//! 				See tssm_swppolicy_swpdependency.cpp file
//! @SYMTestActions		The test will define two (statePluginDependency, one swpPluginDependency) plug-in dll which will just consist on one single command to publish the swp or state, plus another command to request a swp change for a user defined swp (simulating a dependent swp, swpDepen).
//! 					1.The test will map a test swp to this swpPluginDependency plugin, and will request a change to its value. The value of the swp is checked before and after the request.
//! 					2.The test will request a change for a state that will do the equivalent for states, that is, request a change that will load statePluginDependency.  
//! @SYMTestExpectedResults 	In both cases, the value of swpDepen is checked before and after the swp or state request, and found that after the request, 
//! 				apart from the swp and state change, the value of swpDepen is updated according to the affected policy.
RUN_TEST_STEP 100 tssm_server SsmSwpDependenciesStep
END_TESTCASE 			DEVSRVS-SSMA-SSM-0016