// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run SsmNotifyPropertyChangeStep tests

LOAD_SUITE tssm_server

START_TESTCASE 			DEVSRVS-SSMA-SSM-0020
//! @SYMTestCaseID 		DEVSRVS-SSMA-SSM-0020
//!  @SYMPREQ 			DEF119566
//!  @SYMTestType		CIT
//!  @SYMTestPriority		Critical
//!  @SYMTestStatus 		Implemented
//!  @SYMTestCaseDesc		Check behaviour of swp aware session classes  RSsmSystemWideProperty & CSsmSystemWideProperty
//!  @SYMTestActions		The test will check if swp change notifications are received by all subscribers.
//!  					1. Create a swp.
//!  					2. Add subscribers through CSsmSystemWideProperty::AddSubscriberL().
//! 					3. Request for a change in swp through RSsmStateManager.
//! 					4. Check that upon notification NotifySubscribers() performs appropriate action. 
//!  @SYMTestExpectedResults 	Following results are expected:
//! 					Added subscribers are notified appropriately
RUN_TEST_STEP 100 tssm_server SsmNotifyPropertyChangeStep
END_TESTCASE 			DEVSRVS-SSMA-SSM-0020