//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_SCRIPT z:\TestData\Scripts\Te_SimVoice_setup.script
//
LOAD_SUITE Te_SimVoice
//
START_TESTCASE TEL-SIMTSY-VOICE-1000
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1000
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Status Incomming Call
//!@SYMTestPriority critical
//!@SYMTestActions Test the line status of an incomming call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 90 Te_SimVoice TestLineStatusIncommingCall
//
END_TESTCASE TEL-SIMTSY-VOICE-1000


START_TESTCASE TEL-SIMTSY-VOICE-1001
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1001
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Notifications Incomming Call
//!@SYMTestPriority critical
//!@SYMTestActions Test the line notifications of an incomming call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 30 Te_SimVoice TestLineNotificationsIncommingCall
//
END_TESTCASE TEL-SIMTSY-VOICE-1001


START_TESTCASE TEL-SIMTSY-VOICE-1002
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1002
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Call Notifications Incomming Call
//!@SYMTestPriority critical
//!@SYMTestActions  Test the call notification of an incomming call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 30 Te_SimVoice TestCallNotificationsIncommingCall
//
END_TESTCASE TEL-SIMTSY-VOICE-1002


START_TESTCASE TEL-SIMTSY-VOICE-1003
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1003
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test call notifications out going call
//!@SYMTestPriority critical
//!@SYMTestActions Test call notifications of out going call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 30 Te_SimVoice TestCallNotificationsOutgoingCall
//
END_TESTCASE TEL-SIMTSY-VOICE-1003


START_TESTCASE TEL-SIMTSY-VOICE-1004
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1004
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Notifications Outgoing call
//!@SYMTestPriority critical
//!@SYMTestActions Test Line Notifications of Outgoing Calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 60 Te_SimVoice TestLineNotificationsOutgoingCall
//
END_TESTCASE TEL-SIMTSY-VOICE-1004


START_TESTCASE TEL-SIMTSY-VOICE-1005
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1005
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Status Outgoing Call
//!@SYMTestPriority critical
//!@SYMTestActions Test Line Status of a Outgoing Call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 90 Te_SimVoice TestLineStatusOutgoingCall
//
END_TESTCASE TEL-SIMTSY-VOICE-1005


START_TESTCASE TEL-SIMTSY-VOICE-1006
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1006
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Call Status Outgoing Call
//!@SYMTestPriority critical
//!@SYMTestActions Test Call Status of Outgoing Calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 60 Te_SimVoice TestCallStatusOutgoingCall
//
END_TESTCASE TEL-SIMTSY-VOICE-1006


START_TESTCASE TEL-SIMTSY-VOICE-1007
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1007
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Call Status Incomming Call
//!@SYMTestPriority critical
//!@SYMTestActions Test Call Status of an Incomming Call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 60 Te_SimVoice TestCallStatusIncommingCall
//
END_TESTCASE TEL-SIMTSY-VOICE-1007


START_TESTCASE TEL-SIMTSY-VOICE-1008
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1008
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Info
//!@SYMTestPriority critical
//!@SYMTestActions Test Line Information
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 60 Te_SimVoice TestLineInfo
//
END_TESTCASE TEL-SIMTSY-VOICE-1008


START_TESTCASE TEL-SIMTSY-VOICE-1009
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1009
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Call Cancels
//!@SYMTestPriority critical
//!@SYMTestActions Test cancellation of calls
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 30 Te_SimVoice TestCallCancels
//
END_TESTCASE TEL-SIMTSY-VOICE-1009


START_TESTCASE TEL-SIMTSY-VOICE-1010
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1010
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Tes tLine Cancels
//!@SYMTestPriority critical
//!@SYMTestActions Test Line Cancellation
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 30 Te_SimVoice TestLineCancels
//
END_TESTCASE TEL-SIMTSY-VOICE-1010


START_TESTCASE TEL-SIMTSY-VOICE-1011
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1011
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test More Call Info
//!@SYMTestPriority critical
//!@SYMTestActions Test More Call Information
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 120 Te_SimVoice TestMoreCallInfo
//
END_TESTCASE TEL-SIMTSY-VOICE-1011


START_TESTCASE TEL-SIMTSY-VOICE-1012
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1012
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Call Info
//!@SYMTestPriority critical
//!@SYMTestActions Test Call Information
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 60 Te_SimVoice TestCallInfo
//
END_TESTCASE TEL-SIMTSY-VOICE-1012


START_TESTCASE TEL-SIMTSY-VOICE-1013
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1013
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc TestPhoneInfo
//!@SYMTestPriority critical
//!@SYMTestActions Test Phone Information
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 30 Te_SimVoice TestPhoneInfo
//
END_TESTCASE TEL-SIMTSY-VOICE-1013


START_TESTCASE TEL-SIMTSY-VOICE-1014
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1014
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc  Test Dtmf
//!@SYMTestPriority critical
//!@SYMTestActions Tests Dtmf functionality
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 90 Te_SimVoice TestDtmf
//
END_TESTCASE TEL-SIMTSY-VOICE-1014


START_TESTCASE TEL-SIMTSY-VOICE-1015
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1015
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Call Duration
//!@SYMTestPriority critical
//!@SYMTestActions Test the duration of a call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 240 Te_SimVoice TestCallDuration
END_TESTCASE TEL-SIMTSY-VOICE-1015


START_TESTCASE TEL-SIMTSY-VOICE-1016
//!@SYMTestCaseID TEL-SIMTSY-VOICE-1016
//!@SYMREQ EC-47
//!@SYMTestCaseDesc  Test Remote Hangup 
//!@SYMTestPriority critical
//!@SYMTestActions Tests Remote Hang-Up simulation
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 90 Te_SimVoice TestRemoteHangup
//
END_TESTCASE TEL-SIMTSY-VOICE-1016

