// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SERVER TestServerSymbianExcludeBt

START_TESTCASE BT-INC-ROMCONFIG-USER-004
//! @SYMTestCaseID BT-INC-ROMCONFIG-USER-004
//! @SYMTestCaseDesc RHCIDirectAccess can be opened
//! on a standard Techview ROM
//! @SYMREQ 5413
//! @SYMTestType CIT
//! @SYMTestPriority 3
//! @SYMTestStatus Implemented
//! @SYMTestActions Call RHCIDirectAccess::Open
//! @SYMTestExpectedResults Returns KErrNone
RUN_TEST_STEP 10 TestServerSymbianExcludeBt BT_ROMCONFIG_USER_004 c:\testdata\btromconfig\BtRomConfig.ini BluetoothIncluded
END_TESTCASE BT-INC-ROMCONFIG-USER-004

