// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SERVER TestServerSymbianExcludeBt

START_TESTCASE BT-INC-ROMCONFIG-SDPAGENT-001
//! @SYMTestCaseID BT-ROMCONFIG-SDPAGENT-001
//! @SYMTestCaseDesc Can use CSdpAgent
//! on a standard Techview ROM
//! @SYMREQ 5413
//! @SYMTestType CIT
//! @SYMTestPriority 3
//! @SYMTestStatus Implemented
//! @SYMTestActions Construct CSdpAgent, set a search pattern and call NextRecordRequestL()
//! @SYMTestExpectedResults Constructs successfully
RUN_TEST_STEP 10 TestServerSymbianExcludeBt BT_ROMCONFIG_SDP_AGENT_001 c:\testdata\btromconfig\BtRomConfig.ini BluetoothIncluded
END_TESTCASE BT-INC-ROMCONFIG-SDPAGENT-001

