// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SERVER TestServerSymbianExcludeBt

START_TESTCASE BT-ROMCONFIG-SDP-001
//! @SYMTestCaseID BT-ROMCONFIG-SDP-001
//! @SYMTestCaseDesc Cannot connect to RSdp
//! on a !__BT ROM
//! @SYMREQ 5413
//! @SYMTestType CIT
//! @SYMTestPriority 1
//! @SYMTestStatus Implemented
//! @SYMTestActions Call RSdp::Connect
//! @SYMTestExpectedResults Returns KErrNotFound as sdpserver.exe is missing from ROM
RUN_TEST_STEP 10 TestServerSymbianExcludeBt BT_ROMCONFIG_SDP_001 c:\testdata\btromconfig\BtRomConfig.ini BluetoothExcluded
END_TESTCASE BT-ROMCONFIG-SDP-001

