// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SERVER TestServerSymbianExcludeBt

START_TESTCASE BT-ROMCONFIG-RSocket-001
//! @SYMTestCaseID BT-ROMCONFIG-RSocket-0001
//! @SYMTestCaseDesc RSocket::Open should fail for Infra-Red protocols
//! on a !__BT ROM
//! @SYMREQ 5413
//! @SYMTestType CIT
//! @SYMTestPriority 1
//! @SYMTestStatus Implemented
//! @SYMTestActions Call RSocket::Open specifying a Bluetooth protocol
//! @SYMTestExpectedResults Returns an error, as bt_v2.prt has been removed from ROM.
//! Exact error code depends on which overload of Open has been used
RUN_TEST_STEP 10 TestServerSymbianExcludeBt BT_ROMCONFIG_RSocket_001 c:\testdata\btromconfig\BtRomConfig.ini BluetoothExcluded
END_TESTCASE BT-ROMCONFIG-RSocket-001

