//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
//! @file
//! @SYMTestSuiteName APPFWK-SYSMON
// 

//
LOAD_SERVER tsysmon_server
//

//! @SYMTestCaseID 		DEVSRVS-SHMA-SYSMON-0039
//! @SYMPREQ 			PREQ1089 PREQ1871
//! @SYMREQ			REQ6599 REQ9457
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies	appfwk-sysmon-0039_<emulator|hardware>0.rsc must be used in place of SSCForStartupMode0.rsc
//! @SYMTestCaseDesc		Trigger a system restart, attempt to register a process
//! @SYMTestActions		Register a process with the 'ERestartOS' failure policy and retry count of 0.
//! Fail the process then immediately attempt to register another process. (The required capabilities are held.)
//! @SYMTestExpectedResults 	The attempt to register the process returns 'KErrCancel'. The device restarts.
//
START_TESTCASE DEVSRVS-SHMA-SYSMON-0039
RUN_TEST_STEP 100 tsysmon_server ResultCheck z:\shmatest\configs\tsysmon.ini APPFWK-SYSMON-0039
END_TESTCASE DEVSRVS-SHMA-SYSMON-0039
