// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run OOMSYSMON test 

LOAD_SUITE tsysmon_server

START_TESTCASE 			DEVSRVS-SHMA-SYSMON-0062
//! @SYMTestCaseID 		DEVSRVS-SHMA-SYSMON-0062
//! @SYMPREQ			PREQ1871
//! @SYMREQ			REQ9457
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus		Implemented
//! @SYMTestCaseDesc		OOM Test for RSysMonSession API's.
//! @SYMTestActions		Call RSysMonSession::OpenL, MonitorL() and CancelMonitorSelfL() under
//!  				out of memory conditions.
//! @SYMTestExpectedResults 	Test should complete without any memory leaks.
RUN_TEST_STEP 100 tsysmon_server OomSysMon
END_TESTCASE 			DEVSRVS-SHMA-SYSMON-0062