// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run LoadSysMon test 

LOAD_SUITE tsysmon_server

START_TESTCASE 			DEVSRVS-SHMA-SYSMON-0057
//! @SYMTestCaseID 		DEVSRVS-SHMA-SYSMON-0057
//! @SYMPREQ			PREQ1871
//! @SYMREQ			REQ9457
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestStatus		Implemented
//! @SYMTestCaseDesc		To Check the functionality of sysmon monitor using loadsysmon.dll
//! @SYMTestActions		1. Create a test application
//!  				2. Test app loads the loadsysmon.dll
//!  				3. Test app opens a session with sysmoncli using loadsysmon interface.
//!  				4. Test app tests the monitoring functionality of sysmoncli using the 
//!  					loadsysmon interface.
//!  				5. Test app closes the sysmoncli session.
//! 				6. Test steps 3 to 5 are carried out twice once using startupproperties and 
//! 					then with ssmstartupproperties.
//!  				7. Test app is closed.
//! @SYMTestExpectedResults Test Application should be terminated with KErrNone. 	
RUN_TEST_STEP 100 tsysmon_server LoadSysMon
END_TESTCASE 			DEVSRVS-SHMA-SYSMON-0057