//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
//! @file
//! @SYMTestSuiteName APPFWK-SYSMON
// 

//
LOAD_SERVER tsysmon_server
//

//! @SYMTestCaseID 		DEVSRVS-SHMA-SYSMON-0043
//! @SYMPREQ 			PREQ1089 PREQ1871
//! @SYMREQ			REQ6604 REQ9457
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies	appfwk-sysmon-0043_<emulator|hardware>0.rsc is merged with criticalappscmdlist.rsc
//! @SYMTestCaseDesc		Use the new startup configuration format to register for process monitoring, with 'EIgnoreOnFailure' policy.
//! @SYMTestActions		Create a startup configuration that includes a process with the 'EIgnoreOnFailure' policy in the ESsmStateStartingCriticalApps state.
//! Boot the device.
//! @SYMTestExpectedResults 	The process should be registered with the parameters defined in the startup configuration.
//
START_TESTCASE DEVSRVS-SHMA-SYSMON-0043
RUN_TEST_STEP 100 tsysmon_server ResultCheck z:\shmatest\configs\tsysmon.ini 43
END_TESTCASE DEVSRVS-SHMA-SYSMON-0043
