//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
//! @file
//! @SYMTestSuiteName APPFWK-SYSMON
// 

//
LOAD_SERVER tsysmon_server
//

//! @SYMTestCaseID 		DEVSRVS-SHMA-SYSMON-0036
//! @SYMPREQ 			PREQ1089 PREQ1871
//! @SYMREQ			REQ6597 REQ6760 REQ9457
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies	appfwk-sysmon-0036_<emulator|hardware>0.rsc must be used in place of SSCForStartupMode0.rsc
//! @SYMTestCaseDesc		Register a process for monitoring with retry limit = 1 and 'ERestartOSWithMode' policy, fail the process
//! @SYMTestActions		A process is registered with the 'ERestartOSWithMode' policy.
//! Fail the process.
//! SysMon attempts to restart the process.
//! The attempt to restart the process fails.
//! @SYMTestExpectedResults 	The system is restarted in the specified Start-up mode. In debug builds, the failure to restart the process will be written to a log file. The slave process will have been run twice.
//
START_TESTCASE DEVSRVS-SHMA-SYSMON-0036
RUN_TEST_STEP 100 tsysmon_server RunCountCheck z:\shmatest\configs\tsysmon.ini APPFWK-SYSMON-0036
END_TESTCASE DEVSRVS-SHMA-SYSMON-0036
