// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run ProcRestart test 

LOAD_SUITE tsysmon_server

START_TESTCASE 			DEVSRVS-SHMA-SYSMON-0003
//! @SYMTestCaseID 		DEVSRVS-SHMA-SYSMON-0003
//! @SYMPREQ 			PREQ1089 PREQ1871
//! @SYMREQ			REQ6595 REQ9457 REQ9266 REQ9161
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		A process can be restarted on failure.
//! 				A process’s failure policy will be enacted if the rate of failure exceeds the relaunch rate of failure interval.
//! 				A process can be restarted on failure, if the rate of failure doesn’t exceed the relaunch rate of failure interval.
//! @SYMTestActions		DoTestProcRestartL() 1. Start TestApp as a process from test-execute test. 
//! 					2. Call RSysMonSession::Monitor() using startupproperties for this process, with all possible startmethods
//! 					   retry count = 1, and EIgnoreProcessFailure. 
//! 					3. Kill the process 
//! 					5. System Monitor should restart the process after KWaitTime (15s). 
//! 					6. Verify that the process is restarted.
//! 					7. Cleanup 
//! 					8. Repeat steps 1-7 usng ssmstartupproperties
//! 				DoTestProcRestartAferRateOfFailureL() 1. Start TestApp as a process from test-execute test. 
//! 					2. Call RSysMonSession::Monitor() for this process, with all possible startmethods
//! 					   retry count = 1, and EIgnoreProcessFailure. 
//! 					3. Kill the process 
//! 					4. System Monitor should restart the process after KWaitTime (15s). 
//! 					5. Verify that the process is restarted and monitored.
//! 					6. Repeat steps 3-5.
//! 					7. Repeat steps 3-5.
//! 					8. Verify that the process is not restarted.(as the rate of failure exceeds the system monitor's rate of relaunch policy)
//! 					9. Cleanup 
//! 				DoTestProcRestartForRateOfFailureL() 1. Start TestApp as a process from test-execute test. 
//! 					2. Call RSysMonSession::Monitor() for this process, with all possible startmethods
//! 					retry count = 1, and EIgnoreProcessFailure. 
//! 					3. Kill the process 
//! 					4. System Monitor should restart the process after KWaitTime (15s). 
//! 					5. Verify that the process is restarted and monitored.
//! 					6. Repeat steps 3-5.
//! 					7. Wait for KIntervalForReLaunchRateOfFailure and Kill the process
//! 					8. Verify that the process is restarted.
//! 					9. Cleanup 
//! @SYMTestExpectedResults 	pass
//! 				The SysMon doesn’t attempt to restart the process.
//! 				The SysMon attempts to restart the process. The process will successfully start and rendezvous.
RUN_TEST_STEP 500 tsysmon_server ProcRestart
END_TESTCASE 			DEVSRVS-SHMA-SYSMON-0003



