//
// Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
//! @file
//! @SYMTestSuiteName APPFWK-SYSMON
// 

//
LOAD_SERVER tsysmon_server
//

//! @SYMTestCaseID 		DEVSRVS-SHMA-SYSMON-0038
//! @SYMPREQ 			PREQ1089 PREQ1871
//! @SYMREQ			REQ6600 REQ6603 REQ6830 REQ9457
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies	appfwk-sysmon-0038_<emulator|hardware>0.rsc is merged with noncriticalcmdlist.rsc
//! @SYMTestCaseDesc		Register a process for monitoring with retry limit = 2, fail the process twice with a pause
//! @SYMTestActions		A process is registered. Failure policy is not important.
//! Fail the process.
//! The process will be restarted.
//! Wait {patchable constant} (default 15) seconds.
//! Fail the process again.
//! @SYMTestExpectedResults 	The process is restarted again immediately, and reregistered.
//
START_TESTCASE DEVSRVS-SHMA-SYSMON-0038
RUN_TEST_STEP 100 tsysmon_server ResultCheck z:\shmatest\configs\tsysmon.ini 38
END_TESTCASE DEVSRVS-SHMA-SYSMON-0038
