//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
//! @file
//! @SYMTestSuiteName APPFWK-SYSMON
// 

//
LOAD_SERVER tsysmon_server
//

//! @SYMTestCaseID 		DEVSRVS-SHMA-SYSMON-0060
//! @SYMPREQ 			PREQ1871
//! @SYMREQ			REQ9457 REQ9107
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies
//! @SYMTestCaseDesc	A process registers itself for monitoring, with 'ECriticalNoRetries' policy, with the ProtServ capability
//! @SYMTestActions		The process must have the ProtServ PlatSec capability.
//! Open a connection to the SysMon process. (This will return 'KErrNone'.)
//! Attempt to self-register with the 'ECriticalNoRetries' policy.
//! @SYMTestExpectedResults 	The process is registered. This is confirmed by the attempt to register the process returning 'KErrNone'.
//
START_TESTCASE DEVSRVS-SHMA-SYSMON-0060
RUN_PROGRAM 100 setcap tsysmon_app_selfregister.exe 100 sysmontest_selfregister_protserv.exe
RUN_TEST_STEP 100 tsysmon_server Register z:\shmatest\configs\tsysmon.ini APPFWK-SYSMON-0060
END_TESTCASE DEVSRVS-SHMA-SYSMON-0060
