//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
//! @file
//! @SYMTestSuiteName APPFWK-SYSMON
// 

//
LOAD_SERVER tsysmon_server
//

//! @SYMTestCaseID 		DEVSRVS-SHMA-SYSMON-0025
//! @SYMPREQ 			PREQ1089 PREQ1871
//! @SYMREQ			REQ6595 REQ6597 REQ9457
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies
//! @SYMTestCaseDesc	Register a process for monitoring, with 'ERestartOSWithMode' policy, with correct PlatSec capabilities
//! @SYMTestActions		The process to be registered must be running. The process to register the monitoring must have the ProtServ and PowerMgmnt PlatSec capabilities.
//! Open a connection to the SysMon process. (This will return 'KErrNone'.)
//! Attempt to register the process with the 'ERestartOSWithMode' policy.
//! @SYMTestExpectedResults 	The process that was to be monitored is registered. This is confirmed by the attempt to register the process returning 'KErrNone'.
//
START_TESTCASE DEVSRVS-SHMA-SYSMON-0025
RUN_PROGRAM 100 setcap tsysmon_app_register.exe 104 sysmontest_register_protserv+powermgmt.exe
RUN_TEST_STEP 100 tsysmon_server Register z:\shmatest\configs\tsysmon.ini APPFWK-SYSMON-0025
END_TESTCASE DEVSRVS-SHMA-SYSMON-0025
