//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
//! @file
//! @SYMTestSuiteName APPFWK-SYSMON
// 

//
LOAD_SERVER tsysmon_server
//

//! @SYMTestCaseID 		DEVSRVS-SHMA-SYSMON-0046
//! @SYMPREQ 			PREQ1089
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestCaseDependencies	appfwk-sysmon-0046_<emulator|hardware>0.rsc must be used in place of SSCForStartupMode0.rsc
//! @SYMTestCaseDesc		Use the new startup configuration format to register for process monitoring, with 'ERestartOS' policy, have the process fail during startup.
//! @SYMTestActions		Create a SSC file which will contain an item for a test application with EStartupProcess2, EWaitForStart, retry count = 0, ERestartOS, and monitor = 1. The test application will be in the Critical Static section.
//! The test application records a count in a file to check whether it is being loaded first time or second time.
//! First time SysStart loads the test application; it should not rendezvous successfully, causing the system to restart. 
//! After restarting when SysStart loads the test process again it should succeed.
//! A test-execute test should check this count value.
//! @SYMTestExpectedResults 	The count value should be 2.
//
START_TESTCASE DEVSRVS-SHMA-SYSMON-0046
RUN_TEST_STEP 100 tsysmon_server RunCountCheck z:\shmatest\configs\tsysmon.ini APPFWK-SYSMON-0046
END_TESTCASE DEVSRVS-SHMA-SYSMON-0046
