//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
// CAUTION: This script is *NOT* intended to be invoked directly.  Instead, it is to be called
// by another script that sets up a suitable environment in which to run the test cases.
// This includes:
// - loading a suitable test_esock_ip.ini
// - loading a suitable CommDB configuration
// - starting up / shutting down the ESockSvr

// This script contains the set of test cases that:
// - require a connection to a test network
// - do *NOT* perform memory (OOM, Out of MBuf, Alloc Heaven, etc) testing.
// - utilize IPv6 addressing

LOAD_SUITE TE_Esock

RUN_TEST_STEP 10 TE_Esock OpenServer   

PRINT TE_ESock: Net tests - IPv6


START_TESTCASE			COMINF-ESOCK-2706
//! @SYMTestCaseID		COMINF-ESOCK-2706

// run test 27.6 Test Query of 'AAAA' type.
RUN_TEST_STEP 10 TE_Esock Test27.6 z:\testdata\configs\test_esock_ip6.ini
END_TESTCASE			COMINF-ESOCK-2706


START_TESTCASE			COMINF-ESOCK-2801
//! @SYMTestCaseID		COMINF-ESOCK-2801

RUN_TEST_STEP 500 TE_Esock Test28.1 z:\testdata\configs\test_esock_ip6.ini
END_TESTCASE			COMINF-ESOCK-2801


START_TESTCASE			COMINF-ESOCK-2802
//! @SYMTestCaseID		COMINF-ESOCK-2802

RUN_TEST_STEP 20 TE_Esock Test28.2 z:\testdata\configs\test_esock_ip6.ini
END_TESTCASE			COMINF-ESOCK-2802


RUN_TEST_STEP 10 TE_Esock CloseServer
