//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
// CAUTION: This script is *NOT* intended to be invoked directly.  Instead, it is to be called
// by another script that sets up a suitable environment in which to run the test cases.
// This includes:
// - loading a suitable test_esock_ip.ini
// - loading a suitable CommDB configuration
// - starting up / shutting down the ESockSvr

// This script contains the set of test cases that:
// - do not require a connection to a test network
// - perform memory (OOM, Out of MBuf, Alloc Heaven, etc) testing.

LOAD_SUITE TE_Esock 

RUN_TEST_STEP 10 TE_Esock OpenServer

PRINT TE_Esock: Memory tests 


START_TESTCASE			COMINF-ESOCK-1104
//! @SYMTestCaseID		COMINF-ESOCK-1104

RUN_TEST_STEP 20 TE_Esock Test11.4
END_TESTCASE			COMINF-ESOCK-1104


START_TESTCASE			COMINF-ESOCK-2505
//! @SYMTestCaseID		COMINF-ESOCK-2505

RUN_TEST_STEP 20 TE_Esock Test25.5
END_TESTCASE			COMINF-ESOCK-2505


START_TESTCASE			COMINF-ESOCK-2901
//! @SYMTestCaseID		COMINF-ESOCK-2901

//RUN_TEST_STEP 10 TE_Esock CloseServer
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesockForced.script
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
//RUN_TEST_STEP 10 TE_Esock OpenServer

RUN_TEST_STEP 20 TE_Esock Test29 z:\testdata\configs\test_esock_29_1.ini
END_TESTCASE			COMINF-ESOCK-2901


START_TESTCASE			COMINF-ESOCK-2902
//! @SYMTestCaseID		COMINF-ESOCK-2902

//RUN_TEST_STEP 10 TE_Esock CloseServer
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesockForced.script
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
//RUN_TEST_STEP 10 TE_Esock OpenServer

RUN_TEST_STEP 60 TE_Esock Test29 z:\testdata\configs\test_esock_29_2.ini
END_TESTCASE			COMINF-ESOCK-2902


START_TESTCASE			COMINF-ESOCK-2910
//! @SYMTestCaseID		COMINF-ESOCK-2910

//RUN_TEST_STEP 10 TE_Esock CloseServer
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesockForced.script
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
//RUN_TEST_STEP 10 TE_Esock OpenServer

RUN_TEST_STEP 20 TE_Esock Test29.10
END_TESTCASE			COMINF-ESOCK-2910


START_TESTCASE			COMINF-ESOCK-2911
//! @SYMTestCaseID		COMINF-ESOCK-2911

//RUN_TEST_STEP 20 TE_Esock CloseServer
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesockForced.script
//RUN_SCRIPT z:\testdata\scripts\te_esock_test_loadesock.script
//RUN_TEST_STEP 10 TE_Esock OpenServer

RUN_TEST_STEP 10 TE_Esock Test29.11
END_TESTCASE			COMINF-ESOCK-2911

RUN_TEST_STEP 10 TE_Esock CloseServer
