// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// This test script is running against code coverage.
// 
//


RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32ForcedForced.script

PRINT TE_c32_Componentsr: Code Coverage
PRINT ----------------------------------
PRINT

RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32ForcedForced.script

PRINT TE_c32_Componentsr: Component Tests
PRINT ----------------------------------
PRINT

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config1.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 2 only single Threaded cmi file is present in the private dir
PRINT ------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config2.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 3 new multi threaded cmi file only one dealer is present in the private dir
PRINT ------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config3.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 4 old and new cmi files set ROLE=PLAYER
PRINT ------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config4.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 16 all player thread sharing dealer heap, all player cmi files set EShareHeap with Dealer thread
PRINT ---------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config17.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script


PRINT Group 5 new set fo multi threaded cmi files.
PRINT ---------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config5.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_14_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

//Blocking CSY:- Blocking one player thread and Read/Write perform on another player thread.
//LOOPBACK is loaded on the player thread (WorkerId=1) and DummyCsy12 is loaded on the another player Thread (WorkerId=3) both cmi files set to OnDemand=1
PRINT Group 5 new set fo multi threaded cmi files.
PRINT ---------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config5.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_17_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 6 Two cmi files set wild card.
PRINT ----------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config6.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_2_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 2 RUN on Single threaded cmi files.
PRINT ----------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config2.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_3_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 4 old cmi and new cmi set all player
PRINT ------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config4.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_4_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 7 old and new cmi files new cmi file set ROLE=Player and ROLE=Dealer.
PRINT --------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config8.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_5_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 10 Two new cmi file set ROLE=Dealer (Negative test case)
PRINT -------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config11.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_8_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 11 old cmi file and new cmi file set ROLE=Dealer
PRINT --------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config12.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_9_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 15 cmi files contain unsequential workerID 
PRINT --------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config16.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_13_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

//This is the negative test case and which it leads to memory leak. 
PRINT Group 5 new set fo multi threaded cmi files.
PRINT -----------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config5.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_16_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 8 all cmi file set ROLE=Player (Negative Test Case) This group is Depricated
PRINT ----------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config9.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_6_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 9 Two new cmi file set same WorkerID.(Negative Test Case)
PRINT ----------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config10.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_7_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 12 Role parameter is missing in the new set of cmi file(Negative test case)
PRINT -------------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config13.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_10_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 13 CSY List is missing ROLE=Player in the New set of cmi file(Negative test case)
PRINT --------------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config14.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_11_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 14 worker id is missing in New set of cmi file.(Negative test case)
PRINT --------------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config15.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_12_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script


PRINT Group 15 Trying to load a csy in a Unknown CPM in cmi c32_fourth.cmi FileName=C32Test.dll
PRINT ----------------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config7.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_15_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 18 Running DummyTest with MarkHeap and MarkEnd in single thread
PRINT ----------------------------------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config2.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config18.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_18_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script


PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script



PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script


PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script


PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

PRINT Group 1 default cmi files are present in the private dir
PRINT ---------------------------------------------------------
PRINT
RUN_SCRIPT z:\testdata\scripts\te_c32mt_copy_TestC32Config19.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_loadc32.script
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32MT_GROUP_1_SUITE.SCRIPT
RUN_SCRIPT z:\testdata\scripts\TestExecute\TE_C32_NO_PORTS.script
RUN_SCRIPT z:\testdata\scripts\te_c32_test_unloadc32Forced.script
RUN_SCRIPT z:\testdata\scripts\te_c32mt_test_remove_config_files.script

