//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run SUPL Protocol UNIT suite te_suplprotocol


RUN_UTILS DeleteFile c:\config.txt
RUN_UTILS CopyFile c:\testdata\configs\lbssuplconfig.txt c:\config.txt


LOAD_SUITE Te_suplprotocolSuite



START_TESTCASE                LBS-UT-SUPL-PLUGIN-0001
//! @SYMTestCaseID              LBS-UT-SUPL-PLUGIN-0001
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite plugin1Step 
END_TESTCASE                  LBS-UT-SUPL-PLUGIN-0001


START_TESTCASE                LBS-UT-SUPL-PLUGIN-0002
//! @SYMTestCaseID              LBS-UT-SUPL-PLUGIN-0002
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite plugin2Step 
END_TESTCASE                  LBS-UT-SUPL-PLUGIN-0002


START_TESTCASE                LBS-UT-SUPL-MOLR-0001
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0001
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr1Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0001


START_TESTCASE                LBS-UT-SUPL-MOLR-0002
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0002
//! @SYMTestCaseDesc            MOLR basic procedure followed - Assistance Data in RRLP message
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr2Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0002


START_TESTCASE                LBS-UT-SUPL-MOLR-0003
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0003
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr3Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0003


START_TESTCASE                LBS-UT-SUPL-MOLR-0004
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0004
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr4Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0004


START_TESTCASE                LBS-UT-SUPL-MOLR-0005
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0005
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr5Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0005


START_TESTCASE                LBS-UT-SUPL-MOLR-0006
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0006
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr6Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0006


START_TESTCASE                LBS-UT-SUPL-MOLR-0007
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0007
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr7Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0007


START_TESTCASE                LBS-UT-SUPL-MOLR-0008
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0008
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr8Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0008


START_TESTCASE                LBS-UT-SUPL-MOLR-0009
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0009
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr9Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0009


START_TESTCASE                LBS-UT-SUPL-MOLR-0010
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0010
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr10Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0010


START_TESTCASE                LBS-UT-SUPL-MOLR-0011
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0011
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr11Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0011


START_TESTCASE                LBS-UT-SUPL-MOLR-0012
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0012
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr12Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0012


START_TESTCASE                LBS-UT-SUPL-MOLR-0013
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0013
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr13Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0013


START_TESTCASE                LBS-UT-SUPL-MOLR-0014
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0014
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr14Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0014


START_TESTCASE                LBS-UT-SUPL-MOLR-0015
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0015
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr15Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0015


START_TESTCASE                LBS-UT-SUPL-MOLR-0016
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0016
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr16Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0016


START_TESTCASE                LBS-UT-SUPL-MOLR-0017
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0017
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr17Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0017


START_TESTCASE                LBS-UT-SUPL-MOLR-0018
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0018
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr18Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0018


START_TESTCASE                LBS-UT-SUPL-MOLR-0019
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0019
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr19Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0019


START_TESTCASE                LBS-UT-SUPL-MOLR-0020
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0020
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr20Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0020


START_TESTCASE                LBS-UT-SUPL-MOLR-0021
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0021
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr21Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0021


START_TESTCASE                LBS-UT-SUPL-MOLR-0022
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0022
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr22Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0022


START_TESTCASE                LBS-UT-SUPL-MOLR-0023
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0023
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr23Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0023


START_TESTCASE                LBS-UT-SUPL-MOLR-0024
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0024
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr24Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0024


START_TESTCASE                LBS-UT-SUPL-MOLR-0025
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0025
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr25Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0025


START_TESTCASE                LBS-UT-SUPL-MOLR-0026
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0026
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr26Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0026


START_TESTCASE                LBS-UT-SUPL-MOLR-0028
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0028
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr28Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0028


START_TESTCASE                LBS-UT-SUPL-MOLR-0029
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0029
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr29Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0029


START_TESTCASE                LBS-UT-SUPL-MOLR-0030
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0030
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr30Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0030



START_TESTCASE                LBS-UT-SUPL-MOLR-0031
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0031
//! @SYMTestCaseDesc            MOLR, Cell Based - connection terminated by server after SUPL END
//! @SYMTestPriority            High
//! @SYMTestType                UT
//! @SYMCreationDate            10/9/2008
//! @SYMAuthor                  juanmr
RUN_TEST_STEP 100 Te_suplprotocolSuite molr31Step
END_TESTCASE                  LBS-UT-SUPL-MOLR-0031



START_TESTCASE                LBS-UT-SUPL-MOLR-0032
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0032
//! @SYMTestCaseDesc            MOLR - session cancelled due unsupported pos method in RRLP request
//! @SYMTestPriority            High
//! @SYMTestType                UT
//! @SYMCreationDate            10/9/2008
//! @SYMAuthor                  juanmr
RUN_TEST_STEP 100 Te_suplprotocolSuite molr32Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0032



START_TESTCASE                LBS-UT-SUPL-MOLR-0033
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0033
//! @SYMTestCaseDesc            MOLR basic procedure followed - empty assistance data request
//! @SYMTestPriority            High
//! @SYMTestExpectedResults     Test passes
//! @SYMTestType                UT
//! @SYMCreationDate            10/9/2008
//! @SYMAuthor                  juanmr
RUN_TEST_STEP 100 Te_suplprotocolSuite molr33Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0033


START_TESTCASE                LBS-UT-SUPL-MTLR-0001
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0001
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr1Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0001


START_TESTCASE                LBS-UT-SUPL-MTLR-0002
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0002
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr2Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0002


START_TESTCASE                LBS-UT-SUPL-MTLR-0003
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0003
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr3Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0003


START_TESTCASE                LBS-UT-SUPL-MTLR-0004
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0004
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr4Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0004


START_TESTCASE                LBS-UT-SUPL-MTLR-0005
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0005
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr5Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0005


START_TESTCASE                LBS-UT-SUPL-MTLR-0006
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0006
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr6Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0006


START_TESTCASE                LBS-UT-SUPL-MTLR-0007
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0007
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr7Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0007


START_TESTCASE                LBS-UT-SUPL-MTLR-0008
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0008
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr8Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0008
// "no position" test currently failing


START_TESTCASE                LBS-UT-SUPL-MTLR-0009
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0009
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr9Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0009


START_TESTCASE                LBS-UT-SUPL-MTLR-0010
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0010
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr10Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0010


START_TESTCASE                LBS-UT-SUPL-MTLR-0011
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0011
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr11Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0011


START_TESTCASE                LBS-UT-SUPL-MTLR-0012
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0012
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr12Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0012


START_TESTCASE                LBS-UT-SUPL-MTLR-0013
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0013
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr13Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0013


START_TESTCASE                LBS-UT-SUPL-MTLR-0014
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0014
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr14Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0014


START_TESTCASE                LBS-UT-SUPL-MTLR-0015
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0015
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr15Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0015


START_TESTCASE                LBS-UT-SUPL-MTLR-0016
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0016
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr16Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0016


START_TESTCASE                LBS-UT-SUPL-MTLR-0017
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0017
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr17Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0017


START_TESTCASE                LBS-UT-SUPL-MTLR-0018
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0018
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr18Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0018


START_TESTCASE                LBS-UT-SUPL-MTLR-0019
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0019
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr19Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0019


START_TESTCASE                LBS-UT-SUPL-MTLR-0020
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0020
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr20Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0020


START_TESTCASE                LBS-UT-SUPL-MTLR-0021
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0021
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr21Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0021


START_TESTCASE                LBS-UT-SUPL-MTLR-0022
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0022
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr22Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0022


START_TESTCASE                LBS-UT-SUPL-MTLR-0023
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0023
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr23Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0023


START_TESTCASE                LBS-UT-SUPL-MTLR-0024
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0024
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr24Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0024


START_TESTCASE                LBS-UT-SUPL-MTLR-0025
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0025
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr25Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0025


START_TESTCASE                LBS-UT-SUPL-MTLR-0026
//! @SYMTestCaseID              LBS-UT-SUPL-MTLR-0026
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite mtlr26Step
END_TESTCASE                  LBS-UT-SUPL-MTLR-0026
// test currently failing on urel, which upsets the host settings for reamaining tests, hence move to end of script


START_TESTCASE                LBS-UT-SUPL-MOLR-0027
//! @SYMTestCaseID              LBS-UT-SUPL-MOLR-0027
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 Te_suplprotocolSuite molr27Step 
END_TESTCASE                  LBS-UT-SUPL-MOLR-0027
RUN_UTILS DeleteFile c:\config.txt
PRINT End of SUPL Protocol UNIT suite te_suplprotocol



