# platform_path_definitions_api level configuration makefile

#Define this platform as default if nothing is defined

MAKEFILE = $(EPOCROOT)/sf/os/devicesrv/devicesrv_pub/platform_path_definitions_api/makefile

platform_path_all    	:: platform_path_config

include include_template.mk