# common_platform_security_definitions_api level configuration makefile

#Define this platform as default if nothing is defined

MAKEFILE = $(EPOCROOT)/sf/os/devicesrv/devicesrv_pub/common_platform_security_definitions_api/makefile

common_platform_security_all    	:: common_platform_security_config

include include_template.mk