=head1 FShell Documentation

L<Introduction|fshell::commands::fshell/Introduction> - an introduction to fshell.

L<Getting started|getting_started> - a guide to getting fshell up and running on various different platforms.

L<Change History|fshell::change_history>

L<Core FShell functionality|core>

L<FShell Commands|commands> - an A to Z of all the commands that fshell supports.

L<Plug-ins|plugins>

L<Developer documentation|internal> - documentation for developers wishing to extend fshell or write new commands.
