// Copyright (c) 2002-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

// # * Top level script file for TS_MultiHoming for attempted name resolution which fail
// # * Please refer to the "TS_Multihoming Test Specification" for explanation of sub-net labels.
//

RUN_SCRIPT z:\TestData\scripts\esock_test_unloadesock.script
CED Z:\TestData\Configs\TS_MultiHoming_Test18_ced.xml
RUN_SCRIPT z:\TestData\scripts\esock_test_loadesock.script

LOAD_SUITE TS_MultiHoming.dll

RUN_SCRIPT Z:\TestData\Scripts\TS_MultiHoming_Test18.script


# Ensure no implicit sockets are held open before unloading esock.
#
RUN_SCRIPT Z:\TestData\Scripts\esock_test_stopallinterfaces.script
RUN_SCRIPT z:\TestData\scripts\esock_test_unloadesockForced.script

