// Copyright (c) 2002-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

// # * Top level script file for  TS_MultiHoming that calls all 
// # * test cases that use the two ppp network configuration.
//

/**
 # * @file StopConnections.script
*/

# Explicitly start the implicit connection, and then stop it
run_test_step 30000000, TS_MultiHoming, RConnectionStart, Z:\TestData\Configs\TS_MultiHoming_Delay.ini
run_test_step 30000000, TS_MultiHoming, RConnectionStop,  Z:\TestData\Configs\TS_MultiHoming_Delay.ini
DELAY 1000
run_test_step 30000000, TS_MultiHoming, ShowConnections,  Z:\TestData\Configs\TS_MultiHoming_Delay.ini
