// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

// # * IPv4 - DNS By Implicit Connection to an Existing Connection to a Preferred NetID
// # * Para 3.5.3
//


run_test_step 30000000, TS_MultiHoming, RConnectionStart, Z:\TestData\Configs\TS_MultiHoming_Test20.ini

DELAY 5000

run_test_step 30000000, TS_MultiHoming, ResolveName,      Z:\TestData\Configs\TS_MultiHoming_Test20.ini
run_test_step 30000000, TS_MultiHoming, ShowConnections,  Z:\TestData\Configs\TS_MultiHoming_Test20.ini
run_test_step 30000000, TS_MultiHoming, RConnectionStop,  Z:\TestData\Configs\TS_MultiHoming_Test20.ini

TEST_COMPLETE TS_MultiHoming_Test20
