//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//Copy  Te_Data.ini onto c:\system\data
RUN_UTILS  CopyFile z:\TestData\Configs\Te_data.ini c:\system\data\Te_data.ini
RUN_UTILS  MakeReadWrite c:\system\data\Te_data.ini
//
// Initialize CommDb to sensible defaults
//
ced z:\TestData\configs\Te_data_comm1_9210.cfg ced.log
//
