//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//Call the setup script to copy any necessary config
//file to the right places, also, TestHandShake moved
//into Te_Data_handshake.script
RUN_SCRIPT z:\TestData\Scripts\Te_Data_setup.script
//
LOAD_SUITE Te_Data
//
START_TESTCASE TEL-MMTSY-NA-2000
//!@SYMTestCaseID TEL-MMTSY-NA-2000
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Status Incomming Call
//!@SYMTestPriority critical
//!@SYMTestActions Tests the line status of an incomming call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestLineStatusIncommingCall
//
END_TESTCASE TEL-MMTSY-NA-2000

START_TESTCASE TEL-MMTSY-NA-2001
//!@SYMTestCaseID TEL-MMTSY-NA-2001
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Status Outgoing Call
//!@SYMTestPriority critical
//!@SYMTestActions Test the line status of an outgoing call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestLineStatusOutgoingCall
//
END_TESTCASE TEL-MMTSY-NA-2001

START_TESTCASE TEL-MMTSY-NA-2002
//!@SYMTestCaseID TEL-MMTSY-NA-2002
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Info
//!@SYMTestPriority critical
//!@SYMTestActions Test line information 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestLineInfo
//
END_TESTCASE TEL-MMTSY-NA-2002

START_TESTCASE TEL-MMTSY-NA-2003
//!@SYMTestCaseID TEL-MMTSY-NA-2003
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Notifications Incomming Call
//!@SYMTestPriority critical
//!@SYMTestActions Tests the  line notifications of an incomming call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestLineNotificationsIncommingCall
//
END_TESTCASE TEL-MMTSY-NA-2003

START_TESTCASE TEL-MMTSY-NA-2004
//!@SYMTestCaseID TEL-MMTSY-NA-2004
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Notifications Outgoing Call
//!@SYMTestPriority critical
//!@SYMTestActions Tests the line notifications of an outgoing call  
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestLineNotificationsOutgoingCall
//
END_TESTCASE TEL-MMTSY-NA-2004

START_TESTCASE TEL-MMTSY-NA-2005
//!@SYMTestCaseID TEL-MMTSY-NA-2005
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Line Cancels
//!@SYMTestPriority critical
//!@SYMTestActions Test line cancellation
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestLineCancels
//
END_TESTCASE TEL-MMTSY-NA-2005

START_TESTCASE TEL-MMTSY-NA-2006
//!@SYMTestCaseID TEL-MMTSY-NA-2006
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc TestCallInfo
//!@SYMTestPriority critical
//!@SYMTestActions Test call information
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestCallInfo
//
END_TESTCASE TEL-MMTSY-NA-2006

START_TESTCASE TEL-MMTSY-NA-2007
//!@SYMTestCaseID TEL-MMTSY-NA-2007
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Call Notifications
//!@SYMTestPriority critical
//!@SYMTestActions Test call notifications
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestCallNotifications
//
END_TESTCASE TEL-MMTSY-NA-2007

START_TESTCASE TEL-MMTSY-NA-2008
//!@SYMTestCaseID TEL-MMTSY-NA-2008
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Call Status Incomming Call
//!@SYMTestPriority critical
//!@SYMTestActions Test the call status of an incomming call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestCallStatusIncommingCall
//
END_TESTCASE TEL-MMTSY-NA-2008

START_TESTCASE TEL-MMTSY-NA-2009
//!@SYMTestCaseID TEL-MMTSY-NA-2009
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Call Status Outgoing Call
//!@SYMTestPriority critical
//!@SYMTestActions Test Call Status Outgoing Call
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestCallStatusOutgoingCall
//
END_TESTCASE TEL-MMTSY-NA-2009

START_TESTCASE TEL-MMTSY-NA-2010
//!@SYMTestCaseID TEL-MMTSY-NA-2010
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Test Call Cancels
//!@SYMTestPriority critical
//!@SYMTestActions Test Call Cancellations
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestCallCancels
//
END_TESTCASE TEL-MMTSY-NA-2010

START_TESTCASE TEL-MMTSY-NA-2011
//!@SYMTestCaseID TEL-MMTSY-NA-2011
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc TestGetMobileDataCallCapsL
//!@SYMTestPriority critical
//!@SYMTestActions Test Get Mobile Data Call Capabilities
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
RUN_TEST_STEP 300 Te_Data TestGetMobileDataCallCapsL
//
END_TESTCASE TEL-MMTSY-NA-2011

START_TESTCASE TEL-MMTSY-NA-2012
//!@SYMTestCaseID TEL-MMTSY-NA-2012
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc TestHandShake
//!@SYMTestPriority critical
//!@SYMTestActions Test Hand Shake, requires Te_Echo to be run 
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
//
PRINT
PRINT *********************************************************************
PRINT *** About to start handshake test, please ensure T_Echo is ready! ***
PRINT *********************************************************************
PRINT
PAUSE
//
RUN_TEST_STEP 300 Te_Data TestHandShake
END_TESTCASE TEL-MMTSY-NA-2012

