//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
//! @SYMTestSuiteName te_RConnectionServ
//! @SYMScriptTestEnvironment Standard Symbian HRP or emulator environment

// Load the test suite
LOAD_SUITE te_esockteststepsSuite -SharedData



START_TESTCASE			COMINF-ESOCK-RConnectionServ-4601
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionServ-4601
//!@SYMTestCaseDesc           	TODO_CDG
//!@SYMPREQ                   	PREQ399
//!@SYMAPI
// TODO_CDG
//!@SYMTestPriority           	Critical
//!@SYMTestActions
// TODO_CDG
//!@SYMTestType               	CIT
//!@SYMTestExpectedResults    	TODO_CDG

// Start by unloading esock, reseting commsdat and reloading esock
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
CED -i z:\TestData\configs\RConnectionServ\RConnectionServ.cfg -o c:\RConnectionServ.cfg.log
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

// Initialise the availability state of our test access points
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini InitAvailability1
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini InitAvailability2
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini InitAvailability3
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini InitAvailability4

// Create and connect a RConnectionServ instance
RUN_TEST_STEP 100 te_esockteststepsSuite CreateRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini CreateConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini ConnectConnectionServ1

// Basic queries
// Filter by single AP (exists in set)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_1_1

// Filter by multiple APs (exist in set)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_1_2

// Filter by multiple APs (comprise whole set)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_1_3

// Filter by multiple APs (comprise whole set and an outsider)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_1_4

// Filter by single AP (not in set)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_1_5

// Filter by single AP (not in set - but on other tier)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_1_6


// Filter on active status with two link tier APs up
RUN_TEST_STEP 100 te_esockteststepsSuite creatersocketservStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini CreateSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite connectrsocketservStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini ConnectSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite createrconnectionStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini CreateConn1
RUN_TEST_STEP 100 te_esockteststepsSuite createrconnectionStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini CreateConn2
RUN_TEST_STEP 100 te_esockteststepsSuite openrconnectionStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini OpenConn1
RUN_TEST_STEP 100 te_esockteststepsSuite openrconnectionStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini OpenConn2
RUN_TEST_STEP 100 te_esockteststepsSuite startrconnectionStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini StartConn1
RUN_TEST_STEP 100 te_esockteststepsSuite startrconnectionStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini StartConn2
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_2_1
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_2_2
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_2_3
RUN_TEST_STEP 100 te_esockteststepsSuite stoprconnectionStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini StopConn1
RUN_TEST_STEP 100 te_esockteststepsSuite stoprconnectionStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini StopConn2


// Now filter by AP with query on restricted status
// TODO_CDG need to make APs 2 and 3 restricted.. not required for 399 drop so ok to comment out
//UN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_3_1
//UN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_3_2


// Now filter by AP with query on available status
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini SetAvailability1
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini SetAvailability2
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_4_1
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_4_2

// Now filter with multiple status
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_5_1

// Now perform valid query to ensure still working (smoke test)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini Query_6

// Close and cleanup resources
RUN_TEST_STEP 100 te_esockteststepsSuite closerconnectionStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini CloseConn1
RUN_TEST_STEP 100 te_esockteststepsSuite closerconnectionStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini CloseConn2
RUN_TEST_STEP 100 te_esockteststepsSuite closersocketservStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini CloseSockSvr1
RUN_TEST_STEP 100 te_esockteststepsSuite CloseRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini CloseConnectionServ1

RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep

// Shutdown
RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script

// Restore the availability state of our test access points
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini RestoreAvailability1
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini RestoreAvailability2
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini RestoreAvailability3
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_05_100.ini RestoreAvailability4


END_TESTCASE			COMINF-ESOCK-RConnectionServ-4601




