//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
//! @SYMTestSuiteName te_RConnectionServ
//! @SYMScriptTestEnvironment Standard Symbian HRP or emulator environment

// Load the test suite
LOAD_SUITE te_esockteststepsSuite -SharedData



START_TESTCASE			COMINF-ESOCK-RConnectionServ-4301
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionServ-4301
//!@SYMTestCaseDesc           	TODO_CDG
//!@SYMPREQ                   	PREQ399
//!@SYMAPI
//RConnectionServ::Connect()
//RConnectionServ::AccessPointStatusQuery()
//!@SYMTestPriority           	Critical
//!@SYMTestActions
// TODO_CDG
//!@SYMTestType               	CIT
//!@SYMTestExpectedResults    	TODO_CDG


// Start by unloading esock, reseting commsdat and reloading esock
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
CED -i z:\TestData\configs\RConnectionServ\RConnectionServ.cfg -o c:\RConnectionServ.cfg.log
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

// Create an RConnectionServ to use
RUN_TEST_STEP 100 te_esockteststepsSuite CreateRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_04_030.ini CreateConnectionServ1

// Try to connect at all tiers (tierid = 0). Currently not supported
RUN_TEST_STEP !Error=-6 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_04_030.ini Connect1

// Try to connect with an invalid tier id
RUN_TEST_STEP !Error=-1 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_04_030.ini Connect2

// Now try to connect at a valid tier and perform a valid query
RUN_TEST_STEP 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_04_030.ini Connect3
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_04_030.ini APQuery1
RUN_TEST_STEP 100 te_esockteststepsSuite CloseRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_04_030.ini Close1

// Try to connect with an invalid tier id once again
RUN_TEST_STEP !Error=-1 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_04_030.ini Connect4

// Try once again to connect at a valid tier and perform a valid query
RUN_TEST_STEP 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_04_030.ini Connect5
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_04_030.ini APQuery2
RUN_TEST_STEP 100 te_esockteststepsSuite CloseRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_04_030.ini Close1

RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep

// Shutdown
RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script

END_TESTCASE			COMINF-ESOCK-RConnectionServ-4301




