//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
//! @SYMTestSuiteName te_RConnectionServ
//! @SYMScriptTestEnvironment Standard Symbian HRP or emulator environment

// Load the test suite
LOAD_SUITE te_esockteststepsSuite -SharedData



START_TESTCASE			COMINF-ESOCK-RConnectionServ-2501
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionServ-2501
//!@SYMTestCaseDesc           	TODO_CDG
//!@SYMPREQ                   	PREQ399
//!@SYMAPI
//RConnectionServ::Connect()
//RConnectionServ::AccessPointStatusQuery()
//!@SYMTestPriority           	Critical
//!@SYMTestActions
// TODO_CDG
//!@SYMTestType               	CIT
//!@SYMTestExpectedResults    	TODO_CDG

// TODO_CDG need to add as many configurations (commsdat files) as we see fit

// ### Configuration 1 ###
// Start by unloading esock, reseting commsdat and reloading esock
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
CED -i z:\TestData\configs\RConnectionServ\RConnectionServ.cfg -o c:\RConnectionServ.ced.log
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

// Connect at *link* tier
RUN_TEST_STEP 100 te_esockteststepsSuite CreateRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini CreateConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini ConnectConnectionServ1

// Query for the commsdat specific attributes (configured and restricted)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini APQuery1

// Close and cleanup resources
RUN_TEST_STEP 100 te_esockteststepsSuite CloseRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini CloseConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep

// Shutdown
RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script


// ### Configuration 2 ###
// Start by unloading esock, reseting commsdat and reloading esock
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
CED -i z:\TestData\configs\RConnectionServ\RConnectionServ.cfg -o c:\RConnectionServ.ced.log
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

// Connect at *link* tier
RUN_TEST_STEP 100 te_esockteststepsSuite CreateRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini CreateConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini ConnectConnectionServ1

// Query for the commsdat specific attributes (configured and restricted)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini APQuery1

// Close and cleanup resources
RUN_TEST_STEP 100 te_esockteststepsSuite CloseRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini CloseConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep

// Shutdown
RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script


// ### Configuration 3 ###
// Start by unloading esock, reseting commsdat and reloading esock
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
CED -i z:\TestData\configs\RConnectionServ\RConnectionServ.cfg -o c:\RConnectionServ.ced.log
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

// Connect at *link* tier
RUN_TEST_STEP 100 te_esockteststepsSuite CreateRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini CreateConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini ConnectConnectionServ1

// Query for the commsdat specific attributes (configured and restricted)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini APQuery1

// Close and cleanup resources
RUN_TEST_STEP 100 te_esockteststepsSuite CloseRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_02_200.ini CloseConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep

// Shutdown
RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script

END_TESTCASE			COMINF-ESOCK-RConnectionServ-2501




