//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
//! @SYMTestSuiteName te_RConnectionServ
//! @SYMScriptTestEnvironment Standard Symbian HRP or emulator environment

// Load the test suite
LOAD_SUITE te_esockteststepsSuite -SharedData



START_TESTCASE			COMINF-ESOCK-RConnectionServ-5001
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionServ-5001
//!@SYMTestCaseDesc           	TODO_CDG
//!@SYMPREQ                   	PREQ399
//!@SYMAPI
//RConnectionServ::Connect()
//RConnectionServ::AccessPointStatusQuery()
//!@SYMTestPriority           	Critical
//!@SYMTestActions
// TODO_CDG
//!@SYMTestType               	CIT
//!@SYMTestExpectedResults    	TODO_CDG

// Start by unloading esock, reseting commsdat and reloading esock
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
CED -i z:\TestData\configs\RConnectionServ\RConnectionServ.cfg -o c:\RConnectionServ.ced.log
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

// Initialise the availability state of our test access points
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini InitAvailability1
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini InitAvailability2
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini InitAvailability3
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini InitAvailability4

// Connect at *network* tier
RUN_TEST_STEP 100 te_esockteststepsSuite CreateRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini CreateConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini ConnectConnectionServ1

// Request all changes to availability
RUN_TEST_STEP 100 te_esockteststepsSuite RequestAccessPointNotificationStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini APNotificationRequest1

// Make bearer available and detect change at AP
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini SetAvailability1
RUN_TEST_STEP 100 te_esockteststepsSuite ReceiveAccessPointNotificationStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini ReceiveNotification1

// Make bearer unavailable again and detect change at AP
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini SetAvailability2
RUN_TEST_STEP 100 te_esockteststepsSuite ReceiveAccessPointNotificationStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini ReceiveNotification2

// Make second bearer available and detect change with notification
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini SetAvailability3
RUN_TEST_STEP 100 te_esockteststepsSuite ReceiveAccessPointNotificationStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini ReceiveNotification3
RUN_TEST_STEP 100 te_esockteststepsSuite ReceiveAccessPointNotificationStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini ReceiveNotification3_2

// Make second bearer unavailable and detect change with notification
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini SetAvailability4
RUN_TEST_STEP 100 te_esockteststepsSuite ReceiveAccessPointNotificationStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini ReceiveNotification4
RUN_TEST_STEP 100 te_esockteststepsSuite ReceiveAccessPointNotificationStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini ReceiveNotification4_2

// Cancel the notification request
RUN_TEST_STEP 100 te_esockteststepsSuite CancelAccessPointNotificationStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini CancelAPNotificationRequest1

// Close and cleanup resources
RUN_TEST_STEP 100 te_esockteststepsSuite CloseRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini CloseConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep

// Shutdown
RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script

// Restore the availability state of our test access points
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini RestoreAvailability1
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini RestoreAvailability2
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini RestoreAvailability3
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_10_015.ini RestoreAvailability4

END_TESTCASE			COMINF-ESOCK-RConnectionServ-5001




