//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
//! @SYMTestSuiteName te_RConnectionServ
//! @SYMScriptTestEnvironment Standard Symbian HRP or emulator environment

// Load the test suite
LOAD_SUITE te_esockteststepsSuite -SharedData



START_TESTCASE			COMINF-ESOCK-RConnectionServ-3101
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionServ-3101
//!@SYMTestCaseDesc           	TODO_CDG
//!@SYMPREQ                   	PREQ399
//!@SYMAPI
//RConnectionServ::Connect()
//RConnectionServ::AccessPointStatusQuery()
//!@SYMTestPriority           	Critical
//!@SYMTestActions
// TODO_CDG
//!@SYMTestType               	CIT
//!@SYMTestExpectedResults    	TODO_CDG

RUN_UTILS  MakeReadWrite c:\config.txt
RUN_UTILS  DeleteFile c:\config.txt
RUN_UTILS  CopyFile z:\testdata\configs\RConnectionServ\CIT_mixedap_config.txt c:\config.txt

// Start by unloading esock, reseting commsdat and reloading esock
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script
CED -i z:\TestData\configs\RConnectionServ\RConnectionServ_MixedAPTypes.cfg -o c:\RConnectionServ.ced.log
RUN_SCRIPT z:\TestData\scripts\te_esock_test_loadesock.script

// start simtsy
RUN_TEST_STEP 100 te_esockteststepsSuite StartSimTSYStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini SimTsy

// Initialise the availability state of our test access points
RUN_TEST_STEP 100 te_esockteststepsSuite SetPppAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini InitPppAvailability1
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini InitAvailability2
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini InitAvailability3
RUN_TEST_STEP 100 te_esockteststepsSuite SetAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini InitAvailability4

// Connect at *link* tier
RUN_TEST_STEP 100 te_esockteststepsSuite CreateRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini CreateConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite ConnectRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini ConnectConnectionServ1

// Query for available APs (none)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini APQuery1

// Make an AP available *AP1*
RUN_TEST_STEP 100 te_esockteststepsSuite SetPppAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini SetPppAvailability1

// Query for available APs (AP1)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini APQuery2

// Make the same AP unavailable *AP1*
RUN_TEST_STEP 100 te_esockteststepsSuite SetPppAccessPointAvailabilityStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini SetPppAvailability2

// Query for available APs (none)
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini APQuery3
RUN_TEST_STEP 100 te_esockteststepsSuite AccessPointStatusQueryStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini APQuery4

// Close and cleanup resources
RUN_TEST_STEP 100 te_esockteststepsSuite CloseRConnectionServStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini CloseConnectionServ1
RUN_TEST_STEP 100 te_esockteststepsSuite cleanallStep

RUN_TEST_STEP 100 te_esockteststepsSuite StopSimTSYStep z:\testdata\configs\RConnectionServ\RConnectionServ_03_000.ini SimTsy

// Shutdown
RUN_SCRIPT Z:\TestData\Scripts\te_esock_test_stopallinterfaces.script
RUN_SCRIPT Z:\TestData\scripts\te_esock_test_unloadesockForced.script

END_TESTCASE			COMINF-ESOCK-RConnectionServ-3101




