// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file te_hwrm_light.script
//! @SYMTestSuiteName DEVSRVS-HWRM
//! @SYMScriptTestEnvironment telephony

LOAD_SUITE te_hwrm

START_TESTCASE DEVSRVS-HWRM-L-0001
//!@SYMTestCaseID DEVSRVS-HWRM-L-0001
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Initialises light targets
//!@SYMTestPriority High
//!@SYMTestActions Opens a light session and switches all lights off
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestSetupLightsL
END_TESTCASE DEVSRVS-HWRM-L-0001

START_TESTCASE DEVSRVS-HWRM-L-0002
//!@SYMTestCaseID DEVSRVS-HWRM-L-0002
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Performs a number of basic light tests
//!@SYMTestPriority High
//!@SYMTestActions Turns lights on and off, checks that the light status is returned correctly, turns lights on with a limited duration and checks that they go off automatically
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightSimpleL
END_TESTCASE DEVSRVS-HWRM-L-0002

START_TESTCASE DEVSRVS-HWRM-L-0003
//!@SYMTestCaseID DEVSRVS-HWRM-L-0003
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Performs a basic light blink test
//!@SYMTestPriority High
//!@SYMTestActions Makes keyboard blink for a limited duration and checks that it goes back off automatically
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightBlinkKeyboardL
END_TESTCASE DEVSRVS-HWRM-L-0003

START_TESTCASE DEVSRVS-HWRM-L-0004
//!@SYMTestCaseID DEVSRVS-HWRM-L-0004
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Performs a number of complex light tests, including timed actions
//!@SYMTestPriority High
//!@SYMTestActions Turns on display and keyboard, blinks display (timed), turns off keyboard (timed), turns off display (timed), blinks keyboard (timed), waits for display to go back on, blinks display and keyboard and turns off keyboard (timed)
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightBlinkComplexL
END_TESTCASE DEVSRVS-HWRM-L-0004

START_TESTCASE DEVSRVS-HWRM-L-0005
//!@SYMTestCaseID DEVSRVS-HWRM-L-0005
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Performs a number of tests with infinite duration and involving sensor controlled lights.
//!@SYMTestPriority High
//!@SYMTestActions Blink light on keyboard with an infinite cut off timer, check status is blink, set sensors on and off again, and checks that the sensor controlled targets (cenrep) behave correctly
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightBlinkKeyboardInfiniteCutOffTimerL
END_TESTCASE DEVSRVS-HWRM-L-0005

START_TESTCASE DEVSRVS-HWRM-V-0006
//!@SYMTestCaseID DEVSRVS-HWRM-V-0006
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Able to reserve light session
//!@SYMTestPriority High
//!@SYMTestActions Open sessions, reserve light on display, light on display and keyboard then release light and turn light off
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightReserveSessionsL
END_TESTCASE DEVSRVS-HWRM-V-0006

START_TESTCASE DEVSRVS-HWRM-L-0007
//!@SYMTestCaseID DEVSRVS-HWRM-L-0007
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Able to reserve several light sessions
//!@SYMTestPriority High
//!@SYMTestActions Open and reserve multiple light sessions, turn lights on and blink on display and keyboard then release all light sessions
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightReserveSessions2L
END_TESTCASE DEVSRVS-HWRM-L-0007

START_TESTCASE DEVSRVS-HWRM-L-0008
//!@SYMTestCaseID DEVSRVS-HWRM-L-0008
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Able to reserve light on display
//!@SYMTestPriority High
//!@SYMTestActions Open and reserve multiple light sessions on display
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightReserveDisplayL
END_TESTCASE DEVSRVS-HWRM-L-0008

START_TESTCASE DEVSRVS-HWRM-L-0009
//!@SYMTestCaseID DEVSRVS-HWRM-L-0009
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Able to get supported light targets
//!@SYMTestPriority High
//!@SYMTestActions Get supported light targets
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightGetSupportedTargetsL
END_TESTCASE DEVSRVS-HWRM-L-0009

START_TESTCASE DEVSRVS-HWRM-L-0010
//!@SYMTestCaseID DEVSRVS-HWRM-L-0010
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Reserve light on an unsupported target
//!@SYMTestPriority High
//!@SYMTestActions Attempts to reserve light, turn light on and release light on an unsupported target. Expects this to fail with KErrNotSupported		
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightUnsupportedTargetL
END_TESTCASE DEVSRVS-HWRM-L-0010

START_TESTCASE DEVSRVS-HWRM-L-0011
//!@SYMTestCaseID DEVSRVS-HWRM-L-0011
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Light on with custom targets 1, 2, 4
//!@SYMTestPriority High
//!@SYMTestActions Attempts to switch succesively custom targets 1, 2, 4 (one at a time). Custom target 1 is not supported, so expects KErrNotSupported leave.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightOnSimpleCustomTargetsL
END_TESTCASE DEVSRVS-HWRM-L-0011

START_TESTCASE DEVSRVS-HWRM-L-0012
//!@SYMTestCaseID DEVSRVS-HWRM-L-0012
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Turn light on with unsupported intensity
//!@SYMTestPriority High
//!@SYMTestActions Attempts to turn light on with unsupported intensity. Expects this to fail with KErrArgument.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightUnsupportedIntensityL
END_TESTCASE DEVSRVS-HWRM-L-0012

START_TESTCASE DEVSRVS-HWRM-L-0013
//!@SYMTestCaseID DEVSRVS-HWRM-L-0013
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Turn light on with unsupported duration.
//!@SYMTestPriority High
//!@SYMTestActions Attempts to turn light on with unsupported duration. Expects this to fail with KErrArgument.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightUnsupportedDurationL
END_TESTCASE DEVSRVS-HWRM-L-0013

START_TESTCASE DEVSRVS-HWRM-L-0014
//!@SYMTestCaseID DEVSRVS-HWRM-L-0014
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Turn on a light that is removed by target modifier. 
//!@SYMTestPriority High
//!@SYMTestActions Opens flip (by setting P&S key) and attempts to switch on primary display and keyboard. Checks that display does not turn on because it is being removed by the target modifier. Closes flip again.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestModifyTargetL
END_TESTCASE DEVSRVS-HWRM-L-0014

START_TESTCASE DEVSRVS-HWRM-L-0015
//!@SYMTestCaseID DEVSRVS-HWRM-L-0015
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Turn system lights on and off
//!@SYMTestPriority High
//!@SYMTestActions Turn system lights on and off again
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestSystemLightsL
END_TESTCASE DEVSRVS-HWRM-L-0015

START_TESTCASE DEVSRVS-HWRM-L-0016
//!@SYMTestCaseID DEVSRVS-HWRM-L-0016
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Lights on display and keyboard with system target default settings
//!@SYMTestPriority High
//!@SYMTestActions initialise system targets, turn lights on display then turn off lights on display and turn lights on keyboard
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestDisplayLightsOnL
END_TESTCASE DEVSRVS-HWRM-L-0016

START_TESTCASE DEVSRVS-HWRM-L-0017
//!@SYMTestCaseID DEVSRVS-HWRM-L-0017
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Open sessions for extended light
//!@SYMTestPriority High
//!@SYMTestActions open sessions for extended light, session 1 turn on light on and off, session 2 blink lights then turn light off
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestExtendedLightSessionsL
END_TESTCASE DEVSRVS-HWRM-L-0017

START_TESTCASE DEVSRVS-HWRM-L-0018
//!@SYMTestCaseID DEVSRVS-HWRM-L-0018
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Checks that creating sessions with wrong callback parameters cause a leave
//!@SYMTestPriority High
//!@SYMTestActions Tries to create a CHWRMLight, a CHWRMExtendedLight and a CHWRMVibra passing NULL as callback parameter
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestInvalidSessionsL
END_TESTCASE DEVSRVS-HWRM-L-0018

START_TESTCASE DEVSRVS-HWRM-L-0019
//!@SYMTestCaseID DEVSRVS-HWRM-L-0019
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the client-specific light color
//!@SYMTestPriority High
//!@SYMTestActions
//! 1. Create a CHWRMLight object to open a session with HWRM server
//! 2. Call the new API to set color for the supported targets
//!@SYMTestExpectedResults Check the API does not leave and passes the request to adaptation.
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightColorL
END_TESTCASE DEVSRVS-HWRM-L-0019

START_TESTCASE DEVSRVS-HWRM-L-0020
//!@SYMTestCaseID DEVSRVS-HWRM-L-0020
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the client-specific light color for extended target
//!@SYMTestPriority High
//!@SYMTestActions
//! 1. Create a CHWRMEnhancedLight object to open a session with HWRM server
//! 2. Call the new API to set color for the supported targets
//!@SYMTestExpectedResults Check the API does not leave and passes the request to adaptation.
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightColor_ExtendedTargetL
END_TESTCASE DEVSRVS-HWRM-L-0020

START_TESTCASE DEVSRVS-HWRM-L-0021
//!@SYMTestCaseID DEVSRVS-HWRM-L-0021
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the default light color
//!@SYMTestPriority High
//!@SYMTestActions
//!  1. Create a CHWRMLight object to open a session with HWRM server
//!  2. Call the new API to set the default color for the supported targets
//!@SYMTestExpectedResults Check the API does not leave and passes the request to adaptation.
//!@SYMTestType CT
RUN_TEST_STEP 200 te_hwrm TEFUnit.CHWRMTest.TestLightDefaultColorL
END_TESTCASE DEVSRVS-HWRM-L-0021

START_TESTCASE DEVSRVS-HWRM-L-0022
//!@SYMTestCaseID DEVSRVS-HWRM-L-0022
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the default light color for extended target
//!@SYMTestPriority High
//!@SYMTestActions
//! 1. Create a CHWRMEnhancedLight object to open a session with HWRM server
//! 2. Call the new API to set the default color for the supported targets
//!@SYMTestExpectedResults Check the API does not leave and passes the request to adaptation.
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightDefaultColor_ExtendedTargetL
END_TESTCASE DEVSRVS-HWRM-L-0022

START_TESTCASE DEVSRVS-HWRM-L-0023
//!@SYMTestCaseID DEVSRVS-HWRM-L-0023
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the client-specific light color with error
//!@SYMTestPriority Medium
//!@SYMTestActions
//!  1. Create a CHWRMLight object to open a session with HWRM server
//!  2. Call the new API to set color for the un-supported targets
//!@SYMTestExpectedResults Check the API leaves with KErrNotSupported error code.
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightColor_UnSupportedTargetL
END_TESTCASE DEVSRVS-HWRM-L-0023

START_TESTCASE DEVSRVS-HWRM-L-0024
//!@SYMTestCaseID DEVSRVS-HWRM-L-0024
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the client-specific light color with error
//!@SYMTestPriority Medium
//!@SYMTestActions
//!  1. Create a CHWRMLight object to open a session with HWRM server
//!  2. Call the new API to set color for the un-supported targets
//!@SYMTestExpectedResults Check the API leaves with KErrNotSupported error code.
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightColor_PluginErrorL
END_TESTCASE DEVSRVS-HWRM-L-0024

START_TESTCASE DEVSRVS-HWRM-L-0025
//!@SYMTestCaseID DEVSRVS-HWRM-L-0025
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Restore client-specific light color (Frozen state)
//!@SYMTestPriority High
//!@SYMTestActions
//! 1. Reserve (Primary Display, Restore frozen state ON)
//! 2. Set light color (10,10,10)
//! 3. Set Light On for 5 secs
//! 4. Release (Primary Display). Now the default color will be restored. Expect the appropriate command in MockSY.
//! 5. Reserve(Primary Display, Restore frozen state ON). Now the color value(10,10,10) should be restored for Primary Display. Expect the appropriate command in MockSY.
//!@SYMTestExpectedResults Checks that the restoration happens as expected
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestFrozenStateRestoreLightColor_ExtendedTargetL
END_TESTCASE DEVSRVS-HWRM-L-0025

START_TESTCASE DEVSRVS-HWRM-L-0026
//!@SYMTestCaseID DEVSRVS-HWRM-L-0026
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Restore light color (Base state)
//!@SYMTestPriority High
//!@SYMTestActions
//! 1. Reserve (Primary Display)
//! 2. Set light color (10,10,10)
//! 3. Set light ON for INFINITE duration
//! 4. Set light color (20,20,20)
//! 5. Set light blink for 2 secs
//! 6. Release(Primary Display)
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestBaseStateRestoreLightColor_ExtendedTargetL
END_TESTCASE DEVSRVS-HWRM-L-0026

START_TESTCASE DEVSRVS-HWRM-L-0027
//!@SYMTestCaseID DEVSRVS-HWRM-L-0027
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the light color multi client session
//!@SYMTestPriority High
//!@SYMTestActions Checks that the system switches to the proper state of the RGB color setting for multi client sessions
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 200 te_hwrm TEFUnit.CHWRMTest.TestLightColor_MultiClientL
END_TESTCASE DEVSRVS-HWRM-L-0027

START_TESTCASE DEVSRVS-HWRM-L-0028
//!@SYMTestCaseID DEVSRVS-HWRM-L-0028
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the light color multi client session for extended targets
//!@SYMTestPriority High
//!@SYMTestActions Checks that the system switches to the prope state of the RGB color setting for multi client sessions
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightColor_MultiClient_ExtendedTargetL
END_TESTCASE DEVSRVS-HWRM-L-0028

START_TESTCASE DEVSRVS-HWRM-L-0029
//!@SYMTestCaseID DEVSRVS-HWRM-L-0029
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the client-specific light color when already in use
//!@SYMTestPriority Medium
//!@SYMTestActions Checks that the system returns the proper error code when the required target is in use
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightColor_WhenInUseL
END_TESTCASE DEVSRVS-HWRM-L-0029

START_TESTCASE DEVSRVS-HWRM-L-0030
//!@SYMTestCaseID DEVSRVS-HWRM-L-0030
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the default light color when already in use
//!@SYMTestPriority Medium
//!@SYMTestActions Checks that the system returns the proper error code when the required target is in use
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightDefaultColor_WhenInUseL
END_TESTCASE DEVSRVS-HWRM-L-0030

START_TESTCASE DEVSRVS-HWRM-L-0031
//!@SYMTestCaseID DEVSRVS-HWRM-L-0031
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the light on for specific duration
//!@SYMTestPriority High
//!@SYMTestActions Check that the system switches on the light target for the specific duration
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightOnDurationRGBL
END_TESTCASE DEVSRVS-HWRM-L-0031

START_TESTCASE DEVSRVS-HWRM-L-0032
//!@SYMTestCaseID DEVSRVS-HWRM-L-0032
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the light on for specific duration for the extended target
//!@SYMTestPriority High
//!@SYMTestActions Check that the system switches on the light target for the specific duration
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightOnDurationRGB_ExtendedL
END_TESTCASE DEVSRVS-HWRM-L-0032

START_TESTCASE DEVSRVS-HWRM-L-0033
//!@SYMTestCaseID DEVSRVS-HWRM-L-0033
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the light blink for specific duration
//!@SYMTestPriority High
//!@SYMTestActions Check that the system switches on the light target and blinks for the specific duration
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightBlinkDurationRGBL
END_TESTCASE DEVSRVS-HWRM-L-0033

START_TESTCASE DEVSRVS-HWRM-L-0034
//!@SYMTestCaseID DEVSRVS-HWRM-L-0034
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the light blink for specific duration for the extended target
//!@SYMTestPriority High
//!@SYMTestActions Check that the system switches on the light target and blinks for the specific duration
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightBlinkDurationRGB_ExtendedL
END_TESTCASE DEVSRVS-HWRM-L-0034

START_TESTCASE DEVSRVS-HWRM-L-0035
//!@SYMTestCaseID DEVSRVS-HWRM-L-0035
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the light on for specific duration with given intensity
//!@SYMTestPriority High
//!@SYMTestActions Check that the system switches on the light target for the specific duration
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightOnDurationWithIntenistyRGBL
END_TESTCASE DEVSRVS-HWRM-L-0035

START_TESTCASE DEVSRVS-HWRM-L-0036
//!@SYMTestCaseID DEVSRVS-HWRM-L-0036
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the light blink for specific duration with given intensity
//!@SYMTestPriority High
//!@SYMTestActions Check that the system switches on the light target and blinks for the specific duration
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightBlinkDurationWithIntensityRGBL
END_TESTCASE DEVSRVS-HWRM-L-0036

START_TESTCASE DEVSRVS-HWRM-L-0037
//!@SYMTestCaseID DEVSRVS-HWRM-L-0037
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Expecting the proper leavecode for invalid parameter
//!@SYMTestPriority Medium
//!@SYMTestActions Check that test case exits with KErrBadHandle
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightEnhancedLightLeaveL
END_TESTCASE DEVSRVS-HWRM-L-0037

START_TESTCASE DEVSRVS-HWRM-L-0038
//!@SYMTestCaseID DEVSRVS-HWRM-L-0038
//!@SYMComponent telephony_hwrm
//!@SYMTestCaseDesc Set the light on for specific duration with color for suspended target
//!@SYMTestPriority High
//!@SYMTestActions Check the system does not switch on the light target for the specific client session
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_hwrm TEFUnit.CHWRMTest.TestLightSetColorReserveL
END_TESTCASE DEVSRVS-HWRM-L-0038

PRINT Completed te_hwrm_light tests
