//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//
//! @file
//! @SYMTestSuiteName		MM-MMF-ACLNT-CNVRT-PublicAPI
//! @SYMScriptTestEnvironment	This test script requires a basic ROM.
/////////////////////////////////////////////////////////////////////
// MM-MMF-ACLNT-CNVRT-PublicAPI.script
//
// Tests all public elements of the CMdaAudioConvertUtility class
// as a means of confidence that the APIs work as expected.
//
// The purpose is to provide a regression test suite of PublishedAll APIs for CMdaAudioConvertUtility.
// Negative testing is performed to confirm that correct errors are returned when incorrect parameters are given.
// The tests are fully automated.
/////////////////////////////////////////////////////////////////////

LOAD_SUITE	T_MdaAudioConvertUtility


START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0001
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0001
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and convert
//!				Uses API elements: NewL(), OpenL(), ConvertL()
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Convert file
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	File is converted
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		MM-MMF-ACLNT-CNVRT-PublicAPI-0001-001-NewL_command01
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0001-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SourceDataTypeL			
		COMMAND		convertutility1	GetSupportedDestDataTypesL	
		COMMAND		convertutility1	ConvertL			
		OUTSTANDING
		COMMAND		convertutility1	Close				
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0001

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0002
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0002
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files with target format and source, destination codecs
//!				Uses API elements: NewL(), OpenL(), ConvertL()
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Convert file
//! @SYMTestStatus		Not Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	File is converted
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0002-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SourceDataTypeL		
		COMMAND		convertutility1	GetSupportedDestDataTypesL		
		COMMAND		convertutility1	ConvertL		
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0002

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0003
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0003
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with source and target format,
//!				source and target codecs, source and target audio settings
//!				Uses API elements: NewL(), OpenL(), ConvertL()
//! @SYMTestActions		1. Create convert object
//!				2. Open source and target files
//!				3. Convert file
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	File is converted
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0003-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	ConvertL		
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0003

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0004
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0004
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with UID of the controller, UID of the destination format
//!				and audio codec for the destination data sink
//!				Uses API elements: NewL(), OpenL(), ConvertL()
//! @SYMTestActions		1. Create convert object
//!				2. Open source and target files
//!				3. Convert file
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	File is converted
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0004-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	ConvertL	
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0004

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0005
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0005
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and get source datatype.
//!				Get supported detination datatypes and set different destination datatypes.
//!				Uses API elements: 	NewL(), OpenL(), SourceDataTypeL(), GetSupportedDestinationDataTypesL(),
//!							SetDestinationDataTypeL(), DestinationDataTypeL()
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files.
//!				3. Get source datatype
//!				4. Get supported destination datatypes
//!				5. Set destination datatype
//!				6. Get destination datatype
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Destination datatype must been set
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SourceDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-SourceDataTypeL_command03
		COMMAND		convertutility1	GetSupportedDestDataTypesL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-GetSupportedDestDataTypesL_command04
		COMMAND		convertutility1	SetDestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-SetDestinationDataTypeL_command05
		COMMAND		convertutility1	DestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-DestinationDataTypeL_command06
		COMMAND		convertutility1	SetDestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-SetDestinationDataTypeL_command07
		COMMAND		convertutility1	DestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-DestinationDataTypeL_command08
		COMMAND		convertutility1	SetDestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-SetDestinationDataTypeL_command09
		COMMAND		convertutility1	DestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-DestinationDataTypeL_command10
		COMMAND		convertutility1	SetDestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-SetDestinationDataTypeL_command11
		COMMAND		convertutility1	DestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-DestinationDataTypeL_command12
		COMMAND		convertutility1	SetDestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-SetDestinationDataTypeL_command13
		COMMAND		convertutility1	DestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0005-001-DestinationDataTypeL_command14
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0005

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0006
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0006
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and get source bitrate.
//!				Uses API elements: 	NewL(), OpenL(), SourceBitRateL(),
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files.
//!				3. Get source bitrate
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Source bitrate must been returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0006-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SourceBitRateL		MM-MMF-ACLNT-CNVRT-PublicAPI-0006-001-SourceBitRateL_command03
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0006

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0007
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0007
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and get supported conversion bitrates.
//!				Uses API elements: 	NewL(), OpenL(), GetSupportedConversionBitRatesL(),
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files.
//!				3. Get supported conversion bitrates
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0007-001-OpenL_command02
		OUTSTANDING
		COMMAND	!Error=-5	convertutility1	GetSupConversionBitRatesL		
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0007

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0008
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0008
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and set different destination bitrates.
//!				Uses API elements: 	NewL(), OpenL(), SetDestinationBitRateL(), DestinationBitRateL()
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files.
//!				3. Set destination bitrate
//!				4. Get destination bitrate
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0008-001-OpenL_command02
		OUTSTANDING
		COMMAND	!Error=-5	convertutility1	SetDestinationBitRateL		MM-MMF-ACLNT-CNVRT-PublicAPI-0008-001-SetDestinationBitRateL_command03
		COMMAND			convertutility1	DestinationBitRateL	
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0008

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0009
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0009
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and get source sample rate.
//!				Get supported conversion sample rates and set different destination sample rates.
//!				Uses API elements: 	NewL(), OpenL(), SourceSampleRateL(), GetSupportedConversionSampleRatesL(),
//!							SetDestinationSampleRateL(), DestinationSampleRateL()
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Get source sample rate
//!				4. Get supported conversion sample rates
//!				5. Set destination sample rate
//!				6. Get destination sample rate
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Destination bitrate must been set
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0009-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SourceSampleRateL		MM-MMF-ACLNT-CNVRT-PublicAPI-0009-001-SourceSampleRateL_command03
		COMMAND		convertutility1	GetSupConvSampleRatesL		MM-MMF-ACLNT-CNVRT-PublicAPI-0009-001-GetSupConvSampleRatesL_command04
		COMMAND		convertutility1	SetDestinationSampleRateL		MM-MMF-ACLNT-CNVRT-PublicAPI-0009-001-SetDestinationSampleRateL_command05
		COMMAND		convertutility1	DestinationSampleRateL		MM-MMF-ACLNT-CNVRT-PublicAPI-0009-001-DestinationSampleRateL_command06
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0009

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0010
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0010
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and get source format. Set different destination formats.
//!				Uses API elements: 	NewL(), OpenL(), SourceFormatL(),
//!							SetDestinationFormatL(), DestinationFormatL()
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files.
//!				3. Get format of source audio clip
//!				4. Set destination format of audio clip
//!				5. Get destination format of audio clip
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Destination audio format must been set
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0010-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SourceFormatL		MM-MMF-ACLNT-CNVRT-PublicAPI-0010-001-SourceFormatL_command03
		COMMAND		convertutility1	SetDestinationFormatL		MM-MMF-ACLNT-CNVRT-PublicAPI-0010-001-SetDestinationFormatL_command04
		COMMAND		convertutility1	DestinationFormatL		MM-MMF-ACLNT-CNVRT-PublicAPI-0010-001-DestinationFormatL_command05
		COMMAND		convertutility1	SetDestinationFormatL		MM-MMF-ACLNT-CNVRT-PublicAPI-0010-001-SetDestinationFormatL_command06
		COMMAND		convertutility1	DestinationFormatL		MM-MMF-ACLNT-CNVRT-PublicAPI-0010-001-DestinationFormatL_command07
		COMMAND		convertutility1	SetDestinationFormatL		MM-MMF-ACLNT-CNVRT-PublicAPI-0010-001-SetDestinationFormatL_command08
		COMMAND		convertutility1	DestinationFormatL		MM-MMF-ACLNT-CNVRT-PublicAPI-0010-001-DestinationFormatL_command09
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0010

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0011
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0011
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and get source number of channels.
//!				Get supported number of channels for conversion. Set different number of channels for destination.
//!				Uses API elements: 	NewL(), OpenL(), SourceNumberOfChannelsL(),
//!							GetSupportedConversionNumberOfChannelsL(), SetDestinationNumberOfChannelsL(), DestinationNumberOfChannelsL()
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files.
//!				3. Get number of channels of source audio clip
//!				4. Get supported number of channels for conversion
//!				5. Set destination number of channels of audio clip
//!				6. Get destination number of channels of audio clip
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Destination number of channels of audio must been set
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0011-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SourceNumberOfChannelsL		MM-MMF-ACLNT-CNVRT-PublicAPI-0011-001-SourceNumberOfChannelsL_command03
		COMMAND		convertutility1	GetSupportedConversionNumberOfChannelsL		MM-MMF-ACLNT-CNVRT-PublicAPI-0011-001-GetSupportedConversionNumberOfChannelsL_command04
		COMMAND		convertutility1	SetDestinationNumberOfChannelsL		MM-MMF-ACLNT-CNVRT-PublicAPI-0011-001-SetDestinationNumberOfChannelsL_command05
		COMMAND		convertutility1	DestinationNumberOfChannelsL		MM-MMF-ACLNT-CNVRT-PublicAPI-0011-001-DestinationNumberOfChannelsL_command06
		COMMAND		convertutility1	SetDestinationNumberOfChannelsL		MM-MMF-ACLNT-CNVRT-PublicAPI-0011-001-SetDestinationNumberOfChannelsL_command07
		COMMAND		convertutility1	DestinationNumberOfChannelsL		MM-MMF-ACLNT-CNVRT-PublicAPI-0011-001-DestinationNumberOfChannelsL_command08
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0011

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0012
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0012
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and get converter state.
//!				Uses API elements: 	NewL(), OpenL(), State(),
//! @SYMTestActions		1. Create convert object
//!				2. Get converter state
//!				3. Open source and destination files.
//!				4. Get converter state
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Final state must be EOpen
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	State		MM-MMF-ACLNT-CNVRT-PublicAPI-0012-001-State_command02
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0012-001-OpenL_command03
		OUTSTANDING
		COMMAND		convertutility1	State		MM-MMF-ACLNT-CNVRT-PublicAPI-0012-001-State_command04
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0012

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0013
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0013
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files. Close files and get converter state.
//!				Uses API elements: 	NewL(), OpenL(), Close(), State(),
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files.
//!				3. Close files
//!				4. Get converter state
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	State must be ENotReady
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	State		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0013-001-OpenL_command03
		OUTSTANDING
		COMMAND		convertutility1	Close		
		COMMAND		convertutility1	State		MM-MMF-ACLNT-CNVRT-PublicAPI-0013-001-State_command05
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0013

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0014
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0014
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and play (convert)
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Play file
//!				Uses API elements: NewL(), OpenL(), PlayL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	File is converted
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0014-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	PlayL		
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0014

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0015
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0015
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and record (convert)
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Record file
//!				Uses API elements: NewL(), OpenL(), RecordL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	File is converted
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0015-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	RecordL		
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0015

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0016
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0016
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk & Rehana Anwar
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files start conversion and stop conversion.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Start conversion
//!				4. Stop
//!				Uses API elements: NewL(), OpenL(), ConvertL(), Stop()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0016-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	ConvertL 		MM-MMF-ACLNT-CNVRT-PublicAPI-0016-001-ConvertL_command03
		OUTSTANDING
		COMMAND	!AsyncError=-18	convertutility1	Stop		
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE			MM-MMF-ACLNT-CNVRT-PublicAPI-0016

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0017
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0017
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and set clip position many times.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Set postion
//!				4. Get position
//!				Uses API elements: NewL(), OpenL(), SetPosition(), Position()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Clip postion is changed
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0017-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetPosition		MM-MMF-ACLNT-CNVRT-PublicAPI-0017-001-SetPosition_command03
		COMMAND		convertutility1	Position		MM-MMF-ACLNT-CNVRT-PublicAPI-0017-001-Position_command04
		COMMAND		convertutility1	SetPosition		MM-MMF-ACLNT-CNVRT-PublicAPI-0017-001-SetPosition_command05
		COMMAND		convertutility1	Position		MM-MMF-ACLNT-CNVRT-PublicAPI-0017-001-Position_command06
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0017

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0018
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0018
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and crop.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Crop
//!				Uses API elements: NewL(), OpenL(), CropL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	File is cropped
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0018-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetPosition		MM-MMF-ACLNT-CNVRT-PublicAPI-0018-001-SetPosition_command03
		COMMAND		convertutility1	CropL		
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0018

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0019
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0019
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and get record time available.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Get record time available
//!				Uses API elements: NewL(), OpenL(), RecordTimeAvailable()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returned available recording time
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0019-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	RecordTimeAvailable		
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0019

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0020
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0020
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and get clip duration.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Get clip duration
//!				Uses API elements: NewL(), OpenL(), Duration()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returned clip duration
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0020-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	Duration		MM-MMF-ACLNT-CNVRT-PublicAPI-0020-001-Duration_command03
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0020

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0021
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0021
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files. Set and clear window for playpack many times
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Set windows for playback
//!				4. Clear playback window
//!				Uses API elements: NewL(), OpenL(), SetPlayWindow(), ClearPlayWindow()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No Errors
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0021-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetPlayWindow		MM-MMF-ACLNT-CNVRT-PublicAPI-0021-001-SetPlayWindow_command03
		COMMAND		convertutility1	ClearPlayWindow		
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0021

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0022
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0022
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		21/04/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set the number of repetitions for playback
//! @SYMTestActions		1. Create convert object 2. Set the number of repetitions for playback
//!				Uses API elements: NewL(), SetRepeats()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Repetitions set
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0022-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetRepeats		MM-MMF-ACLNT-CNVRT-PublicAPI-0022-001-SetRepeats_command03
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0022

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0023
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0023
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and set maximum write length.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Set maximum write length
//!				Uses API elements: NewL(), OpenL(), SetMaxWriteLength()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No Errors
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0023-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetMaxWriteLength		MM-MMF-ACLNT-CNVRT-PublicAPI-0023-001-SetMaxWriteLength_command03
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0023

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0024
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0024
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and crop from beginning.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Crop audio clip from beginning
//!				Uses API elements: NewL(), OpenL(), CropFromBeginningL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Audio clip is cropped
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0024-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetPosition		MM-MMF-ACLNT-CNVRT-PublicAPI-0024-001-SetPosition_command03
		COMMAND		convertutility1	CropFromBeginningL		
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0024

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0025
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0025
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get controller implementation information
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Get controller information
//!				Uses API elements: NewL(), OpenL(), ControllerImplementationInformationL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Returned controller implementation structure
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0025-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	ControllerImplementationInformationL		
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0025

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0026
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0026
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Send a synchronous custom command to the controller with Dataformat
//! @SYMTestActions		1. Create convert object 2. Send synchronous custom command
//!				Uses API elements: NewL(), CustomCommandSync()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0026-001-OpenL_command02
		OUTSTANDING
		COMMAND	!Error=-5	convertutility1	CustomCommandSync		MM-MMF-ACLNT-CNVRT-PublicAPI-0026-001-CustomCommandSync_command03
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0026

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0027
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0027
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Send a synchronous custom command to the controller without Dataformat
//! @SYMTestActions		1. Create convert object 2. Send synchronous custom command
//!				Uses API elements: NewL(), CustomCommandSync()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0027-001-OpenL_command02
		OUTSTANDING
		COMMAND	!Error=-5	convertutility1	CustomCommandSync		MM-MMF-ACLNT-CNVRT-PublicAPI-0027-001-CustomCommandSync_command03
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0027

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0028
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0028
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Send an asynchronous custom command to the controller with Dataformat
//! @SYMTestActions		1. Create convert object 2. Send synchronous custom command
//!				Uses API elements: NewL(), CustomCommandAsync()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0028-001-OpenL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-5	convertutility1	CustomCommandAsync		MM-MMF-ACLNT-CNVRT-PublicAPI-0028-001-CustomCommandAsync_command03
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0028

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0029
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0029
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Send an asynchronous custom command to the controller without Dataformat
//! @SYMTestActions		1. Create convert object 2. Send synchronous custom command
//!				Uses API elements: NewL(), CustomCommandAsync()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0029-001-OpenL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-5	convertutility1	CustomCommandAsync		MM-MMF-ACLNT-CNVRT-PublicAPI-0029-001-CustomCommandAsync_command03
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0029

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0030
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0030
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set the priority of the controller's sub thread
//! @SYMTestActions		1. Create convert object
//!				2. Set the priority of the controller's sub thread
//!				Uses API elements: NewL(), SetThreadPriority()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Priority is changed
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0030-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetThreadPriority		MM-MMF-ACLNT-CNVRT-PublicAPI-0030-001-SetThreadPriority_command03
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0030

//******************************************************//
//	Phase 2 (negative) tests begin here		//
//******************************************************//

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0031
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0031
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open nonexisting source and target files
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotFound is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-1	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0031-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0031

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0032
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0032
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with not valid target format
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotFound is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-1	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0032-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0032

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0033
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0033
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with not valid audio codec for the destination data sink
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Files are opened
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0033-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0033

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0034
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0034
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with not valid audio setings
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Files are opened
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0034-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0034

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0035
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0035
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with not valid audio setings for source and target files
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-5	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0035-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0035

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0036
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0036
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with not valid audio codec for the source audio object
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-5	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0036-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0036

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0037
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0037
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set not valid destination data type
//! @SYMTestActions		1. Create convert object 2. Open source and target files 3. set destination audio clip data type
//!				Uses API elements: NewL(), OpenL(), SetDestinationDataTypeL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0037-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	SourceDataTypeL		
		COMMAND			convertutility1	GetSupportedDestDataTypesL		
		COMMAND	!Error=-5	convertutility1	SetDestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0037-001-SetDestinationDataTypeL_command05
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0037

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0038
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0038
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get destination audio clip data type without opening files before
//! @SYMTestActions		1. Create convert object 2. Get destination audio clip data type
//!				Uses API elements: NewL(), DestinationDataTypeL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	DestinationDataTypeL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0038

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0039
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0039
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get source audio clip data type without opening files before
//! @SYMTestActions		1. Create convert object 2. Get source audio clip data type
//!				Uses API elements: NewL(), SourceDataTypeL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	SourceDataTypeL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0039

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0040
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0040
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set not valid destination audio clip bit rate
//! @SYMTestActions		1. Create convert object 2. Open source and target files 3. Set destination audio clip bit rate
//!				Uses API elements: NewL(), OpenL(), SetDestinationBitRateL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0040-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	SourceBitRateL		
		COMMAND	!Error=-5	convertutility1	SetDestinationBitRateL		MM-MMF-ACLNT-CNVRT-PublicAPI-0040-001-SetDestinationBitRateL_command04
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0040

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0041
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0041
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get destination audio clip bit rate without opening files before
//! @SYMTestActions		1. Create convert object 2. Get destination audio clip bit rate
//!				Uses API elements: NewL(), DestinationBitRateL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	DestinationBitRateL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0041

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0042
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0042
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get source audio clip bit rate without opening files before
//! @SYMTestActions		1. Create convert object 2. Get source audio clip bit rate
//!				Uses API elements: NewL(), SourceBitRateL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	SourceBitRateL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0042

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0043
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0043
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set not valid destination audio clip sample rate
//! @SYMTestActions		1. Create convert object 2. Open source and target files 3. Set destination audio clip sample rate
//!				Uses API elements: NewL(), OpenL(), SetDestinationSampleRateL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0043-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	SourceSampleRateL		
		COMMAND			convertutility1	GetSupConvSampleRatesL		
		COMMAND	!Error=-5	convertutility1	SetDestinationSampleRateL		MM-MMF-ACLNT-CNVRT-PublicAPI-0043-001-SetDestinationSampleRateL_command05
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0043

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0044
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0044
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get destination audio clip sample rate without opening files before
//! @SYMTestActions		1. Create convert object 2. Get destination audio clip sample rate
//!				Uses API elements: NewL(), DestinationSampleRateL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	DestinationSampleRateL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0044

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0045
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0045
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		23/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get source audio clip sample rate without opening files before
//! @SYMTestActions		1. Create convert object 2. Get source audio clip sample rate
//!				Uses API elements: NewL(), SourceSampleRateL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	SourceSampleRateL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0045

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0046
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0046
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set not valid format for destination audio clip
//! @SYMTestActions		1. Create convert object 2. Open source and target files 3. Sets the format of the destination audio clip
//!				Uses API elements: NewL(), OpenL(), SetDestinationFormatL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0046-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	SourceFormatL		
		COMMAND	!Error=-5	convertutility1	SetDestinationFormatL		MM-MMF-ACLNT-CNVRT-PublicAPI-0046-001-SetDestinationFormatL_command04
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0046

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0047
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0047
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get format of the destination audio clip without opening files before
//! @SYMTestActions		1. Create convert object 2. Get format of the destination audio clip
//!				Uses API elements: NewL(), DestinationFormatL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	DestinationFormatL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0047

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0048
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0048
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get format of the source audio clip without opening files before
//! @SYMTestActions		1. Create convert object 2. Get format of the source audio clip
//!				Uses API elements: NewL(), SourceFormatL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	SourceFormatL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0048

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0049
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0049
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set not valid number of channels for destination audio clip
//! @SYMTestActions		1. Create convert object 2. Open source and target files 3. Sets the number of channels for the destination audio clip
//!				Uses API elements: NewL(), OpenL(), SetDestinationNumberOfChannelsL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0049-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	SourceNumberOfChannelsL		
		COMMAND			convertutility1	GetSupportedConversionNumberOfChannelsL		
		COMMAND	!Error=-5	convertutility1	SetDestinationNumberOfChannelsL		MM-MMF-ACLNT-CNVRT-PublicAPI-0049-001-SetDestinationNumberOfChannelsL_command05
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0049

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0050
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0050
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get number of channels of the destination audio clip without opening files before
//! @SYMTestActions		1. Create convert object 2. Get number of channels of the destination audio clip
//!				Uses API elements: NewL(), DestinationNumberOfChannelsL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	DestinationNumberOfChannelsL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0050

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0051
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0051
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get number of channels of the source audio clip without opening files before
//! @SYMTestActions		1. Create convert object 2. Get number of channels of the source audio clip
//!				Uses API elements: NewL(), SourceNumberOfChannelsL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	SourceNumberOfChannelsL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0051

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0052
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0052
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Start conversion without opening files
//! @SYMTestActions		1. Create convert object 2. Start conversion
//!				Uses API elements: NewL(), ConvertL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-18	convertutility1	ConvertL	
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0052

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0053
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0053
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		25/04/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Close files witout opening them first
//! @SYMTestActions		1. Create convert object 2. Close files
//!				Uses API elements: NewL(), Close()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	Close		
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0053

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0054
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0054
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Start playing without opening files first
//! @SYMTestActions		1. Create convert object 2. Start playing
//!				Uses API elements: NewL(), PlayL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-18	convertutility1	PlayL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0054

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0055
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0055
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Start recording without opening files first
//! @SYMTestActions		1. Create convert object 2. Start recording
//!				Uses API elements: NewL(), RecordL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-18	convertutility1	RecordL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0055

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0056
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0056
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Stop conversion without starting it
//! @SYMTestActions		1. Create convert object 2. Stop conversion
//!				Uses API elements: NewL(), Stop()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	5	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-18	convertutility1	Stop		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0056

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0057
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0057
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Crop without opening files first
//! @SYMTestActions		1. Create convert object 2. Crop current clip from the current position
//!				Uses API elements: NewL(), CropL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	CropL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0057

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0058
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0058
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to set negative and very big postion in the audio clip.
//! @SYMTestActions		1. Create convert object 2. Open audio files 3. Set negative position
//!				Uses API elements: NewL(), OpenL(), SetPosition()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	If the negative value is set then actual postion will be 0 and if very big
//!				positive value is set then the actual position will be max duration.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0058-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetPosition		MM-MMF-ACLNT-CNVRT-PublicAPI-0058-001-SetPosition_command03
		COMMAND		convertutility1	Position		MM-MMF-ACLNT-CNVRT-PublicAPI-0058-001-Position_command04
		COMMAND		convertutility1	SetPosition		MM-MMF-ACLNT-CNVRT-PublicAPI-0058-001-SetPosition_command05
		COMMAND		convertutility1	Position		MM-MMF-ACLNT-CNVRT-PublicAPI-0058-001-Position_command06
		COMMAND		convertutility1	Duration		
		COMMAND		convertutility1	SetPosition		MM-MMF-ACLNT-CNVRT-PublicAPI-0058-001-SetPosition_command08
		COMMAND		convertutility1	Position		MM-MMF-ACLNT-CNVRT-PublicAPI-0058-001-Position_command09
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0058

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0059
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0059
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set the current position in the audio clip without opening files first
//! @SYMTestActions		1. Create convert object 2. Set the current position in the audio clip
//!				Uses API elements: NewL(), SetPosition()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	SetPosition		MM-MMF-ACLNT-CNVRT-PublicAPI-0059-001-SetPosition_command02
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0059

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0060
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0060
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get the current position in the audio clip without opening files first
//! @SYMTestActions		1. Create convert object 2. Get the current position in the audio clip
//!				Uses API elements: NewL(), Position()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	Position		
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0060

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0062
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0062
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Get duration of the audio clip without opening files first
//! @SYMTestActions		1. Create convert object 2. Get duration of the audio clip
//!				Uses API elements: NewL(), Duration()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	Duration		
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0062

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0064
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0064
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set window for playback, startpoint bigger than duration and endpoint negative
//! @SYMTestActions		1. Create convert object 2. Set window for playback
//!				Uses API elements: NewL(), SetPlayWindow()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No Errors returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0064-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	Duration		
		COMMAND		convertutility1	SetPlayWindow		MM-MMF-ACLNT-CNVRT-PublicAPI-0064-001-SetPlayWindow_command04
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0064

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0066
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0066
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set negative value for maximum size of an audio clip.
//! @SYMTestActions		1. Create convert object 2. Open source and target files 3. Set the maximum size of an audio clip
//!				Uses API elements: NewL(), OpenL(), SetMaxWriteLength()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0066-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetMaxWriteLength		MM-MMF-ACLNT-CNVRT-PublicAPI-0066-001-SetMaxWriteLength_command03
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0066

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0067
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0067
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open corrupted destination file
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotFound is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-1	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0067-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0067

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0068
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0068
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Crop the audio clip from the start of the file to the current position without opening files first
//! @SYMTestActions		1. Create convert object 2. Crop the audio clip from the start of the file to the current position
//!				Uses API elements: NewL(), CropFromBeginningL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	CropFromBeginningL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0068

//! START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0069
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0069
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Send a synchronous custom command to the controller with negative function number with reference to an "DataFrom"
//! @SYMTestActions		1. Create convert object 2. Send a synchronous custom command to the controller
//!				Uses API elements: NewL(), CustomCommandSync()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Program is paniced
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK		50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
//! 		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
//! 		COMMAND		convertutility1	NewL			
//! 		COMMAND		convertutility1	OpenL			MM-MMF-ACLNT-CNVRT-PublicAPI-0069-001-OpenL_command02
//! 		OUTSTANDING
//! 		COMMAND		convertutility1	CustomCommandSync	MM-MMF-ACLNT-CNVRT-PublicAPI-0069-001-CustomCommandSync_command03
//! 		COMMAND		convertutility1	Close
//! 	END_TEST_BLOCK	!PanicString=User !PanicCode=72
//! END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0069

//! START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0070
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0070
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Send a synchronous custom command to the controller with negative function number without reference to an "DataFrom"
//! @SYMTestActions		1. Create convert object 2. Send a synchronous custom command to the controller
//!				Uses API elements: NewL(), CustomCommandSync()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Program is paniced
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK		50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
//! 		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
//! 		COMMAND		convertutility1	NewL		
//! 		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0070-001-OpenL_command02
//! 		OUTSTANDING
//! 		COMMAND		convertutility1	CustomCommandSync		MM-MMF-ACLNT-CNVRT-PublicAPI-0070-001-CustomCommandSync_command03
//! 		COMMAND		convertutility1	Close
//! 	END_TEST_BLOCK	!PanicString=User !PanicCode=72
//! END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0070

//! START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0071
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0071
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Send a asynchronous custom command to the controller with negative function number with reference to an "DataFrom"
//! @SYMTestActions		1. Create convert object 2. Send a asynchronous custom command to the controller
//!				Uses API elements: NewL(), CustomCommandAsync()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Program is paniced
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK		50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
//! 		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
//! 		COMMAND		convertutility1	NewL		
//! 		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0071-001-OpenL_command02
//! 		OUTSTANDING
//! 		COMMAND		convertutility1	CustomCommandAsync		MM-MMF-ACLNT-CNVRT-PublicAPI-0071-001-CustomCommandAsync_command03
//! 		OUTSTANDING
//! 		COMMAND		convertutility1	Close
//! 	END_TEST_BLOCK	!PanicString=User !PanicCode=72
//! END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0071

//! START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0072
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0072
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Send a asynchronous custom command to the controller with negative function number without reference to an "DataFrom"
//! @SYMTestActions		1. Create convert object 2. Send a asynchronous custom command to the controller
//!				Uses API elements: NewL(), CustomCommandAsync()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Program is paniced
//! @SYMTestType		CIT
//! 	START_TEST_BLOCK		50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
//! 		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
//! 		COMMAND		convertutility1	NewL		
//! 		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0072-001-OpenL_command02
//! 		OUTSTANDING
//! 		COMMAND		convertutility1	CustomCommandAsync		MM-MMF-ACLNT-CNVRT-PublicAPI-0072-001-CustomCommandAsync_command03
//! 		OUTSTANDING
//! 		COMMAND		convertutility1	Close
//! 	END_TEST_BLOCK	!PanicString=User !PanicCode=72
//! END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0072

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0073
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0073
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		24/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set invalid priority of the controller's sub thread
//! @SYMTestActions		1. Create convert object 2. Set the priority of the controller's sub thread
//!				Uses API elements: NewL(), SetThreadPriority()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0073-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetThreadPriority		MM-MMF-ACLNT-CNVRT-PublicAPI-0073-001-SetThreadPriority_command03
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0073

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0074
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0074
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Construct new instance of the audio converter with parameter aServer not NULL
//! @SYMTestActions		1. Create convert object
//!				Uses API elements: NewL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	New instance created
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		MM-MMF-ACLNT-CNVRT-PublicAPI-0074-001-NewL_command01
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0074

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0075
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0075
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Construct new instance of the audio converter with priority lower than minimal
//! @SYMTestActions		1. Create convert object
//!				Uses API elements: NewL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		MM-MMF-ACLNT-CNVRT-PublicAPI-0075-001-NewL_command01
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0075

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0076
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0076
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Construct new instance of the audio converter with priority higher than maximum
//! @SYMTestActions		1. Create convert object
//!				Uses API elements: NewL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		MM-MMF-ACLNT-CNVRT-PublicAPI-0076-001-NewL_command01
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0076

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0077
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0077
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Construct new instance of the audio converter with invalid Time vs Quality priority preference
//! @SYMTestActions		1. Create convert object
//!				Uses API elements: NewL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors should return as the invalid TMdaPriorityPreference should default to EMdaPriorityPreferenceNone
//!					        when a new instance of the audio converter is constructed.
//! @SYMTestType		CIT

	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		MM-MMF-ACLNT-CNVRT-PublicAPI-0077-001-NewL_command01
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0077

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0078
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0078
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open nonexisting source and destination files with target format, codec and audio settings
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0078-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0078

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0079
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0079
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open nonexisting source file
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotFound is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-1	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0079-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0079

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0080
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0080
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open nonexisting target file
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0080-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0080

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0081
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0081
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with not valid source format
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-5	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0081-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0081

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0082
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0082
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with not valid controller (used for conversion)
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotFound is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-1	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0082-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0082

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0084
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0084
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set window for playback, startpoint negative and endpoint bigger than duration
//! @SYMTestActions		1. Create convert object 2. Set window for playback
//!				Uses API elements: NewL(), SetPlayWindow()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Window for playback is set
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0084-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetPlayWindow		MM-MMF-ACLNT-CNVRT-PublicAPI-0084-001-SetPlayWindow_command03
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0084

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0085
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0085
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set negative number of times to repeat
//! @SYMTestActions		1. Create convert object 2. 2. Open source and target files 3. Set the number of repetitions for playback
//!				Uses API elements: NewL(), OpenL(), SetRepeats()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0085-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SetRepeats		MM-MMF-ACLNT-CNVRT-PublicAPI-0085-001-SetRepeats_command03
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0085

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0086
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0086
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		13/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open corrupted source file
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-5	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0086-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0086

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0087
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0087
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		17/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to get a list of the supported data types for the conversion destination without opening files first.
//! @SYMTestActions		1. Create convert object 2. Get a list of the supported data types for the conversion destination
//!				Uses API elements: NewL(), GetSupportedDestinationDataTypesL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	GetSupportedDestDataTypesL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0087

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0088
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0088
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		17/03/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to get a list of the supported data types for the conversion destination using raw file as destination file.
//! @SYMTestActions		1. Create convert object 2. Get a list of the supported data types for the conversion destination
//!				Uses API elements: NewL(), OpenL(), GetSupportedDestinationDataTypesL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0088-001-OpenL_command02
		OUTSTANDING
		COMMAND	!Error=-5	convertutility1	GetSupportedDestDataTypesL		
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0088

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0089
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0089
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		28/04/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to get a list of the supported bit rates for the conversion destination without opening files first.
//! @SYMTestActions		1. Create convert object 2. Get a list of the supported bit rates for the conversion destination
//!				Uses API elements: NewL(), GetSupportedConversionBitRatesL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	GetSupConversionBitRatesL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0089

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0090
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0090
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to get a list of supported conversion sample rates without opening files first.
//! @SYMTestActions		1. Create convert object 2. Get a list of supported conversion sample rates.
//!				Uses API elements: NewL(), GetSupportedConversionSampleRatesL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	GetSupConvSampleRatesL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0090

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0091
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0091
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to get a list of the supported number of channels for conversion without opening files first.
//! @SYMTestActions		1. Create convert object 2. Get a list of the supported number of channels for conversion.
//!				Uses API elements: NewL(), GetSupportedConversionNumberOfChannelsL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	GetSupportedConversionNumberOfChannelsL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0091

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0092
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0092
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to get the controller implementation information associated with the current controller without opening files first.
//! @SYMTestActions		1. Create convert object 2. Get the controller implementation information associated with the current controller.
//!				Uses API elements: NewL(), ControllerImplementationInformationL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	ControllerImplementationInformationL		
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0092

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0093
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0093
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open corrupted source file.
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-5	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0093-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0093

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0094
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0094
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open corrupted target file.
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Files are opened
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0094-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0094

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0095
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0095
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with not valid target format
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-5	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0095-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0095

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0096
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0096
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open nonexisting source file.
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotFound is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-1	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0096-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0096

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0097
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0097
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open corrupted source file.
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotFound is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-1	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0097-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0097

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0098
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0098
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open corrupted target file.
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotFound is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-1	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0098-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0098

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0099
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0099
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to convert with corrupted target file.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and target files
//!				3. Convert file
//!				Uses API elements: NewL(), OpenL(), ConvertL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0099-001-OpenL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-5	convertutility1	ConvertL		
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0099

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0100
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0100
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and target files with not valid "aDestDataType" (The audio codec to use for the destination data sink)
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrAlreadyExists is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-11	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0100-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0100

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0101
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0101
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open nonexisting source file.
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotFound is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-1	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0101-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0101

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0102
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0102
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open corrupted source file.
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Files are opened
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0102-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0102

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0103
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0103
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open corrupted target file.
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotFound is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-1	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0103-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0103

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0104
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0104
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to convert with corrupted target file.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and target files
//!				3. Convert file
//!				Uses API elements: NewL(), OpenL(), ConvertL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0104-001-OpenL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-5	convertutility1	ConvertL		
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0104

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0105
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0105
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Set invalid destination data type
//! @SYMTestActions		1. Create convert object 2. Open source and target files 3. set destination audio clip data type
//!				Uses API elements: NewL(), OpenL(), SetDestinationDataTypeL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND			convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0105-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	SourceDataTypeL		
		COMMAND			convertutility1	GetSupportedDestDataTypesL		
		COMMAND	!Error=-5	convertutility1	SetDestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0105-001-SetDestinationDataTypeL_command05
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0105

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0106
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0106
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to set destination data type without opening files first
//! @SYMTestActions		1. Create convert object 2. set destination audio clip data type
//!				Uses API elements: NewL(), SetDestinationDataTypeL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	SetDestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0106-001-SetDestinationDataTypeL_command02
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0106

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0107
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0107
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to set destination audio clip bit rate without opnening files first
//! @SYMTestActions		1. Create convert object 2. Set destination audio clip bit rate
//!				Uses API elements: NewL(), SetDestinationBitRateL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	SetDestinationBitRateL		MM-MMF-ACLNT-CNVRT-PublicAPI-0107-001-SetDestinationBitRateL_command02
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0107

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0108
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0108
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to set destination audio clip sample rate without opening files first
//! @SYMTestActions		1. Create convert object 2. Set destination audio clip sample rate
//!				Uses API elements: NewL(), SetDestinationSampleRateL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	SetDestinationSampleRateL		MM-MMF-ACLNT-CNVRT-PublicAPI-0108-001-SetDestinationSampleRateL_command02
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0108

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0109
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0109
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to set format for destination audio clip without opening files first
//! @SYMTestActions		1. Create convert object 2. Sets the format of the destination audio clip
//!				Uses API elements: NewL(), SetDestinationFormatL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	SetDestinationFormatL		MM-MMF-ACLNT-CNVRT-PublicAPI-0109-001-SetDestinationFormatL_command02
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0109

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0110
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0110
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to set number of channels for destination audio clip without opening files first
//! @SYMTestActions		1. Create convert object 2. Sets the number of channels for the destination audio clip
//!				Uses API elements: NewL(), SetDestinationNumberOfChannelsL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!Error=-18	convertutility1	SetDestinationNumberOfChannelsL		MM-MMF-ACLNT-CNVRT-PublicAPI-0110-001-SetDestinationNumberOfChannelsL_command02
		COMMAND			convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0110

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0111
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0111
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to set number of times to repeat without opening files first
//! @SYMTestActions		1. Create convert object 2. Set the number of repetitions for playback
//!				Uses API elements: NewL(), SetRepeats()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	SetRepeats		MM-MMF-ACLNT-CNVRT-PublicAPI-0111-001-SetRepeats_command02
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0111

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0112
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0112
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to set maximum size of an audio clip without opening files first.
//! @SYMTestActions		1. Create convert object 2. Set the maximum size of an audio clip
//!				Uses API elements: NewL(), SetMaxWriteLength()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	No errors returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	SetMaxWriteLength		MM-MMF-ACLNT-CNVRT-PublicAPI-0112-001-SetMaxWriteLength_command02
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0112

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0113
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0113
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Convert wav (note.wav) to AU (note3.au)
//! @SYMTestActions		1. Create convert object
//!				2. Open source and target files
//!				3. Convert file
//!				Uses API elements: NewL(), OpenL(), ConvertL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	File is converted
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0113-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	ConvertL		
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0113

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0114
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0114
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open existing file with wrong codec.
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrAlreadyExists is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-11	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0114-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0114

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0115
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0115
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Try to open existing file with wrong format.
//! @SYMTestActions		1. Create convert object 2. Open source and target files
//!				Uses API elements: NewL(), OpenL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotSupported is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND			convertutility1	NewL		
		COMMAND	!AsyncError=-5	convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0115-001-OpenL_command02
		OUTSTANDING
		COMMAND			convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0115

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0116
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0116
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		02/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Convert wav (note.wav) to RAW (note4.raw)
//! @SYMTestActions		1. Create convert object
//!				2. Open source and target files
//!				3. Get source sample rate
//!				4. Get supported conversion sample rates
//!				5. Get number of channels of source audio clip
//!				6. Get supported number of channels for conversion
//!				7. Set destination number of channels of audio clip
//!				8. Get source datatype
//!				9. Get supported destination datatypes
//!				10. Set destination datatype
//!				11. Get format of source audio clip
//!				12. Get destination format of audio clip
//!				13. Convert file
//!				Uses API elements: NewL(), OpenL(), SourceSampleRateL(), GetSupportedConversionSampleRatesL(),
//!				SourceNumberOfChannelsL(), GetSupportedConversionNumberOfChannelsL(), SetDestinationNumberOfChannelsL(),
//!				SourceDataTypeL(), GetSupportedDestinationDataTypesL(), SetDestinationDataTypeL(), SourceFormatL(),
//!				DestinationFormatL(), ConvertL()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	File is converted
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0116-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	SourceSampleRateL		
		COMMAND		convertutility1	GetSupConvSampleRatesL		
		COMMAND		convertutility1	SourceNumberOfChannelsL		
		COMMAND		convertutility1	GetSupportedConversionNumberOfChannelsL		
		COMMAND		convertutility1	SetDestinationNumberOfChannelsL		MM-MMF-ACLNT-CNVRT-PublicAPI-0116-001-SetDestinationNumberOfChannelsL_command07
		COMMAND		convertutility1	SourceDataTypeL		
		COMMAND		convertutility1	GetSupportedDestDataTypesL		
		COMMAND		convertutility1	SetDestinationDataTypeL		MM-MMF-ACLNT-CNVRT-PublicAPI-0116-001-SetDestinationDataTypeL_command10
		COMMAND		convertutility1	SourceFormatL		
		COMMAND		convertutility1	DestinationFormatL		
		COMMAND		convertutility1	ConvertL		
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0116

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0117
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0117
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Marek Sokk
//! @SYMCreationDate		17/05/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Open source and destination files and convert
//!				Uses API elements: NewL(), OpenL(), UseSharedHeap(), ConvertL(), Close()
//! @SYMTestActions		1. Create convert object
//!				2. Set shared heap
//!				3. Open source and destination files
//!				4. Convert file
//!				5. Repeat twice more
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Files are converted
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		MM-MMF-ACLNT-CNVRT-PublicAPI-0117-001-NewL_command01
		COMMAND		convertutility1	UseSharedHeap		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0117-001-OpenL_command03
		OUTSTANDING
		COMMAND		convertutility1	SourceDataTypeL		
		COMMAND		convertutility1	GetSupportedDestDataTypesL		
		COMMAND		convertutility1	ConvertL		
		OUTSTANDING
		COMMAND		convertutility1	Close		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0117-001-OpenL_command08
		OUTSTANDING
		COMMAND		convertutility1	SourceDataTypeL		
		COMMAND		convertutility1	GetSupportedDestDataTypesL		
		COMMAND		convertutility1	ConvertL		
		OUTSTANDING
		COMMAND		convertutility1	Close		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0117-001-OpenL_command13
		OUTSTANDING
		COMMAND		convertutility1	SourceDataTypeL		
		COMMAND		convertutility1	GetSupportedDestDataTypesL		
		COMMAND		convertutility1	ConvertL		
		OUTSTANDING
		COMMAND		convertutility1	Close		
		COMMAND		convertutility1	~
	END_TEST_BLOCK
END_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0117


START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0118
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0118
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			 Rehana Anwar
//! @SYMCreationDate		22/02/2006
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Positive testcase: Open source and destination files start conversion
//!						and stop conversion while in the EPLAY state.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Start conversion
//!				4. Stop
//!				Uses API elements: NewL(), OpenL(), ConvertL(), Stop()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNone is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0118-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	ConvertL 		MM-MMF-ACLNT-CNVRT-PublicAPI-0118-001-ConvertL_command03
		OUTSTANDING
		COMMAND 	convertutility1 Stop
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE			MM-MMF-ACLNT-CNVRT-PublicAPI-0118


START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0119
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0119
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Rehana Anwar
//! @SYMCreationDate		22/11/2007
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Negative testcase: Open source and destination files and call stop.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				4. Call Stop
//!				Uses API elements: NewL(), OpenL(), ConvertL(), Stop()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0119-001-OpenL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	convertutility1	Stop	
		OUTSTANDING	
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE			MM-MMF-ACLNT-CNVRT-PublicAPI-0119

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0120
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0120
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Rehana Anwar
//! @SYMCreationDate		22/11/2007
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Negative testcase: Call stop before opening source and destination files. Also ensure convert works 
//!				correctly after opening the files.
//! @SYMTestActions		1. Create convert object
//!				2. Call Stop
//!				3. Open source and destination files
//!				4. Call Convert
//!				Uses API elements: NewL(), OpenL(), ConvertL(), Stop()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL	
		COMMAND	!AsyncError=-18	convertutility1	Stop
		OUTSTANDING		
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0120-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	ConvertL	
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE			MM-MMF-ACLNT-CNVRT-PublicAPI-0120

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0121
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0121
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Rehana Anwar
//! @SYMCreationDate		22/11/2007
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Negative testcase: Open source and destination files and call stop.Also ensure Convert works correctly
//!				after Stop fails.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Call Stop
//!				4. Call convert
//!				Uses API elements: NewL(), OpenL(), ConvertL(), Stop()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL	
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0121-001-OpenL_command02
		OUTSTANDING
		COMMAND	!AsyncError=-18	convertutility1	Stop
		OUTSTANDING
		COMMAND		convertutility1	ConvertL	
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE			MM-MMF-ACLNT-CNVRT-PublicAPI-0121

START_TESTCASE 			MM-MMF-ACLNT-CNVRT-PublicAPI-0122
//! @SYMTestCaseID		MM-MMF-ACLNT-CNVRT-PublicAPI-0122
//! @SYMAPI			CMdaAudioConvertUtility
//! @SYMAuthor			Rehana Anwar
//! @SYMCreationDate		22/11/2007
//! @SYMTestCaseDependencies	setup-MM-MMF-ACLNT-CNVRT-PublicAPI.script
//! @SYMTestCaseDesc		Negative testcase: Call stop after Convert completes.
//! @SYMTestActions		1. Create convert object
//!				2. Open source and destination files
//!				3. Call convert
//!				4. Call Stop
//!				Uses API elements: NewL(), OpenL(), ConvertL(), Stop()
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	KErrNotReady is returned
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_MdaAudioConvertUtility	\multimedia\MM-MMF-ACLNT-CNVRT-PublicAPI.ini
		CREATE_OBJECT	CMdaAudioConvertUtility	convertutility1
		COMMAND		convertutility1	NewL	
		COMMAND		convertutility1	OpenL		MM-MMF-ACLNT-CNVRT-PublicAPI-0122-001-OpenL_command02
		OUTSTANDING
		COMMAND		convertutility1	ConvertL 			
		OUTSTANDING
		COMMAND	!AsyncError=-18	convertutility1	Stop
		OUTSTANDING
		COMMAND		convertutility1	Close
	END_TEST_BLOCK
END_TESTCASE			MM-MMF-ACLNT-CNVRT-PublicAPI-0122

