#!perl
# bin2lit.pl
# 
# Copyright (c) 2010 Accenture. All rights reserved.
# This component and the accompanying materials are made available
# under the terms of the "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
# 
# Initial Contributors:
# Accenture - Initial contribution
#

my $litName = shift(@ARGV);
die "Error: No name specified\n" unless $litName;

binmode(STDIN);
undef $/;
my $content = <>;
close (STDIN);

print <<__EOS__;
// This file has been automatically generated by $0
// Do not edit it directly!

_LIT8($litName, 
__EOS__
print "\t\"";
for (my $i=0; $i<length($content); ++$i) {
	print "\"\n\t\"" if ($i && ($i%20) == 0);
	my $c = ord(substr($content, $i, 1));
	printf "\\x%02x", $c;
}
print "\");\n\n"
 