// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

#include <VG/vgu.h>

#include <e32def.h>
#include <e32uid.h>

#ifdef __cplusplus
extern "C" {
#endif
// Read in a cpp file which has been autogenerated by the makefile
// extension "graphics/gen_cpp_from_hdr" from the official Khronos
// source header file "vgu.h"
#include "autogenerated_openvgu11_stub.cpp"
#ifdef __cplusplus
}
#endif

