// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run StartSafe test 

LOAD_SUITE tstartsafe_test_server

START_TESTCASE 			DEVSRVS-SHMA-STARTSAFE-0009
//! @SYMTestCaseID 		DEVSRVS-SHMA-STARTSAFE-0009
//! @SYMPREQ 			PREQ1089 PREQ1871
//! @SYMREQ			REQ6600 REQ9457
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Start process asynchronously.
//! @SYMTestActions		Use the asynchronous CStartSafe::StartL() function to load the good TestApp as a process with EStartProcess, EDeferredWaitForStart.
//! 				Await completion of the async call and check the StartL leave code, TRequestStus and process name
//! @SYMTestExpectedResults 	The process name is logged.
RUN_TEST_STEP 100 tstartsafe_test_server ProcAsynchStart
END_TESTCASE 			DEVSRVS-SHMA-STARTSAFE-0009

