// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run StartSafe test 

LOAD_SUITE tstartsafe_test_server

START_TESTCASE 			DEVSRVS-SHMA-STARTSAFE-0011
//! @SYMTestCaseID 		DEVSRVS-SHMA-STARTSAFE-0011
//! @SYMPREQ 			PREQ1089 PREQ1871
//! @SYMREQ			REQ6594 REQ9457
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		After starting a process it should be possible to initiate monitoring.
//! @SYMTestActions		Call StartAndMonitor() function to start the good Test-App process with EWaitForStart, retry count = 1.
//! 				Test the StartAndMonitorL leave code, check for the existence of the process, kill it and establish that the process is restarted.
//! @SYMTestExpectedResults 	Process name is logged.
RUN_TEST_STEP 100 tstartsafe_test_server ProcStartMon
END_TESTCASE 			DEVSRVS-SHMA-STARTSAFE-0011

