// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run te_sysutils manual Tests

LOAD_SUITE te_sysutilmanualsuite

START_TESTCASE 			SYSLIB-BAFL-CT-4036
//!@SYMTestCaseID       SYSLIB-BAFL-CT-4036
//!@SYMTestCaseDesc		To ensure the functionality for locating the MMC drive operates correctly under different circumstances.
//!@SYMTestActions		The SysUtil::MMCSpaceBelowCriticalLevelL method is called once 
//!@SYMTestActions		the following changes have been made to the product code and the 
//!@SYMTestActions		product code has been rebuilt. The changes to the product are to be 
//!@SYMTestActions		done for each step and the code is then rebuilt and the test is run 
//!@SYMTestActions		again the output is checked against the expected results.
//!@SYMTestActions		1.	KSysUtilDefaultMMCDrive is set to -1.
//!@SYMTestActions		2.	KSysUtilDefaultMMCDrive is set to -1 and the product code is modified so it can’t find an MMC Drive.
//!@SYMTestActions		3.	KSysUtilDefaultMMCDrive is set to EDriveE (4)
//!@SYMTestActions		4.	KSysUtilDefaultMMCDrive is set to EDriveC (2)
//!@SYMTestExpectedResults 	The following result should occur due to changes to the product code:
//!@SYMTestExpectedResults 	1.	The MMC drive should be found and no error should occur
//!@SYMTestExpectedResults 	2.	The code should leave with KErrNotFound
//!@SYMTestExpectedResults 	3.	The MMC drive should be found and no error should occur
//!@SYMTestExpectedResults 	4.	The MMC drive should be found and no error should occur
//!@SYMREQ                 REQ8172
RUN_TEST_STEP 100 te_sysutilmanualsuite SysUtilsMMCDriveLocation
END_TESTCASE 			SYSLIB-BAFL-CT-4036
