// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run CmnSwpValueStep tests

LOAD_SUITE tcmn_server

START_TESTCASE  	DEVSRVS-SSMA-CMN-0003
//!  @SYMTestCaseID 	DEVSRVS-SSMA-CMN-0003
//!  @SYMPREQ 		PREQ1871
//!  @SYMTestType	UT
//!  @SYMTestPriority	Critical
//!  @SYMTestStatus 	Implemented
//!  @SYMTestCaseDesc	Check basic behaviour of T class TSsmSwp.
//!  @SYMTestActions	The test performs basic operations on a TSsmState object, namely calling the following methods:
//! 				1.Constructors and copy constructor
//! 				2.Comparison operators == and !=
//! 				3.Key(), Value(), Clear(), Set()
//!  @SYMTestExpectedResults All methods handle the object data appropriately, with no errors reported.
RUN_TEST_STEP 100 tcmn_server CmnSwpValueStep
END_TESTCASE 		DEVSRVS-SSMA-CMN-0003