// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run CmnStateAwareSessionStep tests

LOAD_SUITE tcmn_server

START_TESTCASE 			DEVSRVS-SSMA-CMN-0005
//! @SYMTestCaseID 		DEVSRVS-SSMA-CMN-0005
//! @SYMPREQ 			PREQ1871
//! @SYMTestType			UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Check correct notifications are received at appropriate level.
//! @SYMTestActions		The test will perform calls to the different methods of the both SsmStateAwareSession classes in different scenarios.
//! 					For RSsmStateAwareSession:
//! 					1.Call Connect() with unknown TDdmDomainId
//! 					2.Call Connect() twice with same TDdmDomainId
//! 					3.Call Connect() twice with different TDdmDomainId
//! 					4.Call Close() on a registered client and non-registered client.
//! 					5.Call RequestStateNotification() and AcknowledgeStateNotification() on a non-registered client.
//! 					6.Call AcknowledgeStateNotification() on client that has not been notified.
//! 					For CSsmStateAwareSession:
//! 					7.Check OOM conditions for all leaving functions 
//! 					8.Add subscribers using AddSubscriberL(). Check that upon notification NotifySubscribers() perfoms appropriate action. 
//! 					9.Delete some of the subscribers using RemoveSubscriber(). Check that upon notification NotifySubscribers() performs appropriate action.
//!  @SYMTestExpectedResults 	The expected results are:
//!  				The request is dealt appropriately resulting in the call to return:
//! 					1.Should return KDmErrBadDomainId
//! 					2.Should return KErrNone
//! 					3.Should return KErrNone
//! 					4.No error is reported
//! 					5.Should Panic
//! 					6.No error is reported
//! 					7.All allocated memory should be cleaned up either by the CleanupStack or by a destructor.
//! 					8.Added subscribers are notified appropriately
//! 					9.Subscribers are notified appropriately except those that were removed MStateChangeNotificationSubscriber
RUN_TEST_STEP 100 tcmn_server CmnStateAwareSessionStep
END_TESTCASE 			DEVSRVS-SSMA-CMN-0005