//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-BRMSG-0001
//!@SYMTestCaseID BA-CTSY-INT-BRMSG-0001
//!@SYMFssID BA/CTSY/BRMSG-0001
//!@SYMTestCaseDesc Set the broadcast messaging simple filter.
//!@SYMTestPriority High
//!@SYMTestActions RMobileBroadcastMessaging::NotifyFilterSettingChange, RMobileBroadcastMessaging::GetFilterSetting, RMobileBroadcastMessaging::SetFilterSetting
//!@SYMTestExpectedResults Pass - Simple filter notifications complete and are set correctly.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestBroadcastMessaging0001 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-BRMSG-0001

START_TESTCASE BA-CTSY-INT-BRMSG-0002
//!@SYMTestCaseID BA-CTSY-INT-BRMSG-0002
//!@SYMFssID BA/CTSY/BRMSG-0002
//!@SYMTestCaseDesc Set the broadcast messaging ID filter
//!@SYMTestPriority High
//!@SYMTestActions CRetrieveMobilePhoneBroadcastIdList::Start, RMobileBroadcastMessaging::NotifyFilterSettingChange, CRetrieveMobilePhoneBroadcastIdList::RetrieveListL, RMobileBroadcastMessaging::GetFilterSetting, RMobileBroadcastMessaging::SetFilterSetting, CMobilePhoneBroadcastIdList::Enumerate, RMobileBroadcastMessaging::NotifyBroadcastIdListChange, RMobileBroadcastMessaging::StoreBroadcastIdListL, CMobilePhoneBroadcastIdList::AddRangeEntryL
//!@SYMTestExpectedResults Pass - Filter setting and notification returned KErrNotSuppoerted and no value can be retrieved.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestBroadcastMessaging0002 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-BRMSG-0002

START_TESTCASE BA-CTSY-INT-BRMSG-0008
//!@SYMTestCaseID BA-CTSY-INT-BRMSG-0008
//!@SYMFssID BA/CTSY/BRMSG-0008
//!@SYMTestCaseDesc Store a broadcast ID list with no IDs
//!@SYMTestPriority High
//!@SYMTestActions RMobileBroadcastMessaging::StoreBroadcastIdListL
//!@SYMTestExpectedResults Pass - List is not stored.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestBroadcastMessaging0008 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-BRMSG-0008

START_TESTCASE BA-CTSY-INT-BRMSG-0009
//!@SYMTestCaseID BA-CTSY-INT-BRMSG-0009
//!@SYMFssID BA/CTSY/BRMSG-0009
//!@SYMTestCaseDesc Store 999 IDs with broadcast ID list
//!@SYMTestPriority High
//!@SYMTestActions RMobileBroadcastMessaging::StoreBroadcastIdListL
//!@SYMTestExpectedResults Pass - List is not stored.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestBroadcastMessaging0009 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-BRMSG-0009

START_TESTCASE BA-CTSY-INT-BRMSG-0010
//!@SYMTestCaseID BA-CTSY-INT-BRMSG-0010
//!@SYMFssID BA/CTSY/BRMSG-0010
//!@SYMTestCaseDesc Store maximum number of broadcast IDs for the phone.
//!@SYMTestPriority High
//!@SYMTestActions RMobileBroadcastMessaging::StoreBroadcastIdListL
//!@SYMTestExpectedResults Pass - List is stored.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestBroadcastMessaging0010 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-BRMSG-0010

START_TESTCASE BA-CTSY-INT-BRMSG-0011
//!@SYMTestCaseID BA-CTSY-INT-BRMSG-0011
//!@SYMFssID BA/CTSY/BRMSG-0011
//!@SYMTestCaseDesc Store broadcast ID list with duplicate IDs
//!@SYMTestPriority High
//!@SYMTestActions RMobileBroadcastMessaging::StoreBroadcastIdListL
//!@SYMTestExpectedResults Pass - List is not stored.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestBroadcastMessaging0011 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-BRMSG-0011

START_TESTCASE BA-CTSY-INT-BRMSG-0012
//!@SYMTestCaseID BA-CTSY-INT-BRMSG-0012
//!@SYMFssID BA/CTSY/BRMSG-0012
//!@SYMTestCaseDesc Store and retrieve broadcast ID list.
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - List retrieved is empty.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestBroadcastMessaging0012 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-BRMSG-0012

START_TESTCASE BA-CTSY-INT-BRMSG-0013
//!@SYMTestCaseID BA-CTSY-INT-BRMSG-0013
//!@SYMFssID BA/CTSY/BRMSG-0013
//!@SYMTestCaseDesc Store and retrieve an empty broadcast ID list.
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - List retrieved is same as that stored.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestBroadcastMessaging0013 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-BRMSG-0013

