//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-DTMF-0001
//!@SYMTestCaseID BA-CTSY-INT-DTMF-0001
//!@SYMFssID BA/CTSY/DTMF-0001
//!@SYMTestCaseDesc Get DTMF caps.
//!@SYMTestPriority High
//!@SYMTestActions RCall::Dial, RCall::HangUp, RMobilePhone::NotifyDTMFCapsChange, RMobilePhone::SetAlternatingCallMode
//!@SYMTestExpectedResults Pass - DTMF caps set when call is active. DTMF caps are 0 when call is not active.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestDTMF0001 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-DTMF-0001

START_TESTCASE BA-CTSY-INT-DTMF-0002
//!@SYMTestCaseID BA-CTSY-INT-DTMF-0002
//!@SYMFssID BA/CTSY/DTMF-0002
//!@SYMTestCaseDesc Send valid DTMF digits and strings.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::StopDTMFTone, RMobilePhone::SendDTMFTones, RMobilePhone::ContinueDTMFStringSending
//!@SYMTestExpectedResults Pass - DTMF tones can be sent individually and as a string.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestDTMF0002 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-DTMF-0002

START_TESTCASE BA-CTSY-INT-DTMF-0003
//!@SYMTestCaseID BA-CTSY-INT-DTMF-0003
//!@SYMFssID BA/CTSY/DTMF-0003
//!@SYMTestCaseDesc Send DTMF strings containing 'p' and 'w'
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::ContinueDTMFStringSending, RMobilePhone::NotifyStopInDTMFString
//!@SYMTestExpectedResults Pass - Notification of a pause in DTMF received.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestDTMF0003 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-DTMF-0003

START_TESTCASE BA-CTSY-INT-DTMF-0004
//!@SYMTestCaseID BA-CTSY-INT-DTMF-0004
//!@SYMFssID BA/CTSY/DTMF-0004
//!@SYMTestCaseDesc Send an invalid DTMF tone.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::StartDTMFTone
//!@SYMTestExpectedResults Pass - Error from baseband / dispatch layer when sending an invalid tone.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestDTMF0004 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-DTMF-0004

START_TESTCASE BA-CTSY-INT-DTMF-0005
//!@SYMTestCaseID BA-CTSY-INT-DTMF-0005
//!@SYMFssID BA/CTSY/DTMF-0005
//!@SYMTestCaseDesc Send a string of DTMF tones contains an invalid tone.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::SendDTMFTones
//!@SYMTestExpectedResults Pass - Error from baseband / dispatch layer.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestDTMF0005 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-DTMF-0005

START_TESTCASE BA-CTSY-INT-DTMF-0007
//!@SYMTestCaseID BA-CTSY-INT-DTMF-0007
//!@SYMFssID BA/CTSY/DTMF-0007
//!@SYMTestCaseDesc Cancel the sending of DTMF Tones
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::SendDTMFTones
//!@SYMTestExpectedResults Pass - KErrCancel returned on cancellation.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestDTMF0007 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-DTMF-0007

START_TESTCASE BA-CTSY-INT-DTMF-0011
//!@SYMTestCaseID BA-CTSY-INT-DTMF-0011
//!@SYMFssID BA/CTSY/DTMF-0011
//!@SYMTestCaseDesc Ensure that DTMF tones can be sent to all conference call participants
//!@SYMTestPriority High
//!@SYMTestActions RMobileCall::Hold, RCall::HangUp, RMobileConferenceCall::CreateConference, RMobilePhone::StartDTMFTone, RMobilePhone::StopDTMFTone, RMobilePhone::SendDTMFTones, RMobilePhone::NotifyStopInDTMFString, RMobilePhone::ContinueDTMFStringSending, RMobilePhone::GetDTMFCaps, RMobilePhone::NotifyDTMFCapsChange
//!@SYMTestExpectedResults Pass - DTMF tones sent to all conference call participants.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestDTMF0011 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-DTMF-0011

