//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-PID-0007
//!@SYMTestCaseID BA-CTSY-INT-PID-0007
//!@SYMFssID BA/CTSY/PID-0007
//!@SYMTestCaseDesc Get subscriber ID (IMSI) when no SIM present.
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - Error returned on attempt to get IMSI with no SIM.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPhoneIdentity0007 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PID-0007

