//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-SMSP-0001
//!@SYMTestCaseID BA-CTSY-INT-SMSP-0001
//!@SYMFssID BA/CTSY/SMSP-0001
//!@SYMTestCaseDesc Store and retrieve a SMSP list.
//!@SYMTestPriority High
//!@SYMTestActions RMobileSmsMessaging::StoreSmspListL, CRetrieveMobilePhoneSmspList::Start, CMobilePhoneSmspList::NewL, CRetrieveMobilePhoneSmspList::NewL, CMobilePhoneSmspList::AddEntryL, RMobileSmsMessaging::NotifySmspListChange
//!@SYMTestExpectedResults Pass - SMSP list stored and retrieved correctly.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestSMSPStore0001 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-SMSP-0001

START_TESTCASE BA-CTSY-INT-SMSP-0003
//!@SYMTestCaseID BA-CTSY-INT-SMSP-0003
//!@SYMFssID BA/CTSY/SMSP-0003
//!@SYMTestCaseDesc Store an empty SMSP list.
//!@SYMTestPriority High
//!@SYMTestActions CMobilePhoneSmspList::NewL, CRetrieveMobilePhoneSmspList::NewL, RMobileSmsMessaging::StoreSmspListL, CRetrieveMobilePhoneSmspList::Start, RMobileSmsMessaging::NotifySmspListChange
//!@SYMTestExpectedResults Pass - Empty SMSP list is not stored and retrieved list is not empty.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestSMSPStore0003 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-SMSP-0003

START_TESTCASE BA-CTSY-INT-SMSP-0004
//!@SYMTestCaseID BA-CTSY-INT-SMSP-0004
//!@SYMFssID BA/CTSY/SMSP-0004
//!@SYMTestCaseDesc Cancel reading SMSP list entries.
//!@SYMTestPriority High
//!@SYMTestActions CRetrieveMobilePhoneSmspList::Start, CRetrieveMobilePhoneSmspList::Cancel
//!@SYMTestExpectedResults Pass - Request is cancelled.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestSMSPStore0004 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-SMSP-0004

START_TESTCASE BA-CTSY-INT-SMSP-0005
//!@SYMTestCaseID BA-CTSY-INT-SMSP-0005
//!@SYMFssID BA/CTSY/SMSP-0005
//!@SYMTestCaseDesc Cancel writing SMSP list entries.
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - Request is cancelled.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestSMSPStore0005 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-SMSP-0005

START_TESTCASE BA-CTSY-INT-SMSP-0006
//!@SYMTestCaseID BA-CTSY-INT-SMSP-0006
//!@SYMFssID BA/CTSY/SMSP-0006
//!@SYMTestCaseDesc Cancel notification of change in SMSP list entries.
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - Request is cancelled.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestSMSPStore0006 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-SMSP-0006

START_TESTCASE BA-CTSY-INT-SMSP-0007
//!@SYMTestCaseID BA-CTSY-INT-SMSP-0007
//!@SYMFssID BA/CTSY/SMSP-0007
//!@SYMTestCaseDesc Store an SMSP list that is too long.
//!@SYMTestPriority High
//!@SYMTestActions RMobileSmsMessaging::StoreSmspListL, CRetrieveMobilePhoneSmspList::Start, CMobilePhoneSmspList::NewL, CMobilePhoneSmspList::AddEntryL
//!@SYMTestExpectedResults Pass - KErrArgument returned.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestSMSPStore0007 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-SMSP-0007

