//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-ACL-0001
//!@SYMTestCaseID BA-CTSY-INT-ACL-0001
//!@SYMFssID BA/CTSY/ACL-0001
//!@SYMTestCaseDesc Append and get entries from the APN control list.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::VerifySecurityCode, RMobilePhone::NotifySecurityEvent, RMobilePhone::NotifyAPNListChanged, RMobilePhone::GetAPNname, RMobilePhone::AppendAPNName
//!@SYMTestExpectedResults Pass - Number of APNs in list is correct. Written entries can be read.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 150 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestAPNControlList0001 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-ACL-0001

START_TESTCASE BA-CTSY-INT-ACL-0002
//!@SYMTestCaseID BA-CTSY-INT-ACL-0002
//!@SYMFssID BA/CTSY/ACL-0002
//!@SYMTestCaseDesc Get APN name from the APN control list with an invalid index.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::EnumerateAPNEntries
//!@SYMTestExpectedResults Pass - Error returned when invalid index is specified.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestAPNControlList0002 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-ACL-0002

START_TESTCASE BA-CTSY-INT-ACL-0003
//!@SYMTestCaseID BA-CTSY-INT-ACL-0003
//!@SYMFssID BA/CTSY/ACL-0003
//!@SYMTestCaseDesc Delete an entry from the APN control list.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::VerifySecurityCode, RMobilePhone::NotifySecurityEvent, RMobilePhone::NotifyAPNListChanged, RMobilePhone::GetAPNname, RMobilePhone::DeleteAPNName, RMobilePhone::AppendAPNName
//!@SYMTestExpectedResults Pass - An APN can be deleted from the APN control list.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 150 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestAPNControlList0003 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-ACL-0003

START_TESTCASE BA-CTSY-INT-ACL-0004
//!@SYMTestCaseID BA-CTSY-INT-ACL-0004
//!@SYMFssID BA/CTSY/ACL-0004
//!@SYMTestCaseDesc Attempt to delete an entry from the APN control list with invalid index.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::VerifySecurityCode, RMobilePhone::NotifySecurityEvent, RMobilePhone::DeleteAPNName
//!@SYMTestExpectedResults Pass - Cannot delete entry from APN control list when index is invalid.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestAPNControlList0004 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-ACL-0004

START_TESTCASE BA-CTSY-INT-ACL-0005
//!@SYMTestCaseID BA-CTSY-INT-ACL-0005
//!@SYMFssID BA/CTSY/ACL-0005
//!@SYMTestCaseDesc Modify APN control list without verifying PIN2.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::DeleteAPNName, RMobilePhone::EnumerateAPNEntries
//!@SYMTestExpectedResults Pass - APN control list cannot be modified without PIN2.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestAPNControlList0005 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-ACL-0005

START_TESTCASE BA-CTSY-INT-ACL-0006
//!@SYMTestCaseID BA-CTSY-INT-ACL-0006
//!@SYMFssID BA/CTSY/ACL-0006
//!@SYMTestCaseDesc Enable and disable the APN control list service.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifySecurityEvent, RMobilePhone::GetAPNControlListServiceStatus, RMobilePhone::SetAPNControlListServiceStatus, RMobilePhone::NotifyAPNControlListServiceStatusChange
//!@SYMTestExpectedResults Pass - APN control list can be enabled and disabled.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestAPNControlList0006 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-ACL-0006

START_TESTCASE BA-CTSY-INT-ACL-0007
//!@SYMTestCaseID BA-CTSY-INT-ACL-0007
//!@SYMFssID BA/CTSY/ACL-0007
//!@SYMTestCaseDesc Enable and disable the APN control list without verifying PIN2.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::AppendAPNName, RMobilePhone::EnumerateAPNEntries
//!@SYMTestExpectedResults Pass - APN control list service cannot be enabled / disabled without PIN2.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestAPNControlList0007 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-ACL-0007

START_TESTCASE BA-CTSY-INT-ACL-0008
//!@SYMTestCaseID BA-CTSY-INT-ACL-0008
//!@SYMFssID BA/CTSY/ACL-0008
//!@SYMTestCaseDesc Add an entry to the APN control list when the list on USIM is full.
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - Cannot append to APN control list when it is full.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestAPNControlList0008 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-ACL-0008

START_TESTCASE BA-CTSY-INT-ACL-0009
//!@SYMTestCaseID BA-CTSY-INT-ACL-0009
//!@SYMFssID BA/CTSY/ACL-0009
//!@SYMTestCaseDesc Activate a context when APN is not in the APN Control List.
//!@SYMTestPriority High
//!@SYMTestActions RPacketContext::NotifyStatusChange, RPacketContext::Activate, RPacketService::GetStatus, RPacketContext::GetLastErrorCause
//!@SYMTestExpectedResults Pass - Context cannot be activated.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestAPNControlList0009 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-ACL-0009

