//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite


START_TESTCASE BA-CTSY-INT-CONC-0017
//!@SYMTestCaseID BA-CTSY-INT-CONC-0017
//!@SYMFssID BA/CTSY/CONC-0017
//!@SYMTestCaseDesc Swap a five party conference call then dial a 6th call.
//!@SYMTestPriority High
//!@SYMTestActions RMobileCall::NotifyMobileCallStatusChange, RMobileConferenceCall::NotifyConferenceEvent, RMobileConferenceCall::NotifyConferenceStatusChange, RMobileCall::GetMobileCallStatus, RMobileConferenceCall::GetConferenceStatus, RMobileConferenceCall::Hangup
//!@SYMTestExpectedResults Pass - Conference call swapped. 6th call dialled.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 200 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestConferenceCallControl0017 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CONC-0017

START_TESTCASE BA-CTSY-INT-CONC-0018
//!@SYMTestCaseID BA-CTSY-INT-CONC-0018
//!@SYMFssID BA/CTSY/CONC-0018
//!@SYMTestCaseDesc Swap 6th active call with five party conference call.
//!@SYMTestPriority High
//!@SYMTestActions RMobileConferenceCall::NotifyConferenceEvent, RMobileConferenceCall::NotifyConferenceStatusChange, RCall::Dial, RMobileCall::Hold, RCall::GetInfo, RMobileConferenceCall::CreateConference, RMobileConferenceCall::Swap, RMobileConferenceCall::AddCall, RLine::NotifyStatusChange, RMobileCall::NotifyMobileCallStatusChange, RMobileConferenceCall::GetCaps, RMobileConferenceCall::GetConferenceStatus, RMobileConferenceCall::GetMobileCallInfo
//!@SYMTestExpectedResults Pass - Conference call swapped with 6th call.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 200 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestConferenceCallControl0018 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CONC-0018

START_TESTCASE BA-CTSY-INT-CONC-0019
//!@SYMTestCaseID BA-CTSY-INT-CONC-0019
//!@SYMFssID BA/CTSY/CONC-0019
//!@SYMTestCaseDesc Create another conference call when there is already a five party conference call active.
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - KErrNotReady on attempt to create second conference call.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 200 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestConferenceCallControl0019 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CONC-0019

START_TESTCASE BA-CTSY-INT-CONC-0020
//!@SYMTestCaseID BA-CTSY-INT-CONC-0020
//!@SYMFssID BA/CTSY/CONC-0020
//!@SYMTestCaseDesc Hang up 3rd call in five party conference call.
//!@SYMTestPriority High
//!@SYMTestActions RMobileConferenceCall::NotifyConferenceStatusChange, RMobileConferenceCall::GetMobileCallInfo, RCall::HangUp, RMobileConferenceCall::NotifyCapsChange, RMobileConferenceCall::GetCaps, RMobileConferenceCall::EnumerateCalls, RMobileConferenceCall::GetConferenceStatus
//!@SYMTestExpectedResults Pass - Third call hung up. Conference is still active. Conference info correct.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 200 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestConferenceCallControl0020 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CONC-0020

START_TESTCASE BA-CTSY-INT-CONC-0022
//!@SYMTestCaseID BA-CTSY-INT-CONC-0022
//!@SYMFssID BA/CTSY/CONC-0022
//!@SYMTestCaseDesc Attempt to add a sixth party to a five party conference call.
//!@SYMTestPriority High
//!@SYMTestActions RMobileConferenceCall::NotifyConferenceStatusChange, RMobileConferenceCall::EnumerateCalls, RMobileConferenceCall::GetCaps, RMobileConferenceCall::AddCall, RMobileCall::GetMobileCallStatus, RMobileConferenceCall::Swap, RMobileConferenceCall::GetConferenceStatus, RCall::Dial
//!@SYMTestExpectedResults Pass - Error on attempt to add a 6th call to the conference.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 200 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestConferenceCallControl0022 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CONC-0022

START_TESTCASE BA-CTSY-INT-CONC-0023
//!@SYMTestCaseID BA-CTSY-INT-CONC-0023
//!@SYMFssID BA/CTSY/CONC-0023
//!@SYMTestCaseDesc Go one to one with call in a two party conference call.
//!@SYMTestPriority High
//!@SYMTestActions RMobileConferenceCall::NotifyConferenceStatusChange, RMobileConferenceCall::GetCaps, RMobileConferenceCall::GetConferenceStatus, RMobileCall::GoOneToOne, RMobileConferenceCall::NotifyCapsChange, RMobileCall::GetMobileCallCaps, RCall::HangUp
//!@SYMTestExpectedResults Pass - Go one to one succeeds.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 200 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestConferenceCallControl0023 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CONC-0023

START_TESTCASE BA-CTSY-INT-CONC-0024
//!@SYMTestCaseID BA-CTSY-INT-CONC-0024
//!@SYMFssID BA/CTSY/CONC-0024
//!@SYMTestCaseDesc Check the last client closing an active conference call hangs it up cleanly
//!@SYMTestPriority High
//!@SYMTestActions RTelServer::Close, RMobilePhone::GetMobileCallStatus, RMobilePhone::Close, RMobileConferenceCall::Close, RMobilePhone::Open, User::After, RTelServer::Connect, RTelServer::SetExtendedErrorGranularity, RMobileConferenceCall::EnumerateCalls, RMobileConferenceCall::Open
//!@SYMTestExpectedResults Pass - Conference call hung up successfully.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestConferenceCallControl0024 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CONC-0024

START_TESTCASE BA-CTSY-INT-CONC-0025
//!@SYMTestCaseID BA-CTSY-INT-CONC-0025
//!@SYMFssID BA/CTSY/CONC-0025
//!@SYMTestCaseDesc Go one to one with call in a five party conference call.
//!@SYMTestPriority High
//!@SYMTestActions RMobileConferenceCall::NotifyConferenceStatusChange, RCall::HangUp, RMobileCall::GoOneToOne, RMobileConferenceCall::NotifyCapsChange, RMobileConferenceCall::GetCaps, RMobileConferenceCall::GetConferenceStatus, RMobileConferenceCall::HangUp, RMobileCall::GetMobileCallCaps
//!@SYMTestExpectedResults Pass - Go one to one succeeds.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 200 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestConferenceCallControl0025 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CONC-0025

START_TESTCASE BA-CTSY-INT-CONC-0026
//!@SYMTestCaseID BA-CTSY-INT-CONC-0026
//!@SYMFssID BA/CTSY/CONC-0026
//!@SYMTestCaseDesc Go one to one with a call that is not part of a conference.
//!@SYMTestPriority High
//!@SYMTestActions RMobileCall::GetMobileCallStatus, RMobileCall::GoOneToOne, RMobileCall::GetMobileCallCaps, RCall::Dial
//!@SYMTestExpectedResults Pass - KErrNotSupported returned.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestConferenceCallControl0026 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CONC-0026

