//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-MMCC-0003
//!@SYMTestCaseID BA-CTSY-INT-MMCC-0003
//!@SYMFssID BA/CTSY/MMCC-0003
//!@SYMTestCaseDesc Ensure a video call can be hung up by remote party.
//!@SYMTestPriority High
//!@SYMTestActions RMobileCall::GetMobileCallInfo, RLine::NotifyIncomingCall, RCall::HangUp, RCall::AnswerIncomingCall, RCall::GetCallParams
//!@SYMTestExpectedResults Pass - Video call is hung up.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies simulated/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestMultimediaCallControl0003 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-MMCC-0003

