//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-PKTS-0001
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0001
//!@SYMFssID BA/CTSY/PKTS-0001
//!@SYMTestCaseDesc Get static caps.
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - Static caps returned.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0001 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0001

START_TESTCASE BA-CTSY-INT-PKTS-0002
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0002
//!@SYMFssID BA/CTSY/PKTS-0002
//!@SYMTestCaseDesc Automatic attach to the packet service.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::NotifyAttachModeChange, RPacketService::GetNtwkRegStatus, RPacketService::GetStatus, RPacketService::GetAttachMode, RPacketService::NotifyDynamicCapsChange, RPacketService::GetDynamicCaps, RPacketService::NotifyStatusChange, RPacketService::GetStaticCaps
//!@SYMTestExpectedResults Pass - Phone automatically attached to packet service.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0002 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0002

START_TESTCASE BA-CTSY-INT-PKTS-0003
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0003
//!@SYMFssID BA/CTSY/PKTS-0003
//!@SYMTestCaseDesc Automatic attach to the packet service.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::GetNtwkRegStatus, RPacketService::GetStatus, RPacketService::GetAttachMode, RPacketService::NotifyDynamicCapsChange, RPacketService::GetDynamicCaps, RPacketService::NotifyStatusChange, RPacketService::NotifyContextAdded, RPacketService::EnumerateContexts, RPacketContext::NotifyStatusChange, RPacketContext::GetStatus
//!@SYMTestExpectedResults Pass - Packet service is active.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 200 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0003 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0003

START_TESTCASE BA-CTSY-INT-PKTS-0004
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0004
//!@SYMFssID BA/CTSY/PKTS-0004
//!@SYMTestCaseDesc Automatic attach and detach to the packet service.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::NotifyAttachModeChange, RPacketService::GetNtwkRegStatus, RPacketService::GetStatus, RPacketService::GetAttachMode, RPacketService::NotifyDynamicCapsChange, RPacketService::GetDynamicCaps, RPacketService::NotifyStatusChange
//!@SYMTestExpectedResults Pass - Phone automatically attaches to then detaches from packet service.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0004 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0004

START_TESTCASE BA-CTSY-INT-PKTS-0005
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0005
//!@SYMFssID BA/CTSY/PKTS-0005
//!@SYMTestCaseDesc Attach to the packet service manually.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::GetNtwkRegStatus, RPacketService::GetStatus, RPacketService::GetAttachMode, RPacketService::NotifyDynamicCapsChange, RPacketService::GetDynamicCaps, RPacketService::NotifyStatusChange
//!@SYMTestExpectedResults Pass - Phone attached to packet service.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0005 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0005

START_TESTCASE BA-CTSY-INT-PKTS-0010
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0010
//!@SYMFssID BA/CTSY/PKTS-0010
//!@SYMTestCaseDesc Attach to packet service when already attached.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::Attach, RPacketService::GetStatus, RPacketService::NotifyStatusChange
//!@SYMTestExpectedResults Pass - Attach fails with KErrAlreadyExists
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0010 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0010

START_TESTCASE BA-CTSY-INT-PKTS-0011
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0011
//!@SYMFssID BA/CTSY/PKTS-0011
//!@SYMTestCaseDesc Attach to packet service when active.
//!@SYMTestPriority High
//!@SYMTestActions RPacketContext::SetConfig, RPacketContext::Activate, RPacketService::Attach, RPacketService::GetStatus, RPacketContext::GetStatus, RPacketService::EnumerateContexts
//!@SYMTestExpectedResults Pass - Attach fails with KErrAlreadyExists
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0011 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0011

START_TESTCASE BA-CTSY-INT-PKTS-0012
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0012
//!@SYMFssID BA/CTSY/PKTS-0012
//!@SYMTestCaseDesc Attach to packet service when suspended.
//!@SYMTestPriority High
//!@SYMTestActions RPacketContext::SetConfig, RPacketContext::Activate, RPacketService::NotifyStatusChange, RPacketService::GetStatus, RCall::Dial, RPacketService::SetMSClass, RPacketService::GetMSClass, RPacketService::NotifyMSClassChange
//!@SYMTestExpectedResults Pass - Attach fails with KErrAlreadyExists
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0012 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0012

START_TESTCASE BA-CTSY-INT-PKTS-0016
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0016
//!@SYMFssID BA/CTSY/PKTS-0016
//!@SYMTestCaseDesc Detach from packet service manually when attached.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::NotifyStatusChange, RPacketService::GetStatus, RPacketService::NotifyDynamicCapsChange, RPacketService::GetNtwkRegStatus, RPacketService::GetDynamicCaps
//!@SYMTestExpectedResults Pass - Phone detached from packet service.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 150 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0016 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0016

START_TESTCASE BA-CTSY-INT-PKTS-0017
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0017
//!@SYMFssID BA/CTSY/PKTS-0017
//!@SYMTestCaseDesc Detach from packet service when active.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::GetDynamicCaps, RPacketService::GetStatus, RPacketService::EnumerateContexts, RPacketService::GetNtwkRegStatus, RPacketContext::GetStatus
//!@SYMTestExpectedResults Pass - Packet service and contexts are still active.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0017 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0017

START_TESTCASE BA-CTSY-INT-PKTS-0018
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0018
//!@SYMFssID BA/CTSY/PKTS-0018
//!@SYMTestCaseDesc Detach from packet service when active.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::EnumerateContextsInNif, RPacketService::EnumerateNifs, RPacketService::GetNifInfo, RPacketService::GetContextNameInNif
//!@SYMTestExpectedResults Pass - Packet service and contexts are still active and correct NIF related info is returned.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0018 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0018

START_TESTCASE BA-CTSY-INT-PKTS-0019
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0019
//!@SYMFssID BA/CTSY/PKTS-0019
//!@SYMTestCaseDesc Detach from packet service when last context is deactivated.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::NotifyStatusChange, RPacketService::GetStatus, RPacketService::NotifyDynamicCapsChange, RPacketService::GetNtwkRegStatus, RPacketService::EnumerateContexts, RPacketContext::NotifyStatusChange, RPacketContext::GetStatus, RPacketService::GetDynamicCaps
//!@SYMTestExpectedResults Pass - Phone detached from packet service.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0019 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0019

START_TESTCASE BA-CTSY-INT-PKTS-0020
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0020
//!@SYMFssID BA/CTSY/PKTS-0020
//!@SYMTestCaseDesc Detach from packet service when last context is deactivated.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::NotifyStatusChange, RPacketService::GetStatus, RPacketService::EnumerateContextsInNif, RPacketService::EnumerateNifs, RPacketService::GetNifInfo, RPacketService::GetContextNameInNif
//!@SYMTestExpectedResults Pass - Phone detached and contexts deactivated.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0020 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0020

START_TESTCASE BA-CTSY-INT-PKTS-0021
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0021
//!@SYMFssID BA/CTSY/PKTS-0021
//!@SYMTestCaseDesc Detach from packet service when already detached.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::GetStatus, RPacketService::SetAttachMode, RPacketService::GetAttachMode
//!@SYMTestExpectedResults Pass - Detach fails.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0021 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0021

START_TESTCASE BA-CTSY-INT-PKTS-0022
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0022
//!@SYMFssID BA/CTSY/PKTS-0022
//!@SYMTestCaseDesc Automatic attach and detach when attach mode is changed.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::NotifyAttachModeChange, RPacketService::GetAttachMode, RPacketService::NotifyStatusChange, RPacketService::GetStatus
//!@SYMTestExpectedResults Pass - Attach mode set successfully. Packet service automatically attaches and detaches depending on mode.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0022 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0022

START_TESTCASE BA-CTSY-INT-PKTS-0023
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0023
//!@SYMFssID BA/CTSY/PKTS-0023
//!@SYMTestCaseDesc Set attach mode to RPacketService::EAttachWhenNeeded when attached.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::NotifyAttachModeChange, RPacketService::GetAttachMode, RPacketService::GetNtwkRegStatus, RPacketService::GetDynamicCaps, RPacketService::GetStatus
//!@SYMTestExpectedResults Pass - Attach mode set successfully.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0023 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0023

START_TESTCASE BA-CTSY-INT-PKTS-0028
//!@SYMTestCaseID BA-CTSY-INT-PKTS-0028
//!@SYMFssID BA/CTSY/PKTS-0028
//!@SYMTestCaseDesc Check preferred bearer has no effect in class A and B.
//!@SYMTestPriority High
//!@SYMTestActions RPacketService::GetPreferredBearer, RPacketService::SetMSClass, RPacketService::NotifyMSClassChange, RPacketService::GetMSClass, RPacketService::SetAttachMode, RPacketService::NotifyAttachModeChange, RPacketService::GetAttachMode, RPacketService::NotifyStatusChange, RPacketService::GetStatus
//!@SYMTestExpectedResults Pass - Packet service status independent of preferred bearer.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPacketService0028 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PKTS-0028

