//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-PID-0001
//!@SYMTestCaseID BA-CTSY-INT-PID-0001
//!@SYMFssID BA/CTSY/PID-0001
//!@SYMTestCaseDesc Deactivate Calling Line Identification Restriction (CLIR).
//!@SYMTestPriority High
//!@SYMTestActions RMobileCall::NotifyMobileCallStatusChange, RMobilePhone::SetIdentityServiceStatus, RMobilePhone::NotifyIdentityServiceStatus, RMobileCall::GetMobileCallInfo, RCall::Dial, RCall::HangUp
//!@SYMTestExpectedResults Pass - CLIR can be deactivated and remote party can get the calling number.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/rps
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPhoneIdentity0001 c:\ctsy\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PID-0001

START_TESTCASE BA-CTSY-INT-PID-0002
//!@SYMTestCaseID BA-CTSY-INT-PID-0002
//!@SYMFssID BA/CTSY/PID-0002
//!@SYMTestCaseDesc Activate Calling Line Identification Restriction (CLIR).
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::GetIdentityServiceStatus, RMobilePhone::SetIdentityServiceStatus, RMobilePhone::NotifyIdentityServiceStatus, RMobileCall::GetMobileCallInfo, RCall::Dial, RCall::HangUp
//!@SYMTestExpectedResults Pass - CLIR can be activated.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/rps
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestPhoneIdentity0002 c:\ctsy\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-PID-0002

