//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-CONC-0021
//!@SYMTestCaseID BA-CTSY-INT-CONC-0021
//!@SYMFssID BA/CTSY/CONC-0021
//!@SYMTestCaseDesc Remote party terminates call in a five party conference call.
//!@SYMTestPriority High
//!@SYMTestActions RMobileConferenceCall::NotifyConferenceStatusChange, RMobileConferenceCall::GetMobileCallInfo, RMobileCall::NotifyCallEvent, RMobileConferenceCall::NotifyCapsChange, RMobileConferenceCall::GetCaps, RMobileConferenceCall::EnumerateCalls, RMobileConferenceCall::GetConferenceStatus
//!@SYMTestExpectedResults Pass - Conference is  still active and conference notifications complete correctly.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/rps
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestConferenceCallControl0021 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CONC-0021


