//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-CAPI-0050
//!@SYMTestCaseID BA-CTSY-INT-CAPI-0050
//!@SYMFssID BA/CTSY/CAPI-0050
//!@SYMTestCaseDesc Test calling RMmCustomAPI::GetLifeTime
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - Place holder - fill this in when writing test
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCustomAPI0050 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CAPI-0050
