//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-NTWC-0004
//!@SYMTestCaseID BA-CTSY-INT-NTWC-0004
//!@SYMFssID BA/CTSY/NTWC-0004
//!@SYMTestCaseDesc Emergency camping
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - Phone registers for emergency calls only
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestNetworkControl0004 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-NTWC-0004

