//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-NTWS-0002
//!@SYMTestCaseID BA-CTSY-INT-NTWS-0002
//!@SYMFssID BA/CTSY/NTWS-0002
//!@SYMTestCaseDesc Get network security notifications when moving from an 3G to 2G only cell.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyNetworkSecurityLevelChange
//!@SYMTestExpectedResults Pass - Network security notification completes.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies simulated/manual
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestNetworkSecurity0002 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-NTWS-0002

