//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TE_CTSYIntegrationTestSuite

START_TESTCASE BA-CTSY-INT-CFOR-0001
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0001
//!@SYMFssID BA/CTSY/CFOR-0001
//!@SYMTestCaseDesc Register call forwarding for all services.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyCallForwardingStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding is registered for all services with each condition.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0001 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0001

START_TESTCASE BA-CTSY-INT-CFOR-0002
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0002
//!@SYMFssID BA/CTSY/CFOR-0002
//!@SYMTestCaseDesc Register call forwarding for each provisioned basic service.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyCallForwardingStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding is registered for each provisioned basic service.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0002 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0002

START_TESTCASE BA-CTSY-INT-CFOR-0003
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0003
//!@SYMFssID BA/CTSY/CFOR-0003
//!@SYMTestCaseDesc Erase call forwarding for all services.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyCallForwardingStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding is erased for all services.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0003 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0003

START_TESTCASE BA-CTSY-INT-CFOR-0004
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0004
//!@SYMFssID BA/CTSY/CFOR-0004
//!@SYMTestCaseDesc Erase call forwarding for each provisioned basic service.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyCallForwardingStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding is erased for each provisioned service group.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0004 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0004

START_TESTCASE BA-CTSY-INT-CFOR-0005
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0005
//!@SYMFssID BA/CTSY/CFOR-0005
//!@SYMTestCaseDesc Activate call forwarding for all services.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyCallForwardingStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding is activated for all services.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0005 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0005

START_TESTCASE BA-CTSY-INT-CFOR-0006
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0006
//!@SYMFssID BA/CTSY/CFOR-0006
//!@SYMTestCaseDesc Activate call forwarding for each provisioned basic service.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyCallForwardingStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding is activated for each provisioned basic service.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0006 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0006

START_TESTCASE BA-CTSY-INT-CFOR-0007
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0007
//!@SYMFssID BA/CTSY/CFOR-0007
//!@SYMTestCaseDesc Deactivate call forwarding for all services.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyCallForwardingStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding is deactivated.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0007 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0007

START_TESTCASE BA-CTSY-INT-CFOR-0008
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0008
//!@SYMFssID BA/CTSY/CFOR-0008
//!@SYMTestCaseDesc Deactivate call forwarding for each provisioned basic service.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyCallForwardingStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding is deactivated for each provisioned basic service.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0008 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0008

START_TESTCASE BA-CTSY-INT-CFOR-0009
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0009
//!@SYMFssID BA/CTSY/CFOR-0009
//!@SYMTestCaseDesc Interrogate call forwarding status when all services have the same status.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::SetCallForwardingStatus, CRetrieveMobilePhoneCFList::NewL
//!@SYMTestExpectedResults Pass - Call forwarding status is retrieved, contains one entry and is correct.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0009 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0009

START_TESTCASE BA-CTSY-INT-CFOR-0010
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0010
//!@SYMFssID BA/CTSY/CFOR-0010
//!@SYMTestCaseDesc Interrogate call forwarding status for different conditions and provisioned basic services.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::SetCallForwardingStatus, CRetrieveMobilePhoneCFList::NewL
//!@SYMTestExpectedResults Pass - Call forwarding status is retrieved and status is that set.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0010 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0010

START_TESTCASE BA-CTSY-INT-CFOR-0011
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0011
//!@SYMFssID BA/CTSY/CFOR-0011
//!@SYMTestCaseDesc Dial a call on a line with call forwarding unconditional active on it.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::SetCallForwardingStatus, RCall::Dial, RCall::HangUp, RMobileCall::NotifyMobileCallStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding active notification completes.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0011 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0011

START_TESTCASE BA-CTSY-INT-CFOR-0012
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0012
//!@SYMFssID BA/CTSY/CFOR-0012
//!@SYMTestCaseDesc Dial a call on a line with call forwarding active.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::SetCallForwardingStatus, RCall::Dial, RCall::HangUp, RMobileCall::NotifyMobileCallStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding active notification completes.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0012 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0012

START_TESTCASE BA-CTSY-INT-CFOR-0013
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0013
//!@SYMFssID BA/CTSY/CFOR-0013
//!@SYMTestCaseDesc Change the 'forward to' number.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyCallForwardingStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding status change notification completes when forward to number is changed.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0013 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0013

START_TESTCASE BA-CTSY-INT-CFOR-0014
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0014
//!@SYMFssID BA/CTSY/CFOR-0014
//!@SYMTestCaseDesc Change the 'no reply' time out.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::NotifyCallForwardingStatusChange
//!@SYMTestExpectedResults Pass - Call forwarding status change notification completes when time out is changed.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0014 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0014

START_TESTCASE BA-CTSY-INT-CFOR-0015
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0015
//!@SYMFssID BA/CTSY/CFOR-0015
//!@SYMTestCaseDesc Get call forwarding indication status.
//!@SYMTestPriority High
//!@SYMTestActions RMobilePhone::SetCallForwardingStatus
//!@SYMTestExpectedResults Pass - Call forwarding indicator is retrieved.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0015 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0015

START_TESTCASE BA-CTSY-INT-CFOR-0016
//!@SYMTestCaseID BA-CTSY-INT-CFOR-0016
//!@SYMFssID BA/CTSY/CFOR-0016
//!@SYMTestCaseDesc Invoke call forwarding
//!@SYMTestPriority High
//!@SYMTestActions 
//!@SYMTestExpectedResults Pass - KErrArgument returned.
//!@SYMTestType CIT
//!@SYMTestCaseDependencies live/automatic
RUN_TEST_STEP 100 TE_CTSYIntegrationTestSuite CCTSYIntegrationTestCallForwarding0016 c:\testdata\configs\ctsyintegration_data.ini
END_TESTCASE BA-CTSY-INT-CFOR-0016

